forcedotcom/salesforcedx-vscode

CONTRIBUTING.md

@vazexqi we should discuss whether we should abandon the `release` branch completely and go directly from develop into master.

Add branching information to contribution guide

---

.gitignore
.travis.yml

This installs latest SFDX CLI and runs tests on Travis CI. 
Note, the build time increases due to the use of "sudo: required" for installing the SFDX CLI. Running the tests also adds to the overall build time.
@W-4092803@

Activate test execution on Travis CI

---

packages/salesforcedx-vscode-core/package.nls.json

Prepends SFDX to the force:source:status command name in English to make it consistent with the rest.
None. This is a small change.

Add the SFDX prefix to force:source:status

---

packages/salesforcedx-vscode-apex-debugger/package.json
packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-visualforce/package.json
packages/salesforcedx-vscode/package.json

This disables the default QnA on the marketplace and allows us to redirect to the GitHub page. This helps prevent yet another QnA site (we already have success community, GitHub issues, etc)
This uses a unpublished attribute in vscode-vsce. See https://github.com/Microsoft/vscode-vsce/blob/f27aa315121e3761f11691db9e129aa8cd276e26/src/package.ts#L155
None. Small change.

Add custom qna attribute to package.json

---

CONTRIBUTING.md
README.md
docs/developing.md

Move content out from README.md into the docs folder. This helps keep the README concise and not overwhelm the first time visitor.

Split up README

---

README.md

URLs are case-sensitive on GitHub.

Change contributing.md to CONTRIBUTING.md

---

packages/salesforcedx-vscode-apex/src/index.ts
packages/salesforcedx-vscode-apex/src/languageServer.ts
packages/salesforcedx-vscode-apex/test/languageServer.test.ts

Due to https://github.com/Microsoft/vscode-languageserver-node/issues/105 the URI that is being sent to the Apex Language Server protocol does not conform to the standard. As such, the Apex Language Server is  confused on what to invalidate. This simple pre-transformation will fix the encoding to match the standard (and what Java expects).
@W-4192006@

Transform URI on Windows prior to sending over

---

packages/salesforcedx-vscode-apex/README.md
packages/salesforcedx-vscode-core/README.md
packages/salesforcedx-vscode-lightning/README.md
packages/salesforcedx-vscode-visualforce/README.md
packages/salesforcedx-vscode/README.md

Updates image URLs to use `raw.githubusercontent.com` instead of `github.com` and to remove `/blob`, so that images will load properly in the VS Code Marketplace.
@W-4166826@

Change image URLs to use raw.githubusercontent.com

---

packages/salesforcedx-vscode-lightning/test/fileAssociations.test.ts
packages/salesforcedx-vscode-visualforce/test/fileAssociations.test.ts

For these tests to detect pass/failure on the command line, you need to be sure to add the `await`. 
I did not notice the missing `await` since I usually run them from VS Code's debug menu which will fail tests on unhandled promised rejections.
But, for CI, we need the `await`.
I verified that there was no regression and that is a test issue.

Add await for test

---

packages/salesforcedx-utils-vscode/src/predicates/predicate.ts
packages/salesforcedx-vscode-core/src/commands/commands.ts
packages/salesforcedx-vscode-core/src/commands/forceApexTestRun.ts
packages/salesforcedx-vscode-core/src/commands/forceAuthWebLogin.ts
packages/salesforcedx-vscode-core/src/commands/forceOrgCreate.ts
packages/salesforcedx-vscode-core/src/commands/forceOrgOpen.ts
packages/salesforcedx-vscode-core/src/commands/forceSourcePull.ts
packages/salesforcedx-vscode-core/src/commands/forceSourcePush.ts
packages/salesforcedx-vscode-core/src/commands/forceSourceStatus.ts
packages/salesforcedx-vscode-core/src/constants.ts
packages/salesforcedx-vscode-core/src/messages/i18n.ts
packages/salesforcedx-vscode-core/src/notifications/notificationService.ts
packages/salesforcedx-vscode-core/src/predicates/index.ts
packages/salesforcedx-vscode-core/src/predicates/salesforcePredicates.ts
packages/salesforcedx-vscode-core/test/commands/commands.test.ts
packages/salesforcedx-vscode-core/test/predicates/index.test.ts

Adds a framework for command precondition-checking, parameter gathering, and execution. What triggered this was that we needed to check if the `vscode.workspace.root` is defined and that the root workspace has a sfdx-project.json.
As part of that refactoring, I introduced a framework for composing all the different stages together.
Also, added a less aggressive filter on -scratch-def.json so that it looks for
those file through out the workspace.
@W-4175532, W-4192163@

Adds a framework for command precondition-checking, parameter gathering, and execution

---

packages/salesforcedx-vscode-core/src/commands/forceOrgCreate.ts

We will assume that all config files will reside under the top-level config folder (or its children folders)
@W-4192163@

Look under config folder (and its nested folders) for -scratch-def.json

---

.appveyor.yml
.gitignore
.travis.yml

This authenticates Travis and AppVeyor with our DevHub for CI testing. The org will be set as default devhub and will also get the alias "devhub" to be used by integration tests.

Authenticate CI with DevHub

---

packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-core/src/commands/forceApexClassCreate.ts

Address an issue where on windows, the path being returned from a context menu in the explorer has an extra '\\' appended before the drive
i.e. \c:\path\to\directory
@W-4197613@

Fix windows path normalization

---

packages/salesforcedx-vscode-core/src/commands/forceApexClassCreate.ts

Gatherer should pass directory's relative path to command builder and then reconstruct the absolute path to open the file later.
@W-4197613@

change absolute explorer dir path to relative path

---

packages/salesforcedx-utils-vscode/package.json

This PR adds the 'engines' key to the package.json of salesforcedx-utils-vscode. It also removes the 'main' key in the package.json.
Fixes #68

Added missing engines definition / removed main key

---

package.json
packages/salesforcedx-apex-debugger/package.json
packages/salesforcedx-utils-vscode/package.json
packages/salesforcedx-vscode-apex-debugger/package.json
scripts/publish.js

Trying to package the extensions with Node 7 doesn't work. 
1. git clone git@github.com:forcedotcom/salesforcedx-vscode.git
2. cd into salesforcedx-vscode
3. npm run install
4. npm run compile
5. npm run vscode:package
**Expected**: 
Should work like it did with Node 6.
**Actual**:
```
vscode-debugadapter-testsupport@1.22.0 node_modules/vscode-debugadapter-testsupport
lerna ERR! vscode:package Errored while running script in 'salesforcedx-vscode-apex'
lerna ERR! execute Error: Command failed: npm run vscode:package
lerna ERR! execute Executing prepublish script 'npm run vscode:prepublish'...
lerna ERR! execute Error: Command failed: npm list --production --parseable --depth=99999
lerna ERR! execute npm ERR! extraneous: @types/node@6.0.88 …
```

Support packaging and publishing with Node 7

---

package.json
packages/salesforcedx-apex-debugger/package.json
packages/salesforcedx-utils-vscode/package.json
packages/salesforcedx-vscode-apex-debugger/package.json
packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-visualforce/package.json
packages/salesforcedx-vscode/package.json
packages/system-tests/package.json
scripts/publish.js
scripts/reformat-with-prettier.js

When we use lerna --publish, it rewrites package.json and destroys the formatting from prettier. This restores the formatting.
I'm going to have to make a similar change in the develop branch to keep all the formatting consistent.
None.

Reformat with prettier after lerna publish (release/v40.8.0 branch) 

---

packages/system-tests/scenarios/scaffolding.test.ts

Removes part of integration tests verifying that the number of files created is correct. This would be an issue that the CLI command should test and handle.
@W-4271774@

Remove unnecessary check for number of files created in e2e tests

---

packages/salesforcedx-apex-debugger/src/adapter/apexDebug.ts
packages/salesforcedx-apex-debugger/src/constants.ts
packages/salesforcedx-apex-debugger/src/index.ts
packages/salesforcedx-apex-debugger/test/unit/adapter/apexDebug.test.ts
packages/salesforcedx-vscode-apex-debugger/src/index.ts

The debug adapter handles Apex Debugger SystemWarning event by logging the description to debug console and handing it off to salesforcedx-vscode-apex-debugger to also show in a top level notification.
@W-4178985@

Handle SystemWarning event

---

packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-apex/test/index.ts
packages/salesforcedx-vscode-apex/test/requirements.test.ts

Adds GoToDefinition feature for the current fie. Limited to the following:
- fields
- properties
- local variables
- params
Others will come later. The goal is to get this in incrementally.
@W-4248232, W-4276176@

Add GoToDefinition feature

---

packages/salesforcedx-apex-debugger/src/adapter/apexDebug.ts
packages/salesforcedx-apex-debugger/src/messages/i18n.ts
packages/salesforcedx-apex-debugger/test/unit/adapter/apexDebug.test.ts

When an Apex Debugger session is terminated outside of VS Code, we handle a SessionTerminated event by printing the event description to debug console. Now, we also show an error top-level notification:
When the scratch org or user does not have Debug Apex perm, we show an error top-level notification that suggests they need both org and user perms. We cannot use "sfdx force:schema:sobject" commands to individually detect for org & user perm. The command sobject:list will return ApexDebuggerSession with & without Debug Apex org perm because its org access is only restricted to AuthorApex. The command sobject:describe on ApexDebuggerSession will return the same thing with & without Debug Apex org perm.
@W-4241196, W-4241210@

Fix error messages with starting & stopping debugger session

---

docs/publishing.md
packages/salesforcedx-apex-debugger/src/adapter/apexDebug.ts
packages/salesforcedx-apex-debugger/test/unit/adapter/apexDebug.test.ts

Apex Debugger event SystemInfo only has a value in its description field. It tells the client whether a request matched their session's userId/request/entryPoint filter. It can get pretty noisy so I'm just logging it in the debug console instead of also showing a top-level notification.
@W-4179008@

Log Apex Debugger event SystemInfo

---

packages/salesforcedx-vscode-apex/README.md

Adds docs for Go to Definition in Apex.
Image will load after PR #128 is merged.
@W-4331114@

Add Go To Definition docs for Apex

---

packages/salesforcedx-vscode/README.md

1) Adds language about documentation to section that contains links to each extension. 
2) Replaces "extension bundle" with "extension pack" for consistency with VS Code terminology.

Clarify that extension links point to docs

---

packages/salesforcedx-apex-debugger/src/adapter/apexDebug.ts
packages/salesforcedx-apex-debugger/src/commands/baseCommand.ts
packages/salesforcedx-apex-debugger/src/commands/index.ts
packages/salesforcedx-apex-debugger/src/commands/requestService.ts
packages/salesforcedx-apex-debugger/src/commands/runCommand.ts
packages/salesforcedx-apex-debugger/src/commands/stateCommand.ts
packages/salesforcedx-apex-debugger/src/commands/stepCommands.ts
packages/salesforcedx-apex-debugger/src/constants.ts
packages/salesforcedx-apex-debugger/src/core/breakpointService.ts
packages/salesforcedx-apex-debugger/src/core/sessionService.ts
packages/salesforcedx-apex-debugger/src/core/streamingClient.ts
packages/salesforcedx-apex-debugger/src/index.ts
packages/salesforcedx-apex-debugger/test/unit/adapter/apexDebug.test.ts
packages/salesforcedx-apex-debugger/test/unit/adapter/apexDebugForTest.ts
packages/salesforcedx-apex-debugger/test/unit/commands/baseCommand.test.ts
packages/salesforcedx-apex-debugger/test/unit/commands/runCommand.test.ts
packages/salesforcedx-apex-debugger/test/unit/commands/stateCommand.test.ts
packages/salesforcedx-apex-debugger/test/unit/commands/stepCommands.test.ts
packages/salesforcedx-vscode-apex-debugger/src/index.ts

There are three parts in the debugger that would concern a proxy: CLI calls for Apex Debugger objects (child_process lib), Streaming API (faye lib), and HTTP calls to Apex Debugger APIs (request-light lib). All those readily accept HTTP_PROXY and HTTPS_PROXY environment variables. VS Code doc suggests extensions could handle http proxy settings https://code.visualstudio.com/docs/setup/network, so this PR is for that.
@W-4315069@

Use vscode's http proxy setting

---

packages/salesforcedx-apex-debugger/src/adapter/apexDebug.ts
packages/salesforcedx-apex-debugger/test/unit/adapter/apexDebug.test.ts
packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-core/src/commands/forceDebuggerStop.ts
packages/salesforcedx-vscode-core/src/messages/i18n.ts
packages/salesforcedx-vscode-core/test/commands/forceDebuggerStop.test.ts

Disable debugger capabilities that we don't support. Remove Apex Debugger stop command from right-click menu in the project explorer. Clean up the notifications from the stop command.
@W-4337014, W-4331254@

Fix debugger capabilities and stop command

---

packages/salesforcedx-apex-debugger/src/adapter/apexDebug.ts
packages/salesforcedx-apex-debugger/src/core/breakpointService.ts
packages/salesforcedx-apex-debugger/test/unit/adapter/apexDebug.test.ts
packages/salesforcedx-apex-debugger/test/unit/core/breakpointService.test.ts

If you enable breakpoints on lines 1, 2, 3, VS Code sends three requests to the adapter. Request 1 wants a breakpoint on line 1. Request 2 wants breakpoints on lines 1 & 2. Request 3 wants breakpoints on lines 1, 2, & 3. 
Each breakpoint request is not handled individually from start to finish. Due to nodejs event loop, a breakpoint request will be put aside when it spawns an SFDX CLI process to add/delete breakpoint. The next breakpoint request will start getting handled. 
We also need to watch out for when we delete & add quickly, and vice versa. For example, if you click on line 1 to delete, then click it again to add, the first request will kick off a breakpoint delete with the CLI. The second request starts getting handled, but the adapter already has line 1 in its cache because the …

Update breakpoint reconcile strategy

---

packages/salesforcedx-apex-debugger/src/adapter/apexDebug.ts
packages/salesforcedx-apex-debugger/test/unit/adapter/apexDebug.test.ts
packages/salesforcedx-vscode-apex-debugger/package.json
packages/salesforcedx-vscode-apex-debugger/package.nls.json

Change UserIdFilter into an array so user doesn't have to type commas. Change RequestTypeFilter into an array and suggest possible values. 
Also, remove the stopped event reason so it defaults to just "Paused" in the callstack.
@W-4314787, W-4314153@

Debugger whitelist

---

packages/salesforcedx-sobjects-faux-generator/src/generator/fauxClassGenerator.ts
packages/salesforcedx-sobjects-faux-generator/test/fauxgeneratortest.ts
packages/salesforcedx-utils-vscode/package.json
packages/salesforcedx-vscode-core/test/index.ts

When fields are generated in the SObject faux class, there were situations
where the relationshipName was not always specified.  In that case, there is
a field/childRelationship name that usually ends in “Id”.
This fix uses that name if the relationshipName is missing and strips off the “Id”.
This is consistent with what Apex and IlluminatedCloud expect and do.
Resolves: @W-4344749@

Fix null field showing up in generated SObject faux classes

---

packages/salesforcedx-vscode-core/src/commands/commands.ts
packages/salesforcedx-vscode-core/src/commands/forceDataSoqlQuery.ts
packages/salesforcedx-vscode-core/src/commands/forceOrgCreate.ts
packages/salesforcedx-vscode-core/src/messages/i18n.ts
packages/salesforcedx-vscode-core/test/commands/forceOrgCreate.test.ts
packages/system-tests/package.json

Add alias prompt for force:org:create. The prompt will set the alias inputted by the user with the --setalias flag on the command. If user hits Enter with no alias inputted, the alias will be set to "scratchOrg" by default. If user hits Escape to cancel out, the command should not execute.
@W-4345929@

Add alias prompt and unit tests

---

packages/salesforcedx-sobjects-faux-generator/src/describe/sObjectDescribe.ts
packages/salesforcedx-sobjects-faux-generator/src/generator/fauxClassGenerator.ts

Fix the SObjectDescribe REST calls to use the same apiVersion as the
current cli.  Done by calling sfdx force --json and extracting the
apiVersion output and using that in the describe REST calls
@W-4369079@

Ensure that apiVersion of the cli and REST calls are the same

---

packages/salesforcedx-vscode-apex-debugger/README.md
packages/salesforcedx-vscode/README.md

Adds Apex Debugger docs for VS Code.
"Considerations" language is mostly taken from https://developer.salesforce.com/docs/atlas.en-us.eclipse.meta/eclipse/debugger_considerations.htm
@W-4337237@

Add debugger docs

---

README.md
packages/salesforcedx-vscode-apex-debugger/README.md
packages/salesforcedx-vscode-apex/README.md
packages/salesforcedx-vscode-core/README.md
packages/salesforcedx-vscode-lightning/README.md
packages/salesforcedx-vscode-visualforce-next/README.md
packages/salesforcedx-vscode-visualforce/README.md
packages/salesforcedx-vscode/README.md

* Changes product name from "Salesforce Development Tools for Visual Studio Code" to "Salesforce Extensions for VS Code"
* Removes beta disclaimers from docs
* Removes " (Beta)" from link text for links to other Salesforce DX guides
* Removes links to Salesforce DX Beta group in Success Community
* Moves instructions for verifying SHA values to bottoms of READMEs to avoid distracting the reader
* Adds suggestion to use all extensions in the bundle to the top of the salesforcedx-vscode-apex-debugger README, for consistency with the other READMEs
@W-4359231@

Update product name; remove beta language

---

.appveyor.yml
.travis.yml
packages/salesforcedx-utils-vscode/package.json
packages/salesforcedx-vscode-core/test/index.ts

The installers are now all at v5.9.9.x and we no longer need to use `sfdx update alpha`. Changing the CI jobs to reflect that.
None. Normal CI tasks.

Use V6 with the latest installers

---

packages/salesforcedx-apex-debugger/src/adapter/apexDebug.ts
packages/salesforcedx-apex-debugger/test/unit/adapter/apexDebug.test.ts
packages/salesforcedx-vscode-apex-debugger/package.json

The adapter sends one stopped event to VS Code when we've hit a breakpoint or finished stepping. VS Code sends a stackTraceRequest as a result of that stopped event. Then, for some reason, their tree api refreshes the callstack view which again sends a stackTraceRequest. As a result, our adapter fires off two state requests. If the timing is very close, apex debugger engine could still be processing the first request and cannot evaluate the state again. So, we're locking the stackTraceRequest to process one at a time.
Also, make default type of requestTypeFilter from string to array.
@W-4380397, W-4380128@

Lock stacktraceRequest. Fix default type of requestTypeFilter.

---

packages/salesforcedx-apex-debugger/src/commands/requestService.ts
packages/salesforcedx-apex-debugger/src/constants.ts
packages/salesforcedx-apex-debugger/test/unit/commands/baseCommand.test.ts
packages/salesforcedx-apex-debugger/test/unit/commands/frameCommand.test.ts
packages/salesforcedx-apex-debugger/test/unit/commands/referencesCommand.test.ts
packages/salesforcedx-apex-debugger/test/unit/commands/runCommand.test.ts
packages/salesforcedx-apex-debugger/test/unit/commands/stateCommand.test.ts
packages/salesforcedx-apex-debugger/test/unit/commands/stepCommands.test.ts

Add a client ID in RequestService following the spec in https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/headers_calloptions.htm.
@W-4395263@

Add client identifier to debugger REST calls

---

packages/salesforcedx-vscode-apex-debugger/package.nls.json
packages/salesforcedx-vscode-apex/package.nls.json
packages/salesforcedx-vscode-visualforce/package.json
packages/salesforcedx-vscode-visualforce/package.nls.json

Rename the configuration titles to use the more general "Salesforce" term instead of "Salesforce DX".
@W-4401094@

Rename settings from 'Salesforce DX' to 'Salesforce'

---

packages/salesforcedx-vscode-apex-debugger/README.md

Adds VS Code version 1.17 requirement for salesforcedx-vscode-apex-debugger extension.

Add VS Code version requirement to debugger README

---

packages/salesforcedx-slds-linter/package.json
packages/salesforcedx-sobjects-faux-generator/package.json
packages/salesforcedx-utils-vscode/package.json
packages/salesforcedx-visualforce-language-server/package.json
packages/salesforcedx-visualforce-markup-language-server/package.json
packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-visualforce/package.json
packages/salesforcedx-vscode/package.json
packages/system-tests/package.json

Once they install the pack, vscode prevents them from uninstalling the pack's dependencies, so they won't be able to remove the debugger extension. By bumping the pack's vscode version, the error message should be about the pack's required version instead of a specific dependency.

Debugger requires 1.17 so the extension pack should also require 1.17

---

packages/salesforcedx-vscode/package.json

Changes name that displays in VS Code Marketplace to the official name of the extension pack.
@W-4420480@

Update displayName for extension pack

---

packages/salesforcedx-apex-debugger/src/adapter/apexDebug.ts
packages/salesforcedx-apex-debugger/src/constants.ts
packages/salesforcedx-apex-debugger/test/unit/adapter/apexDebug.test.ts

The debugger adapter asks for line breakpoint info from Apex language server. When the adapter receives the info, it would send an initialized response to vs code so the rest of the debugger launch sequence can proceed. VS Code used to show the debugger controls while launching so if the line breakpoint info takes too long, the user could simply stop the launch. It seems those controls are no longer shown, so if the launch is stuck because of the language server, the user cannot terminate the launch. This change is to use setTimeout to check the status of line breakpoint info after a specified timeout.
@W-4428718@

Default timeout if debugger cannot get line breakpoint info in that time

---

packages/salesforcedx-vscode-visualforce/package.json

Respects the embedded mode inside CSS and JavaScript for Visualforce pages.
Resolves #198

Respect commenting for embedded JavaScript and CSS in Visualforce

---

packages/system-tests/src/main.ts
packages/system-tests/src/spectron/application.ts
packages/system-tests/test_data/keybindings.linux.json
packages/system-tests/test_data/keybindings.osx.json
packages/system-tests/test_data/keybindings.win.json

Add platform keybinding json files to our test_data directory and read the bindings from them directly.
Autobuilds failing because keybinding retrieval is broken. Used to pull them from vscode-docs but they removed the files in https://github.com/Microsoft/vscode-docs/pull/1229

Remove keybinding fetching and use local bindings from test_data

---

packages/salesforcedx-apex-debugger/src/adapter/apexDebug.ts
packages/salesforcedx-apex-debugger/test/unit/adapter/apexDebug.test.ts

I reverted some changes made in https://github.com/forcedotcom/salesforcedx-vscode/pull/194. How it used to work before that PR:
1. VS Code asks the adapter to initialize.
1. The adapter asks apex extension for line breakpoint info.
1. When the adapter gets them (could take however long), it sends an initialized response to VS Code so it can continue the launch. 
https://github.com/forcedotcom/salesforcedx-vscode/pull/194 replaced that sequence with a setTimeout so after the default timeout, the adapter checks if it has received line breakpoint info. If yes, send an initialized response to continue the launch. If not, send error message. It ensured we error out with a message if it takes too long. However, in the case where line breakpoint info is received before the timeout, we don't …

Fix debugger launch sequence

---

packages/system-tests/src/spectron/application.ts

Removes hardcoded path in keybinding retrieval
While path.join does normalize path segments, it would be safer not to have it hardcoded

Remove hardcoded path in keybinding retrieval

---

packages/salesforcedx-sobjects-faux-generator/package.json
packages/salesforcedx-sobjects-faux-generator/src/generator/fauxClassGenerator.ts
packages/salesforcedx-sobjects-faux-generator/src/messages/i18n.ts
packages/salesforcedx-sobjects-faux-generator/src/messages/index.ts
packages/salesforcedx-sobjects-faux-generator/test/fauxClassGenerator.test.ts
packages/salesforcedx-sobjects-faux-generator/test/integration/fauxGenerate.test.ts
packages/salesforcedx-sobjects-faux-generator/test/integration/integrationTestUtil.ts
packages/salesforcedx-sobjects-faux-generator/test/integration/sObjectDescribe.test.ts
packages/salesforcedx-utils-vscode/src/cli/commandExecutor.ts
packages/salesforcedx-utils-vscode/src/cli/index.ts
packages/salesforcedx-utils-vscode/src/cli/localCommandExecutor.ts
packages/salesforcedx-utils-vscode/src/constants.ts
packages/salesforcedx-utils-vscode/src/index.ts
packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-core/package.nls.json
packages/salesforcedx-vscode-core/src/channels/channelService.ts
packages/salesforcedx-vscode-core/src/commands/commands.ts
packages/salesforcedx-vscode-core/src/commands/forceGenerateFauxClasses.ts
packages/salesforcedx-vscode-core/src/messages/i18n.ts

Convert the ForceGenerateFauxClassesExecutor (command) and FauxClassGenerator to properly utilize the support in SfdxCommandLetExecutor to hook into notification, cancellation, and status bar.  This involves creating a LocalCommandExecution to feed the observables from an emitter (exit, error, stdout, stderr). 
Cancellation is checked before each batch of SObject describes is done - as these are the long operations in FauxClassGenerator.
Added fauxGenerateTest for integration tests of the generate() call.
More cleanup of the testing in general to ensure that scratch orgs are deleted, etc.
@W-4358436@

Notify the user of Refresh command status

---

packages/salesforcedx-vscode-core/src/commands/forceApexTestRun.ts
packages/salesforcedx-vscode-core/test/commands/commands.test.ts
packages/salesforcedx-vscode-core/test/commands/forceApexTestRun.test.ts
packages/system-tests/assets/sfdx-simple/force-app/test/default/testSuites/DemoSuite.testSuite-meta.xml

This adds the ability to run force:apex:test:run command with a single Apex class. The command always executes with --synchronous option so the test is debuggable.
@W-4337479@

Run single apex test with synchronous option

---

packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-core/package.nls.json
packages/salesforcedx-vscode-core/src/commands/commands.ts
packages/salesforcedx-vscode-core/src/commands/forceProjectCreate.ts
packages/salesforcedx-vscode-core/src/commands/index.ts
packages/salesforcedx-vscode-core/src/index.ts
packages/salesforcedx-vscode-core/src/messages/i18n.ts
packages/salesforcedx-vscode-core/src/scratch-org-decorator.ts
packages/salesforcedx-vscode-core/test/commands/forceProjectCreate.test.ts
packages/system-tests/scenarios/scaffolding.test.ts

Add command to create a new DX project
@W-4284294@

[WIP] James/create project

---

.travis.yml

Allows OSX builds to fail without blocking a PR
Tests on mac builds have been flakey and don't usually catch errors that the linux build do not catch. Let's make them optional to pass so flakiness does not block a PR.

Allow osx build to fail

---

packages/salesforcedx-apex-debugger/src/adapter/apexDebug.ts
packages/salesforcedx-apex-debugger/src/breakpoints/exceptionBreakpoint.ts
packages/salesforcedx-apex-debugger/src/constants.ts
packages/salesforcedx-apex-debugger/src/core/breakpointService.ts
packages/salesforcedx-apex-debugger/src/index.ts
packages/salesforcedx-apex-debugger/src/messages/i18n.ts
packages/salesforcedx-apex-debugger/test/unit/adapter/apexDebug.test.ts
packages/salesforcedx-apex-debugger/test/unit/adapter/apexDebugForTest.ts
packages/salesforcedx-apex-debugger/test/unit/core/breakpointService.test.ts
packages/salesforcedx-vscode-apex-debugger/package.json
packages/salesforcedx-vscode-apex-debugger/package.nls.json
packages/salesforcedx-vscode-apex-debugger/src/index.ts
packages/salesforcedx-vscode-apex-debugger/src/messages/i18n.ts
packages/salesforcedx-vscode-apex-debugger/src/messages/index.ts
packages/salesforcedx-vscode-apex-debugger/test/index.test.ts
packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-apex/src/constants.ts
packages/salesforcedx-vscode-apex/src/index.ts

This change allows a debugging user to add/remove exception breakpoints for System and user-defined exception types. The list of exception types are acquired from Apex language server. Configuring an exception breakpoint is done through the command palette.
**Typical UX Flow**
1. Open SFDX project in VS Code with Salesforce extensions installed
1. Start Apex Debugger session
1. Open command palette
1. Select `Apex Debug: Configure Exceptions`
1. Select an exception type
1. Select whether to always break (add breakpoint) or never break (remove breakpoint)
1. Wait until a log line in Debug Console verifies the breakpoint has been configured
1. Trigger the Apex exception 
**Notes**
- Exception types in the command palette are listed alphabetically.
- Enabled exception breakpoints will be …

Exception breakpoints

---

packages/salesforcedx-sobjects-faux-generator/src/generator/fauxClassGenerator.ts
packages/salesforcedx-sobjects-faux-generator/src/messages/i18n.ts
packages/salesforcedx-sobjects-faux-generator/test/fauxClassGenerator.test.ts

…lasses
The generated faux classes are intended for use by the Apex Language Server
and for viewing by a developer.   They are not to be edited and an explanatory
comment about being generated is added.
The generation is also changed to make the generated files read-only.
@W-4477572@

Add an explanatory comment to the generated SObject faux classes

---

packages/salesforcedx-vscode-core/src/commands/forceGenerateFauxClasses.ts
packages/salesforcedx-vscode-core/src/messages/i18n.ts

The Refresh SObject Definitions command can take a few seconds.
If the user hits the command again while running, it will do the command
all over again when the first one ends - not intended behavior.
Add checks and a warning message to the command forceGenerateFauxClasses.ts
to disallow multiple invocations at the same time.
@W-4471720@

Prevent repeats of Refresh SObject while running

---

packages/salesforcedx-vscode-core/README.md
packages/salesforcedx-vscode/README.md

* Adds `force:apex:trigger:create` to list of commands supported in salesforcedx-vscode-core
* Mentions Visualforce Language Server in the extension pack's README
@W-4470502@

Add trigger:create; mention VF lang svr in ext pack README

---

.vscode/launch.json
docs/tests.md
package.json
packages/salesforcedx-apex-debugger/package.json
packages/salesforcedx-slds-linter/package.json
packages/salesforcedx-sobjects-faux-generator/package.json
packages/salesforcedx-sobjects-faux-generator/test/unit/fauxClassGenerator.test.ts
packages/salesforcedx-utils-vscode/package.json
packages/salesforcedx-visualforce-language-server/package.json
packages/salesforcedx-visualforce-markup-language-server/package.json
packages/salesforcedx-vscode-apex-debugger/package.json
packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-visualforce/package.json

Add Integration Tests and Unit Tests to framework  …
There are a few tests in salesforcedx-apex-debugger and
salesforcedx-sobjects-faux-generator that require authentication
and create a scratch org.
These are turned into test:integration tests.
Also a test:unit set is created - tests that don’t require
the core server/scratch orgs and are not end-to-end system-tests
@W-4402142@

Add Integration Tests and Unit Tests to framework

---

package.json
packages/salesforcedx-apex-debugger/package.json
packages/salesforcedx-slds-linter/package.json
packages/salesforcedx-slds-linter/src/server/index.ts
packages/salesforcedx-sobjects-faux-generator/package.json
packages/salesforcedx-sobjects-faux-generator/test/integration/fauxGenerate.test.ts
packages/salesforcedx-utils-vscode/package.json
packages/salesforcedx-visualforce-language-server/package.json
packages/salesforcedx-visualforce-language-server/src/modes/javascriptMode.ts
packages/salesforcedx-visualforce-language-server/src/utils/edits.ts
packages/salesforcedx-visualforce-markup-language-server/package.json
packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-apex/test/languageServer.test.ts
packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lwc/package.json
packages/salesforcedx-vscode-visualforce/package.json
packages/system-tests/assets/sfdx-simple/.vscode/settings.json
packages/system-tests/package.json

Switch salesforcedx-vscode over to use TypeScript 2.6 instead of TypeScript 2.4. 
TypeScript 2.6 was released in October so it’s stable now. See https://blogs.msdn.microsoft.com/typescript/2017/10/31/announcing-typescript-2-6/
None. This is an engineering commit.

Upgrade to TypeScript 2.6.2

---

packages/salesforcedx-apex-debugger/src/adapter/apexDebug.ts
packages/salesforcedx-apex-debugger/src/constants.ts
packages/salesforcedx-apex-debugger/test/unit/adapter/apexDebug.test.ts

Add a visual indicator telling the user what exception the user is paused on
@W-4518683@

Add visual indication for exception being paused on

---

packages/salesforcedx-vscode-apex-debugger/README.md
packages/salesforcedx-vscode-apex/README.md

* salesforcedx-vscode-apex README:  
* Adds classes and interfaces to list of Apex items whose definitions you can visit (https://github.com/forcedotcom/salesforcedx-vscode/pull/247)  
* Alphabetizes items in lists of items whose definitions you can visit
* salesforcedx-vscode-apex-debugger README: Adds mention that call stack shows paused-on exception (https://github.com/forcedotcom/salesforcedx-vscode/pull/240)
@W-4605866@

Update docs for v41.16.0

---

docs/publishing.md
package.json
packages/salesforcedx-apex-debugger/package.json
packages/salesforcedx-slds-linter/package.json
packages/salesforcedx-sobjects-faux-generator/package.json
packages/salesforcedx-utils-vscode/package.json
packages/salesforcedx-visualforce-language-server/package.json
packages/salesforcedx-visualforce-markup-language-server/package.json
packages/salesforcedx-vscode-apex-debugger/package.json
packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lwc/package.json
packages/salesforcedx-vscode-replay-debugger/package.json
packages/salesforcedx-vscode-visualforce/package.json
packages/salesforcedx-vscode/package.json
scripts/publish.js
scripts/reformat-with-prettier.js

Node 8 makes it more difficult to `require` global libraries. So the previous way of trying to use the globally installed shelljs library doesn't work. See https://nodejs.org/api/modules.html#modules_loading_from_the_global_folders for the full resolution order.
We could make the old way work but that would require us to either install it in the $HOME directory, or mess with NODE_PATH. Neither sounds desirable.
So, instead the main changes are:
1. You do a `npm install` at the top-level. This brings in the dependencies.
1. When we do a `git clean` we ignore the top-level node_module which only contains things like shelljs, lerna, etc. These are never bundled so they don't affect the generated vsix.

Update the way we publish

---

packages/salesforcedx-vscode-replay-debugger/src/adapter/apexReplayDebug.ts
packages/salesforcedx-vscode-replay-debugger/src/constants.ts
packages/salesforcedx-vscode-replay-debugger/src/core/logContext.ts
packages/salesforcedx-vscode-replay-debugger/src/states/index.ts
packages/salesforcedx-vscode-replay-debugger/src/states/userDebugState.ts
packages/salesforcedx-vscode-replay-debugger/test/unit/adapter/apexReplayDebug.test.ts
packages/salesforcedx-vscode-replay-debugger/test/unit/adapter/debugConsole.test.ts
packages/salesforcedx-vscode-replay-debugger/test/unit/core/logContext.test.ts
packages/salesforcedx-vscode-replay-debugger/test/unit/states/frameEntryState.test.ts
packages/salesforcedx-vscode-replay-debugger/test/unit/states/frameExitState.test.ts
packages/salesforcedx-vscode-replay-debugger/test/unit/states/logEntryState.test.ts
packages/salesforcedx-vscode-replay-debugger/test/unit/states/noOpState.test.ts
packages/salesforcedx-vscode-replay-debugger/test/unit/states/statementExecuteState.test.ts
packages/salesforcedx-vscode-replay-debugger/test/unit/states/userDebugState.test.ts

When it detects `USER_DEBUG` log event, it will:
- Send a `DebugProtocol.OutputEvent` to VS Code with `DebugProtocol.Source`, line number, and `DebugProtocol.OutputEvent.body.category`.
- `DebugProtocol.Source` is always the source of the topmost frame (if any) because the execution in debug log is linear.
- Line number is from the `USER_DEBUG` log line.
- `DebugProtocol.OutputEvent.body.category` is "console" so the color is orange.
**Up for discussion**:
- If the user configures their launch config to print debug log lines as they are parsed, they see:
@ W-4549446@

Print USER_DEBUG messages to console with link to source

---

packages/salesforcedx-vscode-lwc/package.json

Use 0.16.4 of the language server.
The UI tests for this PR will still fail. That's because VS Code 1.20 (latest one) just released some changes in the way we access the elements. This is a test issue and we have manually verified the scenarios and things are working.

Use LWC 0.16.4

---

packages/salesforcedx-utils-vscode/src/i18n/localization.ts
packages/salesforcedx-utils-vscode/test/i18n/localizationTest.ts

Instead of throwing an error when a label is missing, a dummy text is returned.
This improves the development flow. It support a prototyping first approach with having all labels in place. Without that change, all labels have to exist first before one is able to use them. With this change a !!! MISSING LABEL !!! label_key is printed instead of failing with an error. 
This allows postponing the task of finalizing labels till when the code is ready. Additionally it improves error handling by presenting missing labels prominently in the UI. Depending on the code location, a thrown error might go by unrecognized.
n/a

Don't fail for missing labels

---

packages/salesforcedx-vscode-core/README.md
packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-core/package.nls.json
packages/salesforcedx-vscode-core/src/commands/forceApexTestRun.ts
packages/salesforcedx-vscode-core/src/commands/forceApexTestRunCodeAction.ts
packages/salesforcedx-vscode-core/src/commands/index.ts
packages/salesforcedx-vscode-core/src/index.ts
packages/salesforcedx-vscode-core/src/messages/i18n.ts
packages/salesforcedx-vscode-core/test/commands/forceApexTestRun.test.ts
packages/salesforcedx-vscode-core/test/commands/forceApexTestRunCodeAction.test.ts

Invoke `force:apex:test:run` w/ `--resultformat human` to include source link to stacktraces.
Also:
- `force:apex:test:run` invoked w/ `--loglevel error` to avoid distracting warning messages.
- Support for re-running Apex test class and test method code actions via "Recently Used".
This PR requires `force-com-toolbelt` PR #1837.
@W-4709572@

Source link support for test failures

---

packages/salesforcedx-vscode-lwc/src/index.ts
packages/salesforcedx-vscode-lwc/test/index.ts

Removes error of the form 
```
[Extension Host] [salesforce.salesforcedx-vscode-lwc] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for 'eslint.nodePath';, provide the URI of a resource or 'null' for any resource. (at e._validateConfigurationAccess (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:511:635))
```
@W-4650780@

Access preference using scoped resource style

---

.appveyor.yml
.circleci/config.yml
package.json
packages/salesforcedx-vscode-lwc/package.json

Stores the .vsix as part of the artifact for debugging purposes.
@W-4700676@

Store .vsix as part of appveyor CI

---

packages/salesforcedx-vscode-apex-debugger/.vscodeignore
packages/salesforcedx-vscode-replay-debugger/.vscodeignore

Add .vscodeignore to debugger packages so that we don't accidentally package the .vscode binaries for test. This can help prevent unnecessary bloat.
Small tech debt.

Add .vscodeignore to debugger packages

---

scripts/publish-vsix.js

It adds error handling when executing vsce via shelljs. This addresses the execution of the publish scripts not stopping when errors while publishing the extension happen.
@W-4736684@

Error handling for publish vsix script

---

packages/salesforcedx-sobjects-faux-generator/test/integration/config/simpleObjectAndField/objects/MyCustomObject2__c/MyCustomObject2__c.object-meta.xml
packages/salesforcedx-sobjects-faux-generator/test/integration/config/simpleObjectAndField/objects/MyCustomObject3__c/MyCustomObject3__c.object-meta.xml
packages/salesforcedx-sobjects-faux-generator/test/integration/config/simpleObjectAndField/objects/MyCustomObject__c/MyCustomObject__c.object-meta.xml

Disable the external sharing model attribute in the test custom objects. We now disable the external sharing model in scratch orgs. See https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F93A000000HTp1&fId=0D53A00003SQizw for more information.
Backport from develop to make tests pass in release.

Disable external sharing model

---

packages/salesforcedx-slds-linter/package.json
packages/salesforcedx-visualforce-markup-language-server/package.json
packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-lwc/package.json

Pegs the server versions to avoid https://github.com/Microsoft/vscode-languageserver-node/issues/317
We have a special dependency on version 3.4.x for the visualforce branch because of our use of the proposed color provider. 
The rest have been updated to v3.5.x
Fixes the build.

Peg language server versions

---

packages/salesforcedx-slds-linter/package.json
packages/salesforcedx-visualforce-markup-language-server/package.json
packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-lwc/package.json

A fix has been made upstream from Microsoft that will rectify #332. We don't need to bundle all the versions of it, which would help make our .vsix leaner.
Build issues.

[WIP] Do not bundle all the vscode-languageserver/clients/types/protocol

---

packages/salesforcedx-utils-vscode/src/test/testrunner.ts
packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-core/package.nls.json
packages/salesforcedx-vscode-core/src/commands/commands.ts
packages/salesforcedx-vscode-core/src/commands/forceAuthLogout.ts
packages/salesforcedx-vscode-core/src/commands/forceAuthWebLogin.ts
packages/salesforcedx-vscode-core/src/commands/forceStopApexDebugLogging.ts
packages/salesforcedx-vscode-core/src/commands/index.ts
packages/salesforcedx-vscode-core/src/decorators/demo-mode-decorator.ts
packages/salesforcedx-vscode-core/src/decorators/index.ts
packages/salesforcedx-vscode-core/src/decorators/scratch-org-decorator.ts
packages/salesforcedx-vscode-core/src/decorators/traceflag-time-decorator.ts
packages/salesforcedx-vscode-core/src/index.ts
packages/salesforcedx-vscode-core/src/messages/i18n.ts
packages/salesforcedx-vscode-core/src/modes/demo-mode.ts
packages/salesforcedx-vscode-core/src/modes/index.ts
packages/salesforcedx-vscode-core/src/notifications/notificationService.ts
packages/salesforcedx-vscode-core/src/traceflag/developerLogTraceFlag.ts
packages/salesforcedx-vscode-core/test/commands/commands.test.ts
packages/salesforcedx-vscode-core/test/commands/forceApexTestRun.test.ts
packages/salesforcedx-vscode-core/test/commands/forceApexTestRunCodeAction.test.ts
packages/salesforcedx-vscode-core/test/commands/forceAuthLogout.test.ts
packages/salesforcedx-vscode-core/test/commands/forceAuthWebLogin.test.ts
packages/salesforcedx-vscode-core/test/commands/forceOrgCreate.test.ts
packages/salesforcedx-vscode-core/test/commands/forceProjectCreate.test.ts
packages/salesforcedx-vscode-core/test/modes/index.test.ts
packages/salesforcedx-vscode-core/test/traceflag/DeveloperLogTraceFlag.test.ts

Supports demo mode from the CLI. If we detect that SFDX_ENV is set to DEMO we activate demo mode, which does two things:
1. Shows the status bar item at the bottom right corner.
2. If the user authenticates against a non-trial org, we warn the user and ask if she wants to proceed.
@W-4714447@

Add demo mode for VS Code

---

package.json

I've noticed that a lot of times (myself included) that we have pushed to GitHub without first running `npm run lint`. Instead of trying to force everyone to remember to do so, I've automated it using [husky](https://www.npmjs.com/package/husky).
So, now when you do a `npm install` it will set up everything for you.
Now, when you do a `git push` it will run lint first for you.
If for some reason you want to bypass this, you can always do `git push --no-verify` to skip all the hooks.
Code health.

Run npm lint before push

---

packages/salesforcedx-vscode-apex-debugger/README.md
packages/salesforcedx-vscode-apex/README.md
packages/salesforcedx-vscode-core/README.md
packages/salesforcedx-vscode/README.md

* Adds links to wiki pages from Resources lists
* Clarifies that Go To Definition works only for user-defined Apex types (and updates capitalization of related list items to comply with style standards)
* Adds info about demo mode to README for salesforcedx-vscode-core
https://github.com/forcedotcom/salesforcedx-vscode/pull/347
https://github.com/forcedotcom/salesforcedx-vscode/pull/335

Update docs for v42.7.0

---

packages/salesforcedx-vscode-core/src/commands/forceAuthWebLogin.ts

Removes an unused variable on forceAuthWebLogin to fix a lint error.
During release tasks we got a lint error:
salesforcedx-vscode/packages/salesforcedx-vscode-core/src/commands/forceAuthWebLogin.ts[16, 10]: 'CancellationToken' is declared but its value is never read.

Remove unused variable

---

packages/salesforcedx-apex-debugger/package.json
packages/salesforcedx-apex-debugger/test/integration/adapter.test.ts
packages/salesforcedx-apex-debugger/test/unit/adapter/apexDebug.test.ts
packages/salesforcedx-vscode-apex-debugger/package.json

This allows interactive debugger to work on Windows when there's spaces in the project's path
@W-4709469@

Bump version for vscode debugger modules to use their uri to path fixes

---

packages/salesforcedx-apex-debugger/test/integration/config/variables/source/permissionsets/DebugApex.permissionset-meta.xml
packages/salesforcedx-vscode-replay-debugger/adaptertest/unit/core/logContext.test.ts
packages/salesforcedx-vscode-replay-debugger/src/core/logContext.ts

Sample signature is `BotController.findMatchingHandlerIfPossible(BotController.HandlerMapping, String, Map<String,String>, List<String>)`, so we need to remove the params then the method name.
@W-4852805@

Fix getting the uri for a signature with inner class

---

packages/salesforcedx-vscode-replay-debugger/src/breakpoints/checkpointService.ts
packages/salesforcedx-vscode-replay-debugger/src/index.ts

1. Update to remove the checkpoint correctly if it fails to create.
2. The result message from the checkpoint create can actually result in a message that is not a ApexExecutionOverlayFailureResult but, is instead, is just a string. This can happen in the case where maybe the user loses network connectivity and can't connect to the appserver. The message returned in that case is just a string. If we're unable to parse the error message as an ApexExecutionOverlayFailureResult then just give the error string as the error message.
3. Last but not least, instead of showInformationMessage when we retrieve the breakpoint information, just print it to the console like the other informational messages.
@W-4719064@

Update to remove checkpoint from VS Code if it fails to create

---

.travis.yml

The https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz now untars to a directory that contains the version number. So we need to handle this differently.
Build issues on Travis on Linux.

Untar to sfdx folder

---

.appveyor.yml
package.json
packages/salesforcedx-sobjects-faux-generator/package.json
packages/salesforcedx-utils-vscode/package.json
packages/salesforcedx-utils-vscode/src/cli/commandExecutor.ts
packages/salesforcedx-vscode-core/src/commands/isvdebugging/bootstrapCmd.ts

The new Salesforce CLI installers no longer produce a sfdx.exe. Instead it produces a sfdx.cmd. When using a .cmd on Windows, we need a different way to launch this. See https://nodejs.org/api/child_process.html#child_process_spawning_bat_and_cmd_files_on_windows
We also need to make sure that we use the old way for customers who are still on the older installers, which are still on sfdx.exe
@W-4914336@
Resolves #383

Handle both sfdx.cmd and sfdx.exe on Windows

---

packages/salesforcedx-vscode-apex/README.md

Formerly, this link pointed to the IDE2 docs. Now it points to this repo's wiki. I looked at the (now-retired) doc that we previously pointed to, and it didn't really contain useful info that's not already in the wiki.
@W-4682014@

Update Apex Language Server link to point to wiki

---

packages/salesforcedx-vscode-replay-debugger/src/breakpoints/checkpointService.ts
packages/salesforcedx-vscode-replay-debugger/src/constants.ts
packages/salesforcedx-vscode-replay-debugger/src/messages/i18n.ts
packages/salesforcedx-vscode-replay-debugger/test/unit/checkpoints/checkpointService.test.ts

There are 3 bug fixes here.
W-4919185 - The checkpoint result was useful for diagnostics when doing the initial work on the feature. Because we're not creating the checkpoint if there's a failure (we remove it) it's far less useful. Move the checkpoint result onto the CheckpointNode instead of making it its own CheckpointInfoNode.
W-4919352 - The difference in behavior is due to not checking canSetLineBreakpoint before passing things off to the appserver. Once that check is in place if the user tries to create a checkpoint on an invalid line it'll give them an error "Checkpoints can be set only on a valid line of Apex source." 
W-4919978 - This error message is "confusing" if you're not getting in from SFDX after passing in an invalid typeRef to create a checkpoint from the command line. …

Replay Debugger Bug Fixes

---

packages/salesforcedx-apex-debugger/src/core/breakpointService.ts
packages/salesforcedx-apex-debugger/src/core/sessionService.ts
packages/salesforcedx-apex-debugger/test/unit/core/breakpointService.test.ts
packages/salesforcedx-apex-debugger/test/unit/core/sessionService.test.ts
packages/salesforcedx-utils-vscode/src/cli/commandBuilder.ts
packages/salesforcedx-utils-vscode/src/cli/commandOutput.ts
packages/salesforcedx-utils-vscode/src/cli/forceConfigGet.ts
packages/salesforcedx-utils-vscode/src/cli/forceOrgDisplay.ts
packages/salesforcedx-utils-vscode/test/cli/commandBuilderTest.ts
packages/salesforcedx-utils-vscode/test/cli/forceConfigGet.test.ts
packages/salesforcedx-utils-vscode/test/cli/forceOrgDisplay.test.ts
packages/salesforcedx-vscode-core/src/commands/forceApexLogGet.ts
packages/salesforcedx-vscode-core/src/commands/forceAuthWebLogin.ts
packages/salesforcedx-vscode-core/src/commands/forceDebuggerStop.ts
packages/salesforcedx-vscode-core/src/commands/forceStartApexDebugLogging.ts
packages/salesforcedx-vscode-core/src/commands/isvdebugging/bootstrapCmd.ts
packages/salesforcedx-vscode-core/test/commands/forceApexLogGet.test.ts
packages/salesforcedx-vscode-core/test/commands/forceAuthWebLogin.test.ts
packages/salesforcedx-vscode-core/test/commands/forceDebuggerStop.test.ts
packages/salesforcedx-vscode-core/test/commands/forceStartApexDebugLogging.test.ts
packages/salesforcedx-vscode-core/test/commands/isvdebugger/bootstrapCmd.test.ts
packages/salesforcedx-vscode-lwc-next/package.json
packages/salesforcedx-vscode-lwc-next/test/eslint.test.ts
packages/salesforcedx-vscode-lwc-next/test/index.ts
packages/salesforcedx-vscode-lwc/package.json
packages/salesforcedx-vscode-lwc/test/eslint.test.ts
packages/salesforcedx-vscode-lwc/test/index.ts

This change standardizes CLI calls that need --json to use `CommandBuilder.withJson()`. In `withJson()`, it will append `--loglevel fatal` to ignore warnings from CLI so we avoid getting multiple JSON objects.
Additionally, CLI outputs messages when it's updating to the latest version. When this happens with a command that needs --json, the messages are in human-readable format and it cannot be supressed with `--loglevel fatal`. You would see something like this:
```
sfdx-cli: Updating to ...
{ ... the JSON we care about ... }
```
The update messages actually go to stderr, so the fix is to ignore stderr.
@W-4485495@

Ignore warnings and CLI update messages when using --json

---

packages/salesforcedx-vscode-replay-debugger/adaptertest/unit/adapter/apexReplayDebug.test.ts
packages/salesforcedx-vscode-replay-debugger/adaptertest/unit/breakpoints/breakpointUtil.test.ts
packages/salesforcedx-vscode-replay-debugger/package.json
packages/salesforcedx-vscode-replay-debugger/src/adapter/apexReplayDebug.ts
packages/salesforcedx-vscode-replay-debugger/src/breakpoints/breakpointUtil.ts

Replay Debugger's VS Code dependency was bumped to 1.21 to detect breakpoint changes without an active debugger session. However, from 1.21 and above, VS Code changed their `DebugProtocol.SetBreakpointsArguments.source.path`. It used to give lower case Windows drive (e.g. c:\foo.cls). But now it gives C:\foo.cls.
That path is converted to a URI that is then validated against language server. The language server returns lower case Windows drive, so the upgrade to 1.21 broke the validation. Changing vscode-debugadapter version to 1.28 makes sure the debugger extension converts that path to the same URI provided by language server.
@W-4995585@

Bump vscode-debug dependencies to 1.28

---

packages/salesforcedx-vscode-replay-debugger/package.json
packages/salesforcedx-vscode-replay-debugger/src/index.ts

There are a couple of things here
1. If the user has previously loaded a log to debug, save that path off. If the user starts a new debug session and is prompted to load a log then the getLogFileName will use that path as the default, if it still exists.
2. If the user has used the SFDX command to download logs, they'll downloaded to the .sfdx/tools/debug/logs sub-directory of the current workspace. If that directory exists and there's no previously loaded log folder, then we'll use that. Otherwise we'll stick with the .sfdx which was the previous default.
@W-4995493@

Remember the last open log folder for log picker

---

packages/system-tests/src/main.ts
scripts/install-vsix-dependencies.js

Use the new location for VS Code executables.
See https://github.com/Microsoft/vscode-extension-vscode/commit/43a8268ef8075ddec04f901f8bc03f3b5d172351#diff-f900621cc6a1719b5473baf0191f297b
Build failures for integration tests.

Use new location of VS Code executable for test

---

packages/salesforcedx-vscode-core/src/commands/isvdebugging/bootstrapCmd.ts

Ensure that the global environment is skipped during bootstrap command. This prevents inheritance of global auth variables from a previous (old) session.
@W-4998734@

Do not inherit global env during Bootstrap

---

packages/salesforcedx-vscode-apex-replay-debugger/package.json
packages/salesforcedx-vscode-apex-replay-debugger/package.nls.json
packages/salesforcedx-vscode-apex-replay-debugger/src/commands/launchFromLogFile.ts
packages/salesforcedx-vscode-apex-replay-debugger/src/constants.ts
packages/salesforcedx-vscode-apex-replay-debugger/src/index.ts
packages/salesforcedx-vscode-apex-replay-debugger/test/unit/adapter/debugConfigurationProvider.test.ts

Added the command "SFDX: Launch Apex Replay Debugger with Last Log File" which will start a new debugging session with the last log debugged. Note: This command is only available if there isn't an active debug session. The reason for this is that the Restart Debugging command (through the menu option or through the button on the debug panel) will already restart the session with the same parameters. 
As part of this fix, store the last debugged log and the last debugged log directory in the workspaceState Memento. This will persist both variables for the workspace similar to the way breakpoints are persisted which is to say if you were to unload/reload the same project we'd still have the last log and last log directory if they were previously set (otherwise we'd prompt).
Also, fixed an …

Add command to debug last used log

---

packages/salesforcedx-vscode-lwc-next/package.json
packages/salesforcedx-vscode-lwc/package.json
packages/salesforcedx-vscode-lwc/package.nls.json
packages/salesforcedx-vscode-lwc/src/commands/forceLightningLwcCreate.ts
packages/salesforcedx-vscode-lwc/src/index.ts
packages/salesforcedx-vscode-lwc/src/messages/i18n.ts

The main changes are:
1. The command to call the way we scaffold a new component (requires new version of the Salesforce CLI)
2. The version of the language server that we are using
@W-5028685@

Make lwc-next the current version of lwc

---

packages/salesforcedx-apex-debugger/package.json
packages/salesforcedx-apex-replay-debugger/package.json
packages/salesforcedx-slds-linter/package.json
packages/salesforcedx-sobjects-faux-generator/package.json
packages/salesforcedx-utils-vscode/package.json
packages/salesforcedx-visualforce-language-server/package.json
packages/salesforcedx-visualforce-markup-language-server/package.json
packages/salesforcedx-vscode-apex-debugger/package.json
packages/salesforcedx-vscode-apex-replay-debugger/package.json
packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lwc-next/package.json
packages/salesforcedx-vscode-lwc/package.json
packages/salesforcedx-vscode/package.json

Webview Panels in VS Code are only available in version 1.23 and higher.
To support custom UI we need to be able to use webview panels.
I separated this from #451 to make it clearer than this is a version bump.
@W-5013822@

Bump vscode dependency to 1.23

---

packages/salesforcedx-apex-replay-debugger/src/adapter/apexReplayDebug.ts
packages/salesforcedx-apex-replay-debugger/test/unit/adapter/apexReplayDebug.test.ts

With a Live Share session enabled, the ordering of requests/events doesn't appear to be consistent. Live Share team is still looking into it; their suggestion is to fix our `InitializedEvent`. The issue did expose a flaw in when the replay debugger sends an `InitializedEvent` to VS Code. It should do it after `LogContext` is initialized because it's actually ready for breakpoints and etc.
@W-5013801@

Send InitializedEvent when LogContext is ready

---

packages/salesforcedx-apex-replay-debugger/package.json

Apex Replay Debugger is open beta in Summer '18. We should use `preview: true` as documented at https://code.visualstudio.com/docs/extensionAPI/extension-manifest
@W-5001732@

Mark apex replay debugger as preview

---

packages/salesforcedx-vscode-core/src/decorators/scratch-org-decorator.ts

This pr adds an event listener to detect the creation of the config file where the default scratch org is specified. That event is used to update the scratch org shortcut in the vscode status bar. 
W-4959520: The scratch org shortcut was not showing up in the vscode status bar in cases where the <workspace-dir>/.sfdx/sfdx-config.json was created after the creation of the scratch org. This is because we only had an event listener listening to updates made to the sfdx-config.json file, and no event listener detecting the creation of the file.

Add an event listener for the creation of the sfdx-config file

---

packages/salesforcedx-vscode-core/package.json

Fix capitalization of "Integration" in salesforcedx-vscode-core package's display name.
Per https://github.com/forcedotcom/salesforcedx-vscode/pull/463#discussion_r193571519

Fix capitalization of package display name

---

.circleci/config.yml
package.json

Turn on Synk monitoring on each build for new vulnerabilities. This will run [`snyk monitor`](https://snyk.io/docs/using-snyk#monitor) and upload the results to https://snyk.io/org/vazexqi for now. I've already enquired about a global one for forcedotcom.
This will continuously update the security checks on each build (and, if no builds happen, it's set to check each day).
I've added @lcampos and @DatGuyJonathan as admins to https://snyk.io/org/vazexqi for now.
Trust.

Turn on Synk monitoring on each build for new vulnerabilities

---

packages/salesforcedx-vscode-core/src/commands/forceDataSoqlQuery.ts
packages/salesforcedx-vscode-core/src/messages/i18n.ts
packages/system-tests/scenarios/forceSoqlQueryUi.test.ts

Adds an extra dropdown for the user to select whether they want to query the "REST API" or "Tooling API". 
W-4365988: Needs a way to be able to specify --usetoolingapi flag for SOQL query

Add an extra quickPick for the api type (REST vs. Tooling API)

---

packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-core/package.nls.json
packages/salesforcedx-vscode-core/src/commands/forceApexTestRun.ts
packages/salesforcedx-vscode-core/src/commands/forceApexTestRunCodeAction.ts
packages/salesforcedx-vscode-core/test/channels/index.test.ts
packages/salesforcedx-vscode-core/test/commands/forceApexTestRun.test.ts
packages/salesforcedx-vscode-core/test/commands/forceApexTestRunCodeAction.test.ts

Adds a configuration flag indicating whether code coverage should be retrieved when running Apex Unit Tests (@vazexqi  - this is a replacement for the previous pull request - this one is cleaner without all of the messy history).
#473

Add a setting flag for retrieving coverage when running Apex unit tests

---

packages/salesforcedx-vscode-core/src/commands/isvdebugging/bootstrapCmd.ts
packages/salesforcedx-vscode-core/src/index.ts
packages/salesforcedx-vscode-core/src/messages/i18n.ts

salesforcedx-vscode-core does some environment setup for ISV Debugger. The setup allows SFDX commands to work in an ISV Debugger project. If there's an exception during the setup, it prevents salesforcedx-vscode-core extension to activate, therefore other extensions that depend on it also fail to activate.
So, this just catches the error, outputs it to a console in VS Code Developer Tools, and tells the user there was a problem with the setup. If there's an error, the user can still start and use the isv debugger, but SFDX commands won't work.
@W-5093261@

Wrap environment setup for isv debugger in a try-catch

---

packages/salesforcedx-visualforce-language-server/src/visualforceServer.ts
packages/salesforcedx-vscode-apex/src/languageServer.ts
packages/salesforcedx-vscode-lwc-next/src/index.ts
packages/salesforcedx-vscode-lwc/src/index.ts
packages/salesforcedx-vscode-visualforce/src/extension.ts

Specify a document selector for Apex, Visualforce, and LWC. This follows best practice principles from https://code.visualstudio.com/docs/extensionAPI/document-selectors. 
Currently a warning only occurs when you are running from Code Insiders with debugging turned on but this is good to fix.
@W-5035486@

Specify document selector

---

docs/commit-guidelines.md

Add guidelines for Git commit messages. 
I've seen us using different styles. This PR and the final document is meant to codify the conventions that we have and to help new contributors get up to speed.
Trust.

Add guidelines for Git commit messages

---

packages/salesforcedx-vscode-core/src/index.ts

The core extension runs `force:config:get` from the root workspace folder, so the filewatcher for sfdx-config.json should only watch the immediate sfdx-config.json. Previously, it had `**` in the path so any child SFDX projects would unnecessarily trigger the CLI command for the root workspace folder.
@W-5133366@

Set filewatcher on the immediate .sfdx/sfdx-config.json

---

.github/ISSUE_TEMPLATE/Bug_report.md

Adds a notice about github not being an official support channel.
N/A

Added notice to github bug template

---

packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-core/package.nls.json
packages/salesforcedx-vscode-core/src/commands/forceProjectCreate.ts
packages/salesforcedx-vscode-core/src/commands/index.ts
packages/salesforcedx-vscode-core/src/commands/isvdebugging/bootstrapCmd.ts
packages/salesforcedx-vscode-core/src/index.ts
packages/salesforcedx-vscode-core/test/commands/commands.test.ts
packages/salesforcedx-vscode-core/test/commands/forceProjectCreate.test.ts
packages/system-tests/src/spectron/client.ts
tslint.json

Adds a command that calls out to the Salesforce CLI to generate a manifest for working with non-scratch orgs. For those curious about this feature, it requires the latest version (unpublished) of the Salesforce CLI to work.
@W-5070910@

Add SFDX: Create Change-set-based Project command

---

packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-core/package.nls.json
packages/salesforcedx-vscode-core/src/commands/forceAuthDevHub.ts
packages/salesforcedx-vscode-core/src/commands/forceAuthWebLogin.ts
packages/salesforcedx-vscode-core/src/commands/index.ts
packages/salesforcedx-vscode-core/src/index.ts
packages/salesforcedx-vscode-core/src/messages/i18n.ts
packages/salesforcedx-vscode-core/test/commands/forceAuthDevHub.test.ts
packages/salesforcedx-vscode-core/test/commands/forceAuthWebLogin.test.ts

Renamed the existing forceAuthWebLogin to forceAuthDevHub so that
forceAuthWebLogin could be repurposed for the `SFDX: Authorize an Org` 
command.
* Adds a new command that authenticates an org and sets it as the 
default username
* Supports demo mode, similar to the existing command `SFDX: Authorize a Dev Hub`
* Hides the new command behind the `salesforcedx-vscode-core.change_set_based_tools.enabled` perm
For change set development, users should be able to authorize their production and 
sandbox orgs.
@W-5070919@

Add SFDX: Authenticate an Org

---

.gitignore
package-lock.json

Use package-lock at top level of the repo to lock down module version's being used. This is to address current security issues with eslint-scope (https://status.npmjs.org/incidents/dn7c1fgrr7ng)

Use package-lock on repo to lock module versions being used.

---

packages/salesforcedx-vscode-apex/src/languageServer.ts
packages/salesforcedx-vscode-lwc-next/package.json

When lwc-next is not installed, use the old type definitions, i.e., @apex/MyClass.MyMethod.
If lwc-next is installed, use the new type definitions, i.e, @salesforce/apex/MyClass.MyMethod
@W-4987185@

Generate a default export for the type definitions

---

packages/salesforcedx-vscode-lwc-next/package.json
packages/salesforcedx-vscode-lwc/package.json

Updates lwc & lwc-next extension to the latest language server version.
@W-5215984@

Update lwc-language-server to the latest version @W-5215984@

---

packages/salesforcedx-vscode-core/README.md

Updates doc to explain how to retrieve Apex code coverage results when running tests. We previously added this info to the change log but not to the doc.
@W-5083565@
https://github.com/forcedotcom/salesforcedx-vscode/pull/482

Explain how to retrieve code coverage results

---

packages/salesforcedx-vscode-core/src/commands/commands.ts
packages/salesforcedx-vscode-core/src/commands/forceApexClassCreate.ts
packages/salesforcedx-vscode-core/src/commands/forceApexExecute.ts
packages/salesforcedx-vscode-core/src/commands/forceApexLogGet.ts
packages/salesforcedx-vscode-core/src/commands/forceApexTriggerCreate.ts
packages/salesforcedx-vscode-core/src/commands/forceAuthWebLogin.ts
packages/salesforcedx-vscode-core/src/commands/forceDebuggerStop.ts
packages/salesforcedx-vscode-core/src/commands/forceGenerateFauxClasses.ts
packages/salesforcedx-vscode-core/src/commands/forceLightningAppCreate.ts
packages/salesforcedx-vscode-core/src/commands/forceLightningComponentCreate.ts
packages/salesforcedx-vscode-core/src/commands/forceLightningEventCreate.ts
packages/salesforcedx-vscode-core/src/commands/forceLightningInterfaceCreate.ts
packages/salesforcedx-vscode-core/src/commands/forceProjectCreate.ts
packages/salesforcedx-vscode-core/src/commands/forceStartApexDebugLogging.ts
packages/salesforcedx-vscode-core/src/commands/forceStopApexDebugLogging.ts
packages/salesforcedx-vscode-core/src/commands/forceVisualforceComponentCreate.ts
packages/salesforcedx-vscode-core/src/commands/forceVisualforcePageCreate.ts
packages/salesforcedx-vscode-core/src/commands/isvdebugging/bootstrapCmd.ts
packages/salesforcedx-vscode-core/src/notifications/progressNotification.ts
packages/salesforcedx-vscode-core/test/notifications/progressNotification.test.ts
packages/salesforcedx-vscode-lwc-next/src/commands/forceLightningLwcCreate.ts
packages/salesforcedx-vscode-lwc/src/commands/forceLightningLwcCreate.ts

Fixes the hanging progress bar that prevents 
* `SFDX: Refresh SObject Definitions`
* `SFDX: Turn on Apex Debug Log for Replay Debugger`
* `SFDX: Get Apex Debug Logs...`
from executing. 
W-5227494

*WIP* Fix Hanging Progress Bar

---

packages/salesforcedx-apex-replay-debugger/src/adapter/apexReplayDebug.ts
packages/salesforcedx-apex-replay-debugger/src/constants.ts
packages/salesforcedx-apex-replay-debugger/src/core/heapDumpService.ts
packages/salesforcedx-apex-replay-debugger/src/core/logContext.ts
packages/salesforcedx-apex-replay-debugger/test/unit/adapter/apexReplayDebugVariablesHandling.test.ts
packages/salesforcedx-apex-replay-debugger/test/unit/adapter/heapDumpTestUtil.ts

This is the matching VS Code side changes for adding the Trigger context variables to the heap dump. Like the live debugger these variables show up under the Global variables. 
It's probably worth adding here that collections are not displayed correctly as of yet. That's the next bug I'm working on.
@W-5186304@

First update for Trigger context vars in heapdumps

---

packages/salesforcedx-vscode-core/package.json

Move vscode-extension-telemetry from devDependencies to dependencies since it's not being included in vsix files.
It fixes a bundling issue with telemetry on vsix @W-5066473@

Update dependencies to bundle vscode telemetry

---

packages/salesforcedx-vscode-apex-debugger/package.json
packages/salesforcedx-vscode-apex-replay-debugger/package.json
packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lwc-next/package.json
packages/salesforcedx-vscode-lwc/package.json
packages/salesforcedx-vscode-visualforce/package.json

It makes sure that vscode-extension-telemetry dependency is included in the vsix for all extensions which are now depending on core to load it.
@W-5307674@

Update telemetry dependency for all extensions

---

.appveyor.yml
package.json
packages/salesforcedx-sobjects-faux-generator/test/integration/fauxGenerate.test.ts
packages/salesforcedx-sobjects-faux-generator/test/integration/sObjectDescribe.test.ts
packages/system-tests/package.json

Disable system tests until tests are updated

Temporarily do not run system tests

---

packages/salesforcedx-apex-debugger/package.json
packages/salesforcedx-apex-replay-debugger/package.json
packages/salesforcedx-apex-replay-debugger/test/integration/goldFileUtil.ts
packages/salesforcedx-slds-linter/package.json
packages/salesforcedx-sobjects-faux-generator/package.json
packages/salesforcedx-utils-vscode/package.json
packages/salesforcedx-utils-vscode/src/test/orgUtils.ts
packages/salesforcedx-visualforce-language-server/package.json
packages/salesforcedx-visualforce-markup-language-server/package.json
packages/salesforcedx-vscode-apex-debugger/package.json
packages/salesforcedx-vscode-apex-replay-debugger/package.json
packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lwc-next/package.json
packages/salesforcedx-vscode-lwc/package.json
packages/salesforcedx-vscode-visualforce/package.json
packages/system-tests/package.json

Updates node types to 8.0.0 now that vscode has updated to a newer electron version (https://code.visualstudio.com/updates/v1_26#_nodejs-update)
Comments on PR #555

Update node types to version 8.0.0

---

packages/salesforcedx-vscode-apex/package.json

The Apex Test View should only show up when you have an SFDX project opened. Without this fix, the Apex Test View shows up for all projects.
@W-5296138@

Selectively show apex test view

---

packages/salesforcedx-apex-debugger/package.json
packages/salesforcedx-apex-replay-debugger/package.json
packages/salesforcedx-slds-linter/package.json
packages/salesforcedx-sobjects-faux-generator/package.json
packages/salesforcedx-utils-vscode/package.json
packages/salesforcedx-visualforce-language-server/package.json
packages/salesforcedx-visualforce-markup-language-server/package.json
packages/salesforcedx-vscode-apex-debugger/package.json
packages/salesforcedx-vscode-apex-replay-debugger/package.json
packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lwc-next/package.json
packages/salesforcedx-vscode-lwc/package.json
packages/salesforcedx-vscode/package.json

See the changes in https://code.visualstudio.com/updates/v1_26#_extension-packs-revisited
#562

Use new `extensionPack` key

---

packages/salesforcedx-vscode-lightning/test/deprecatedClassName.test.ts

Updates tests in vscode-lightning extension that were failing. Root cause of the failure is an increase in the time it takes to activate salesforcedx-vscode-core extension.

Fix vscode-lightning test failure

---

packages/salesforcedx-vscode-apex-debugger/package.json
packages/salesforcedx-vscode-apex-replay-debugger/package.json

Updated the package.json for apex debugger and replay debugger to activate when 'apex' is specified.
I checked to see that apex debugger and replay debugger do not get activated and .sfdx folder is not created in non-sfdx projects. Checked to make sure debuggers are still getting activated in sfdx projects. (I'm not sure if this should be tested for something else as well.)
W-4629156

Updated debugger package.json to prevent activation in non sfdx project

---

packages/salesforcedx-vscode-core/src/commands/forceOrgCreate.ts
packages/salesforcedx-vscode-core/test/commands/forceOrgCreate.test.ts

Changes the default alias name to be the folder name rather than the hard-coded string.
This is from the intern, I am just submitting it since his internship ended.

Change default scratch alias to folder name

---

packages/salesforcedx-vscode-lightning/OSSREADME.json
packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lightning/syntaxes/html.tmLanguage.json

Forks the previous version of the html syntax file (https://github.com/textmate/html.tmbundle) and includes it as part of the lightning extension.
#573

Fix lightning component syntax highlighting issues

---

packages/salesforcedx-vscode-apex/src/index.ts
packages/salesforcedx-vscode-apex/src/languageServer.ts
packages/salesforcedx-vscode-apex/src/telemetry/telemetry.ts
packages/salesforcedx-vscode-apex/test/unit/telemetry/telemetry.test.ts

Adds apex extension activation time, Apex LSP errors and startup time to insights.
@W-4883803@

Track Apex LSP startup time, errors and apex extension startup time

---

packages/salesforcedx-vscode-core/src/commands/forceStartApexDebugLogging.ts
packages/salesforcedx-vscode-core/src/context/index.ts
packages/salesforcedx-vscode-core/src/context/workspaceOrgType.ts
packages/salesforcedx-vscode-core/src/messages/i18n.ts
packages/salesforcedx-vscode-core/test/commands/forceStartApexDebugLogging.test.ts
packages/salesforcedx-vscode-core/test/context/workspaceOrgType.test.ts

This pr changes the `SFDX: Turn On Apex Debug Log for Replay Debugger` command to query orgs directly for the user's id so that we can use the command against non-scratch orgs. Previously, the command was using the `sfdx force:org:display` to get the user id of an org, but this command throws an error when called against non-scratch orgs. 
@W-5461537@

SFDX: Turn On Apex Debug Log for Replay Debugger throws an error for non-scratch orgs

---

packages/salesforcedx-apex-replay-debugger/src/core/logContext.ts

When modifying the static variables for heap dump processing it turns out that the staticVariablesClassMap holds shallow copies of the ApexVariableContainers. What was happening is that these were getting modified as part of heap dump processing and not getting restored. The way this manifested itself was after stepping off checkpoint line one of static variable collections was showing all of the fields under "this". This was because of the variablesRef created when displaying the heap dump augmented variables had the same variablesRef value as "this" after things were restored and because the staticVariablesClassMap wasn't backed up with the rest of the stuff.
@W-5490706@

backup and restore staticVariableClassMap when processing heap dumps

---

packages/salesforcedx-vscode-lwc/package.json
packages/salesforcedx-vscode-lwc/src/commands/forceLightningLwcCreate.ts
packages/salesforcedx-vscode-lwc/src/index.ts

Uses the latest version of LWC for Winter '19.
@W-5487489@

Swap LWC with LWC-next

---

packages/salesforcedx-apex-replay-debugger/src/core/heapDumpService.ts
packages/salesforcedx-apex-replay-debugger/test/unit/adapter/apexReplayDebugVariablesHandling.test.ts
packages/salesforcedx-apex-replay-debugger/test/unit/adapter/heapDumpTestUtil.ts

There was an issue where circular references weren't being hooked up correctly. This was causing the value of the name/value pair displayed in VS Code to display the wrong thing. Initially I'd opted stop hooking things up when there was a circular reference but this ended leaving a dangling reference. This also caused the value, when it was computed, to be incorrect as well. Right now, with the way it's hooked up it'll mimic the live debugger which is to say that you can just open up the variables until rapture. There is a slight difference in the replay debugger vs live debugger here. The live debugger does something special when it encounters a circular reference and puts it in braces (see picture) instead of keeping it in the same list/variable format as non-recusive references.
The …

Fix for circular references

---

packages/salesforcedx-apex-replay-debugger/src/states/variableAssignmentState.ts
packages/salesforcedx-apex-replay-debugger/test/integration/config/logs/recursive.gold

There was an issue with log variable processing that happened when the object had properties with the same names as method parameters. If a class had myInteger is a property and a method on that class had myInteger as a parameter, the processing would get confused. Take the following log line segment:
VARIABLE_ASSIGNMENT|[6]|this.myInteger|1|0x759bccda
Instead of processing the variable assignment on "this.myInteger" what ended up happening is that the variable myInteger, which is the parameter, would end up getting processed. Because the log line has a reference, which points back to 'this', we ended up with a myInteger that expanded with all of this' properties. 
The fix was relatively simple, before pulling the local variable, look to see if processing 'this'.
The goldfile test …

Fix log variable processing for object properties and parameters

---

.appveyor.yml
package.json
packages/salesforcedx-vscode-apex-replay-debugger/package.json

Flips the salesforcedx-vscode-apex-replay-debugger-checkpoints.enabled boolean from false to true, enabling checkpoints by default. It was decided for GA that flipping the boolean was enough. A second work item will be created for the removal of the setting and conditional code entirely but those changes would be made at a later date.
@W-5491026@

Enable Checkpoints by default

---

.appveyor.yml

Disables running system test in appveyor builds. This is being done to unblock  PRs from getting merged while we work on a fix for the appveyor builds.

Disable system tests from running in appveyor

---

packages/salesforcedx-apex-replay-debugger/src/adapter/apexReplayDebug.ts
packages/salesforcedx-apex-replay-debugger/src/breakpoints/index.ts
packages/salesforcedx-apex-replay-debugger/src/constants.ts
packages/salesforcedx-apex-replay-debugger/test/integration/adapter.test.ts
packages/salesforcedx-apex-replay-debugger/test/unit/adapter/apexReplayDebug.test.ts
packages/salesforcedx-apex-replay-debugger/test/unit/adapter/apexReplayDebugVariablesHandling.test.ts
packages/salesforcedx-apex-replay-debugger/test/unit/adapter/debugConsole.test.ts
packages/salesforcedx-apex-replay-debugger/test/unit/core/logContext.test.ts
packages/salesforcedx-apex-replay-debugger/test/unit/states/frameEntryState.test.ts
packages/salesforcedx-apex-replay-debugger/test/unit/states/frameExitState.test.ts
packages/salesforcedx-apex-replay-debugger/test/unit/states/statementExecuteState.test.ts
packages/salesforcedx-apex-replay-debugger/test/unit/states/userDebugState.test.ts
packages/salesforcedx-apex-replay-debugger/test/unit/states/variableAssignmentState.test.ts
packages/salesforcedx-apex-replay-debugger/test/unit/states/variableBeginState.test.ts
packages/salesforcedx-vscode-apex-replay-debugger/package.json
packages/salesforcedx-vscode-apex-replay-debugger/package.nls.json
packages/salesforcedx-vscode-apex-replay-debugger/src/adapter/debugConfigurationProvider.ts
packages/salesforcedx-vscode-apex-replay-debugger/src/index.ts
packages/salesforcedx-vscode-apex-replay-debugger/test/unit/adapter/MockJorje.ts
packages/salesforcedx-vscode-apex-replay-debugger/test/unit/adapter/debugConfigurationProvider.test.ts
packages/salesforcedx-vscode-apex-replay-debugger/test/unit/checkpoints/checkpointService.test.ts
packages/salesforcedx-vscode-apex/src/index.ts

Refactors the way the replay debugger configuration is received on initialize. Changing from an event that set line breakpoint information on initialize phase to updating resolveDebugConfiguration to be asynchronous and pass the line breakpoint information as parameters to the debug protocol.
Note: This also includes removing the checkpoint setting.
@W-5402619@

Refactor replay debugger config on initialize

---

packages/salesforcedx-vscode-apex-debugger/README.md
packages/salesforcedx-vscode-apex-debugger/package.json
packages/salesforcedx-vscode-apex-replay-debugger/README.md
packages/salesforcedx-vscode-apex-replay-debugger/package.json
packages/salesforcedx-vscode-apex/README.md
packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-core/README.md
packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-lightning/README.md
packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lwc-next/README.md
packages/salesforcedx-vscode-lwc-next/package.json
packages/salesforcedx-vscode-lwc/README.md
packages/salesforcedx-vscode-lwc/package.json
packages/salesforcedx-vscode-visualforce/README.md
packages/salesforcedx-vscode-visualforce/package.json
packages/salesforcedx-vscode/README.md
packages/salesforcedx-vscode/package.json

Updates the extension names and titles in the readmes to be in line with what other extensions on the Marketplace use.
The second goal of this is to help people find the right extension. Currently, we are seeing higher numbers of downloads on some of the individual extension rather than the extension pack. My hope is this clarification in naming will ensure that when users search "Salesforce" they will find the extension pack as the most likely option.

Updated package names and readmes

---

packages/salesforcedx-vscode-apex-replay-debugger/src/adapter/debugConfigurationProvider.ts
packages/salesforcedx-vscode-apex-replay-debugger/test/unit/adapter/debugConfigurationProvider.test.ts
packages/salesforcedx-vscode/package.json

Updates Apex Replay Debugger's debugConfigurationProvider to check if Apex LSP is ready to provide information. This is needed since the extension(s) being active does not mean Apex LSP is ready.
@W-5402619@

Check if Apex LSP is ready before getting breakpoint info

---

packages/salesforcedx-vscode-apex-debugger/README.md
packages/salesforcedx-vscode-apex-replay-debugger/README.md
packages/salesforcedx-vscode-apex/README.md
packages/salesforcedx-vscode-core/README.md
packages/salesforcedx-vscode-lightning/README.md
packages/salesforcedx-vscode-visualforce/README.md
packages/salesforcedx-vscode/package.json

Renames Salesforce Extension to Salesforce Extension Pack to be consistent with other extension packs.
Also, fixes an extra space that broke the link on the readmes.

Renaming Salesforce Extension

---

packages/salesforcedx-apex-debugger/src/core/streamingService.ts

In Windows, we experience issues initializing the Apex Interactive Debugger because the url we build to connect to the Streaming API has an additional slash, making it an invalid url. The changes here strip the trailing slash of the host url.
Moved PR #751 to be part of release v44.7.0
#722, @W-5622038@

Remove trailing slash on instanceURL

---

packages/salesforcedx-vscode-core/src/commands/forceStartApexDebugLogging.ts
packages/salesforcedx-vscode-core/src/messages/i18n.ts
packages/salesforcedx-vscode-core/src/traceflag/developerLogTraceFlag.ts
packages/salesforcedx-vscode-core/test/traceflag/DeveloperLogTraceFlag.test.ts

This PR changes the `SFDX: Turn On Apex Debug Log for Replay Debugger` command to throw an error when the query for trace flags returns a trace flag with a null debugLevelId. 
https://github.com/forcedotcom/salesforcedx-vscode/issues/761
`SFDX: Turn On Apex Debug Log for Replay Debugger` first queries TraceFlag for any existing DEVELOPER_LOG type logs. If it finds any existing trace flags, it will take the first one from query results, and it will update that trace flag's associated DebugLevel. 
If the trace flag has no associated DebugLevel, then the command is currently returning the error referenced by the issue above. Since trace flags without Debug Levels are now considered invalid, the fix in this pr will notify the user to delete the invalid trace flags with a helpful error …

Show better error message for SFDX: Turn On Apex Debug Log for Replay Debugger when updating a trace flag that is missing a debug level

---

packages/salesforcedx-vscode-core/README.md
packages/salesforcedx-vscode-core/package.nls.json
packages/salesforcedx-vscode-core/src/messages/i18n.ts
packages/system-tests/scenarios/scaffolding.test.ts

This reverts commit 48dd1ef1198ed4753e7ae61e49b9883f5e2c70f7.
@W-5637607@

Revert "Update lightning component command text #774"

---

packages/salesforcedx-vscode-apex/src/views/testOutlineProvider.ts

Rebase and run the automation for the changes sent in PR #776 
This PR will sort tests alphabetically, so that on orgs with many test classes, you can easily find the one you're looking for.
Turn this:
Into this:
Unfortunately, the diff contains a whole lot more than what I've actually changed (just added the sort) due to prettier re-formatting the code.
Might be considered related to #605, though it doesn't add any searching/filtering.
@W-5652397@

Sort Tests (by Test Class Name)

---

packages/salesforcedx-vscode-apex/src/views/testOutlineProvider.ts

Fixes Apex Test sidebar sorting so that the test methods are kept in the same order as they are in the test class.
@W-5652397@

Keep the order of test methods per test class in Apex Test sidebar

---

packages/system-tests/src/areas/common.ts

Saves us 50% (or more) of the old execution time for system tests. Below is the comparison using our longest running test.
Before this: 
- Should execute anonymous apex from current editor : exec time = 2 min 21 sec (avg)
After this: 
- Should execute anonymous apex from current editor : exec time = 56 sec 599 ms (avg)

Avoid screenshots on every word being typed

---

packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-apex/package.nls.json
packages/salesforcedx-vscode-apex/src/index.ts
packages/salesforcedx-vscode-apex/src/views/testOutlineProvider.ts
packages/salesforcedx-vscode-apex/src/views/testRunner.ts
packages/salesforcedx-vscode-apex/test/views/testJSONOutputs.ts
packages/salesforcedx-vscode-apex/test/views/testOutline.test.ts
packages/system-tests/src/areas/common.ts

Looking for some feedback on how I went about this. Also noticed there aren't any tests for the functionality of going to the error/definition, I'll work on that as well.
When right clicking on a test that hasn't run, passed, or is skipped, the menu option now says "Go to Definition" instead of "Display Error", the latter which is shown only when the test has failed. 
W-5368845

Update right click menu label based on test status

---

packages/salesforcedx-vscode-lwc/README.md

Changed the link to use https not http and also found a typo in the link (salesforce was missing the 'c').
@W-5699220@

fix typo in url and change http to https

---

packages/salesforcedx-visualforce-language-server/package.json

Makes typescript a dependency of the salesforcedx-visualforce-language-server package rather than a devDependency, since the typescript module is required in the javascriptMode.ts file. 
This change to move typescript from a dependency to devDependency caused an error when activating our Visualforce Language Server extension https://github.com/forcedotcom/salesforcedx-vscode/pull/793/files#diff-0138c82fb9a6a54a14d9a4cdb8cb6f5aR43. This change moves typescript back to being a dependency, but specifically in our salesforcedx-visualforce-language-server package since that is the package where typescript is required in the code. 
Same change as: https://github.com/forcedotcom/salesforcedx-vscode/pull/861

Move typescript to dependency from devDependency

---

packages/salesforcedx-vscode-core/src/context/workspaceOrgType.ts
packages/salesforcedx-vscode-core/src/telemetry/telemetry.ts
packages/salesforcedx-vscode-core/test/context/workspaceOrgType.test.ts

Fixes current salesforce-vscode-core issue during activation when the cli throws errors like `GenericKeychainServiceError: The service and acount specified in key.json do not match the version of the toolbelt ...`
#742 , [W-5767373](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000005jRQwIAM/view)

Handle cli errors when loading workspace context

---

packages/salesforcedx-apex-debugger/test/integration/adapter.test.ts
packages/salesforcedx-apex-replay-debugger/test/integration/adapter.test.ts
packages/salesforcedx-vscode-apex-debugger/test/vscode-integration/telemetry/telemetry.test.ts
packages/salesforcedx-vscode-apex-replay-debugger/test/vscode-integration/telemetry/telemetry.test.ts
packages/salesforcedx-vscode-apex/test/vscode-integration/telemetry/telemetry.test.ts
packages/salesforcedx-vscode-lightning/test/vscode-integration/telemetry/telemetry.test.ts
packages/salesforcedx-vscode-lwc/test/vscode-integration/telemetry/telemetry.test.ts
packages/salesforcedx-vscode-visualforce/src/extension.ts
packages/salesforcedx-vscode-visualforce/test/vscode-integration/telemetry/telemetry.test.ts
tslint.json

- removes "no-floating-promises" key in tslint.json. TSlint should check this by default
- adds await to functions throughout the project that are flagged by tslint
- ignores 2 linter issues that should not have been flagged 
W-5676815 - Refactor non-debugger vscode extensions to conform to "no-floating-promises" tslint rule

Refactor to enable no-floating-promises typescript rule

---

packages/salesforcedx-vscode-apex/package.json

Splits apex (`.cls` and `.trigger` files) from anon apex (`.apex` files) so that the `.apex` files only get the grammar and not the language server - which doesn't work on anon apex anyway.
Part of #929

Split Apex and Anon Apex languages

---

packages/salesforcedx-vscode-core/src/commands/forceSourceDeploy.ts

Clears source:deploy errors until the next deploy is triggered. This allows users to keep the errors around until everything is addressed.
#771 , @W-5641403@

Clear errors in problem view until next deploy finishes

---

packages/salesforcedx-vscode-core/src/commands/forceSourceDeploy.ts

@W-5641403@
Porting this change done in release/v45.1.0 into develop

Clear errors in problem view until next deploy finishes (#1016)

---

docs/articles/user-guide/org-development-model.md

When creating a new project with manifest, the directory created is called 'manifest', not 'manifests', and the right-click commands on package.xml will not work if the directory is called 'manifests'. Also removed a stray "in" before the link to Metadata API docs.
*Docs changes only, to one article*. 
Replaces two instances of 'manifests' with 'manifest' in the Org Development Model article.
Removes awkward 'in' before Metadata API docs link.

Fix 'manifests' vs. 'manifest' and one other typo

---

packages/salesforcedx-sobjects-faux-generator/package.json
packages/salesforcedx-vscode-apex-debugger/src/index.ts
packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-core/src/constants.ts
packages/salesforcedx-vscode-core/src/index.ts
packages/salesforcedx-vscode-core/src/messages/i18n.ts
packages/salesforcedx-vscode-core/src/util/cliConfiguration.ts
packages/salesforcedx-vscode-core/src/util/index.ts
packages/salesforcedx-vscode-core/test/vscode-integration/util/cliConfiguration.test.ts
packages/system-tests/package.json

Fixes core extension not getting activated when the salesforce cli is not installed or can't be found, which currently causes all the other extensions to fail.
With the new behavior, we check if the cli is installed before executing cli commands during extension activation. If the cli is not installed, a warning message is surfaced to the user pointing them to where they can download the cli.

Fix extensions failing to activate when sfdx cli is missing

---

packages/salesforcedx-vscode-core/src/settings/pushOrDeployOnSave.ts

Right now if a user enables "push-or-deploy-on-save.enabled" they'll have to reload VS Code for the setting to take effect. The reason for this was because of the way registerPushOrDeployOnSave was implemented. At the time we didn't know what the exact performance impact of the onDidSaveTextDocument listener and wanted the ability to be able to turn it off, just in case. My change doesn't actually change any functionality except that we're registering the vscode.workspace.onDidSaveTextDocument() listener regardless of whether the user has the setting enabled or not. The user can now enable/disable the setting without having to reload VS Code for it to take effect.
@W-5896670@

Push or Deploy on Save shouldn't require reloading VS Code

---

packages/salesforcedx-vscode-apex/src/messages/i18n.ts

@lcampos - I made a couple more changes to your messages.
#1145

Edit code coverage messages

---

packages/salesforcedx-vscode-apex/src/codecoverage/statusBarToggle.ts

Updates the icons used by the colorizer status bar. The change now makes sure that the icon displayed is the one that reflects the current status of the feature (On/Off).
W-5951754

Update icons used by colorizer statusbar

---

lerna.json
package.json

This PR bumps the version of Lerna that we are using from 2.4.0 to 3.13.1
W-5917685

Bump Lerna from 2.4.0 to 3.13.1

---

packages/salesforcedx-vscode-core/src/channels/channelService.ts
packages/salesforcedx-vscode-core/src/notifications/notificationService.ts

Commands writing to the output channel were stealing focus. For some command this was happening twice, once during the initial execution and then a second time during the results reporting. The solution here was actually quite simple, OutputChannel.show takes an optional boolean parameter that, when set to true, preserves the focus.
The widgets/commands that were stealing focus:
The notificationService - would steal focus reporting command results (success, fail or cancel)
Apex test runner - would steal focus when reporting a test failure
Apex replay debugger - would steal focus when writing errors to the output window
SfdxCommandletExecutor - would steal focus for any command if showChannelOutput was set (defaults to true)
forceDebuggerStop - would steal focus when stopping the debugger …

Output panel shouldn't steal focus

---

packages/salesforcedx-vscode/CHANGELOG.md

Updates changelog for release v45.8.0

Update changelog v45.8.0

---

packages/salesforcedx-vscode-apex-debugger/src/telemetry/telemetry.ts
packages/salesforcedx-vscode-apex-debugger/test/vscode-integration/telemetry/telemetry.test.ts
packages/salesforcedx-vscode-apex-replay-debugger/src/telemetry/telemetry.ts
packages/salesforcedx-vscode-apex-replay-debugger/test/vscode-integration/telemetry/telemetry.test.ts
packages/salesforcedx-vscode-apex/src/telemetry/telemetry.ts
packages/salesforcedx-vscode-apex/test/vscode-integration/telemetry/telemetry.test.ts
packages/salesforcedx-vscode-core/src/commands/commands.ts
packages/salesforcedx-vscode-core/src/commands/forceApexClassCreate.ts
packages/salesforcedx-vscode-core/src/commands/forceApexTriggerCreate.ts
packages/salesforcedx-vscode-core/src/commands/forceLightningAppCreate.ts
packages/salesforcedx-vscode-core/src/commands/forceLightningComponentCreate.ts
packages/salesforcedx-vscode-core/src/commands/forceLightningEventCreate.ts
packages/salesforcedx-vscode-core/src/commands/forceLightningInterfaceCreate.ts
packages/salesforcedx-vscode-core/src/commands/forceVisualforceComponentCreate.ts
packages/salesforcedx-vscode-core/src/commands/forceVisualforcePageCreate.ts
packages/salesforcedx-vscode-core/src/telemetry/telemetry.ts
packages/salesforcedx-vscode-core/test/vscode-integration/telemetry/index.test.ts
packages/salesforcedx-vscode-lightning/src/telemetry/telemetry.ts
packages/salesforcedx-vscode-lwc/src/commands/forceLightningLwcCreate.ts
packages/salesforcedx-vscode-lwc/src/telemetry/telemetry.ts
packages/salesforcedx-vscode-lwc/test/vscode-integration/telemetry/telemetry.test.ts
packages/salesforcedx-vscode-visualforce/src/telemetry/telemetry.ts

Updates metrics for command execution so that command name is not mixed with directory type. Also updates execution time format for all metrics.
@W-6007844@

Update telemetry for dirType on command events

---

packages/salesforcedx-vscode-apex-debugger/src/telemetry/telemetry.ts
packages/salesforcedx-vscode-apex-debugger/test/vscode-integration/telemetry/telemetry.test.ts
packages/salesforcedx-vscode-apex-replay-debugger/src/telemetry/telemetry.ts
packages/salesforcedx-vscode-apex-replay-debugger/test/vscode-integration/telemetry/telemetry.test.ts
packages/salesforcedx-vscode-apex/src/telemetry/telemetry.ts
packages/salesforcedx-vscode-apex/test/vscode-integration/telemetry/telemetry.test.ts
packages/salesforcedx-vscode-core/src/commands/commands.ts
packages/salesforcedx-vscode-core/src/commands/forceApexClassCreate.ts
packages/salesforcedx-vscode-core/src/commands/forceApexTriggerCreate.ts
packages/salesforcedx-vscode-core/src/commands/forceLightningAppCreate.ts
packages/salesforcedx-vscode-core/src/commands/forceLightningComponentCreate.ts
packages/salesforcedx-vscode-core/src/commands/forceLightningEventCreate.ts
packages/salesforcedx-vscode-core/src/commands/forceLightningInterfaceCreate.ts
packages/salesforcedx-vscode-core/src/commands/forceVisualforceComponentCreate.ts
packages/salesforcedx-vscode-core/src/commands/forceVisualforcePageCreate.ts
packages/salesforcedx-vscode-core/src/telemetry/telemetry.ts
packages/salesforcedx-vscode-core/test/vscode-integration/telemetry/index.test.ts
packages/salesforcedx-vscode-lightning/src/telemetry/telemetry.ts
packages/salesforcedx-vscode-lwc/src/commands/forceLightningLwcCreate.ts
packages/salesforcedx-vscode-lwc/src/telemetry/telemetry.ts
packages/salesforcedx-vscode-lwc/test/vscode-integration/telemetry/telemetry.test.ts
packages/salesforcedx-vscode-visualforce/src/telemetry/telemetry.ts

Ports fix #1224 to release v45.9.0
@W-6007844@

Update telemetry for dirType on command events (#1224)

---

packages/salesforcedx-apex-debugger/package.json
packages/salesforcedx-apex-replay-debugger/package.json
packages/salesforcedx-sobjects-faux-generator/package.json
packages/salesforcedx-test-utils-vscode/package.json
packages/salesforcedx-utils-vscode/package.json
packages/salesforcedx-vscode-apex-replay-debugger/package.json

Version 0.2.1 of request-light has a dependency on a version of http-proxy-agent which contains a security vulnerability. request-light to 0.2.4 uses an updated version of http-proxy-agent in which this vulnerability has been fixed.
@W-5997778@

update request-light to 0.2.4

---

packages/salesforcedx-vscode-core/package.json

Limits create commands to only be exposed on default folders
Closes #852, @W-5746531@

Expose create commands only on default folders

---

packages/salesforcedx-vscode-core/test/vscode-integration/channels/index.test.ts

Fixes test failing because of vscode 1.33.0 (https://github.com/Microsoft/vscode/issues/71947) that's currently blocking other PRs from getting merged.
@W-6028723@

Comment out test failure caused by issue in vscode 1.33.0 and above

---

docs/articles/getting-started/prettier.md

Updates prettier doc to use latest prettier release.

Updated prettier doc to use latest prettier release

---

packages/salesforcedx-vscode-core/src/context/workspaceOrgType.ts
packages/salesforcedx-vscode-core/src/messages/i18n.ts
packages/salesforcedx-vscode-core/src/orgBrowser/orgMetadata.ts
packages/salesforcedx-vscode-core/src/orgPicker/orgList.ts
packages/salesforcedx-vscode-core/src/util/authInfo.ts
packages/salesforcedx-vscode-core/src/util/configUtil.ts
packages/salesforcedx-vscode-core/src/util/index.ts
packages/salesforcedx-vscode-core/test/vscode-integration/util/configUtil.test.ts

Display a message when the user does not have a defaultusername set for the current project OR if the defaultusername is being pulled from the global config instead of the local project config.
If there is no defaultusername in the local or global configs we were already displaying a message to the debug console I just added that message as an informational popup. That message will be displayed if the user create a new project or loads a project that has not authenticated yet.
If the defaultusername is pulled from the global config we will now display a warning message (console and popup) with instructions to authorize an org.
As part of this I refactored the config code out of the OrgAuthInfo class into its own class, ConfigUtil. The fact is, the CLI's ConfigAggregator class should do …

display message based upon defaultname and where it was found or not

---

packages/salesforcedx-vscode-core/package.json

Updates to the latest salesforce/core version, 1.3.3, which includes a fix to parsing package names in `sfdx-project.json` which are not camel-cased.
Issue #1266 , @W-6050587@

Update to latest core version, 1.3.3

---

packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lightning/package.nls.json
packages/salesforcedx-vscode-lightning/src/commands/quickpick/quickpick.ts
packages/salesforcedx-vscode-lightning/src/dxsupport/waitForDX.ts
packages/salesforcedx-vscode-lightning/src/index.ts
packages/salesforcedx-vscode-lightning/src/telemetry/telemetry.ts
packages/salesforcedx-vscode-lightning/src/views/component-tree-provider.ts
packages/salesforcedx-vscode-lightning/test/vscode-integration/telemetry/telemetry.test.ts
packages/salesforcedx-vscode-lightning/tsconfig.json
packages/salesforcedx-vscode-lwc/package.json
packages/salesforcedx-vscode-lwc/src/index.ts
packages/salesforcedx-vscode-lwc/src/telemetry/telemetry.ts
packages/salesforcedx-vscode-lwc/test/vscode-integration/telemetry/telemetry.test.ts
packages/salesforcedx-vscode-lwc/tsconfig.json

- Update the lightning lsps to 2.1.0
- Fix settings.json file being overwritten
- Async startup for aura language server
- Add vscode settings for configuring LSP activation
- Cleanup activation logic for internal and external developers
#1210

update Lightning LSPs to 2.1.0 / add new activation logic

---

packages/salesforcedx-vscode-core/src/commands/commands.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/commands.test.ts

When selecting a custom directory for a create command, the custom options displayed are shown for directories under a project's package directories.
W-5995110

Custom output directory for create commands under package directories only

---

packages/salesforcedx-vscode-core/src/context/workspaceOrgType.ts
packages/salesforcedx-vscode-core/src/index.ts
packages/salesforcedx-vscode-core/src/orgBrowser/metadataOutlineProvider.ts
packages/salesforcedx-vscode-core/src/orgPicker/orgList.ts
packages/salesforcedx-vscode-core/test/vscode-integration/context/workspaceOrgType.test.ts

This PR updates the activation logic for the org picker, org browser, and workspace org type to only collect default username information once.

Update activation logic for default username information

---

packages/salesforcedx-vscode-lightning/src/index.ts
packages/salesforcedx-vscode-lwc/src/index.ts

Fixes an issue where launching in debug mode can cause CPU to spike to 100%

remove -brk option from debug options

---

packages/salesforcedx-vscode-core/src/index.ts
packages/salesforcedx-vscode-core/src/messages/i18n.ts
packages/salesforcedx-vscode-core/src/orgBrowser/index.ts
packages/salesforcedx-vscode-core/src/orgBrowser/metadataCmp.ts
packages/salesforcedx-vscode-core/src/orgBrowser/metadataType.ts
packages/salesforcedx-vscode-core/test/vscode-integration/orgBrowser/metadataCmp.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/orgBrowser/metadataType.test.ts

This PR does the groundwork for retrieving metadata component information for a given metadata type. For types that support folders, we are only fetching the components in the top level public folders at this point.
@W-5980323@

[Org Browser] Lazy loading for metadata components

---

packages/salesforcedx-vscode-core/src/orgPicker/orgList.ts
packages/salesforcedx-vscode-core/test/vscode-integration/orgPicker/orgList.test.ts

Show all the org auth/creation options in the org picker.
W-6143678

Show all the org auth/creation options in picker regardless of auth status

---

packages/salesforcedx-vscode-core/src/orgPicker/orgList.ts
packages/salesforcedx-vscode-core/test/vscode-integration/channels/index.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/orgPicker/orgList.test.ts

This PR allows for scratch orgs associated with the default dev hub username to be displayed even when the default dev hub has no alias set. Also includes a test fix due to the new version of the CLI.
W-6155361

Fix for default dev hub username in org picker and test fix

---

packages/salesforcedx-visualforce-language-server/src/modes/javascriptMode.ts
packages/salesforcedx-vscode-visualforce/.vscodeignore

Update how we import typescript & how we bundle it when creating the visualforce extension. This change will allow us to decrease the size of the visualforce extension from 9MB to 2.5MB
FYI: this is a similar strategy to what VSCode is doing when bundling extensions that rely on `typescript` e.g. Javascript https://github.com/microsoft/vscode/blob/master/extensions/postinstall.js
@W-6330667@

Bundling changes for vf extension

---

packages/salesforcedx-vscode-core/src/settings/pushOrDeployOnSave.ts
packages/salesforcedx-vscode-core/src/telemetry/telemetry.ts
packages/salesforcedx-vscode-core/test/vscode-integration/settings/pushOrDeployOnSave.test.ts

We're suspecting the way the listeners are set up to determine what documents are dirty before kicking of a deploy is problematic for some users. This removes the check for a dirty document before kicking off a deploy and will do so whether or not the file actually changed when a user saves it. To help further investigate, telemetry data is being added. 
W-6330470
#1451

Remove dirty doc check for deploy on save and add telemetry

---

packages/salesforcedx-vscode-core/src/context/workspaceOrgType.ts

Removes a regex that was exclusively used for telemetry purposes. A long enough string would cause the evaluation to error and crash initialization of the core extension.
e.g. defaultUsername = usernameThatDoesntExistAndHasAnIncreadiblyLongLongName
@W-6411742@

Remove regex that evaluates defaultusername

---

packages/salesforcedx-vscode-core/src/commands/forceDescribeMetadata.ts
packages/salesforcedx-vscode-core/src/commands/forceListMetadata.ts
packages/salesforcedx-vscode-core/src/orgBrowser/metadataOutlineProvider.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceDescribeMetadata.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceListMetadata.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/orgBrowser/metadataCmp.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/orgBrowser/metadataType.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/orgBrowser/outlineProvider.test.ts

This PR adds functionality to 'sanitize' any errors that may get thrown before displaying them to the user. It also adds logging for the describeMetadata and listMetadata calls.
@W-6383707@

[Org Browser] Handle errors not in JSON format

---

packages/salesforcedx-utils-vscode/test/unit/cli/orgOpenContainerResultParser.test.ts

Change the test mock URLs to `www.example.com` for security purposes.
Nate Totten has reminded me that the only safe URL to use are reserved ones such as `example.com, net, org` to avoid an accidental visit to a malware site.
More info can be found here: https://www.iana.org/domains/reserved
This is not related to specific work item.

Change test placeholders for security

---

docs/articles-jp/apex/interactive-debugger.md
docs/articles/apex/interactive-debugger.md
packages/salesforcedx-vscode-apex-debugger/package.json
packages/salesforcedx-vscode-apex-debugger/package.nls.json

fixed visibility bug; added prefix to palette command text
@W-6197646@

"Apex Debug: Configure Exceptions" command is visible in non-sfdx projects

---

packages/salesforcedx-utils-vscode/src/cli/commandExecutor.ts
packages/salesforcedx-vscode-core/src/commands/forceDescribeMetadata.ts
packages/salesforcedx-vscode-core/src/commands/forceListMetadata.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceDescribeMetadata.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceListMetadata.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/orgBrowser/metadataCmp.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/orgBrowser/metadataType.test.ts

This PR resolves test failures with the forceListMetadata and forceDescribeMetadata commands. The code has been refactored to follow the pattern used by other commands by overriding the execute command and returning the execution. This also addresses the problem with mocking the observable property on the `execution.processExitSubject`.
@W-6418018@

Resolve test failures in forceListMetadata and forceDescribeMetadata commands

---

packages/salesforcedx-vscode-core/src/commands/forceSourceRetrieveCmp.ts

CustomObject components are in a bundle like format in a local workspace, so we should add them to the set for FilePathExistsChecker.
W-6463163

Add CustomObject to bundle types for path checker

---

packages/salesforcedx-vscode-core/src/orgBrowser/metadataCmp.ts
packages/salesforcedx-vscode-core/test/vscode-integration/orgBrowser/metadataCmp.test.ts

Due to how we were filtering components based on their manageability, we were accidentally omitting standard objects from appearing under CustomObjects. This fixes the filtering condition.
#1542 
W-6467588

Fix not being able to retrieve standard objects in org browser

---

packages/salesforcedx-utils-vscode/src/date/format.ts
packages/salesforcedx-utils-vscode/src/date/index.ts
packages/salesforcedx-utils-vscode/test/unit/date/format.test.ts
packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-core/src/commands/forceApexLogGet.ts
packages/salesforcedx-vscode-core/src/decorators/traceflag-time-decorator.ts

This PR replaces momentjs by using the native locale methods and other date formatting utilities. This is part of the changes needed to reduce the size of the extensions. By removing momentjs, we remove a dependency on a module that is not tree-shakeable.
@W-6587405@

Remove use of momentjs

---

packages/salesforcedx-vscode-apex/package.json

Updates the dependencies in the apex extension to address a limitation with lerna not bundling dependencies that are 2 or more levels deep for local modules.
#1671 , @W-6597872@

Add missing @salesforce/core dependency

---

docs/articles/user-guide/org-browser.md
packages/salesforcedx-vscode-core/src/commands/forceSourceRetrieveMetadata/describers.ts
packages/salesforcedx-vscode-core/src/commands/util/postconditionCheckers.ts
packages/salesforcedx-vscode-core/src/index.ts
packages/salesforcedx-vscode-core/src/messages/i18n.ts
packages/salesforcedx-vscode-core/src/orgBrowser/browser.ts
packages/salesforcedx-vscode-core/src/orgBrowser/index.ts
packages/salesforcedx-vscode-core/src/orgBrowser/metadataOutlineProvider.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceSourceRetrieveMetadata/describers.test.ts

Refresh the component list before kicking off a multi-retrieve triggered by a metadata type BrowserNode. 
W-6633366

Refresh component list before retrieving metadata

---

packages/salesforcedx-vscode-core/src/commands/forceProjectCreate.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceProjectCreate.test.ts

Removes the analytics option from project create since the cli piece will not go out in the next release.

Remove analytics option from project create

---

.circleci/config.yml

(cherry picked from commit fc2f1c1446e82ed4dea90593438b3a925444a3a4)
Port CircleCI cache key change to master

Port CircleCI cache key change to master

---

packages/salesforcedx-vscode-core/src/commands/forceProjectCreate.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceProjectCreate.test.ts

Adds the `analytics` template option to the `SFDX: Project Create ...` command.
@W-6819727@

Add analytics option to project create command

---

packages/salesforcedx-vscode-core/src/orgBrowser/browser.ts

This PR fixes a bug with displaying the correct org name/alias in the org browser. The bug had to do with how the visibility event was being registered.
@W-6767384@, #1761

Fix to display correct org name/alias in org browser

---

.vscode/settings.json

Removed legacy prettier setting that is no longer used in prettier vscode 3.0

removed legacy prettier setting

---

packages/salesforcedx-vscode/CHANGELOG.md

Changelog for v47.11.0. The release only contains doc changes and will not be released to the marketplace.

Changelog for v47.11.0

---

packages/salesforcedx-utils-vscode/src/helpers/index.ts
packages/salesforcedx-utils-vscode/src/helpers/validations.ts
packages/salesforcedx-utils-vscode/test/unit/helpers/validations.test.ts
packages/salesforcedx-vscode-core/src/commands/forceOrgCreate.ts
packages/salesforcedx-vscode-core/src/messages/i18n.ts
packages/salesforcedx-vscode-core/src/orgPicker/orgList.ts

1) Allow spaces in alias names during scratch org creation.
2) Slight modification for retrieving alias names via the OrgList.
@W-6009445@

Allow spaces in scratch org alias creation

---

packages/salesforcedx-vscode-apex/src/index.ts

This PR fixes an issue where upon failure of syncing sobject definitions, we were sending the error data in an unreadable format. This was occurring because we were accidentally sending the stack trace as `additional data` instead of as part of the error object.
@W-7144699@

Fix telemetry error data on apex activation

---

packages/salesforcedx-utils-vscode/src/cli/commandExecutor.ts

Set SFDX_TOOL on all CLI commands invoked by vscode extensions. The CLI will record that envar to appinsights so we can see what percentage of commands are invoked by vscode.
@W-7162538@

feat: set envar for cli logging

---

packages/salesforcedx-vscode-core/src/telemetry/telemetryReporter.ts

Logs the `vscode.env.uiKind` (current values are either "Desktop" or "Web") as a common telemetry property. This way we can filter in AppInsights based on whether a telemetry event comes from the Desktop client or Web client.
W-6984859

Log vscode.env.uiKind as common telemetry property

---

packages/salesforcedx-vscode-apex/package.json

Updates the apex-tmlanguage dependency to get the latest syntax highlighting updates. Below is a list of updates.
- SOQL when clause highlighting
- Switch statements with multiple string clauses
- JavaDoc support
- Missing apex class highlighting
@W-6532166@, @W-7210864@, @W-5973555@, 
SOQL
JavaDoc
Apex keyword
Strings on switch
SOQL
JavaDoc
Apex keyword
Strings on switch

Update apex-tmlanguage dependency

---

docs/_articles/en/aura/writing.md
docs/_data/sidebar.yml
docs/_redirects

Fixes sidebar and article aura links that are broke
@W-7226967@

Fix broken write-aura doc links

---

.circleci/config.yml

Fixes failing tests in develop branch after the ci jobs started using the latest version of the cli. This is a temporary fix while we sort out the issues in the latest cli version.

Install previous cli version

---

.circleci/config.yml

Ports PR #1990 to the master branch
@W-7230394@

Use cli version v7.45.1 on CircleCI builds (#1990)

---

packages/salesforcedx-utils-vscode/src/cli/commandExecutor.ts
packages/salesforcedx-utils-vscode/test/unit/cli/commandExecutorTest.ts

Updates the assignment of SFDX_TOOL in scenarios where env variables need to be ignored. This fixes the current issues with ISV Debugger.
#2013 , @W-7256523@

Handle scenarios where global envs should be ignored in CLICommandExecutor

---

scripts/publish-vsix.js

Updates publish-vsix.js script to use the global vsce module instead of hardcoding the path to a locally installed one. 
@W-7298800@

Update publish-vsix.js to use the global vsce module

---

packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lwc/package.json

These changes will prevent LWC & Lightning extensions activating in non-Salesforce projects which cause the salesforce-core extension to activate and throw errors.
This addresses issues #1988 and #2065

Prevent lwc and lightning extensions activating in non-Salesforce projects

---

packages/salesforcedx-apex-debugger/src/adapter/apexDebug.ts
packages/salesforcedx-apex-debugger/src/messages/i18n.ts
packages/salesforcedx-apex-debugger/test/unit/adapter/apexDebug.test.ts

This PR addresses the missing label issue with the Apex Interactive Debugger. It handles an issue with the json parsing of the error object and displays a default error message if an unexpected error is thrown.
#2005 , @W-7287990@

Missing/misconfigured label for Apex Interactive Debugger

---

packages/salesforcedx-vscode-apex/package.json

Hide Apex Test sidebar commands from showing in Command Palette. This is needed since these commands cannot run successfully from the Command Palette.
#2088 , @W-7353790@

Hide Apex test sidebar commands from showing in Command Palette

---

.vscode/launch.json

1. Removes duplicate configs for Lightning and LWC Integration Tests.
2. Adds config for running Lightning and LWC Unit Tests.
3. Renamed configs for easier recognition of Test configs.
4. Reordered Replay Debugger config so all Test configs were together.

Changes to Launch Config

---

packages/salesforcedx-vscode-lwc/src/commands/forceLightningLwcStart.ts
packages/salesforcedx-vscode-lwc/test/vscode-integration/commands/forceLightningLwcStart.test.ts

Checks for error logging in the event that the start of the local dev server failed. This output is printed in the event that the address for the server is invalid, or an error was caught during start up.
@W-7462993@

Add check for local dev server start failure

---

docs/_articles/en/user-guide/perf-enhancements.md
docs/_articles/ja/user-guide/perf-enhancements.md
packages/salesforcedx-vscode-core/src/commands/forceSourceDeploySourcePath.ts
packages/salesforcedx-vscode-core/src/commands/forceSourceRetrieveSourcePath.ts
packages/salesforcedx-vscode-core/src/commands/util/libraryCommandlet.ts
packages/salesforcedx-vscode-core/src/commands/util/retrieveParser.ts
packages/salesforcedx-vscode-core/src/messages/i18n.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceSourceRetrieveSourcePath.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/util/retrieveParser.test.ts

Here's an early version of how consuming the new retrieve library endpoint will look like. These changes include a new small wrapper that will handle calling channelservice, notificationservice, showing the progress of the execution, etc.
@W-7500391@

Perf changes for source retrieve

---

packages/salesforcedx-vscode-lwc/src/commands/forceLightningLwcStart.ts
packages/salesforcedx-vscode-lwc/test/vscode-integration/commands/forceLightningLwcStart.test.ts
packages/salesforcedx-vscode-lwc/test/vscode-integration/commands/forceLightningLwcStop.test.ts

Fix for regression caused by initial PR. When stopping the local development server, the user would be presented with errors that they should not see.
@W-7462993@

Fix for serverStarted check

---

packages/salesforcedx-vscode-lwc/src/commands/forceLightningLwcStart.ts
packages/salesforcedx-vscode-lwc/src/messages/i18n.ts
packages/salesforcedx-vscode-lwc/test/vscode-integration/commands/forceLightningLwcStart.test.ts

Adds a check for the error text 'EADDRINUSE: address already in use'. When this happens, we will call the error handling logic with exit code 98.
@W-7148356@

Add check for server address already in use

---

.github/CODEOWNERS

Removes default for adding lightning-tooling when making changes to the lwc and lightning extensions.
@W-7540957@

Update Code Owners to PDT for Lwc and Lightning Extensions

---

packages/salesforcedx-vscode-core/src/commands/forceAuthDevHub.ts
packages/salesforcedx-vscode-core/src/commands/forceAuthWebLogin.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceAuthDevHub.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceAuthWebLogin.test.ts

This PR flips the showChannelOutput boolean based on the environment variable SFDX_CONTAINER_MODE.  When the extensions are running in a container, like visual studio remote development in docker, where the browser is not available to the sfdx cli, the user can see the instructions to manually launch the browser to a url with a token.
I need to manually switch to the output channel
The command automatically shows the output channel
#2195, @W-7491069@

Show the Salesforce CLI channel output when executing auth commands in a container

---

contributing/telemetry.md
packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-core/src/constants.ts
packages/salesforcedx-vscode-core/src/index.ts
packages/salesforcedx-vscode-core/src/telemetry/telemetry.ts
packages/salesforcedx-vscode-core/src/util/cliConfiguration.ts
packages/salesforcedx-vscode-core/src/util/index.ts
packages/salesforcedx-vscode-core/test/vscode-integration/telemetry/index.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/util/cliConfiguration.test.ts

- Honor CLI telemetry setting for extension telemetry
- Disable telemetry for spawned CLI functionality when extension telemetry is disabled
@W-7263491@
Even when telemetry is opted-out in the extension telemetry is still enabled for any spawned CLI functionality. Extension did not honor the CLI disablement setting.
Opting out of extension telemetry will disable telemetry for any spawned CLI functionality. Disabling CLI telemetry will disable extension telemetry.

Honor CLI telemetry disablement setting

---

contributing/telemetry.md
packages/salesforcedx-vscode-core/src/util/cliConfiguration.ts
packages/salesforcedx-vscode-core/test/vscode-integration/util/cliConfiguration.test.ts

- Revert CLI telemetry disablement check
SalesforceDX extensions did not properly activate for previous CLI versions
Extensions will activate properly

Revert CLI telemetry changes

---

packages/salesforcedx-utils-vscode/src/cli/commandOutput.ts

Makes sure we return error info from a CLI execution. Old versions of the CLI used to return error info in stdError but newer versions return it in stdOut.
@W-7287990@, #2160 , #2005

Fix for getting execution errors from the CLI

---

packages/salesforcedx-vscode-lwc/src/commands/forceLightningLwcPreview.ts
packages/salesforcedx-vscode-lwc/test/vscode-integration/commands/forceLightningLwcPreview.test.ts

Fixes "SFDX: Preview Component Locally" in Windows
Fixes #1903, @W-7387219@
It is throwing an error - SFDX: Preview Component Locally failed to run. Can't find the Lightning Web Components module in. Check that the module exists. 
It should preview the Lightning web component using local development server

Fix preview component in windows @W-7387219@

---

.git2gus/config.json

No longer created Gus issues for the 'type:feature' label.  These user stories will be crafted outside of GH.
Remove the mapping for the 'type:feature' label so that it stops creating Gus User Stories
User story created for the 'feature' label
No Gus WI created for the 'feature' label

Removing the issue creation for Feature label

---

contributing/telemetry.md
packages/salesforcedx-vscode-core/src/util/cliConfiguration.ts
packages/salesforcedx-vscode-core/test/vscode-integration/util/cliConfiguration.test.ts

Guards the check for _disableTelemetry_, which is unsupported by earlier versions of Salesforce CLI
@W-7605599@

Add guard for unsupported cli telemetry setting

---

packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-apex/package.nls.json
packages/salesforcedx-vscode-apex/src/languageServer.ts

Adds a configurable preference to pass to the Apex LSP for printing completion statistics.
Add the following value to the settings.json:
`"salesforcedx-vscode-apex.advanced.enable-completion-statistics": "true"`
@W-7637588@

Add preference for completion statistics

---

packages/salesforcedx-vscode-apex-replay-debugger/package.json

Set salesforcedx-vscode-apex-replay-debugger vscode devDependencies to 1.1.36

Release v48.20.0 - Set vscode devDependencies to 1.1.36

---

contributing/tests.md
package.json
packages/salesforcedx-vscode-lwc/package.json
scripts/run-tests-with-recipes.js
scripts/run-vscode-integration-tests-with-top-level-extensions.js
scripts/run-vscode-integration-tests.js
scripts/vscode-integration-testrunner.js

Update `vscode-test` to `^1.4.0`. (Note: We were originally using `vscode-test` to download VS code, but not to launch tests.)
Update test scripts to use `runTests` from `vscode-test` module: (npm scripts  test:vscode-integration invoke the test scripts)
* `scripts/run-vscode-integration-tests-with-top-level-extensions.js`
* `scripts/run-tests-with-recipes.js`
* `scripts/run-vscode-integration-tests.js`
Update docs:
* Update Running through the CLI section to deprecate `CODE_DOWNLOAD_URL`.
* Remove mentions of vscode/bin/test
@W-7742828@
We use `vscode` module for VS Code integration tests.
We don't use `vscode` module for VS Code integration tests.

Migrate to vscode-test

---

packages/salesforcedx-apex-debugger/package.json
packages/salesforcedx-apex-replay-debugger/package.json
packages/salesforcedx-vscode-apex-debugger/package.json
packages/salesforcedx-vscode-apex-replay-debugger/package.json
packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lwc/package.json
packages/salesforcedx-vscode-visualforce/package.json
packages/system-tests/package.json

* Remove `vscode` dependency from package.json. 
* Add `@types/vscode` dependency.
* Remove `"postinstall": "node ./node_modules/vscode/bin/install"` from `package.json`.
@W-7747884@

Migrate to @types/vscode

---

packages/salesforcedx-vscode-lwc/package.json
packages/salesforcedx-vscode-lwc/package.nls.json
packages/salesforcedx-vscode-lwc/src/testSupport/commands/forceLwcTestWatchAction.ts
packages/salesforcedx-vscode-lwc/src/testSupport/commands/index.ts
packages/salesforcedx-vscode-lwc/src/testSupport/testRunner/testWatcher.ts
packages/salesforcedx-vscode-lwc/test/vscode-integration/testSupport/commands/forceLwcTestWatchAction.test.ts
packages/salesforcedx-vscode-lwc/test/vscode-integration/testSupport/mocks/index.ts
packages/salesforcedx-vscode-lwc/test/vscode-integration/testSupport/testRunner/testWatcher.test.ts

Expose LWC stop watching all tests
@W-7752733@
Stop watching all tests is not exposed in the commands.
Stop watching all tests is exposed in the commands.

Expose LWC stop watching all tests

---

packages/salesforcedx-vscode-core/src/orgBrowser/metadataCmp.ts
packages/salesforcedx-vscode-core/test/vscode-integration/orgBrowser/metadataCmp.test.ts

Updates the Org Browser to allow viewing and retrieving components belonging to an unlocked package.
#2204, @W-7765801@

Add unlocked package support to Org Browser @W-7765801@

---

package.json

Lock Snyk version 1.358.0 since the previous version introduced a regression that causes the extensions to not compile in development mode.

Lock Snyk version 1.358.0

---

packages/salesforcedx-utils-vscode/src/cli/commandOutput.ts
packages/salesforcedx-vscode-core/src/commands/forceProjectCreate.ts
packages/salesforcedx-vscode-core/src/commands/forceStopApexDebugLogging.ts
packages/salesforcedx-vscode-core/src/commands/templates/baseTemplateCommand.ts
packages/salesforcedx-vscode-lwc/src/commands/forceLightningLwcStart.ts

This pr is responsible for handling toString errors for SFDX commands
@W-5757070@

Cancelling a command execution throws errors - W-5757070

---

packages/salesforcedx-utils-vscode/src/cli/forceConfigGet.ts
packages/salesforcedx-vscode-apex/src/index.ts
packages/salesforcedx-vscode-core/src/channels/channelService.ts
packages/salesforcedx-vscode-core/src/index.ts
packages/salesforcedx-vscode-core/src/telemetry/telemetry.ts
packages/salesforcedx-vscode-core/src/util/cliConfiguration.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceAuthDevHub.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceAuthWebLogin.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/util/betaDeployRetrieve.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/modes/index.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/util/cliConfiguration.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/util/configUtil.test.ts
packages/salesforcedx-vscode-lwc/src/testSupport/testIndexer/lwcTestIndexer.ts

Removes the CLI checks done during core activation, adds ignoring `node_modules` in globs used for searching files and updates telemetry checks to use `@salesforce/core` libraries
#2295

Core activation perf changes

---

packages/system-tests/package.json

Fixes a security alert caused by the version of electron used in `system-alerts` module
@W-7792404@

@W-7792404@ Fix security alert on system-tests

---

packages/salesforcedx-vscode-lwc/src/testSupport/commands/forceLwcTestDebugAction.ts
packages/salesforcedx-vscode-lwc/src/testSupport/workspace/getCliArgsFromJestArgs.ts
packages/salesforcedx-vscode-lwc/test/vscode-integration/testSupport/commands/forceLwcTestDebugAction.test.ts
packages/salesforcedx-vscode-lwc/test/vscode-integration/testSupport/mocks/index.ts
packages/salesforcedx-vscode-lwc/test/vscode-integration/testSupport/mocks/vscodeConfiguration.ts
packages/salesforcedx-vscode-lwc/test/vscode-integration/testSupport/workspace/getCliArgsFromJestArgs.test.ts

Fixes LWC test debugging in VS Code 1.47.0, which introduced [new JavaScript debugger](https://github.com/microsoft/vscode-js-debug) by default on 07/10/2020 
@W-7771814@
Debugging LWC tests doesn't work if `"debug.javascript.usePreview"` VS Code setting is set to true (default value) in VS Code 1.47.0
Debugging LWC tests works if `"debug.javascript.usePreview"` VS Code setting is set to true (default value) in VS Code 1.47.0

Support for new JavaScript debugger in VS Code 1.47.0

---

.circleci/config.yml
package.json
packages/salesforcedx-apex-debugger/package.json
packages/salesforcedx-apex-replay-debugger/package.json
packages/salesforcedx-sobjects-faux-generator/package.json
packages/salesforcedx-test-utils-vscode/package.json
packages/salesforcedx-utils-vscode/package.json
packages/salesforcedx-utils-vscode/src/i18n/localization.ts
packages/salesforcedx-visualforce-language-server/package.json
packages/salesforcedx-visualforce-markup-language-server/package.json
packages/salesforcedx-visualforce-markup-language-server/src/utils/paths.ts
packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lwc/package.json
packages/salesforcedx-vscode-visualforce/package.json
packages/system-tests/package.json
packages/system-tests/src/spectron/application.ts

- Update TypeScript version to `3.7.5`.
Version number comes from the stable release tag of the engine version we are using (1.40) in vscode repo. The [commit](https://github.com/microsoft/vscode/blob/86405ea23e3937316009fc27c9361deee66ffbf5/package.json#L135) uses TypeScript version `3.7.1-rc`.
- Remove `@salesforce/kit` dependency, which was a hack to stick to the older `@salesforce/kit` version
@W-7823323@

Update typescript to 3.7.5

---

.circleci/config.yml

Updates the SHA commit message during publishing to remove [skip ci]. This is not needed anymore since we've now moved to using parameters to kick off publishing.

Remove skip ci from sha update message

---

packages/salesforcedx-vscode-lwc/src/commands/forceLightningLwcPreview.ts
packages/salesforcedx-vscode-lwc/src/messages/i18n.ts
packages/salesforcedx-vscode-lwc/test/vscode-integration/commands/forceLightningLwcPreview.test.ts

Adds the feature to show a list of available/compatible devices for LWC Preview command and allows the user to pick a device from the list.
https://github.com/forcedotcom/lwc-dev-mobile/issues/21
The user was presented with an input box and they had to type in the name of the device manually.
The user is presented with a quick pick with a list of available/compatible devices and the user can pick one from the list.

Show list of available devices for LWC Preview

---

packages/salesforcedx-vscode-core/src/commands/forceApexExecute.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceApexExecute.test.ts

This PR addresses the issue where an error is thrown if the user tries to run `SFDX: Execute Anonymous Apex with Editor Contents` when the file has not been saved yet.
#2369, @W-7860461@

Execute anonymous apex if file is not saved

---

packages/salesforcedx-vscode-soql/package.json
packages/salesforcedx-vscode-soql/src/client/client.ts
packages/salesforcedx-vscode-soql/src/index.ts

This PR implements a SOQL language client to connect with the SOQL language server.
@W-7904819@
Functions in the text editor for SOQL files is provided by the Apex language server.
Functions in the text editor for SOQL files is provided by the SOQL language server.
- Since the SOQL extension is not ready to release, the .soql extension support for the Apex language server is not removed. It will be at a later time.
- CI did not work on https://github.com/forcedotcom/salesforcedx-vscode/pull/2395 since that PR was from a fork and not a feature branch.

SOQL Language Client (replaces #2395)

---

packages/salesforcedx-vscode-apex/src/commands/forceGenerateFauxClasses.ts
packages/salesforcedx-vscode-apex/src/commands/index.ts
packages/salesforcedx-vscode-apex/test/vscode-integration/commands/forceGenerateFauxClasses.test.ts

Checks if an org has been authorized before showing a pop up to refresh sobjects
@W-7904975@
The pop up to refresh sobject is not shown if no org is authorized.

@W-7904975@ Do not show SObject refresh pop up when a project does not have a defaultusername

---

packages/salesforcedx-vscode-apex/snippets/apex.json

Added missing "s" in assertion snippets as per documentation of system method.
https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_methods_system_system.htm
Snippets were resolved to "System.AssertEqual" and "System.AssertNotEqual" which gives error: method do not exists.
Snippets are now resolved to "System.AssertEquals" and "System.AssertNotEquals" which are correct method names as per documentation of System class.

Fix snippets for Assertions

---

packages/salesforcedx-vscode-core/src/commands/isvdebugging/bootstrapCmd.ts
packages/salesforcedx-vscode-core/src/messages/i18n.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/isvdebugger/bootstrapCmd.test.ts

Fixes an issue with the ISV Debugger that leaves stale unmanaged source and installed packages. Upon creation of the ISV project, we will remove the current project after prompting the user with an overwrite prompt.
@W-5620191@
_This screen recording shows an old 'Subscriber' project being overwritten by a new 'Subscriber' project with the ISV Debugger. Upon completion, there are still old installed-packages at `.sfdx/tools/installed-packages`, along with old unmanaged source code in `force-app/main/default/classes`._
_This screen recording shows an old 'Subscriber' project being completely overwritten by the new 'Subscriber' project. Only the new installed-packages are seen in `.sfdx/tools/installed-packages` and old unmanaged source code is no longer present._

ISV Debugger - Clear project prior to new creation (@W-5620191)

---

packages/salesforcedx-sobjects-faux-generator/src/generator/fauxClassGenerator.ts
packages/salesforcedx-sobjects-faux-generator/test/unit/fauxClassGenerator.test.ts

Refresh ignores sobjects ending with Share, History, Feed and Event
@W-7905048@
All sobjects definitions are fetched ( about 568)
SObjects ending with Share, History, Feed and Event are filtered out while refreshing SObjects either at the project loading or when "Refresh SObject Definition" command is run (386 sobjects in all).

@W-7905048@ Refresh ignores sobjects ending with Share, History, Feed and Event

---

docs/_articles/en/getting-started/java-setup.md

Fix the exemple on the Advanced Setup for setting up Java.
The type required for the setting "salesforcedx-vscode-apex.java.memory" is integer, not string.
The example have been updated accordingly.
Example in [Advanced Setup](https://developer.salesforce.com/tools/vscode/en/getting-started/java-setup/#advanced-setup) is using string.
Example in Advanced Setup is using integer as required.

Update java-setup.md Advanced setup

---

packages/salesforcedx-sobjects-faux-generator/package.json
packages/salesforcedx-sobjects-faux-generator/src/describe/sObjectDescribe.ts
packages/salesforcedx-sobjects-faux-generator/src/generator/fauxClassGenerator.ts
packages/salesforcedx-sobjects-faux-generator/test/integration/fauxGenerate.test.ts
packages/salesforcedx-sobjects-faux-generator/test/integration/sObjectDescribe.test.ts

Update the Refresh SObject Definitions command to use an sfdx-core connection when making the sObject describe request. A core connection will automatically take care of refreshing an access token, reducing the chances of the command failing due to authentication issues.
@W-7709580@

Make Refresh SObject Definitions more resilient when handling expired access tokens 

---

packages/salesforcedx-vscode-core/src/commands/templates/forceLightningAppCreate.ts
packages/salesforcedx-vscode-core/src/commands/templates/forceLightningComponentCreate.ts
packages/salesforcedx-vscode-core/src/commands/templates/forceLightningEventCreate.ts
packages/salesforcedx-vscode-core/src/commands/templates/forceLightningInterfaceCreate.ts
packages/salesforcedx-vscode-core/src/commands/templates/forceLightningLwcCreate.ts
packages/salesforcedx-vscode-core/src/commands/templates/forceVisualforceComponentCreate.ts
packages/salesforcedx-vscode-core/src/commands/templates/forceVisualforcePageCreate.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/templates/forceLightningAppCreate.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/templates/forceLightningComponentCreate.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/templates/forceLightningEventCreate.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/templates/forceLightningInterfaceCreate.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/templates/forceLightningLWCCreate.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/templates/forceVisualforceComponentCreate.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/templates/forceVisualforcePageCreate.test.ts

Use `@salesforce/templates` library for creating templates. Follow up of #2428
- Lightning App
- Lightning Component
- Lightning Event
- Lightning Interface
- Lightning LWC
- Visualforce Component
- Visualforce Page
@W-7747009@

Use @salesforce/templates library (Remaining templates)

---

packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-core/package.nls.json
packages/salesforcedx-vscode-core/src/commands/forceProjectCreate.ts
packages/salesforcedx-vscode-core/src/commands/templates/forceAnalyticsTemplateCreate.ts
packages/salesforcedx-vscode-core/src/commands/templates/forceApexClassCreate.ts
packages/salesforcedx-vscode-core/src/commands/templates/forceApexTriggerCreate.ts
packages/salesforcedx-vscode-core/src/commands/templates/forceLightningAppCreate.ts
packages/salesforcedx-vscode-core/src/commands/templates/forceLightningComponentCreate.ts
packages/salesforcedx-vscode-core/src/commands/templates/forceLightningEventCreate.ts
packages/salesforcedx-vscode-core/src/commands/templates/forceLightningInterfaceCreate.ts
packages/salesforcedx-vscode-core/src/commands/templates/forceLightningLwcCreate.ts
packages/salesforcedx-vscode-core/src/commands/templates/forceVisualforceComponentCreate.ts
packages/salesforcedx-vscode-core/src/commands/templates/forceVisualforcePageCreate.ts
packages/salesforcedx-vscode-core/src/commands/templates/libraryBaseTemplateCommand.ts
packages/salesforcedx-vscode-core/src/constants.ts
packages/salesforcedx-vscode-core/src/settings/sfdxCoreSettings.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceProjectCreate.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/templates/forceAnalyticsTemplateCreate.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/templates/forceApexClassCreate.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/templates/forceApexTriggerCreate.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/templates/forceLightningAppCreate.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/templates/forceLightningComponentCreate.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/templates/forceLightningEventCreate.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/templates/forceLightningInterfaceCreate.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/templates/forceLightningLWCCreate.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/templates/forceVisualforceComponentCreate.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/templates/forceVisualforcePageCreate.test.ts

Use `@salesforce/templates` library for creating templates. This functionality is behind the flag `salesforcedx-vscode-core.experimental.useTemplatesLibrary`
- Analytics
- Apex Class
- Apex Trigger
- Project
See remaining templates in #2437 (for an easier review)
- Lightning App
- Lightning Component
- Lightning Event
- Lightning Interface
- Lightning LWC
- Visualforce Component
- Visualforce Page
@W-7747009@
We should cancel the progress bar :) task is finished before it knows
Measurement:
```
ApexClassCreate Elapsed: 4205.001875013113 
ApexClassCreate Elapsed: 2854.296660989523 
ApexClassCreate Elapsed: 2824.861781001091 
ApexClassCreate Elapsed: 2846.4673389792442 
ApexClassCreate Elapsed: 2850.0102190077305
ApexClassCreate (Library) Elapsed: 601.2615059912205 
ApexClassCreate …
```

Use @salesforce/templates library for template creation

---

package.json
packages/salesforcedx-sobjects-faux-generator/src/generator/fauxClassGenerator.ts
packages/salesforcedx-sobjects-faux-generator/src/index.ts
packages/salesforcedx-sobjects-faux-generator/test/integration/fauxGenerate.test.ts
packages/salesforcedx-vscode-apex/src/commands/forceGenerateFauxClasses.ts
packages/salesforcedx-vscode-apex/test/vscode-integration/commands/forceGenerateFauxClasses.test.ts

New type of sobject refresh that gets the definition of a reduced set of SObjects. This is meant to be used through the activation message. Reducing the amount of sobject definitions helps avoid the performance spikes seen lately while still allowing the user to have a better apex lang server experience.
NOTE: i'm still working on updating the test but the changes are ready to start getting feedback
#2410 , @W-8027533@

fix: create minimal sobject refresh on activation

---

packages/salesforcedx-vscode-soql/package.json

This fixes the compile error:
```salesforcedx-vscode-soql: node_modules/@salesforce/core/lib/util/fs.d.ts(4,28): error TS7016: Could not find a declaration file for module 'mkdirp'. '/Users/tcromer/workspace/vscode/salesforcedx-vscode/packages/salesforcedx-vscode-soql/node_modules/mkdirp/index.js'```
This appears to be a downstream dependency from us as we don't use this module directly.
Compile and Lint pass.

chore(soql): add missing type for mkdirp

---

packages/salesforcedx-vscode-soql/package.json

This PR will lock down the version of soql-builder-ui to version 0.0.4 and soql-language-server to 0.2.1.  This will prevent any unintended breakage to this repo while we are iterating quickly, moving things around, and **generally being quite volatile**.  
None, it's a task.

Lock down soql-builder-ui and soql-language-server versons while we iterate

---

.vscode/tasks.json
scripts/change-log-generator.js

1. Adds a task for calling the change log generator with the param options that the script accepts.
1. Adds the ability to automatically add commits following the new commitizen format into the Added/Fixed sections of the change log.
1. Adds the ability to automatically filter out certain commitizen types that are not customer facing. Currently the types to ignore include: chore, style, refactor, test, build, ci, and revert.
1. Adds clarity to the steps the change log generator is taking.
@W-8115261@
Old change log results, along with verbose output from the script.
[CLG_OldChangeLog.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/5269758/CLG_OldChangeLog.txt)
[CLG_VerboseResults.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/5269759/CLG_VerboseResults.txt) …

chore: update change log generator to utilize the recent commitizen rule sets (@W-8115261@)

---

packages/salesforcedx-vscode-core/src/commands/util/apexLibraryExecutor.ts
packages/salesforcedx-vscode-core/src/commands/util/deployRetrieveLibraryExecutor.ts
packages/salesforcedx-vscode-core/src/context/index.ts
packages/salesforcedx-vscode-core/src/context/workspaceContext.ts
packages/salesforcedx-vscode-core/src/index.ts
packages/salesforcedx-vscode-core/src/orgPicker/orgList.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceSourceDeploySourcePath.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceSourceRetrieveSourcePath.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/util/apexLibraryExecutor.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/util/deployRetrieveLibraryExecutor.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/context/workspaceContext.test.ts

The test suite doesn't wait for extension activation to initialize, so when it was trying to access the instance of WorkspaceContext on start up it didn't run the suite at all since an error was thrown. This caused false positives in the autobuilds.

test: fix core test suite not running due to WorkspaceContext initialization

---

.circleci/config.yml

Restricts approval access for circle ci workflows. Only members of the GitHub Team 'PDT' should be able to approve workflows for publishing, creating release branches, or running pre-publish steps (merging).
@W-8165486@

chore: add context restriction for circle ci workflows

---

packages/salesforcedx-vscode-core/src/commands/forceSourceRetrieveMetadata/forceSourceRetrieveCmp.ts

- Fix metadata retrieve using the Org Browser
@W-8221083@, #2634

Fix Org Browser metadata retrieve

---

.circleci/config.yml

Update the publish job so we store the generated artifacts (vsix files) before publishing to the marketplace. This will help in scenarios where publishing fails because of a connection issue but some of the artifacts were successfully published.
@W-8257686@

fix: store artifacts before pushing to marketplace

---

packages/salesforcedx-vscode-core/src/commands/baseDeployCommand.ts
packages/salesforcedx-vscode-core/src/commands/forceSourceDeploySourcePath.ts

Fixes different issues with clearing diagnostics for deploy operations:
- Clear diagnostics before parsing deploy results
- Clear diagnostics in case there was an error parsing deploy results
- Use the same diagnostics collection between CLI and Library implementation so diagnostics can be cleared correctly regardless of which path created the diagnostics
#2608, @W-8266770@

fix: clear deploy diagnostics

---

packages/salesforcedx-vscode-core/src/commands/forceApexExecute.ts

Fixes an issue where diagnostics would not clear after successfully executing anonymous apex.
#2608, @W-8272124@

fix: diagnostics not clearing for apex execute

---

docs/_articles/en/getting-started/install.md
docs/_articles/ja/getting-started/install.md

Fix broken links to Java Setup article in doc site
@W-8277599@

fix: broken java setup links in doc site

---

.circleci/config.yml

In order to clarify when there is a post merge issue vs. a publishing issue, this change adds additional messaging to the slack output.
@W-8290541@

chore: add additional slack messages for post publish steps

---

packages/salesforcedx-vscode-lwc/package.nls.json
packages/salesforcedx-vscode-lwc/src/messages/i18n.ts
packages/salesforcedx-vscode-lwc/test/vscode-integration/commands/commandUtils.test.ts

This PR is renaming 'Local development server' with 'Component Preview'
@W-8247907@

Rename 'Local dev server' commands

---

packages/salesforcedx-vscode-core/package.json

Fixes the order in which debug log list is returned.
@W-8331099@, #2698

fix: debug log list in descending order

---

packages/salesforcedx-vscode-soql/package.json

Read soql TextMate grammar file from `apex-tmlanguage` package (instead of `soql-tmlanguage`).
@W-8179607@

feat(soql): soql grammar moved to apex-tmlanguage repo

---

packages/salesforcedx-vscode-soql/package.json

This PR will activate the SOQL extension only if there is a `sfdx-project.json` present in the workspace, just like the rest of the Salesforce extensions. This PR will also change the priority of our custom editor to `option`, that means that when a user clicks on a `.soql` file they will see the text document by default and have to take extra steps to see the SOQL Builder UI.
@W-8253044@
SOQL Extension would activate and open any time a user clicks on a .soql file
The SOQL Extension will only activate if there is an `sfdx-project.json` in the root of the workspace. The users will also see the text document by default instead of the builder UI.

feat(soql): only activate with sfdx project

---

.circleci/config.yml

1. Changes color for start of the merge of main back into develop. This is to help indicate that it is in progress.
1. Added suggestion from CircleCi support to resolve the error:
> error: Terminal is dumb, but EDITOR unset
> Not committing merge; use 'git commit' to complete the merge.
> 
@W-8290541@
Example Failure:
https://app.circleci.com/pipelines/github/forcedotcom/salesforcedx-vscode/2842/workflows/d69adcc2-687a-418f-8bf6-1c26014d0b73/jobs/14623

chore: update post publish job for merging (@W-8290541)

---

packages/salesforcedx-vscode-soql/src/editor/queryRunner.ts

This PR will surface the error `name` and `message` returned by the REST API to the user when running an soql query.
There is a plan to address the root cause of some errors, such as showing fields that can not be queried, or to display the errors in a prettier way post beta.
This PR will provide a better UX to help address issues [52](https://github.com/forcedotcom/soql-tooling/issues/52), [82](https://github.com/forcedotcom/soql-tooling/issues/82), [83](https://github.com/forcedotcom/soql-tooling/issues/83), [86](https://github.com/forcedotcom/soql-tooling/issues/86) in the forcedotcom/soql-tooling repo.
@W-8393352@
Issues [86](https://github.com/forcedotcom/soql-tooling/issues/86) and [52](https://github.com/forcedotcom/soql-tooling/issues/52):
Issue …

JHork: Show api error when running query

---

README.md

This PR will add the soql extension to the list of Salesforce extensions in the main repo README.

 Add the SOQL Builder to list of extensions

---

.git2gus/config.json

Updated Git2Gus to assign WI to SOQLBuilder product tag (web tools) instead of SOQL (dev tools)

---

package.json

Adds `git clean -xfd` to the clean script.

chore: add git clean to clean script

---

packages/salesforcedx-sobjects-faux-generator/package.json
packages/salesforcedx-utils-vscode/package.json
packages/salesforcedx-vscode-apex/.vscodeignore
packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-core/.vscodeignore
packages/salesforcedx-vscode-lightning/.vscodeignore
packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lwc/.vscodeignore
packages/salesforcedx-vscode-lwc/package.json

Remove unused code from being part of the generated vsix files specific to the core, apex, lightning and lwc extensions.
- Remove unused code installed by `@salesforce/core`
- Remove unused code installed by `rxjs`
- Update to the same version of `@salesforce/core` (except for the salesforcedx-sobject-faux-generator module)
| extension        | Old size           | New size  |
| ------------- |:-------------:| -----:|
| salesforcedx-vscode-core     | 14.2 MB | 10 MB |
| salesforcedx-vscode-apex      | 24 MB      |   22 MB|
| salesforcedx-vscode-lightning | 23.3 MB      |    21.6 MB |
| salesforcedx-vscode-lwc | 44.1 MB      |    41 MB |
@W-7870137@

Remove unused code from generated extensions (vsix)

---

docs/_articles/en/apex/interactive-debugger.md

Updates the Interactive Debugger documentation with additional information about licenses provided to LMOs. The default license provided to LMOs can only be used with the ISV Debugger to debug a Subscriber org.
#2737, @W-8493955@

docs: add license note for interactive debugger

---

packages/salesforcedx-vscode-soql/package.json
packages/salesforcedx-vscode-soql/src/client/client.ts
packages/salesforcedx-vscode-soql/src/editor/queryRunner.ts
packages/salesforcedx-vscode-soql/src/index.ts
packages/salesforcedx-vscode-soql/test/vscode-integration/client/client.test.ts

[W-7977000](https://gus.my.salesforce.com/one/one.app#/alohaRedirect/a07B0000008ULb1IAG)
Dependent on https://github.com/forcedotcom/soql-tooling/pull/93
Handles `runQuery` requests from the SOQL language server. This will run the query unmodified and return the result to the LS. The LS may then validate and add diagnostic messages.

Remote SOQL Errors - Language Client Part

---

.vscode/launch.json
packages/salesforcedx-vscode-soql/package.json
packages/salesforcedx-vscode-soql/package.nls.json
packages/salesforcedx-vscode-soql/src/commands/index.ts
packages/salesforcedx-vscode-soql/src/commands/soqlFileCreate.ts
packages/salesforcedx-vscode-soql/src/index.ts
packages/salesforcedx-vscode-soql/test/vscode-integration/commands/soqlFileCreate.test.ts

This PR implements the command "SOQL: New Query", which opens an untitled, unsaved, empty query in the SOQL Builder.  This command is enabled in the command palette when an SFDX project is open.
@W-8516491@
User must create .soql file, then "Open With" SOQL Builder to open a new query in the SOQL Builder.
User uses command "SOQL: New Query" to open a new query in the SOQL Builder.

feat(soql): new query command

---

docs/_articles/en/codepreview/set-up-lwc-code-preview.md
docs/_articles/ja/codepreview/set-up-lwc-code-preview.md

Adds documentation for disabling the browser cache for code preview. Also adds a workaround tip for those that do not want to disable the cache.
@W-8247036@

docs: add cache information for code preview

---

packages/salesforcedx-vscode-lwc/test/vscode-integration/hover.test.ts

Adds more padding to the timeout for the lwc hover tests to allow the language client to initialize. If we find ourselves increasing this timeout more and more, we should reconsider doing something more drastic with the test.

test: Increase hover test timeout to 10000

---

packages/salesforcedx-vscode-soql/package.json
packages/salesforcedx-vscode-soql/test/vscode-integration/commands/soqlFileCreate.test.ts

This is a cherry-pick of commit b3c64e78bd0159abd86a1b15c022169d5ed2b0f3 from develop to fix a bug where soql builder ui does not render because the viewType is incorrect.
Soql Builder not rendered.

bug: fix bug causing soql builder does not show (#2827)

---

packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-core/src/commands/forceSourceRetrieveSourcePath.ts

Updates to v1.1.15 of SDR that includes a fix for establishing a connection when running the extensions in development mode. This was not an issue with production builds.
@W-8667800@

chore: update sdr with connection fix

---

.vscode/launch.json
packages/salesforcedx-vscode-soql/package.json
packages/salesforcedx-vscode-soql/package.nls.json
packages/salesforcedx-vscode-soql/src/client/client.ts
packages/salesforcedx-vscode-soql/src/client/codeCompletion.ts
packages/salesforcedx-vscode-soql/src/client/queryValidation.ts
packages/salesforcedx-vscode-soql/src/constants.ts
packages/salesforcedx-vscode-soql/test/vscode-integration/client/client.test.ts
packages/salesforcedx-vscode-soql/test/vscode-integration/client/completion.test.ts
packages/salesforcedx-vscode-soql/test/vscode-integration/testUtilities.ts

@W-8611581@
SOQL editor would always call the remote API to validate queries
This "experimental" feature is now disabled by default. Added new configuration option for the user to enable it.
https://user-images.githubusercontent.com/152839/103817675-e501d480-5045-11eb-8f54-36ac25cec8b3.mov

fix(soql): disable remote query checks. Make it an experimental option

---

packages/salesforcedx-vscode-soql/package.json
packages/salesforcedx-vscode-soql/src/client/codeCompletion.ts
packages/salesforcedx-vscode-soql/src/index.ts
packages/salesforcedx-vscode-soql/test/vscode-integration/client/client.test.ts
packages/salesforcedx-vscode-soql/test/vscode-integration/client/completion.test.ts
packages/salesforcedx-vscode-soql/test/vscode-integration/commands/soqlBuilderToggle.test.ts
packages/salesforcedx-vscode-soql/test/vscode-integration/commands/soqlFileCreate.test.ts
packages/salesforcedx-vscode-soql/test/vscode-integration/editor/queryRunner.test.ts
packages/salesforcedx-vscode-soql/test/vscode-integration/editor/soqlEditorInstance.test.ts
packages/salesforcedx-vscode-soql/test/vscode-integration/testUtilities.ts

Code completion of WHERE clause expressions
* Complete operators based on type of field
* Complete literal values based on type of field
* Show type name (and icon) on completion items for fields
* Offer NULL as a completion value only if field is nillable
Also: refactoring of "placeholder" completion items: receive JSON data instead
of parseable values inside item label string.
@W-8597428@
Related LSP-server PR: https://github.com/forcedotcom/soql-tooling/pull/112
n/a
https://user-images.githubusercontent.com/152839/103246284-b139f700-4941-11eb-9228-2a56fc06dd87.mov
https://user-images.githubusercontent.com/152839/103816838-60fb1d00-5044-11eb-9c42-8336da6bb86b.mov

SOQL code-completion on WHERE clause expressions

---

packages/salesforcedx-utils-vscode/src/context/index.ts
packages/salesforcedx-vscode-apex-replay-debugger/src/commands/quickLaunch.ts
packages/salesforcedx-vscode-apex-replay-debugger/src/context/index.ts
packages/salesforcedx-vscode-apex-replay-debugger/src/context/workspaceContext.ts
packages/salesforcedx-vscode-apex-replay-debugger/src/index.ts
packages/salesforcedx-vscode-apex-replay-debugger/test/vscode-integration/commands/quickLaunch.test.ts
packages/salesforcedx-vscode-apex/src/commands/forceApexTestRunCodeAction.ts
packages/salesforcedx-vscode-apex/src/context/index.ts
packages/salesforcedx-vscode-apex/src/context/workspaceContext.ts
packages/salesforcedx-vscode-apex/src/index.ts
packages/salesforcedx-vscode-apex/test/vscode-integration/commands/forceApexTestRunCodeAction.test.ts

This PR changes how we are initializing the workspaceContext service in the apex and replay-debugger packages. This fixes an issue where 'Run Test' and 'Debug & Run Test' were not picking up the default org when the project was opened for the first time.
@W-8732172@

fix: workspaceContext initialization across apex & replay-debugger packages

---

packages/salesforcedx-vscode-soql/package.json

The command to toggle between Soql Builder and Soql Editor has snuck into the Command Palette, even though it is not explicitly mentioned that it contributes to the command palette.  Fortunately, it's an easy fix.
@W-8728692@

fix: do not show toggle command in palette

---

packages/salesforcedx-utils-vscode/src/commands/commandletExecutors.ts
packages/salesforcedx-utils-vscode/src/commands/sfdxCommandlet.ts
packages/salesforcedx-utils-vscode/src/index.ts
scripts/aggregate-junit-xml.js

Simply copies the library commandlet to the utils module. Commands have not been changed to use this version yet because there are other things that need to be updated first. E.g. the utils version of the telemetry service needs to be used in the extensions packages first, otherwise telemetry will stop working.
@W-8659966@

refactor: copy library commandlet to utils module

---

packages/salesforcedx-vscode-apex/package.json

Follow up to #2877 - adds the app insights key to the Apex package.json. Because of the recent telemetry changes, the extension will not activate without this 
@W-8720933@

fix: add aiKey to apex package

---

.vscode/tasks.json
scripts/change-log-generator.js

Adds a configurable param that can be passed to the change log generator that contains a list of packages to ignore when generating the change log. This approach allows for future instances where we do not want to include changes from a certain package. It also allows the PWT team to still use this automation within their own change log.
@W-8778016@
```
- Remove channelService from core extension ([PR #2853](https://github.com/forcedotcom/salesforcedx-vscode/pull/2853))
- Do not emit message from custom editor to webview if soql has not changed ([PR #2818](https://github.com/forcedotcom/salesforcedx-vscode/pull/2818))
- Do not show toggle command in palette ([PR #2867](https://github.com/forcedotcom/salesforcedx-vscode/pull/2867))
- Disable remote query checks. Make it an experimental …
```

chore: add ability to ignore packages for the change log generator

---

docs/_articles/en/getting-started/java-setup.md

Adds a note on how to get the Java path for Mac OS. Original PR #2899.
@W-8836836@

Java path doc update for Mac OS

---

packages/salesforcedx-vscode-apex-debugger/src/index.ts
packages/salesforcedx-vscode-apex-replay-debugger/src/index.ts
packages/salesforcedx-vscode-visualforce/src/extension.ts

Follow up to PRs #2878 & #2894. This fixes an issue on `salesforcedx-vscode-apex`, `salesforcedx-vscode-apex-replay-debugger` and `salesforcedx-vscode-visualforce` where it fails to find a now removed `showTelemetryMessage` method.
@W-8792554@

fix: missing telemetry method

---

packages/salesforcedx-vscode-soql/package.json
packages/salesforcedx-vscode-soql/src/editor/queryRunner.ts
packages/salesforcedx-vscode-soql/test/vscode-integration/client/client.test.ts
packages/salesforcedx-vscode-soql/test/vscode-integration/editor/queryRunner.test.ts

On SOQL Builder: when there are comments at the top of `.soql` files, strip them out before calling the "Run Query" API.
@W-8611529@

feat(soql): extract comments out of soql text before running query

---

packages/salesforcedx-vscode-lwc/resources/static/js-meta.xsd

add lightning_recordaction, lightning_globalaction target and actiontype tag
https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B00000095m2AIAQ/view
sfdx plugin will show error when user has lightning_recordaction, lightning_globalaction as target, actiontype as a config tag
no error for these

add target and actiontype

---

packages/salesforcedx-vscode-lwc/src/messages/i18n.ts
packages/salesforcedx-vscode-lwc/src/metasupport/metaSupport.ts
packages/salesforcedx-vscode-lwc/test/vscode-integration/metaSupport/metaSupport.test.ts

What does this PR do?
Activates XML extension only if it is version 0.14.0
What issues does this PR fix or reference?
W-8852786
Functionality Before
LWC Extension activation error for some users
Functionality After
Fix for the LWC Extension activation error for some users

fix: activate redhat XML extension only if it is version 0.14.0 @W-8852786@

---

packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-apex/src/commands/forceApexTestRunCodeAction.ts
packages/salesforcedx-vscode-apex/src/commands/forceGenerateFauxClasses.ts
packages/salesforcedx-vscode-apex/src/views/testOutlineProvider.ts
packages/salesforcedx-vscode-apex/src/views/testRunner.ts
packages/salesforcedx-vscode-apex/test/vscode-integration/commands/forceGenerateFauxClasses.test.ts
packages/salesforcedx-vscode-apex/test/vscode-integration/views/testOutline.test.ts
packages/salesforcedx-vscode-apex/test/vscode-integration/views/testOutlineNamespace.test.ts

Removes the core extension dependency from the apex extension. This allows the Apex extension to start activating before the core extension finishes.
@W-8659996@

refactor: remove core extension dependency from apex extension

---

packages/salesforcedx-vscode-apex-replay-debugger/src/commands/quickLaunch.ts
packages/salesforcedx-vscode-apex-replay-debugger/test/vscode-integration/commands/quickLaunch.test.ts
packages/salesforcedx-vscode-apex/src/commands/forceApexTestRun.ts
packages/salesforcedx-vscode-apex/src/commands/forceApexTestRunCodeAction.ts
packages/salesforcedx-vscode-apex/src/views/testOutlineProvider.ts
packages/salesforcedx-vscode-apex/test/vscode-integration/commands/forceApexTestRun.test.ts
packages/salesforcedx-vscode-apex/test/vscode-integration/commands/forceApexTestRunCodeAction.test.ts
packages/salesforcedx-vscode-apex/test/vscode-integration/views/testJSONOutputs.ts
packages/salesforcedx-vscode-apex/test/vscode-integration/views/testNamespacedOutputs.ts

This PR consumes the functionality added by the Apex library to support namespaces. Users should now be able to run tests from a namespaced scratch org and see the results in the output & test sidebar. Fixes an issue where test runs from namespaced scratch orgs were not updating the sidebar with results.
#2865, @W-8870724@

feat: add namespace support to test:run & debug commands

---

packages/salesforcedx-vscode-soql/package.json

This fixes a P0 bug in the published version of soql builder, where the UI does not render.  
No UI Rendered
UI Rendered

fix: update the dependency of soql-builder-ui

---

packages/salesforcedx-vscode-soql/package.json

This is a cherry-pick of https://github.com/forcedotcom/salesforcedx-vscode/commit/22700611d4e295f8ea31a1067b27686ace7e3f80, a patch to fix a P0 bug in Soql Builder.
@W-8970512@
UI does not render
UI Renders

chore: cherry-pick of 7fb614 from release/v51.3.1 branch

---

.circleci/config.yml

Update the scheduled job that cuts the release branch on monday nights to run at 8pm pst.

chore: delay cutting the branch job by 2 hrs

---

packages/salesforcedx-sobjects-faux-generator/src/describe/sObjectDescribe.ts
packages/salesforcedx-sobjects-faux-generator/test/integration/sObjectDescribe.test.ts

Handles `undefined` results from sobject describe calls
#3056 , @W-9007196@

fix: handle undefined results from describe calls

---

packages/salesforcedx-utils-vscode/test/unit/commands/commandletExecutor.test.ts
packages/salesforcedx-vscode-core/src/commands/baseDeployRetrieve.ts
packages/salesforcedx-vscode-core/src/commands/templates/baseTemplateCommand.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/baseDeployRetrieve.test.ts

Adds cancellation logic for Deploy Retrieve Library commands.
@W-8979870@

feat: add cancellation to Deploy Retrieve Library commands

---

packages/salesforcedx-utils-vscode/src/commands/commandletExecutors.ts
packages/salesforcedx-utils-vscode/src/commands/notificationService.ts
packages/salesforcedx-utils-vscode/test/unit/commands/notificationService.test.ts
packages/salesforcedx-vscode-core/src/commands/forceRefreshSObjects.ts
packages/salesforcedx-vscode-lwc/src/commands/forceLightningLwcPreview.ts
packages/salesforcedx-vscode-lwc/src/commands/forceLightningLwcStart.ts
packages/salesforcedx-vscode-lwc/src/commands/forceLightningLwcStop.ts

Adds back in functionality for jumping to the correct output channel when clicking the 'Show' button.
#2987, @W-8935765@
Clicking the 'Show' button did not redirect the user to the appropriate output channel.
Clicking the 'Show' button redirects the user to the correct output channel. 
- This fix also applies for the Apex Plugin & Library.
- Jumping to the correct output channel upon successful completion for SDR has already been fixed by #3027.
- The text "Null Extension Description" is specific only to the dev environment. This does not impact customers.

fix: add ability to jump to channel output via the 'Show' button

---

packages/salesforcedx-vscode-core/package.json

Updates SDR to 1.1.20. This update changes the suffix type on the metadata file for Document metadata types. This fixes deployment issues for Document types when using a combination of the CLI and SDR Library to deploy and retrieve.
@W-9043410@
See https://github.com/forcedotcom/source-deploy-retrieve/pull/263 for more information.

fix: update deploy and retrieve beta to use 1.1.20

---

packages/salesforcedx-vscode-core/src/commands/forceRefreshSObjects.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceRefreshSObjects.test.ts

Does not show refresh success message for min sobjects are refreshed at startup
@W-9042465@
Above message not shown

fix: do not show refresh success message for min sobjects @W-9042465@

---

packages/salesforcedx-vscode-core/src/commands/forceRefreshSObjects.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceRefreshSObjects.test.ts

Port "do not show refresh success message for min sobjects" commit to release

Port "do not show refresh success message for min sobjects"

---

.circleci/config.yml

Change case management logic is currently broken due to some recent changes from the CLI team. We will be commenting out the change case management for now and implementing the recommended approach later this week. Goal is for change cases to automagically generate starting next week. For now, we don't want to block releases.
@W-9070014@

chore: temporarily remove change case management logic

---

packages/salesforcedx-vscode-core/package.json

Flips source deploy retrieve on by default.
@W-9076651@

feat: turn experimental.deployRetrieve on by default

---

docs/_articles/en/user-guide/perf-enhancements.md

Update the doc page to reflect that Deploy / Retrieve library is now on be default

docs: denote that deploy and retrieve perf enhancements are on by default

---

docs/_articles/en/user-guide/development-models.md

https://github.com/forcedotcom/salesforcedx-vscode/issues/3095
We said Org Picker was located on Side Bar
Update docs to say Org Picker is on status bar

[GitHub feedback] Update Org Picker location

---

packages/salesforcedx-utils-vscode/src/helpers/index.ts
packages/salesforcedx-utils-vscode/src/helpers/paths.ts
packages/salesforcedx-utils-vscode/src/index.ts
packages/salesforcedx-utils-vscode/test/unit/helpers/paths.test.ts
packages/salesforcedx-vscode-core/src/commands/baseDeployCommand.ts
packages/salesforcedx-vscode-core/src/commands/baseDeployRetrieve.ts
packages/salesforcedx-vscode-core/src/commands/forceSourceDeployManifest.ts
packages/salesforcedx-vscode-core/src/commands/forceSourceDeploySourcePath.ts
packages/salesforcedx-vscode-core/src/commands/forceSourceRetrieveManifest.ts
packages/salesforcedx-vscode-core/src/commands/forceSourceRetrieveMetadata/forceSourceRetrieveCmp.ts
packages/salesforcedx-vscode-core/src/commands/forceSourceRetrieveSourcePath.ts
packages/salesforcedx-vscode-core/src/commands/util/betaDeployRetrieve.ts
packages/salesforcedx-vscode-core/src/commands/util/index.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/baseDeployRetrieve.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/util/betaDeployRetrieve.test.ts

Properly handles file paths when throwing TypeInfereceError exceptions. Also fixes it for when we are creating component counts in the baseDeployExecutor. 
@W-9105085@

fix: better exception handling for type inference errors

---

packages/salesforcedx-vscode-core/src/commands/forceSourceRetrieveMetadata/forceSourceRetrieveCmp.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceSourceRetrieveMetadata/forceSourceRetrieveCmp.test.ts

Fixes an issue retrieving all components of a type using the org browser. If there was a mixed of locally present components and remote only components, only the locally present ones were retrieved.
@W-9102368@
Only locally present components were retrieved when retrieving all components of a type.
Both remote components and locally present ones are retrieved.

fix: retrieving all components of org browser type

---

packages/salesforcedx-vscode-core/src/commands/baseDeployCommand.ts
packages/salesforcedx-vscode-core/src/commands/baseDeployRetrieve.ts
packages/salesforcedx-vscode-core/src/commands/util/betaDeployRetrieve.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/baseDeployRetrieve.test.ts

Surfaces the original error instead of "Unknown Exception". While this doesn't exactly fix underlying issues if there are some, we or the user at least can triage what's going on.
#3137, @W-9178716@
"Unknown Exception" message reported for any issues that are not TypeInferenceErrors
Original errors are now surfaced to make triaging easier.

fix: unknown exception with deploy/retrieve

---

packages/salesforcedx-vscode-core/src/commands/baseDeployRetrieve.ts
packages/salesforcedx-vscode-core/src/commands/forceSourceRetrieveMetadata/forceSourceRetrieveCmp.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/baseDeployRetrieve.test.ts

Fixes #3124 by removing the usage of the tooling api in the new deploy/retrieve. Querying for the metadata xml content with the tooling api is inconsistent across types, incomplete, and is maintenance overhead. It was only used for a small subset of types for single component retrieves. The metadata api is still fast and is safer to use.
#3124 , @W-9110541@
Retrieving components such as ApexComponent returned incomplete metadata xml, preventing you from redeploying it later and was a loss of information.
Metadata xml files are obtained directly from a metadata api call instead.

fix: metadata xml issues by removing tooling retrieve

---

packages/salesforcedx-vscode-core/package.json

Updates to the latest version of SDR that contains the fix for preserving leading zeroes in xml tags during deploys and retrieves.
#3138, @W-9118281@
Deploying and retrieving metadata with leading zeroes in xml tags were not preserved.
Now they are.

fix: preserve leading zeros in xml tags during deploy/retrieve

---

.circleci/config.yml

Reduces jobs required for pre-publish workflow (merging release branch into main). In order for commits to have made it this far, they would have already gone through the build-all, unit tests, and integration test checks. They should not be required again. 
Note this is a temporary measure to get around the vscode tests not always launching in circleci, and thus failing the build.

chore: remove tests as requirement for pre-publish workflow

---

packages/salesforcedx-vscode-core/src/commands/baseDeployRetrieve.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/baseDeployRetrieve.test.ts

Respects the overridden API version in an SFDX project when using the new deploy/retrieve logic. Note that deploying/retrieving with a manifest will always honor the version specified in the manifest - this is the CLI behavior.
#3151, @W-9179305@
New deploy/retrieve logic always used the latest API version when using Org Browser or source paths.
Now it only uses the latest if a version isn't overridden through SFDX configuration or with a manifest file's version.

fix: respect sfdx api version override during new deploy/retrieve

---

packages/salesforcedx-vscode-core/src/conflict/metadataCacheService.ts
packages/salesforcedx-vscode-core/test/vscode-integration/conflict/metadataCacheService.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/directoryDiffer.test.ts
packages/system-tests/assets/differ-testdata/classes/DemoDriver.cls

Provide an SDR based service for caching project metadata based on a project path. The service and its executor will be used in subsequent source diff and conflict detection work. The service retrieves metadata specified by a project path that may indicate a single resource, or any level of project folder. Properties of each resource are retrieved and saved to a dedicated file in the cache. Paths returned from the retrieve operation are normalized to allow difference or conflict analysis of the two folder structures.
@ W-9166495@

feat: cache metadata based on a project path

---

packages/salesforcedx-vscode/CHANGELOG.md

Updates the change log date for v51.12.0. 
Note this PR is mainly being used to pull in a new commit for the publishing process. The auth token being used by sf-change-case-management should hopefully be resolved once we can pull in a fresh commit.

chore: update change log date for v51.12.0

---

.circleci/config.yml

1. Adds the content CLI_CTC to our publish job. This will add the environment variable SF_CHANGE_CASE_SFDX_AUTH_URL. I am not 100% sure if our own value for SF_CHANGE_CASE_SCHEDULE_BUILD will override what's currently in CLI_CTC.
2. Removed the environment variable SF_CHANGE_CASE_SFDX_AUTH_URL from [CircleCi](https://app.circleci.com/settings/project/github/forcedotcom/salesforcedx-vscode/environment-variables?return-to=%2F). Note that previously this value ended in '.com', though I'm not sure what the actual value was.
This change should hopefully push us past some of the Change Case Management issues we have been seeing around authorization.
@W-9237090@

chore: add CLI_CTC context

---

packages/salesforcedx-vscode-lwc/resources/static/js-meta.xsd
packages/salesforcedx-vscode-lwc/src/messages/i18n.ts
packages/salesforcedx-vscode-lwc/src/metasupport/metaSupport.ts
packages/salesforcedx-vscode-lwc/test/vscode-integration/metaSupport/metaSupport.test.ts

This updates the js-meta.xml schema support:
- Adds `analytics__Dashboard` js-meta.xml support, for the new LWC's in analytics dashboard feature. This includes the `Dimension` and `Measure` `type`'s in `<property>`.
- Updated the js-meta.xml feature's checking of the vscode-xml extension version -- it appears that the bug that broke 0.15.0 got fixed in 0.16.0
- Adds missing fields: `<propertyType>`, `filter` on `<property>`
- Adds typing to `type` on `<property>`
@W-9191640@, @W-8852786@
- You would get a schema error in the editor if you used `<target>analytics__Dashboard</target>` or used `<hasStep>` in a `<targetConfig>`.
- You didn't get code-completion for `analytics__Dashboard`, nor hover text
- You would get schema error on `<propertyType>` and `filter`.
- You got a wrong output …

feat: add analytics__Dashboard js-meta.xml support, and js-meta bug fixes

---

packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-core/package.nls.json
packages/salesforcedx-vscode-core/src/commands/forceSourceDiff.ts
packages/salesforcedx-vscode-core/src/commands/index.ts
packages/salesforcedx-vscode-core/src/conflict/conflictDetectionService.ts
packages/salesforcedx-vscode-core/src/conflict/index.ts
packages/salesforcedx-vscode-core/src/conflict/metadataCacheService.ts
packages/salesforcedx-vscode-core/src/index.ts
packages/salesforcedx-vscode-core/src/messages/i18n.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceSourceDiff.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/conflict/metadataCacheService.test.ts

Enable the SFDX file diff command in vscode extensions for project folders. The command will perform a metadata diff and display the results in the Conflict Detection UI
@W-9166602@
N/A

feat: enable conflict UI for folder diff @W-9166602@

---

packages/salesforcedx-vscode-core/src/commands/forceSourceDiff.ts
packages/salesforcedx-vscode-core/src/commands/util/postconditionCheckers.ts
packages/salesforcedx-vscode-core/src/conflict/conflictDetectionService.ts
packages/salesforcedx-vscode-core/src/conflict/metadataCacheService.ts
packages/salesforcedx-vscode-core/src/messages/i18n.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceSourceDiff.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/util/postconditionCheckers.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/conflict/conflictDetectionService.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/conflict/metadataCacheService.test.ts
packages/system-tests/assets/proj-testdata/manifest/one-class.xml

- Use SDR library to improve performance of conflict detection.
- Add manifest support for caching project metadata
@W-9164033@

feat: use SDR for conflict detect perf improvements

---

packages/salesforcedx-vscode-core/src/commands/functions/forceFunctionInvoke.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/functions/forceFunctionInvoke.test.ts

Invoke uses new CLI + java support
@W-9282250@
N/A
No change in behavior

fix: use new cli for functions invoke @W-9282250@

---

packages/salesforcedx-vscode-core/src/commands/functions/forceFunctionStart.ts
packages/salesforcedx-vscode-core/src/commands/functions/types/constants.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/functions/forceFunctionStart.test.ts

- Update the default debug port used for functions
- Correctly identify when a function has been started
@W-9282233@

fix: update default debug port

---

packages/salesforcedx-vscode-core/src/commands/functions/forceFunctionStart.ts
packages/salesforcedx-vscode-core/src/commands/functions/functionService.ts
packages/salesforcedx-vscode-core/src/commands/functions/types/constants.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/functions/forceFunctionStart.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/functions/functionService.test.ts

- Allow use of Debug Invoke feature for Java Functions
@W-9330349@

feat: add Java support for Functions debugging

---

packages/salesforcedx-vscode/CHANGELOG.md

chore: generated CHANGELOG for origin/release/v51.16.0

---

packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-core/src/constants.ts
packages/salesforcedx-vscode-core/src/index.ts
packages/salesforcedx-vscode-core/src/messages/i18n.ts
packages/salesforcedx-vscode-core/src/settings/sfdxCoreSettings.ts

Function enabled by default and doc has been updated to point to the latest functions plugin
@W-9311863@
'Experimental: Support Functions' had to be turned on to see functions commands
Functions commands appear in command palette and right-click by default
Doc has been updated to point to the latest functions plugin.

remove functions feature-flag and update doc @W-9311863@

---

packages/salesforcedx-vscode-core/src/conflict/metadataCacheService.ts
packages/salesforcedx-vscode-core/src/conflict/persistentStorageService.ts
packages/salesforcedx-vscode-core/test/vscode-integration/conflict/metadataCacheService.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/conflict/persistentStorageService.test.ts

This PR cleans up a few items from a previous PR. First, FileProperties used to not be able to be imported from the top level so this PR addresses that. Second, there was a typo on 'persistant'. Third, I changed the unit tests to use path.join() (I figure this is better even though it didn't really matter as they are hard-coded strings). 
None that are documented, although it finishes what was started with @W-9225729@
No change in functionality
No change in functionality

fix: import FileProperties from the top level

---

packages/salesforcedx-vscode-core/src/commands/forceSourceDiff.ts
packages/salesforcedx-vscode-core/src/conflict/persistentStorageService.ts
packages/salesforcedx-vscode-core/test/vscode-integration/conflict/persistentStorageService.test.ts

The PersistentStorageService cache is global. This PR adds an org/project prefix to every cache entry's key so that they are unique identifiers. 
@[W-9456559](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000OPsiYAG/view)@
Cache key was `${type}#${fullName}`.
Cache key is now `${org}#${project}#${type}#${fullName}`.

feat: add org/project prefix to cache key

---

packages/salesforcedx-vscode-core/src/commands/baseDeployRetrieve.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/baseDeployRetrieve.test.ts

This PR saves `ConflictFileProperties` to the metadata cache after a deploy. 
@[W-9275248](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000LuKpYAK/view)@, @[W-9275447](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000LuaOYAS/view)@
`setPropertiesForFilesDeploy` in `PersistentStorageService` was unused. 
After a deploy operation, `ConflictFileProperties` are saved to the metadata cache within `PersistentStorageService`. This PR addresses both single file and multi file deploy because they both extends `BaseDeployExecutor`.

feat: save fileproperties after deploy

---

packages/salesforcedx-vscode-core/src/commands/util/postconditionCheckers.ts
packages/salesforcedx-vscode-core/src/conflict/conflictDetectionService.ts
packages/salesforcedx-vscode-core/src/conflict/directoryDiffer.ts
packages/salesforcedx-vscode-core/src/conflict/timestampConflictDetector.ts
packages/salesforcedx-vscode-core/src/messages/i18n.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/util/postconditionCheckers.test.ts

With how conflict detection used to work, the number of files scanned both locally and remotely was reported to the user. The new mechanism does not operate in the same way but currently still displays those values and hardcodes them to be 0. This PR removes `scannedRemote` and `scannedLocal` from the new conflict detection mechanism code and messages.
@[W-9499182](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000PEjEYAW/view)@
Hardcoded `scannedLocal` and `scannedRemote` were displayed to the user after a conflict was detected. 
The new mechanism does not hardcode values of 0 for `scannedLocal` and `scannedRemote` and these fields are not displayed to the user after a conflict is detected.

fix: remove scannedRemote and scannedLocal

---

packages/salesforcedx-vscode-apex/src/languageServer.ts
packages/salesforcedx-vscode-apex/test/vscode-integration/languageServer.test.ts

when creating the language server, sets the client options to never reveal the output channel,
preventing focus from being stolen and distracting the user during development.
fix #1429
#1429 , @W-9464384@
Language server output panel liked to steal focus.
Output panel will no longer automatically be opened and receive focus.

perf: stops the language service output panel from stealing focus

---

packages/salesforcedx-vscode-core/src/conflict/metadataCacheService.ts

Solves a bug that caused conflict detection to throw an error in a new project.
The two fixes are
1. When doing a retrieve, forceAddWildcards should be true so that the ComponentSet can be created properly. See forceSourceRetrieveManifest.ts for an example.
2. If there are no components (specifically no local components) the common root should be '' not baseDir, because the common root is defined as the relative path from baseDir.
#3294, @W-9368479@
After creating a new project and running `Retrieve with Manifest` with conflict detection on, an error was triggered 'No components in the package to retrieve'
Creating a new project and running `Retrieve with Manifest` with conflict detection on causes conflict detection to work as normal.

fix: conflict detection not working on new project

---

docs/_articles/en/user-guide/detect-conflicts.md
packages/salesforcedx-vscode-core/package.nls.json
packages/salesforcedx-vscode-core/src/commands/forceSourceRetrieveManifest.ts
packages/salesforcedx-vscode-core/src/commands/forceSourceRetrieveSourcePath.ts
packages/salesforcedx-vscode-core/src/commands/util/postconditionCheckers.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/util/postconditionCheckers.test.ts

This PR enables the new conflict detection mechanism for both retrieve with manifest and retrieve from source path. For the source path side, a new helper class CompositePostconditionChecker was created. 
@W-9164035@
Conflict detection was not used for retrieve from source path, the old conflict detection mechanism was used for retrieve with manifest.
The new conflict detection mechanism is used for all retrieves.

feat: enable conflict detection on retrieve

---

packages/salesforcedx-sobjects-faux-generator/src/transformer/transformerFactory.ts
packages/salesforcedx-vscode-apex/src/languageServer.ts
packages/salesforcedx-vscode-apex/test/vscode-integration/languageServer.test.ts
packages/salesforcedx-vscode-core/src/commands/util/postconditionCheckers.ts

What does this PR do?
This PR enables the new conflict detection mechanism for 1) deploy with manifest 2) deploy single source path and 3) deploy multiple source paths. 
What issues does this PR fix or reference?
@[W-9164037](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000BO4PYAW/view)@
Functionality Before
We had conflict detection for 1) deploy with manifest but did not have conflict detection for 2) & 3) deploy single/multiple source path. 
Functionality After
The new conflict detection mechanism is enabled for 1) deploy with manifest 2) deploy single source path and 3) deploy multiple source paths. 
manifest example: 
single path example:
multiple path example (called in deploy on save):

feat: conflict detection enable deploy

---

packages/salesforcedx-vscode-core/src/commands/util/postconditionCheckers.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/util/postconditionCheckers.test.ts

During QA, a bug was found on deploying and retrieving with source path due to conflict detection changes. The problem went back to CompositePostconditionChecker not returning the correct data. This PR updates that class to chain the data rather than aggregate, which makes more sense for the common use case of data being file paths.
@W-9164035@, @W-9164037@
Running deploy or retrieve from source path would result in the error "fsPaths is not iterable", due to incorrect data being returned from CompositePostconditionChecker. 
CompositePostconditionChecker returns the correct data and there is no longer an error.

fix: correct response from CompositePostconditionChecker

---

.github/ISSUE_TEMPLATE/Bug_report.md
.github/ISSUE_TEMPLATE/Feature_request.md

we often have to ask a follow-up question to see which extension version they are on.  Changing the template to ask that upfront.  if we need to also know the VS Code version, we will ask in follow-ups and consider adding that to the template if we have to ask a lot

Update bug template to ask for SF EXTENSION version

---

docs/_articles/en/user-guide/detect-conflicts.md
packages/salesforcedx-vscode-core/src/commands/forceSourceRetrieveManifest.ts
packages/salesforcedx-vscode-core/src/commands/forceSourceRetrieveSourcePath.ts

This PR disables conflict detection for source path retrieve and manifest retrieve. Reasons for this decision were discussed in this [slack thread](https://platformcloud.slack.com/archives/GCDT2EVAQ/p1625172470054400). 
@W-9549931@, @W-9549942@
The timestamp conflict detection mechanism was used in source path retrieve and manifest retrieve. 
The timestamp conflict detection mechanism is disabled for source path retrieve and manifest retrieve.

fix: disable retrieve conflict detection 

---

packages/salesforcedx-vscode-core/src/commands/forceSourceDeploySourcePath.ts
packages/salesforcedx-vscode-core/src/commands/util/postconditionCheckers.ts
packages/salesforcedx-vscode-core/src/conflict/conflictDetectionService.ts
packages/salesforcedx-vscode-core/src/conflict/conflictNode.ts
packages/salesforcedx-vscode-core/src/conflict/conflictView.ts
packages/salesforcedx-vscode-core/src/conflict/directoryDiffer.ts
packages/salesforcedx-vscode-core/src/conflict/timestampConflictDetector.ts
packages/salesforcedx-vscode-core/src/messages/i18n.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/util/postconditionCheckers.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/conflict/timestampConflictDetector.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/directoryDiffer.test.ts

This PR displays local and remote `LastModifiedDate` for each conflicting file as tooltip. 
@[W-9164041](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000BO4jYAG/view)@
We did not display local and remote `LastModifiedDate` for each conflicting file.

feat: conflict detection UI enhancement

---

packages/salesforcedx-vscode-core/src/messages/i18n.ja.ts
packages/salesforcedx-vscode-core/src/messages/i18n.ts

Removes an unused message that makes reference to the deprecated sfdx-diff plugin.
@W-9166652@
N/A
N/A

chore: remove sfdx-diff message

---

packages/salesforcedx-vscode-core/package.json

Opening the packaged extension was failing due to global-agent being missing. This new version of functions-core moves global-agent to dependencies in package.json
VS Code would occasionally refuse to load due to a missing dependency on global-agent.
Dependency has been relocated and VS Code loads as expected.

fix: bump up functions-core version

---

packages/salesforcedx-vscode-core/package.json

Adds the changes for #3439 into the release branch to prevent releasing a breaking change.

fix: bump up functions-core version (#3439)

---

packages/salesforcedx-vscode-core/src/conflict/metadataCacheService.ts
packages/salesforcedx-vscode-core/test/vscode-integration/conflict/metadataCacheService.test.ts

This PR allows child components to work for conflict detection. Child components do not have their own FileProperties objects and thus have to use their parents'.
@W-9608415@
Deploying a single or multiple child components without their corresponding parent would never be able to detect conflicts.
Conflicts can be detected in child components, but they use their parents' lastModifed timestamps.
Testing this PR made me realize a piece of strange behavior for conflict detection, which is that extra conflicts can result from timestamps existing at the component level and not the file level. For example: a conflict exists in CustomField X and CustomField Y from the same CustomObject is deployed with a local change. A conflict will be detected in Y because the conflict in X caused the …

fix: support child components in correlateResults

---

packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-apex/package.nls.json
packages/salesforcedx-vscode-apex/src/commands/forceApexTestRun.ts
packages/salesforcedx-vscode-apex/src/commands/forceApexTestSuite.ts
packages/salesforcedx-vscode-apex/src/commands/index.ts
packages/salesforcedx-vscode-apex/src/index.ts
packages/salesforcedx-vscode-apex/src/messages/i18n.ts
packages/salesforcedx-vscode-apex/test/vscode-integration/commands/forceApexTestSuite.test.ts

This PR introduces Test Suites to our command palette. It adds the following commands:
- `SFDX: Run Apex Test Suite`
- Allows the user to choose an Apex Test Suite via quickpick. The test suite is run through the same code path as the test sidebar & the results are displayed after the test finishes running.
- `SFDX: Create Apex Test Suite`
- User enters the name of the new Apex Test Suite & selects tests to add to the suite via a quickpick. After selection, the command is run.
- `SFDX: Add Tests to Apex Test Suite`
- User chooses an existing Apex Test Suite and then selects tests to add to the select suite via the quickpick. After the selection, the command is run.
@W-9632080@
@W-9632072@
@W-9632048@
new functionality!
https://user-images.githubusercontent.com/21326913/126533374-5df40b6b-4 …

feat: introduce 3 Apex Test Suite commands

---

packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-core/src/commands/baseDeployRetrieve.ts
packages/salesforcedx-vscode-core/src/conflict/metadataCacheService.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/baseDeployRetrieve.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceSourceDeployManifest.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceSourceDeploySourcePath.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceSourceRetrieveManifest.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceSourceRetrieveMetadata/forceSourceRetrieveCmp.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceSourceRetrieveSourcePath.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/conflict/metadataCacheService.test.ts

This PR bumps SDR to 3.0.0 and fixes a few breaking changes from [SDR #334](https://github.com/forcedotcom/source-deploy-retrieve/pull/334/) which adds support for making asynchronous metadata transfers. 
SDR #334, @W-9521922@
There is no change in functionality. 
There is no change in functionality.

chore: bump SDR to 3.0.0

---

packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lwc/package.json

Updates the lightning language servers to the latest version (3.0.14)
@W-9556613@
No doc urls in `lightning/analyticsWaveApi` wire adapters' jsdoc hover text.
Doc urls are there:

chore: update lightning lang servers to 3.0.14

---

packages/salesforcedx-vscode-core/src/commands/forceSourceDeploySourcePath.ts
packages/salesforcedx-vscode-core/src/commands/forceSourceRetrieveSourcePath.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceSourceDeploySourcePath.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceSourceRetrieveSourcePath.test.ts

Set sourceApiVersion for sourcepath based deploy and retrieve
@W-9634598@
Source path based deploy/retrieve ignores the sourceApiVersion set in sfdx-project.json
Source path based deploy/retrieve respects the sourceApiVersion set in sfdx-project.json

Set sourceApiVersion for sourcepath based deploy and retrieve

---

packages/salesforcedx-vscode-lwc/src/testSupport/workspace/getCliArgsFromJestArgs.ts
packages/salesforcedx-vscode-lwc/test/vscode-integration/testSupport/mocks/vscodeConfiguration.ts
packages/salesforcedx-vscode-lwc/test/vscode-integration/testSupport/workspace/getCliArgsFromJestArgs.test.ts

Fixes LWC debug code lens issue for VS Code 1.60+
@W-9883286@

fix: fix debug code lens for vscode 1.60+

---

packages/salesforcedx-vscode-apex-replay-debugger/src/commands/traceFlags.ts
packages/salesforcedx-vscode-apex-replay-debugger/test/vscode-integration/commands/traceFlags.test.ts

There was an error with the trace flag start and end date overlapping, which is fixed by setting the start date on the trace flag when it is created and updated. This issue was [reported](https://developer.salesforce.com/forums/?id=9062I000000DIR4QAO) online, and also discovered while testing the tail log command.
#
When a trace flag is updated with the replay debugger, we receive an error message: `This entity is already being traced by a trace flag with a start and expiration date that overlap this trace flag's start and expiration date.: Traced Entity ID`. To get around this error, users have to delete the trace flag and create a new one.
Trace flags can be updated from the replay debugger directly.

fix: fix trace flag update error

---

packages/salesforcedx-vscode-core/src/commands/baseDeployCommand.ts

removed SDR from base deploy, since scratch orgs were running into errors in SDR for missing paths
@W-10004893@
When pushing code to scratch orgs, error messages were being quietly logged to our telemetry.
Telemetry will be cleaner, and make it easier to see real errors.

fix: unnecessary SDR errors

---

packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lwc/package.json

Update `lightning-language-server` (and related modules) to 3.1.0 to pickup the updated wire adapter type defs.
@W-9717230@
No code-complete or hover text on adapters added in forcedotcom/lightning-language-server#450
Code-completion and hover texts:
cc: @reidaelliott, @yijian-wang, @mblumreich

fix: update lightning-language-server to latest version

---

packages/salesforcedx-vscode-core/src/orgBrowser/metadataCmp.ts
packages/salesforcedx-vscode-core/test/vscode-integration/orgBrowser/metadataCmp.test.ts

Displays the items under org browser folders like Email Templates, Dashboards, Documents and Reports.
@W-10255794@

fix: org browser folders no longer display items

---

packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-core/src/orgBrowser/nodeTypes.ts

Provides the `Retrieve Source from Org` button for all custom objects in Org Browser
@W-10304052@

fix: display retrieve source button

---

.circleci/config.yml
.github/dependabot.yml
docs/_articles/en/getting-started/recommended-extensions.md
package.json

* Add config to enable dependabot to create PRs for updating dependencies 
* Add scheduled automated merging of minor/patch PRs
* Replaces https://github.com/forcedotcom/salesforcedx-vscode/pull/3690
@W-10247959@
* PRs to update dependencies were created manually
* PRs to update dependencies are created automatically by dependabot and merged on schedule according to given config

ci(dependabot): add dependabot config for updating dependencies

---

contributing/tests.md
packages/salesforcedx-vscode-core/src/orgPicker/orgList.ts
packages/salesforcedx-vscode-core/test/vscode-integration/orgPicker/orgList.test.ts

We already had a command to remove dead scratch orgs (#2523), but that functionality isn't readily
available to users, and it can be frustrating for new users to dig it up. Meanwhile the list of
expired orgs only grows! This change surfaces that functionality in the org list directly, so users
can view the commands that interact with their orgs from one spot.
@W-10351429@
The command `SFDX: Remove Deleted and Expired Orgs` was only available from the command palette.
It's now easier to clean up stale orgs. 🧹

feat: add ability to remove expired orgs from the org list

---

.circleci/config.yml
.github/dependabot.yml

Modifies CI configs to
* use recently added `squash` merge option with dependabot automerge
* 	that should fix `ERROR running dependabot:automerge: Merge commits are not allowed on this repository.`
* disable major version updates with dependabot temporarily until we have minor/patch updates working without any issues
Followup to #3714
@W-10247959@

ci: add squash merge option to automerge

---

packages/salesforcedx-vscode-soql/src/sfdx.ts
packages/salesforcedx-vscode-soql/test/vscode-integration/sfdx.test.ts

This PR removes a telemetry call that clutters telemetry unnecessarily.
@[W-10523357](https://gus.lightning.force.com/a07EE00000kLzFqYAK)@
When SOQL tooling fails to connect to an org for any reason, telemetry logs the error.
When SOQL tooling fails to connect to an org for any reason, there is no telemetry.

fix(soql): remove excess telemetry

---

.circleci/config.yml

Uses context to access common environment variables across different projects
@W-10714614@
All environment variables are defined at project settings.
Few common env variables are now defined in a context and remaining at project settings.

chore: use context for common env variables

---

packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lwc/package.json

Bump lightning language server to v3.5.0, which includes the following packages:
- aura-language-server": "3.5.0"
- lightning-lsp-common": "3.5.0"
- lwc-language-server": "3.5.0"
@10759995@
Bracket syntax ‘{ }’ did not work in HTML files for LWCs. So users would have to go into the JS file to find the variables they need, or type them out by hand.
We provide autocompletion for basic bracket syntax, including backspaces and retries.

chore: bump lightning language server to v3.5.0

---

packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-core/package.json

update SDR dependency to v15.12.3 which include readFileSync fix for ZipTree. This fixes the issue where we can diff objects against the org. 
@W-10159064@ @W-10120433@
Failed to retrieve diff for objects. 
Deploy source to org fails for custom objects. 
Successfully diffs objects against org. 
1. Right click Account -> Select `SFDX: Diff Folder Against Org`
Deploy source to org works as expected. 
01:50:45.605 Starting SFDX: Deploy Source to Org
=== Deployed Source
STATE      FULL NAME            TYPE          PROJECT PATH                                                            
─────────  ───────────────────  ────────────  ────────────────────────────────────────────────────────────────────────
Unchanged  Order__c.Account__c  CustomField …

fix(apex and core package.json): update SDR to v5.12.3 to pick up fix for child reads

---

packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-core/package.json

Running into issue on certain systems for users with the latest version of source-deploy-retieve.
This reverts to the version prior to the latest in order to unblock those users until an alternative
can be found.
#3901 
Some users are unable to run SFDX commands. 
Functionality should return to normal.

fix: revert source-deploy-retrieve to previous version

---

docs/_articles/en/getting-started/java-setup.md
docs/_articles/en/getting-started/recommended-extensions.md

We updated set documentation to include instructions for JDK 17.
#<Insert GitHub Issue>, @https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000TxnSEYAZ/view@
Documentation didn't include instructions for JDK 17
Documentation now includes instructions for JDK 17.

Update Java Setup for JDK 17

---

packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lwc/package.json

Bumps the lightning-language-server version to consume latest changes to prevent excessive
autocompletion in JS files with the opening of curly braces.
#3902 , @W-10832653@
Autocompletion was provided for all opening curly braces in LWC JS files.
Autocompletion is no longer triggered with curly braces in LWC JS files.

fix: prevent excessive autocompletion in template JS files

---

packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-lwc/package.json
packages/salesforcedx-vscode-lwc/package.nls.json

Add a new debugger configuration for LWC jest tests.
A few items to note that were different from how the tickets was written.
1. There is a @salesforce/lwc-jest-test module that is included in our default and analytics packages so no need to worry about verifying jest or the config existing. 
2. For an empty project with the current change the user will need to add the module from 1  in order to run the test.  
@W-10536658@
No debug configuration available for LWC jest tests

feat: add flow for creating LWC jest debug config

---

.git2gus/config.json

Adds a git2gus config mapping the label `type:community-contrib` to a `USER STORY`
@@
No direct way to create WIs associated with community contributed PRs
Git2Gus should be able to create WIs for community contributed PRs when `type:community-contrib` label is applied

config(git2gus): add community contribution label map to user story

---

packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lwc/package.json

Consumes the latest lightning-language-server packages, which fixes the textDocument/hover error in
the event that the lsp is incorrectly parsing the content of .js files.
#3929, @W-10857157@
Users were often experiencing the textDocument/hover error, which drew focus to the output panel and caused excessive noise.
This error is now suppressed, and users can continue developing without being constantly pestered with unhelpful errors 😌

fix: hover error fixed in LSP

---

scripts/change-log-generator-utils.js

Currently, denpendabot PRs are automatically categorized to "FIXED" field in changelog, which requires the technical writer to delete them manually. To reduce the workload for technical writer and minimize the number of commits for changing changlog, this PR makes changelog generator to ignore dependabot PRs. 
@W-10959446@

chore: changelog generator ignores dependabot PRs

---

packages/salesforcedx-vscode-core/src/commands/forceRenameLightningComponent.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceRenameLightningComponent.test.ts

Enable SFDX: Rename Component command to rename test file under __tests__ folder for LWC components. Only the test file that has the same name as component will be renamed. 
@W-10976932@
SFDX: Rename Component does not rename test file under __tests__ folder in LWC components. 
SFDX: Rename Component now rename the test file in LWC components as well.

fix: SFDX:Rename Component now also rename the test file that has the same name as component under __tests__ folder for LWC components

---

packages/salesforcedx-apex-debugger/package.json
packages/salesforcedx-apex-replay-debugger/package.json
packages/salesforcedx-sobjects-faux-generator/package.json
packages/salesforcedx-test-utils-vscode/package.json
packages/salesforcedx-utils-vscode/package.json
packages/salesforcedx-visualforce-markup-language-server/package.json
packages/salesforcedx-vscode-apex-debugger/package.json
packages/salesforcedx-vscode-apex-replay-debugger/package.json
packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lwc/package.json
packages/salesforcedx-vscode-soql/package.json
packages/salesforcedx-vscode-visualforce/package.json
packages/system-tests/assets/sfdx-simple/functions/demoJavaScriptFunction/package.json
packages/system-tests/package.json

* pin @types/chai to 4.3.0 as 4.3.1 has introduced breaking changes
@W-10994021@
Build is broken in main and multiple branches
Build is fixed

fix: changed version of types/chai to 4.3.0

---

package-lock.json
packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-lwc/package.json

- chore: update @salesforce/templates to 54.5.0 as followup to https://github.com/forcedotcom/salesforcedx-templates/pull/476
- override transitive ajv version from @salesforce/core breaking the build (vsce package)
@W-10832350@

chore: update @salesforce/templates to 54.5.0, fix ajv transitive dep version 

---

docs/404.html
docs/README.md

Update our 404 page in the repo to redirect to the docs site if the current url matches the github pages url. Should have zero impact on the current docs site. 
@W-10817909@
Showed an incomplete 404 page when attempting to access the github pages link for the repo 
Should redirect to the docs site (have to verify after merge).

fix(404.html): update github pages 404 to redirect to docs site

---

packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-core/package.nls.json
packages/salesforcedx-vscode-core/src/constants.ts
packages/salesforcedx-vscode-core/src/settings/sfdxCoreSettings.ts

Reverted setting to enable deploy and retrieve commands for source-tracked orgs
This reverts the work done in https://github.com/forcedotcom/salesforcedx-vscode/pull/4006/files, and will be added back in when we continue work on https://github.com/forcedotcom/salesforcedx-vscode/pull/4078

fix: reverted setting to enable deploy and retrieve commands for source-tracked orgs

---

docs/package.json
lerna.json
package-lock.json
packages/salesforcedx-apex-debugger/package.json
packages/salesforcedx-apex-replay-debugger/package.json
packages/salesforcedx-sobjects-faux-generator/package.json
packages/salesforcedx-test-utils-vscode/package.json
packages/salesforcedx-utils-vscode/package.json
packages/salesforcedx-visualforce-language-server/package.json
packages/salesforcedx-visualforce-markup-language-server/package.json
packages/salesforcedx-vscode-apex-debugger/package.json
packages/salesforcedx-vscode-apex-replay-debugger/package.json
packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-expanded/package.json
packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lwc/package.json
packages/salesforcedx-vscode-soql/package.json
packages/salesforcedx-vscode-visualforce/package.json
packages/salesforcedx-vscode/package.json
packages/system-tests/package.json
scripts/change-log-generator-utils.js

This reverts commit ff49172c0534bebcd9941929ff70eb3d340efe80.
revert build commit for moving to version v54.12.0
Needed in order to verify build via circleci for release.
Update commit builder script for change log to account for bad commit messages. 
This will enable us to re-run the release script in circle to generate the next release branch and change log.

 chore: revert commit for version 54.12.0

---

.github/dependabot.yml

- Reverts https://github.com/forcedotcom/salesforcedx-vscode/pull/3945
- Number of max open PRs by dependabot was increased for getting a figure of how many dependency updates have breaking code changes

ci: revert dependabot max open PRs limit back to 10

---

scripts/create-release-branch.js

Add package-lock.json to cut release script. Required due to the addition of npm workspaces to the repo. 
@W-11146084@
lock file was not included in commit pushed to develop
lock file is included.

chore: add package-lock.json change as a result of version bump to cut release script

---

packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lwc/package.json

This PR reflects recent changes in lightning language server:
-  Ctrl + Space now re-trigger autocomplete within {}: [#496](https://github.com/forcedotcom/lightning-language-server/pull/496)
-  Updated `@lwc/engine` version, now it's called `@lwc/engine-dom` [#502](https://github.com/forcedotcom/lightning-language-server/pull/502)
@W-1093050@
In HTML file, typing {} is the only way to trigger autocomplete for {}. 
If you delete the content within {} or move your cursor away then move it back within {}, you can use Ctrl + Space to re-trigger the autocomplete.

feat: Ctrl+Space now re-trigger autocomplete within {} in HTML file

---

package-lock.json
packages/salesforcedx-vscode-core/src/commands/util/parameterGatherers.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/util/parameterGatherers.test.ts

Fixed an issue where escaping from the 'Create Lightning Web Component Test' could generate an error.
#3983 , @W-10915684@
When you run the command 'Create Lightning Web Component Test', select a directory, then exit out of selecting a component, you get a nasty error, shown in #3983.
Escaping that command is quiet and error-message free, as it should be.

fix: allow for escaping lwc test create command

---

.circleci/config.yml

Update the circleci config for the create-release-branch job to install and use the latest npm. 
fix #4191
`npm install` fails with an E404 message due to the local workspaces not being in the package-lock.json file.  
Running npm install will update the package-lock.json file.

chore: update create-release-branch script to use latest npm

---

package-lock.json
packages/salesforcedx-vscode-core/package.json

The PR adds a default/boilerplate unit test to the LWC template.
When a new LWC is created, only the .js and .html are created. We should encourage our customers to write unit tests, and adding a default unit test along with the component class will help encourage customers to write unit tests.
What issues does this PR fix or reference?
#@W-11171762@

Updated @salesforce/templates to 55.0.0.  The LWC template now adds a unit test

---

packages/salesforcedx-vscode-core/package.json

Adds an additional when clause to specify where the generate manifest file command should appear.
@W-10737780@
Selecting any file or folder in the project would allow you to generate a manifest file.
The generate command now only appears in the package directory folder - ie. force-app directory.

fix: add additional context for scope of generate manifest command

---

package-lock.json
packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lwc/package.json

* Bumps the version of lightning and lwc language servers to version 3.10.  The new version adds a wire adapter type for getProgramTemplates in the lightning/salesEnablementProgramApi package, and handles malformed tags quietly when components are not compiled correctly due to the outdated LWC Compiler.

chore: bump lwc and lightning language servers to 3.10

---

packages/salesforcedx-vscode-core/package.json

This PR fixes the issue where the "Create Apex Class" option is not available in sub-directories of the `classes` directory when a user right-clicks on windows ( or control clicks on mac ).
#https://github.com/forcedotcom/salesforcedx-vscode/issues/3572, @W-10288492@
https://user-images.githubusercontent.com/599418/174657434-e32a4636-8d60-4ff1-bc6a-153a3889be92.mov
https://user-images.githubusercontent.com/599418/174658151-8ef486cd-9ee6-40c8-abd3-252b8ace425e.mov

fix: use regex to match sub-directories in when clause

---

package-lock.json

Bumps salesforcedx-schemas to 1.1.3 -> https://github.com/forcedotcom/schemas/compare/v1.1.0...v1.1.3
#4218
Functionality updated to use latest json for validation of sfdx json files

build: update the salesforcedx-schemas version to pick up the latest release

---

packages/salesforcedx-utils-vscode/src/helpers/index.ts
packages/salesforcedx-utils-vscode/src/helpers/utils.ts
packages/salesforcedx-utils-vscode/test/unit/helpers/utils.test.ts
packages/salesforcedx-vscode-apex/src/commands/forceLaunchApexReplayDebuggerWithCurrentFile.ts
packages/salesforcedx-vscode-apex/test/vscode-integration/commands/forceLaunchApexReplayDebuggerWithCurrentFile.test.ts
packages/salesforcedx-vscode-core/src/commands/forceSourceDelete.ts
packages/salesforcedx-vscode-core/src/commands/forceSourceDeploySourcePath.ts
packages/salesforcedx-vscode-core/src/commands/forceSourceRetrieveSourcePath.ts
packages/salesforcedx-vscode-core/src/commands/util/libraryPathsGatherer.ts
packages/salesforcedx-vscode-core/src/messages/i18n.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceSourceDelete.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceSourceDeploySourcePath.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceSourceRetrieveSourcePath.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/functions/forceFunctionStart/ForceFunctionContainerStartExecutor.test.ts

Issue reported for running deploy/retrieve on windows.  Suspect the change from PR #4240 so reverting to build and test on windows. 
#4261
deploy fails on windows
deploy succeeds on windows.

chore: Revert "fix: added flushFilePath() (#4240)"

---

package-lock.json
packages/salesforcedx-vscode-core/package.json

adds @octokit/plugin-paginate-rest@2.21.2 to the salesforcedx-vscode-core repo dependancies in order to avoid an issue that exists for 2.21.2.
patch release

chore: fix dep issue in 55.4.1 patch publish flow

---

packages/salesforcedx-vscode-core/test/vscode-integration/util/orgUtil.test.ts

This PR fixes a test that was failing.  The failure was due to the way JavaScript parses strings for dates, and constructs date objects.  Because of UTC offsets, the test would sometime pass, and sometimes fail.  To fix the issue, I just changed the day offset in the failing test.  No change to the actual implementation in `checkForExpiredOrgs()` was made.
No logged issue, just something discussed in Slack.
The `should display multiple orgs in the output when there are several scratch orgs about to expire` test was failing.
The `should display multiple orgs in the output when there are several scratch orgs about to expire` test is now passing.
No change to the actual implementation in `checkForExpiredOrgs()` was made.

fix: updated day offset to compensate for UTC and failing test

---

packages/salesforcedx-utils-vscode/src/commands/channelService.ts
packages/salesforcedx-utils-vscode/src/commands/commandletExecutors.ts
packages/salesforcedx-utils-vscode/src/commands/notificationService.ts
packages/salesforcedx-utils-vscode/src/commands/sfdxCommandlet.ts
packages/salesforcedx-utils-vscode/src/constants.ts
packages/salesforcedx-utils-vscode/src/index.ts
packages/salesforcedx-utils-vscode/src/settings/index.ts
packages/salesforcedx-utils-vscode/src/settings/sfdxSettingsService.ts
packages/salesforcedx-utils-vscode/src/telemetry/telemetry.ts
packages/salesforcedx-utils-vscode/test/unit/commands/channelService.test.ts
packages/salesforcedx-utils-vscode/test/unit/commands/commandletExecutor.test.ts
packages/salesforcedx-utils-vscode/test/unit/settings/sfdxSettingsService.test.ts
packages/salesforcedx-vscode-apex-replay-debugger/src/utils/settings.ts
packages/salesforcedx-vscode-apex-replay-debugger/test/vscode-integration/commands/quickLaunch.test.ts
packages/salesforcedx-vscode-apex/src/settings.ts
packages/salesforcedx-vscode-apex/test/vscode-integration/commands/forceApexExecute.test.ts
packages/salesforcedx-vscode-apex/test/vscode-integration/settings.test.ts
packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-core/package.nls.ja.json
packages/salesforcedx-vscode-core/package.nls.json
packages/salesforcedx-vscode-core/src/commands/util/sfdxCommandlet.ts
packages/salesforcedx-vscode-core/src/constants.ts
packages/salesforcedx-vscode-core/src/index.ts
packages/salesforcedx-vscode-core/src/settings/sfdxCoreSettings.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/util/sfdxCommandlet.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/telemetry/index.test.ts
packages/salesforcedx-vscode-lwc/test/vscode-integration/jsconfig.test.ts

This PR adds a user/workspace preference and changes the preference category they display under in the preferences UI.  When set, the output channel is cleared between each common command.   There are a few commands that do not output to the channel ( Like Create Soql Query ) and those do not clear the channel.
#941, @W-10288504@
Old and New Preference Shown Below
https://user-images.githubusercontent.com/599418/180885264-b1a61c1b-42f8-4e73-86d2-e9d7f9238fbe.mov

Add preference clear output channel

---

packages/salesforcedx-vscode-core/src/orgPicker/orgList.ts
packages/salesforcedx-vscode-core/test/vscode-integration/orgPicker/orgList.test.ts

since no longer reading from disk to generate the fileInfos but instead using
AuthInfo.listAllAuthorizations()

refactor: remove unneeded getOrgAuthorization method and related tests

---

packages/salesforcedx-vscode-core/src/commands/forceCreateManifest.ts

Fixes manifest builder for core v3. Consolidated retrieval of package.xml to limit passing around unnecessary data and resolve promise early.
#@W-11556536@
Manifest builder wasn't working with core v3 bump (getting an error)
Manifest builder is working again!

fix: fixed manifest builder error

---

packages/salesforcedx-vscode-apex/src/messages/i18n.ts
packages/salesforcedx-vscode-core/src/messages/i18n.ts

Moves an error message from one i18n file to another in different packages so that the message is displayed correctly 
#4351, @W-11555524@

fix: missing error label

---

packages/salesforcedx-vscode-core/src/commands/baseDeployRetrieve.ts
packages/salesforcedx-vscode-core/src/util/authInfo.ts
packages/salesforcedx-vscode-core/src/util/configUtil.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/baseDeployRetrieve.test.ts

Uses the Api Version from the order associated with the default username when deploying components, if there is no local or global value that has been configured by the user in settings.
@W-11555227@

refactor: use org api version if no user config

---

package-lock.json

Bump the version of core to the latest in order to pick up changes make for templates.

chore: bump version of @salesforce/core in all packages to 3.26.1

---

.github/workflows/publish-beta-release.yml

- Reverts latest, since that syntax [did not work](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/2974301105).

chore: workflow fix for node version

---

packages/salesforcedx-vscode-core/src/settings/index.ts
packages/salesforcedx-vscode-core/src/settings/pushOrDeployOnSave.ts
packages/salesforcedx-vscode-core/test/vscode-integration/settings/pushOrDeployOnSave.test.ts

Prevents the auto-deploy of SOQL and anonymous apex files that are stored within the main project directory.
#4050 
Save happens, and no deploy is attempted 🛑

fix: prevent soql and anon apex files from deploying on save

---

packages/salesforcedx-vscode-core/package.json

This PR reverts the changes made in [4208](https://github.com/forcedotcom/salesforcedx-vscode/pull/4208/files) PR. The project can be customized in multiple package directories and not necessarily have `force/app` folder in it. It caused more harm than gain. So reverting it.
#4310
`SFDX: Generate Manifest File` option was only available within force-app directory.
`SFDX: Generate Manifest File` option available on open project.

fix: generate manifest command option in open projects

---

packages/salesforcedx-sobjects-faux-generator/src/transformer/transformerFactory.ts
packages/salesforcedx-utils-vscode/src/config/configUtil.ts
packages/salesforcedx-utils-vscode/src/index.ts
packages/salesforcedx-utils-vscode/src/providers/configAggregatorProvider.ts
packages/salesforcedx-utils-vscode/src/providers/index.ts
packages/salesforcedx-utils-vscode/src/workspaces/index.ts
packages/salesforcedx-utils-vscode/src/workspaces/rootWorkspace.ts
packages/salesforcedx-utils-vscode/src/workspaces/workspaceUtils.ts
packages/salesforcedx-utils-vscode/test/unit/config/configUtil.test.ts
packages/salesforcedx-utils-vscode/test/unit/providers/configAggregatorProvider.test.ts
packages/salesforcedx-vscode-core/src/commands/forceRefreshSObjects.ts
packages/salesforcedx-vscode-core/src/context/workspaceContext.ts
packages/salesforcedx-vscode-core/src/providers/index.ts
packages/salesforcedx-vscode-core/src/util/configUtil.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceRefreshSObjects.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/util/authInfo.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/util/configUtil.test.ts

This is a change to prove out having a dependency from core to the utils-vscode package. The intention is to only have classes for accessing configs in the untils package that all other extensions use to utilize.
@W-11528403@
configAggragatorProvider lives in core package.
refresh sobject command will fail with error due to use of alias instead of username. 
configAggragatorProvider lives in the utils package.
refresh sobject command works as expected

Chore: move the configAggregator to the utils package. 

---

package-lock.json
packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lwc/package.json

This PR reflects recent changes in lightning lsp common:
- Gets rid of the double logging to the LWC Language Server Output Tab when Attribute Not Found: [#510](https://github.com/forcedotcom/lightning-language-server/pull/510)
[@W-11307712@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000zN76PYAS/view)
- "Attribute x not found" was being logged twice per each cmd+click/hover when applicable
- "Attribute x not found" is being logged once per each cmd+click/hover when applicable

fix: remove double logging from lwc language server on error

---

packages/salesforcedx-vscode-core/src/conflict/metadataCacheService.ts

Remove an unused import that was pulling from the not public level of SDR.
#4490
No impact. import was unused.

chore: cleanup unused invalid SDR import

---

packages/salesforcedx-vscode-core/src/commands/auth/forceAuthWebLogin.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/auth/forceAuthWebLogin.test.ts

*Problem*
When using the org login command in a containerized environment such as Code Builder, the core extension uses the device flow. When the initial device flow request returns with a verification URL, the `user_code` query parameter is appended and the URL is opened in a new tab. This is the `/connect` page. When the page form is submitted:
- If there is an active browser session to an org, the device flow with authorize the device to the org that is currently logged in.
- If not, the device flow will route the user to the login screen, where they can supply their credentials for their target org.
The first case is often an inconvenience for developers, who may want to log in to the Sandbox, DE Org,  or Dev Hub of their choice rather that whatever org is currently logged in. Even if …

chore: always show login screen for device flow

---

packages/salesforcedx-utils-vscode/src/providers/configAggregatorProvider.ts
packages/salesforcedx-utils-vscode/test/unit/providers/configAggregatorProvider.test.ts

Update the config agg provider to not attempt to chdir when the current working directory is undefined or empty string.
#4465
Successful creation of a new project from the empty project state.

fix: update to verify path exists before chdir in configAggProvider

---

.circleci/config.yml
package-lock.json
packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-core/src/commands/templates/forceFunctionCreate.ts

Update the core extension bundling to exclude the functions-core module from bundling. 
To test this change do the following: 
1. npm install 
2. npm run compile 
3. cd package/salesforcedx-vscode-core
4. npm run bundle:extension
5. npm run vscode:package
This will generate the `salesforcedx-vscode-core-56.4.0.vsix` extension.
To install: 
Go to whatever version of vscode you'd like to use for verifying the extension.  Uninstall add salesforce extension & reload.
Click the '...' button at the top of the extensions view and then 'install from vsix' 
select the generated vsix file 
The bundled extension should now be installed in your vscode and you can test with 
'SFDX: Create Function'
fix #4531 
@W-11998949@
Create Functions command fails for all types when used from a bundled core …

fix: update bundling for core extension to exclude functions-core

---

packages/salesforcedx-vscode-apex-debugger/package.json

Update the apex interactive debugger extension to exclude @salesforce/core and install it directly in the packaged extension.
This was due to updating the apex debugger to use the common code in utils for getting the config directory.  B/c it pulled in utils and utils depends on core this required a move to having core external for the extension. 
#4536 @W-120117332@
apex interactive debugger failed to activate
apex interactive debugger activates without issue.

fix: update apex interactive debugger package step to include @salesforce/core

---

package-lock.json
packages/salesforcedx-sobjects-faux-generator/package.json
packages/salesforcedx-utils-vscode/package.json
packages/salesforcedx-vscode-apex-debugger/package.json
packages/salesforcedx-vscode-apex-replay-debugger/package.json
packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-core/src/commands/forceSourceRetrieveMetadata/forceSourceRetrieveCmp.ts
packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lwc/package.json
packages/salesforcedx-vscode-soql/package.json

- bumps SDR version from 6.0.4 to 7.5.5
- bumps sfdx-core to 3.31.18
@W-11549361@, https://github.com/forcedotcom/salesforcedx-vscode/issues/4498
@salesforce/source-deploy-retrieve at 6.0.4
@salesforce/core at ^3.23.0
@salesforce/source-deploy-retrieve at 7.5.5
@salesforce/core at ^3.31.18

chore: update SDR version 6.0.4 to 7.5.5

---

packages/salesforcedx-vscode-core/src/constants.ts
packages/salesforcedx-vscode-core/src/context/workspaceContext.ts
packages/salesforcedx-vscode-core/src/decorators/index.ts
packages/salesforcedx-vscode-core/src/decorators/scratch-org-decorator.ts
packages/salesforcedx-vscode-core/src/index.ts
packages/salesforcedx-vscode-core/test/jest/decorators/scratch-org-decorator.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/context/workspaceContext.test.ts

Just a place holder PR for showing updates to get things working again for int tests for PR #4514 
Fix two things here.
1. So the issue with running the integration tests in core was a circular dependency.  index.ts -> decorators.ts -> index.ts.  It def wasn't obvious and I only eventually found the solution by looking at what changed paired with the stack trace. Fix was to move the command constant from index to the constants file and 🏁 
2. After getting the int tests running again I was seeing a failure in the workspaceContest test.  There were two issues there.  The first was how the  stub for showOrg was getting created: 
`showOrgStub = env.stub(showOrg).resolves();` ❌ 
`showOrgStub = env.stub(decorators, 'showOrg').resolves();` ✅ 
The second was our old pass by value problem friend. …

chore: update how we import command const and alter test 

---

.circleci/config.yml
.github/workflows/buildAll.yml
.github/workflows/createReleaseBranch.yml
.github/workflows/integrationTests.yml
.github/workflows/integrationTestsWindows.yml
.github/workflows/nightlyBuildDevelop.yml
.github/workflows/nightlyBuildMain.yml
.github/workflows/testCommitExceptMain.yml
.github/workflows/unitTests.yml
.github/workflows/unitTestsLinux.yml
.github/workflows/unitTestsWindows.yml
.github/workflows/validatePR.yml

Add Name for any github actions workflows that were missing it.  Put the slack notification back on the cutReleaseBranch job since it is now merged into main. 
@W-11949791@ 
Names will be listed instead of workflow files.

chore: add names to all GHA workflows.  put slack notification back

---

package-lock.json
packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-core/package.json

Bumps the templates library, which contains a fix removing the additional line which is added when creating Apex Classes from the default class template.
This PR also includes the version bump that sets the default API version for all metadata to the latest major Salesforce version 56.
#3490 
Compare behavior before (left) with after (right):

fix: fix extra line from default apex template and all default versions

---

.github/workflows/buildAll.yml
.github/workflows/integrationTests.yml
.github/workflows/integrationTestsWindows.yml
.github/workflows/nightlyBuild.yml
.github/workflows/nightlyBuildDevelop.yml
.github/workflows/nightlyBuildMain.yml
.github/workflows/unitTests.yml
.github/workflows/unitTestsLinux.yml
.github/workflows/unitTestsWindows.yml

Update the GHA nightly workflows to fix the issue of being able to pass a branch to run on the other workflows. Note that the branch inputs are optional on all but the nightly workflow and should default to an empty string which will continuing using the default behavior.  
Also updated the time when the nightly tasks are run to be more middle of the night.
@W-11949791@
nightly runs for main/develop failing due to branch inputs not being supported for the underlying workflows. 
Update to allow passing the specific branch.

ci: fix nightly workflow for branch handling

---

package-lock.json
package.json
packages/salesforcedx-vscode-lwc/src/constants.ts
packages/salesforcedx-vscode-lwc/src/index.ts
packages/salesforcedx-vscode-lwc/test/vscode-integration/activation/activationMode.test.ts
packages/salesforcedx-vscode-lwc/test/vscode-integration/jsconfig.test.ts
packages/salesforcedx-vscode-lwc/test/vscode-integration/testSupport/testExplorer/testOutlineProvider.test.ts
scripts/download-vscode.js
scripts/install-vsix-dependencies.js
scripts/run-tests-with-recipes.js
scripts/vscode-integration-testrunner.js

Update the vscode-test dependancy.
Alter a few lwc vscode-integration tests to make them more reliable. 
Add Logging to the integration test script so we can track where they fail when they do. 
@W-12216803@
Every GHA int test run fails.
GHA int test runs succeed.

ci: update vscode-test and add logging for tests

---

package-lock.json
packages/salesforcedx-utils-vscode/src/config/configUtil.ts
packages/salesforcedx-utils-vscode/src/context/workspaceContextUtil.ts
packages/salesforcedx-utils-vscode/test/jest/context/workspaceContextUtil.test.ts
packages/salesforcedx-vscode-core/src/orgPicker/index.ts
packages/salesforcedx-vscode-core/src/orgPicker/orgList.ts
packages/salesforcedx-vscode-core/src/util/authInfo.ts
packages/salesforcedx-vscode-core/test/vscode-integration/orgPicker/orgList.test.ts

* Skips Org Authentications that have errors when building the org list for display.
* Clears the cache of StateAggregator after modifying the config file to ensure it loads up the freshest data.
#4519, @W-11970040@
1. Authorize an org (SFDX: Authorize an Org)
2. Log out from all auth’d orgs (or just the default) (SFDX: Log Out from All Authorized Orgs)
3. Click on the “No Default Org Set” in the bottom status bar
4. See the “No auth info found for <org auth’d in step 1>” error msg
or
1. Authorize an org with an alias (SFDX: Authorize an Org) 
2. Right click on a Class or the classes folder in the Explorer View
3. Click "SFDX: Deploy Source to Org"
4. See the “No auth info found for <org auth’d in step 1>” error msg
1. Authorize an org (SFDX: Authorize an Org)
2. Log out from all auth’d …

fix: Fix "No authorization information found" Error After Authenticating an Org

---

packages/salesforcedx-vscode-lwc/test/vscode-integration/navigation.test.ts

Int test failed in the nightly build so I took a look at it and made it more reliable. 
@W-12216803@
Test would fail depending on the order of the values returned in the code lens.
Find the failure in this GHA run https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/3701606628/jobs/6271072025
Test will pass regardless of position of the expected file in the results.

test: update flakey lwc test

---

.github/workflows/buildAll.yml
.github/workflows/buildAndTest.yml
.github/workflows/publishOnMergeWIthMain.yml
.github/workflows/publishVSCode.yml

- add a custom name for publish vsixes  that get uploaded during the publish flow
- add secrets to the publish flow so that slack calls will work
- 
@W-11596486@
All artifacts uploaded though GHA were named the same
Artifacts uploaded during publish flow use version for the name.

ci: add custom name for vsixs uploaded for publish

---

.github/workflows/publishVSCode.yml

- Update the publishVSCode GHA to always checkout the code prior to interacting with GH
- Use npx with vsce so it can be found during publish. 
- 
@W-11596486@
Failed due to not checking out the code when generating a sha for publish
checks out code prior to sha generation.

ci: update publish job to checkout code correctly

---

package.json
scripts/generate-sha256.js

Update the script and related npm script for generating the SHAs during publishing.
Note this PR is targeting main b/c it needs to be in main in order to get executed for during the deploy.
@W-11596486@
Previous way SHAs were generated depended on the vsix being in the each package directory.  With GHA we have them all in a single top level directory. 
sha report correctly built off the single directory of vsix files.

ci: Fix how was generate the SHAs for validating published extensions

---

packages/salesforcedx-utils/src/helpers/ensureCurrentWorkingDirIsProjectPath.ts
packages/salesforcedx-utils/src/helpers/index.ts
packages/salesforcedx-utils/test/jest/helpers/ensureCurrentWorkingDirIsProjectPath.test.ts
packages/salesforcedx-vscode-core/src/index.ts

* Sets the current working directory to the projectPath at activation time for better integration with VSCE's's core shared libraries.
@W-12424555@
VSCE processes run in the default dir ('/') on a Mac
VSCE processes run in the project directory (returning project path from process.cwd()) after activation.

feat: Switch to Project Path at Activation for Better Integration with Shared Libraries

---

.github/workflows/publishVSCode.yml

- Add a button to the release job for publishing from main.
- Update the configuration for firing off the publish job to only happen for actual releases and not pre-releases instead of filtering in the workflow. 
@W-12370302@

ci: add manual publish option

---

.github/workflows/integrationTestsWindows.yml

After changing the VSCode version used to run the windows integration tests it was discovered that the npm version has now changed for the node install flow we were using in the GHA.  To stay consistent with local development I altered the GHA to use the .nvmrc file to pick the npm/node version installed for running the int tests. 
I verified this functionality in my fork prior to opening this PR. 
https://github.com/gbockus-sf/salesforcedx-vscode/actions/runs/4127688182/jobs/7131203184
@W-12498824@
Int tests fail on npm setting 
```
Run npm config set scripts-prepend-node-path true
npm ERR! `scripts-prepend-node-path` is not a valid npm option
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\npm\cache\_logs\2023-02-08T19_0[6](https://github.com/forcedotcom/salesforcedx …
```

ci: update windows int test GHA to use nvmrc

---

package-lock.json
packages/salesforcedx-apex-debugger/package.json
packages/salesforcedx-apex-replay-debugger/package.json
packages/salesforcedx-apex-replay-debugger/test/unit/commands/apexExecutionOverlayResultCommand.test.ts
packages/salesforcedx-test-utils-vscode/package.json
packages/salesforcedx-utils-vscode/package.json
packages/salesforcedx-utils/package.json
packages/salesforcedx-utils/src/requestService/requestService.ts
packages/salesforcedx-utils/test/jest/requestService/__snapshots__/requestService.test.ts.snap
packages/salesforcedx-utils/test/jest/requestService/requestService.test.ts
packages/salesforcedx-vscode-apex-replay-debugger/package.json
packages/salesforcedx-vscode-apex-replay-debugger/test/vscode-integration/commands/apexExecutionOverlayActionCommand.test.ts

Update the version of request-light we import and ^ the dep so we pickup updates in the future. 
This is to fix the issue where when SDR attempts to go find the current API version via a request using the got module it is failing due to an older agent-base that patched https.request.
The error was only present in when running via vsix.  I believe with was b/c request-light is getting bundled with the source and it would load in such a way that the https.request was patched at startup vs when needed when running in debugging mode.
The problem code can be found in the before version bundle by running `npm run vscode:bundle` from the top level directory of the project.  Then view the `packages/salesforcedx-vscode-core/dist/index.js` file and search for `https.request =`.  
Note this is no …

chore: update request-light dependency to avoid patching https.request

---

.github/workflows/buildAll.yml
.github/workflows/createReleaseBranch.yml
.github/workflows/publishBetaRelease.yml
.github/workflows/publishVSCode.yml
.github/workflows/tagAndRelease.yml

Update the setup-node steps in our GHA configs to use the `.nvmrc` file to install the same version of node we use locally and define in package.json. 
@W-12573832@
GHA scripts failed due to node version mismatch
GHA script succeed. 
Verified the buildall flow and createReleaseBranch flow in my fork [here](https://github.com/gbockus-sf/salesforcedx-vscode/actions)

ci: update build/publish steps to use nvm for node version

---

packages/salesforcedx-apex-debugger/test/unit/commands/baseDebuggerCommand.test.ts
packages/salesforcedx-visualforce-language-server/test/unit/javascriptMode.test.ts

There was a single unit test that was regularly failing locally due to a timeout.  Fixed it locally by adding a longer timeout.
There were some unit tests that were failing locally due to the recent request-light update.  Fixed. 
Related to @W-9466545@
Unit tests failed local
Unit tests pass. 
Created 
https://github.com/forcedotcom/easywriter/issues/140 to track why a couple of the tests suites are exiting early in GHA which is why we didn't see the unit test failure in the visualforce package on GHA.

chore: fix unit tests

---

.github/workflows/release.yml
contributing/publishing.md

The environment during the `Test, Build, and Release` GHA was proving unnecessary. We can't get the VSIX files from the held build, so our updated flow should be: 
- `Test, Build, and Release` creates a github release without intervention
-  `Publish in Microsoft Marketplace` job starts automatically and pauses execution to allow for testing
-  VSIX files are downloaded from there for testing
-  If a serious bug is found, we can delete the tag & release
-  Otherwise, approve the `Publish in Microsoft Marketplace` job
Follow-up to #4627 
- `Test, Build, and Release` **needs to be manually approved before creating a release**
-  `Publish in Microsoft Marketplace` job **starts after approval** and pauses execution to allow for testing
-  VSIX files are downloaded from there for testing
-  If …

ci: remove environment from release and update publishing doc

---

package-lock.json
packages/system-tests/package.json
packages/system-tests/tsconfig.json

* On a recently re-imaged M1 Mac, I am unable to install with the following error. 
* This PR unblocks my current build on M1 by removing the offending dependency (that is no longer used by VSCE anyway)
`npm ERR! code 1
npm ERR! path /Users/kenneth.lewis/dev/salesforcedx-vscode/node_modules/electron-chromedriver
npm ERR! command failed
npm ERR! command sh -c node ./download-chromedriver.js
npm ERR! /Users/kenneth.lewis/dev/salesforcedx-vscode/node_modules/electron-chromedriver/download-chromedriver.js:19
npm ERR!   if (err != null) throw err
npm ERR!                    ^
npm ERR!
npm ERR! Error: Failed to find Electron v7.0.0 for darwin-arm64 at https://github.com/electron/electron/releases/download/v7.0.0/chromedriver-v7.0.0-darwin-arm64.zip
npm ERR!     at Request.<anonymous> …

refactor: Remove Dependencies Causing Install Issues on M1 (electron, spectron)

---

package-lock.json
packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lwc/package.json

Updates the version of the lighting-language-server dependencies to pick up:
- updated lighting/salesAutomationRulesApi typings from https://github.com/forcedotcom/lightning-language-server/pull/555.
- updated lightning/messageService to be optional from https://github.com/forcedotcom/lightning-language-server/pull/547
- updated lightning/placeQuoteApi, lightning/industriesSchedulerApi, lightning/salesEnablementProgramApi typings from: https://github.com/forcedotcom/lightning-language-server/pull/544
@W-12689558@
No hover text or code completion for some adapters
Hover text and code completion for some adapters

feat: bump lightning language server version

---

package-lock.json
packages/salesforcedx-vscode-lwc/package.json

- Add a flag to esbuild for the vscode-lwc package to get around the fsevents error 
- ```       ✘ [ERROR] No loader is configured for ".node" files: node_modules/fsevents/fsevents.node
node_modules/fsevents/fsevents.js:13:23:
13 │ const Native = require("./fsevents.node");
╵                        ~~~~~~~~~~~~~~~~~```
- Revert @salesforce/eslint-config-lwc back to 3.3.3 
- ```       ✘ [ERROR] Could not resolve "@babel/preset-typescript/package.json"
node_modules/@babel/core/lib/config/files/module-types.js:87:40:
87 │ ...st packageJson = require("@babel/preset-typescript/package.json");```
@W-12947525@
bundling fails
bundling succeeds

chore: updates fix bundling of vsixs

---

scripts/create-release-branch.js

Allows for a release branch to be generated even if the changelog creation fails. This week there was an error that caused a patch release to fail, but the commit had already been pushed to develop. This avoids having to revert or cherry-pick the version bump commit.
Example of the changelog failing in my fork [here](https://github.com/randi274/salesforcedx-vscode-fork/actions/runs/4692455457/jobs/8318195026), but [the branch](https://github.com/randi274/salesforcedx-vscode-fork/tree/release/v57.10.5) is still created.
Whereas [this](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/4670468097) failure in the main repo did not create the correct branch, and I had to create + cherry-pick the version bump.
@W-12471668@
A failure in the changelog creation wouldn't create the …

ci: add error handling for changelog generation

---

package-lock.json
packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lwc/package.json

Fixes an issue where internal developers weren't able to use the Lightning Language Server with the BLT setup.
@W-13007946@. Includes forcedotcom/lightning-language-server#564.
The LWC Language Server would show errors if BLT was not included in Core developer setup. 
The Language Server checks for a configuration setup at a different location that is more commonly used, and doesn't require the use of the core config if it can't be located.

fix: update lls to fix core devs

---

package-lock.json
packages/salesforcedx-vscode-apex-debugger/package.json
packages/salesforcedx-vscode-apex-debugger/tsconfig.json
packages/salesforcedx-vscode-apex-replay-debugger/package.json
packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lwc/package.json
packages/salesforcedx-vscode-soql/package.json

Update the extensions that use the salesforcedx-vscode-utils package to exclude `@salesforce/source-tracking` from the bundle.  
Related to 
@W-11309172@
@W-13051164@
vsixes for several extensions failed to activate.
all extensions activate.

chore: update bundles to exclude source-tracking

---

packages/salesforcedx-vscode-soql/src/sfdx.ts
packages/salesforcedx-vscode-soql/test/jest/sfdx.test.ts
packages/salesforcedx-vscode-soql/test/vscode-integration/sfdx.test.ts

Suppresses the `error_connection` ("We can’t query your org") toast message when no default org is set when opening VS Code. It retains the message in other cases, such as when actually opening the SOQL builder or trying to query the org.
@W-13131914@
When opening VS Code without a default org set, the SOQL extension would display an error on project load. Additional errors also shown when trying to open the SOQL builder or run a SOQL query.
When opening VS Code without a default org set, no error is shown on project load. Errors are only shown when trying to open the SOQL builder or run a SOQL query.

fix: soql builder should not error when no default org

---

package-lock.json
packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lwc/package.json

Updates the lightning language server dependency to process stale components faster during initialization. 
#4829, forcedotcom/lightning-language-server#568
Startup of projects with large LWCs was slowed significantly by reloading the list of components in a loop.
These projects should now startup faster as that list is loaded in advance.

perf: update to lightning language server performance

---

packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-core/package.json

This is a follow-up to #4851 to include bundling updates. It was discovered during release testing that `@salesforce/templates` had not been included in the bundled updates for the extensions. 
#4851 
Templates had not been updated in the bundled release.
Templates will be updated correctly next week.

build: update bundling for salesforce/templates

---

packages/salesforcedx-vscode-core/src/index.ts

Service will be used to report back telemetry data from within the GPT extension.
Exposes the `TelemetryService` in the core API.
@W-13218122@
Only the telemetry service which had been instantiated in the core extension was exposed via the API
We have access to the TelemetryService class to instantiate and report from within the GPT extension.

feat: expose TelemetryService class in core API

---

package-lock.json
packages/salesforcedx-vscode-apex-replay-debugger/package.json
packages/salesforcedx-vscode-apex/package.json

Pinned apex-node to v1.6.1 as v1.6.2 introduced a major release of @salesforce/core. The new version is causing compile errors with conflicts on class Connection from core. 
@W-13532434@

fix: pin apex-node to 1.6.1 due to conflicts

---

.github/workflows/validatePR.yml

Runs the validate PR workflow when just the PR description is edited.
https://github.com/forcedotcom/easywriter/issues/173, @W-13522251@
Validate PR workflow runs when commits are pushed to the branch.
In addition to the existing functionality, Now Validate PR workflow also runs when just the PR description is edited with no commits pushed.

fix: re-run pr validation

---

packages/salesforcedx-vscode-core/src/index.ts

* exposes WorkspaceContext, so that we can use the API from the core extension to access the connection to the default org in dependent extensions
@W-13217600@
* workspace context was not exposed via the API
* workspace context is exposed via the API

feat: expose WorkspaceContext from core extension API

---

.github/workflows/e2e.yml

- Adds a new command `npm run setup` before running any e2e test in step `Run headless test`
- Make use of two GHA secrets
#<Insert GitHub Issue>, @W-12516010@
No Authorization step before running e2e test.
Authorize to a persistent testing org before running one / all e2e test.

feat: add authorize devhub to e2e gha

---

packages/salesforcedx-vscode-core/src/services/sdr/componentSetUtils.ts
packages/salesforcedx-vscode-core/test/jest/services/sdr/componentSetUtils.test.ts
packages/salesforcedx-vscode/CHANGELOG.md

This hot fix removed the `exports.` that was added in v58.3.0.
https://github.com/forcedotcom/salesforcedx-vscode/issues/4938, @W-10273533@

fix: hot fix for 58.3.1

---

.vscode/launch.json
packages/salesforcedx-vscode-core/src/commands/baseDeployRetrieve.ts
packages/salesforcedx-vscode-core/src/conflict/metadataCacheService.ts
packages/salesforcedx-vscode-core/src/services/sdr/componentSetUtils.ts
packages/salesforcedx-vscode-core/test/jest/conflict/metadataCacheService.test.ts
packages/salesforcedx-vscode-core/test/jest/services/sdr/componentSetUtils.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/baseDeployRetrieve.test.ts

This PR adds the unit tests for componentSetUtils.ts back in.  In order to do so:
1. The way function are exported in componentSetUtils.ts was changed
2. How the functions in componentSetUtils are imported was changed to reflect the new export style
3. The unit tests for componentSetUtils was aded back in.
https://github.com/forcedotcom/salesforcedx-vscode/issues/4938, @W-10273533@

fix: changed export style of componentSetUtils.ts and added unit tests back in

---

packages/salesforcedx-vscode-lwc/package.json
packages/salesforcedx-vscode-lwc/snippets/lwc-html.json
packages/salesforcedx-vscode-lwc/snippets/lwc-js.json
packages/salesforcedx-vscode-lwc/snippets/lwc.json

Created snippets for each LWC HTML component and certain variants. Full list of components/ variants at bottom
#4857 
longform writing of LWC components and pivoting back to documentation
https://github.com/forcedotcom/salesforcedx-vscode/assets/4053083/698daf9b-4cb6-4935-b7f2-697c1cc653aa
| name                                      | qa pass |
| ----------------------------------------- | ------- |
| lwc-accordion                             | x       |
| lwc-accordion-section                     | x       |
| lwc-avatar                                | x       |
| lwc-badge                                 | x       |
| lwc-barcode-scanner                       | x       |
| lwc-breadcrumb-link                       | x       |
| lwc-breadcrumb-onclick                    | x       |
| …

Chore: Add Snippets for LWCsIssue 4857

---

packages/salesforcedx-vscode-core/package.json

- Adds @salesforce/source-tracking to the excluded libs in the bundling script
closes
#4945 #4867

chore: fix to exclude source-tracking in bundling

---

packages/salesforcedx-vscode-core/src/commands/isvdebugging/bootstrapCmd.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/isvdebugger/bootstrapCmd.test.ts

Upgrades deprecated cli flags to new flags.
Removes warnings while setting up the ISV debugger
#<Insert GitHub Issue>, @W-13834204@
| Old style  | New style |
|--------|--------|
| --outputdir | --output-dir |
| --projectname | --name |
| --targetusername | --target-org |
| --retrievetargetdir | --target-metadata-dir |
| --unpackaged | --manifest |
|--packagenames | --package-name |
isvDebuggerSid | org-isv-debugger-sid
isvDebuggerUrl |org-isv-debugger-url
instanceUrl |org-instance-url
Cli warnings should go away
Docs for reference: https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_force_mdapi.htm#cli_reference_force_mdapi_retrieve

feat: replace sfdx to sf style flag name

---

.github/workflows/integrationTestsWindows.yml

Replaces the `1.74.3` pinned version of vscode with `stable` in IntegrationTestsWindows.yml
Now it allows the win integration tests to run on latest stable version of vscode.
@W-12498824@
Win Integration tests were run on vscode v1.74.3
Win Integration tests run on latest stable version
Reference: #[VSCode Issue](https://github.com/microsoft/vscode/issues/181528)

chore: remove pinned vsc version from int test run

---

.github/workflows/createReleaseBranch.yml

Modifies default branch shown in the dropdown to cut a new release branch
@W-14002446@
- Default branch type to cut a new release branch is 'minor'
- Default branch type to cut a new release branch is 'patch'

chore: modify default branch type for cut release branch workflow

---

.github/workflows/createReleaseBranch.yml

- Removes the setup to schedule weekly creations of release branch
- Release branch is created automatically every mondyat at 1 pm
- Release branch is created on demand

chore: unschedule creation of release branch

---

package-lock.json
packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lwc/package.json

- Updates the version of the lighting-language-server dependencies to pick up: 
https://github.com/forcedotcom/lightning-language-server/pull/578
#4994 
- Language server crashes if main class can't be identified
- Language server doesn't crash if main class can't be identified

chore: bump lls version to 4.7.1

---

.github/workflows/e2e.yml

- Makes e2e run every night
@W-14242077@
- e2e would only run manually
- e2e run automatically every night

chore: schedule e2e tests to run nightly

---

.github/dependabot.yml

@W-14260306@
Modify dependabot.yml to allow only dep changes that affect package.json.
This change should prevent PRs from being created when the module being bump is transient dependency.

fix: only depbot changes to both pkg json and lock

---

contributing/publishing.md

Update publishing.md to clear up confusion about the commit name after generating changelog.

chore: update publishing doc

---

.github/dependabot.yml

Major version bumps for dependencies typically require more consideration before applying the change to our code base.
This PR disables dependabot ability to create major bump PRs
@W-14266199@

fix: disable dependabot major version prs

---

.github/workflows/apexE2E.yml
.github/workflows/coreE2E.yml
.github/workflows/e2e.yml
.github/workflows/lspE2E.yml

- Unschedules End to End Tests workflow and schedules the 3 workflows called from it (Apex, Core and LSP)
- Tests being skipped in scheduled runs
- Tests running nightly

chore: schedule e2e categories instead

---

packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lightning/syntaxes/html.tmLanguage.json

The html grammar in the Aura extension had a three part name that forced it to take precedence when looking at html associated files.  (text.html.basic).  This has been reported as an issue a couple of times for php which has an html grammar scope of (html.php). 
I altered the scope name to be simpler (aura.html) and now php html files are correctly parsed and visually marked up by the php grammar file. 
@W-10934996@
#5154
#1988
Aura html file still works properly
php files also works properly

fix: update aura html grammar scope

---

packages/salesforcedx-vscode-core/src/messages/i18n.ja.ts
packages/salesforcedx-vscode-core/src/messages/i18n.ts

CodeBuilder found a flow where we had a missing label.  I verified by altering the local code to always print the label and found it was indeed missing from the core extension.  
@W-14284449@
#5156

fix: add missing label

---

.github/workflows/runE2ETest.yml

Update runE2ETest.yml to download Node 18 instead of Node 16 so that E2E tests can be run after the upgrade to Node 18.
@W-13209367@

chore: use node 18 for e2e test workflow

---

.github/workflows/createReleaseBranch.yml

- Reschedules the creation of the release branch
@W-14352369@
- We needed to manually trigger a new cut for the release branch every week
- A new release branch is created every Monday

chore: reschedule cut of release branch

---

.github/workflows/apexE2E.yml
.github/workflows/coreE2E.yml
.github/workflows/lspE2E.yml
.github/workflows/slackNotification.yml

Every time the Apex E2E, Core E2E or LSP E2E workflows are run, a notification with details about the outcome of each run is sent via slack
@W-14324982@
- no notifications after running e2e tests
- notifications after running e2e tests are sent to slack channel #e2e-tests-results

Slack notification for e2e test runs

---

.github/workflows/createReleaseBranch.yml
.github/workflows/unitTestsLinux.yml
.github/workflows/unitTestsWindows.yml
.github/workflows/validatePR.yml
packages/salesforcedx-vscode-soql/package.json

With the node18 upgrade we moved to npm workspaces which changed where dependencies  are located in the project.  For development they are pulled up to the root node_modules folder when shared across packaged, but still have to be in the package node_modules folder when running as a VSIX. 
I missed this update for ensuring we get the SOQL LSP from the right location in vsix. 
GHA updates: 
The node LST version changed from 18->20 on 10/24/2023.  
Updated our GHA that were using lts/* to use the nvm file for getting the node version
Update the created release branch GHA to pin the npm and lerna version to the same version as in the repo. 
@W-13209367@
SOQL LSP fails to start when on used via vsix. 
SOQL LSP behaves normally when used both in dev and vsix. 
GHA use node 18
create release …

chore: fix soql LSP location for vsix and fix GHA for node 18

---

package-lock.json
packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lwc/package.json

- Updates the version of the lighting-language-server dependencies to pick up: 
https://github.com/forcedotcom/lightning-language-server/pull/583
#5069, @W-14391061@ 
- Language server crashes if a class has a property with only a setter.
- Language server doesn't crash if a class has a property with only a setter.

chore: bump lls to 4.7.2

---

.github/workflows/e2e.yml

- Uses the right run id of the Nightly Build Develop workflow run
@W-14182445@
- e2e.yml is triggered only after Nightly Build Develop runs
- e2e.yml has the run number instead of the run id of Nightly Build Develop
- e2e.yml would run after when Nightly Build Develop status was `requested`, `in_progress` and `completed`
- e2e.yml has the right run id of the triggering workflow (`Nightly Build Develop` and `Test, Build, and Release`)
- e2e.yml runs only when triggering workflow status is `completed`
- e2e.yml is triggered after triggering workflow runs

chore: get right id from workflow_run

---

packages/salesforcedx-vscode-apex/.gitignore
packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-soql/.gitignore
packages/salesforcedx-vscode-soql/package.json

Update how the apex and soql extension pull in the apex & soql grammar file so that it works locally & in vsix.  Note this is a fallout change from moving to npm workspaces. 
Related to @W-14413832@
Local debug runs couldn't find the apex or soql grammar files. 
grammar files are found for both vsix and local development.

chore:  grammar local fix

---

packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-apex/package.nls.json

This PR allows users to change the trace level of Apex LS in VS Code Settings UI.
@W-14363691@
The trace level is set off by default. It is not available for users to change it in VS Code Settings UI.
Users can change the trace level of Apex LS in VS Code Settings UI.

feat: add vscode setting for Apex LS trace level

---

packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-expanded/package.json
packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lwc/package.json
packages/salesforcedx-vscode-soql/package.json

Update the extensions to have extDeps when not already present. 
core <- apex, lwc, lighting, soql
apex <- apex-debugger, apex-replay-debugger
One concern is this makes uninstalling individual extensions have an order. You can not uninstall an ext until all ext with deps have been uninstalled.   Not an issue when using extension packs. 
@W-14418821@
four extension attempted to activate at the same time
core activates first, then apex, lwc, lightning, and soql, then the debugger after apex.
Tested vsix files on windows to verify all extensions load

feat: add ext deps to enable faster activation

---

packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-core/package.nls.ja.json
packages/salesforcedx-vscode-core/package.nls.json
packages/salesforcedx-vscode-core/src/constants.ts
packages/salesforcedx-vscode-core/src/index.ts
packages/salesforcedx-vscode-core/src/settings/sfdxCoreSettings.ts
packages/salesforcedx-vscode-core/src/util/cliConfiguration.ts
packages/salesforcedx-vscode-core/src/util/index.ts

- Adds new core setting for the NODE_EXTRA_CA_CERTS environment value
@W-11384659@
- NODE_EXTRA_CA_CERTS has no effect in deploy/retrieve operations
- new setting for NODE_EXTRA_CA_CERTS so it has effect in deploy/retrieve operations

chore: new setting for NODE_EXTRA_CA_CERTS environment value

---

.github/workflows/runE2ETest.yml
.github/workflows/vscodeSupportE2E.yml
packages/salesforcedx-apex-debugger/test/integration/adapter.test.ts
packages/salesforcedx-apex-replay-debugger/test/integration/adapter.test.ts

- Adds a new nightly GHA that will run just the initial E2E test suite (verifying extension start) against the desired version of vscode
@W-14366453@
- E2E anInitialSuite.e2e.ts Test run after Nightly build develop runs.
- E2E anInitialSuite.e2e.ts Test run against oldest vscode version we support (by default same as engines property in the source code) or any other we provide
- E2E anInitialSuite.e2e.ts Test is the default test we run but any other suite e.g deployAndRetrieve.e2e.ts can be run as well

Cristi/w 14366453/e2e in old vscode

---

packages/salesforcedx-apex-replay-debugger/fix-these-rules.json
packages/salesforcedx-apex-replay-debugger/test/integration/adapter.test.ts
packages/salesforcedx-apex-replay-debugger/test/unit/adapter/heapDumpTestUtil.ts
packages/salesforcedx-apex-replay-debugger/test/unit/commands/apexExecutionOverlayResultCommand.test.ts

@W-14564471@
refactor apex replay debugger to use arrow functions where applicable

chore: replay debugger to arrow functions

---

packages/salesforcedx-utils-vscode/src/date/format.ts
packages/salesforcedx-utils-vscode/test/jest/date/format.test.ts
packages/salesforcedx-vscode-apex/src/commands/forceAnonApexExecute.ts

@ W-13682486@
fix logfile name formatting error introduced by #5277
Ensures the directory to the logfiles is present before saving the log file when log file directories are not present issue [#178](https://github.com/forcedotcom/easywriter/issues/178)

fix: correct log file name formatting error

---

packages/salesforcedx-vscode-core/package.json

- Fixes org delete commands that were still in old sfdx style
- org delete commands show up outside of a sf project
- org delete commands show up only inside of a sf project

chore: wrong commands in package.json

---

packages/salesforcedx-vscode-core/package.json

- Sets SF_LOG_LEVEL to default in 'fatal'

fix: default SF_LOG_LEVEL to fatal

---

config/base-eslintrc.json
packages/salesforcedx-utils-vscode/src/helpers/utils.ts
packages/salesforcedx-utils-vscode/src/telemetry/index.ts
packages/salesforcedx-utils-vscode/test/jest/helpers/utils.test.ts
packages/salesforcedx-vscode-apex/src/commands/forceLaunchApexReplayDebuggerWithCurrentFile.ts

Corrects a bug when starting the apex replay debugger from an apex class file "Apex: Launch Apex Replay Debugger With Current File"
@W-12508503@
When launching Apex replay debugger with an Apex class the command would fail with a file system error stating the class name did not exist.
The launch of Apex replay debugger is now using the full path to the current Apex class, rather than the name

fix: fix entry not found when launching apex replay debugger from apex class 

---

packages/salesforcedx-vscode-apex/package.json

@W-14840136@
Exclude @salesforce/source-tracking from being bundled with apex extension.
When included in the bundle, Apex extension activation fails.

fix: exclude source-tracking from apex ext bundle

---

packages/salesforcedx-vscode-core/src/index.ts

Comment out call to `verifyCliInstallationAndVersion()` in `packages/salesforcedx-vscode-core/src/index.ts` to temporarily disable the Verify CLI Version on Startup feature.

revert: comment out Verify CLI Version feature

---

packages/salesforcedx-vscode-apex/src/messages/i18n.ts
packages/salesforcedx-vscode-apex/src/requirements.ts
packages/salesforcedx-vscode-apex/test/jest/languageUtils/requirements.test.ts
packages/salesforcedx-vscode-core/src/commands/forceSourceDeploySourcePath.ts

Modified the check to include java option `XshowSettings:properties`
@W-14888195@ #5358 
The validation of java version used a string match for `build 17.` and the customer's java version reported `build 17+` causing a false positive when check version during startup
The validation function has been changed to run the java version command with an option that displays all of the assign System properties the JVM will be using. One of the is `java.version = nn[.nn[.nn]]`. This representation is more reliable that using the `build` string from the java version command.

fix: check java version was criteria was ambiguous

---

package-lock.json
packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lwc/package.json

Updates the version of the lighting-language-server dependencies to pick up changes from https://github.com/forcedotcom/lightning-language-server/pull/586 to disable the generation of `jsconfig.json` file on core if there is an existing `tsconfig.json`.
@W-14943725@
- conflict between `tsconfig.json` and `jsconfig.json` file that is automatically generated.
- the generation of `jsconfig.json` file on core is disabled if there is an existing `tsconfig.json`.

fix: bump lls

---

.github/workflows/runE2ETest.yml

Downgrades the VSCode version used for our E2E tests from 1.86.0 to 1.85.2
@W-14972243@
Our E2E tests started failing with this error sometime between the hours of 1AM and 9AM on 2/1/2024, between the [original run of the E2E tests workflow and its rerun](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/7737166196): `ERROR @wdio/cli:utils: A service failed in the 'onPrepare' hook SevereServiceError: Couldn't set up Chromedriver Response code 404 (Not Found)`.  After digging into this error message, we found that the time the E2E test failures started happening was the same as when the `latest` version of VSCode changed from 1.85.2 to 1.86.0, which changed the Chromedriver version used from [114.0.5735.289](https://raw.githubusercontent.com/microsoft/vscode/1.85.2/cgmanifest. …

chore: downgrade VSCode to 1.85.2 for E2E tests

---

.github/workflows/runE2ETest.yml

Adds a comment in runE2ETest.yml explaining why we are using VSCode 1.85.2 instead of the latest VSCode version for our E2E tests
@W-14972243@

chore: add comment for why we are using VSCode 1.85.2 for E2E tests

---

packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-core/package.nls.ja.json
packages/salesforcedx-vscode-core/package.nls.json
packages/salesforcedx-vscode-core/src/commands/auth/orgLoginAccessToken.ts
packages/salesforcedx-vscode-core/src/commands/index.ts
packages/salesforcedx-vscode-core/src/commands/projectGenerateManifest.ts
packages/salesforcedx-vscode-core/src/commands/renameLightningComponent.ts
packages/salesforcedx-vscode-core/src/index.ts
packages/salesforcedx-vscode-core/src/messages/i18n.ja.ts
packages/salesforcedx-vscode-core/src/messages/i18n.ts
packages/salesforcedx-vscode-core/src/orgPicker/orgList.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/auth/orgLoginAccessToken.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/projectGenerateManifest.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/renameLightningComponent.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/orgPicker/orgList.test.ts

- Transitions "SFDX: Authorize an Org using Session ID" & "SFDX: Generate Manifest File" & "SFDX: Rename Component" commands to SF
@W-14720800@

fix: sfdx to sf for auth access token, generate manifest and rename lwc component

---

docs/_articles/en/apex/interactive-debugger.md
docs/_articles/en/deploy-changes/metadata-operations.md
docs/_articles/en/localdev/set-up-lwc-local-dev.md
docs/_articles/en/sf-dev-env/byotemplate.md
docs/_articles/en/source-control/source-format.md

Updates all CLI (terminal) examples in the docs from "sfdx" to "sf".  I obviously left all VScode command pallet references as-is. 
@W-15052113@

fix: update "sfdx" examples in docs to their "sf" equivalents

---

.github/workflows/baseSuiteE2E.yml

In the Base E2E Test Suite, wire the LWC LSP checkbox correctly to the LWC LSP E2E test instead of to Templates.

chore: fix incorrectly wired checkbox in BaseSuiteE2E.yml

---

packages/salesforcedx-vscode-apex/src/index.ts

@W-15122337@ #5467 
Updates apex lsp to account for anon apex command rename in extensions

fix: bump apex lsp to include command rename

---

.github/workflows/baseSuiteE2E.yml

- fixes base e2e workflow to successfully get vsixes with run id when triggered with workflow run
- run id was only passed when workflow was manually started and received input for run id
- run id is passed by user input or by workflow run

chore: fix base e2e workflow to successfully get vsixes when triggered with workflow run

---

.github/workflows/baseSuiteE2E.yml

Fixes an issue where AnInitialSuite cannot be cloned in the Base E2E Suite because of an incorrect input of automationBranch

chore: fix automation branch input for AnInitialSuite in Base E2E Suite

---

.github/workflows/baseSuiteE2E.yml

Show the correct values for **VSCode version** and **E2E branch** inputs in Slack notifications for scheduled runs of Base E2E suite that are triggered by other workflows, instead of a blank value.
Blank value was being shown because the default VSCode version and E2E branch were being used, and default values were treated as blank instead of their actual value when displayed in human-readable format.

chore: show correct input values in Slack notifications for scheduled runs of Base E2E Suite

---

docs/_articles/ja/codebuilder/about.md
docs/_articles/ja/codebuilder/cb-diffs.md
docs/_articles/ja/codebuilder/cb-remove.md
docs/_articles/ja/codebuilder/cb-setup.md
docs/_articles/ja/codebuilder/cb-start.md
docs/_articles/ja/codebuilder/cb-tips.md

The Code Builder ja docs folder has old versions of the en files that refer to Beta. This PR updates ja folder to have the latest en files, which no longer refer to Beta. I'll separately follow up to see how to get the ja files localized.
@W-15256202@

docs: sync ja docs with latest en versions

---

packages/salesforcedx-utils-vscode/src/helpers/utils.ts
packages/salesforcedx-utils-vscode/test/jest/helpers/utils.test.ts

The vsce has been using `realpathSync.native(filePath)` to get the canonical pathname of a given path. So for customers that are using sfdx project with a symbolic link, it fails to run deploy or retrieve commands with error: “Error deploying or retrieving source: The file or directory that you tried to deploy or retrieve isn’t in a package directory that’s specified in your sfdx-project.json file. Add this location to your “packageDirectories” value, or deploy or retrieve a different file or directory. For details about sfdx-project.json, see: https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_ws_config.htm"
The reason why it uses `realpathSync.native(filePath)`  is that there was a [previous issue …

fix: support folder with symbol link

---

package-lock.json
packages/salesforcedx-sobjects-faux-generator/package.json
packages/salesforcedx-utils-vscode/package.json
packages/salesforcedx-vscode-apex-debugger/package.json
packages/salesforcedx-vscode-apex-replay-debugger/package.json
packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lwc/package.json
packages/salesforcedx-vscode-soql/package.json

Fixes bug introduced in apex-node that did not properly manage dangling commas in apex test results
@W-15471840@
#5534 
See issue
Enabling code coverage highlighting functions properly.

fix: bump apex-node apply json dangling comma bug

---

package-lock.json
packages/salesforcedx-vscode-apex-replay-debugger/package.json
packages/salesforcedx-vscode-apex/package.json

pick up latest v4 version of apex-node to correct test result parsing error when no code coverage is in test results.
#5534 , @W-15530915@
When using the highlight code coverage feature and running apex tests without code coverage, extensions were displaying an message stating coverage results parsing failed. This is due to a bug introduced in apex-node streaming changes in v60.8.0.
The fix to apex-node corrected the JSON results used for highlighting code coverage, when there is not code coverage present, no produces the correct warning that no code coverage is present in the latest test run for the apex class opened in the editor.

fix: bump apex-node for dangling comma fix

---

packages/salesforcedx-utils-vscode/src/helpers/activationTracker.ts
packages/salesforcedx-utils-vscode/test/jest/helpers/activationTrackerClass.test.ts

@W-15328509@
Prevent negative extension activation time from being included in telemetry data
Modified the calculations and logic that sends the extended activation data to telemetry to:
- Only calculate activation time when load start date is present and activate end date >= load start date
- Only send extended activation data if activation time > -1

fix: prevent negative extension activations times

---

.github/workflows/runE2ETest.yml

- Use macos-12 instead of macos-latest so E2E pass on mac

chore: test e2e continue working on macos 12

---

.github/ISSUE_TEMPLATE/Bug_report.md

Changes the bug report template in Github issues to ask for Salesforce CLI version instead of SFDX CLI version.

chore: update bug report issue template to ask for Salesforce CLI instead of SFDX CLI

---

.github/ISSUE_TEMPLATE/Bug_report.md

Ask customers in bug report Github issues template for most recent version of the extensions where the functionality was working.

chore: ask in bug report issues template whether the issue is a regression

---

.github/workflows/closeStaleIssues.yml

1. Update closeStaleIssues.yml to add stale label after 3 days and close issues as not planned after 2 more days
2. Upgrade closeStaleIssues.yml to run the latest version `actions/stale@v9` and use Node 20

chore: update closeStaleIssues.yml to add stale label after 3 days and close issues as not planned after 2 more days

---

.github/workflows/publishOpenVSX.yml
.github/workflows/publishVSCode.yml

Will revert - Hard-code the values of the access tokens in the Publish in Microsoft Marketplace and Publish in Open VSX Registry GHA workflows to dummy values, in order to test a failed publish run in the real environment.

will revert: use dummy tokens for Publish Microsoft Marketplace and Publish OpenVSX Registry workflows to test

---

.github/workflows/publishOpenVSX.yml
.github/workflows/publishVSCode.yml

This reverts commit 5735f63769d24c065518f99be7f985c5b422e3c5.

Revert "chore: dummy tokens for Publish Microsoft Marketplace and Publish OpenVSX Registry workflows to test (#5568)"

---

.github/workflows/publishOpenVSX.yml
.github/workflows/publishVSCode.yml

Adds the `--skip-duplicate` flag to the commands in the **Publish to Microsoft Marketplace** and **Publish to Open VSX Registry** workflows so that they fail silently if the version being published already exists.
This is needed to handle the case where the Publish workflow fails halfway through, with some extensions published and some not published.  The extensions are always published in the same order, so we want to be able to publish the remaining extensions during a rerun and not be blocked by fail-fast.
@W-15437641@

chore: add --skip-duplicate flag in Publish workflows to fail silently if version already exists

---

docs/_articles/en/codebuilder/cb-setup.md
docs/_articles/en/codebuilder/cb-start.md

Surface more prominently the known issue that Code Builder won't work if the org has trusted IP ranges 
#@W-15808576@
Known issue mentioned in [Known Gaps and Issues doc](https://github.com/forcedotcom/code-builder-feedback/wiki/Known-Gaps-and-Issues#ip-restricted-orgs) on GitHub.
Known issue also mentioned prominently in doc where user is likely to encounter this issue (setup and connect to org topics)

docs: more prominent notes for known issue with trusted IP ranges

---

.github/workflows/approveAndPublishBeta.yml
.github/workflows/createAndTestBetaReleaseBranch.yml
.github/workflows/e2e.yml
.github/workflows/publishBeta.yml
.github/workflows/publishBetaRelease.yml
package-lock.json
packages/salesforcedx-vscode-apex-debugger/package.json
packages/salesforcedx-vscode-apex-replay-debugger/package.json
packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lwc/package.json
packages/salesforcedx-vscode-soql/package.json
scripts/create-release-branch.js

Implement the workflow to publish beta release for core-bundle. 
The workflow first changes the codebase from the core reference to the core-bundle reference, cuts the release branch from main, and then runs buildAndTest workflow.
If build is successful and unit tests pass, it will trigger the e2e tests against the build.
Then a reviewer is required to publish the beta release to Github, after the reviewer checks the test results and potential smoke testing.
The beta release will be available only in Github release.
Also fixes a typo in e2e test.
@W-15635226@
No such a workflow.
One can trigger the beta release workflow from GHA.

Chore: implement the workflow to publish beta release for core-bundle

---

package-lock.json
packages/salesforcedx-sobjects-faux-generator/package.json
packages/salesforcedx-utils-vscode/package.json
packages/salesforcedx-vscode-apex-debugger/package.json
packages/salesforcedx-vscode-apex-replay-debugger/package.json
packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lwc/package.json
packages/salesforcedx-vscode-soql/package.json

Pulls in fixes in the @salesforce/apex-node dependency for:
1. All Apex classes/triggers in the ApexCodeCoverageAggregate table are displayed when the "Show Only Aggregated Code Coverage" setting is checked
2. Add heap monitoring
@W-15783639@, @W-15760648@

fix: bump @salesforce/apex-node to v6.1.2

---

.github/workflows/runE2ETest.yml

Fixes the issue where screenshots were not being produced for E2E test failures.  The issue is happening as a result of the breaking change in actions/upload-artifact@v4.
@W-15960945@
Only one job in a failing E2E test run produces screenshots; the other jobs produce error messages in the upload artifact step with the error message `Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run`.
https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/9477771277
All jobs in a failing E2E test run produce screenshots, in separate folders for each job.
https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/9486595338

chore: update screenshots folder name to match actions/upload-artifact@v4

---

packages/salesforcedx-vscode-expanded/package.json

apex-pmd has different publishers in VS Code Marketplace and Open VSX Registry. Code Builder installs the extensions from Open VSX, so apex-pmd is not able to be installed in Code Builder. The entry for Open VSX is added. By adding the entry, installing from VS Code marketplace is not affected and no errors can be detected. There is also no error to install apex-pmd from Open VSX with the existence of the entry for Marketplace confirmed by CB team.
@W-15936982@
apex-pmd is not installed from Open VSX.
apex-pmd is installed from Open VSX

chore: point to the right apex-pmd in Open VSX

---

package-lock.json
packages/salesforcedx-vscode-apex-replay-debugger/package.json
packages/salesforcedx-vscode-apex/package.json

Downgrade the @salesforce/apex-node dependency to not include the heap monitoring change which was causing issues with bundling.
@W-15960945@
Apex extension does not activate and produces and error message.
Apex extension works as expected.
https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/9500842559

chore: downgrade @salesforce/apex-node to v6.0.1

---

.github/workflows/closeStaleIssues.yml

Update the **Close Stale Issues** GHA workflow to also close issues tagged with "missing required information"
**Close Stale Issues** only runs on issues tagged with "more information required"
**Close Stale Issues** runs on issues tagged with "more information required" and "missing required information"

chore: update closeStaleIssues.yml to close stale issues tagged with "missing required information"

---

package-lock.json
packages/salesforcedx-vscode-soql/package.json

This PR will update the dependencies `soql-builder-ui` and `soql-model` in the SOQL Builder extension. The new versions include a bug fix addressing issue https://github.com/forcedotcom/soql-tooling/issues/268 where users were unable to filter for NULL values if the SObject field type is a string. 
[The functional change in the soql-tooling repo is here](https://github.com/forcedotcom/soql-tooling/pull/285/files#diff-c349389e35d166cc7575fc1d35958ec6eb8ad43ae0fcf1ef24473cb3ff50bfe7R17)
Note: The soql-tooling repo had not been touched in 3 years, some of the changes address issues with development workflow such as linting and building. We also had some issue with out release automation in CI, so I ended up manually publishing to NPM with a fresh start at `v1.0.0` for `soql-model` and …

fix: allow user to filter by null strings in SOQL Builder

---

package.json

the previous shellscript is not able to link the modules in node_modules in root directory, and makes the link not effect.  this PR is to update the script to link all lsp modules to the local one.
@W-16085908@
cannot link
link all lsp modules under vsce to the local lsp project.

fix: link lsp with node_modules in root folder

---

.github/workflows/apexE2ENew.yml
.github/workflows/e2eNew.yml

Adds windows os to apexLsp and anInitialSuite
- apexLsp.e2e.ts and anInitialSuite.e2e.ts run agains windows os
Test runs: 
- [Apex End to End Tests - ESM](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/9814756714) ✅ 
- [E2E Test Suite - ESM](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/9814831064) ✅

chore: add windows os to apexlsp and aninitialsuite

---

.github/workflows/validateNewIssues.yml
.github/workflows/validateUpdatedIssues.yml

Issues tagged with "pending release" no longer unnecessarily go through the validation process.

ci: Github issues tagged with 'pending release' do not need to be validated

---

packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-lwc/package.json

- Adds condition to collapse all tests commands so they only show up within an open sf project
@W-16296381@
- `SFDX: Collapse All Apex Tests` and `SFDX: Lightning Web Components Collapse All Tests` only show up within an open sf project

chore: collapse all tests commands only show up within open project

---

package-lock.json
packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lwc/package.json

Bumps the version of @salesforce/lightning-lsp-common, @salesforce/aura-language-server, and @salesforce/lwc-language-server to include the changes in the LWC LSP for supporting lightning-record-picker
@W-14457297@

fix: bump lightning-language-server dependencies from v4.8.0 to v4.11.0

---

.github/workflows/validateUpdatedIssues.yml

Updates the message for `status: owned by another team` to say that issues owned by another team will be closed.

chore: message for status: owned by another team

---

package-lock.json
packages/salesforcedx-utils-vscode/package.json
packages/salesforcedx-utils-vscode/src/cli/commandOutput.ts
packages/salesforcedx-utils-vscode/src/commands/channelService.ts
packages/salesforcedx-utils-vscode/src/helpers/utils.ts
packages/salesforcedx-utils-vscode/test/jest/helpers/utils.test.ts
packages/salesforcedx-utils/src/cli/commandOutput.ts
packages/salesforcedx-utils/src/helpers/index.ts
packages/salesforcedx-utils/src/helpers/utils.ts
packages/salesforcedx-utils/test/jest/cli/commandOutput.test.ts

A number of CLI commands are returning ANSI color characters in JSON results. This change removes those characters prior to the JSON strings being parsed.
This change also include removal of the strip-ansi dependency and replaced with internal functions
@W-16375638@, #5695

fix: strip ansi color control chars from json

---

.github/actions/validate-issue/src/index.ts

Simplifies the versions validation for github issues
- prefix for cli version is now optional
- vscode version can include "Version: " as it's what people would copy and paste from "About Visual Studio Code"

chore: simplify versions validation in github issues

---

packages/salesforcedx-vscode-core/src/commands/sourceDiff.ts
packages/salesforcedx-vscode-core/src/messages/i18n.ja.ts
packages/salesforcedx-vscode-core/src/messages/i18n.ts

Gets rid of the Running SFDX: Diff File Against Org notification when the diff source fails.
@W-16006725@
- Running notification even when the command already failed
- Only failure notifications when it fails

fix: no infinite running command notification for diff file and folder commands

---

.github/workflows/validateNewIssues.yml
.github/workflows/validateUpdatedIssues.yml

Skips Github issue validation process for issues tagged with `announcement`
Announcements are tagged with `missing required information`
Announcements are not validated

fix: announcements do not go through Github issue validation process

---

packages/salesforcedx-vscode-core/package.json

Fixes an issue where the "SFDX: Generate Manifest File" command exists in Explorer view context menu for manifest files and can be used to generate a blank manifest file.
@W-16550710@
When you right click on a manifest file in Explorer view context menu, "SFDX: Generate Manifest File" is an option and can be used to generate a blank manifest file.
Video of issue: https://drive.google.com/file/d/10ovH5qZZ0g2g3cZRLptd2pCTpjeCB2xX/view?usp=sharing
When you right click on a manifest file in Explorer view context menu, "SFDX: Generate Manifest File" is not an option.

fix: "SFDX: Generate Manifest File" command should not exist for manifest files

---

.github/workflows/apexE2E.yml
.github/workflows/coreE2E.yml
.github/workflows/deployRetrieveE2E.yml
.github/workflows/e2e.yml
.github/workflows/lspE2E.yml
.github/workflows/lwcE2E.yml

- Sets VSCode version for e2e tests to 1.92.2 while we figure out why they're failing for stable (1.93)

chore: set vscode version to 1.92.2 for e2e tests

---

package-lock.json
packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lwc/package.json

Bumps the versions of @salesforce/lightning-lsp-common, @salesforce/aura-language-server, and @salesforce/lwc-language-server to remove TypeScript-related files from the `.forceignore` for JS-only projects. See https://github.com/forcedotcom/lightning-language-server/pull/601 for details.
@W-16625817@

fix(deps): bump to latest lightning-language-server @W-16625817@

---

packages/salesforcedx-utils-vscode/src/cli/parsers/projectDeployStartResultParser.ts
packages/salesforcedx-utils-vscode/src/cli/parsers/projectRetrieveStartResultParser.ts
packages/salesforcedx-vscode-core/src/diagnostics/diagnostics.ts
packages/salesforcedx-vscode-core/test/vscode-integration/diagnostics/index.test.ts

- Shows error message for push/pull when the error is not related to files
- no error message and command kept running forever
- Error message displayed and no infinite notification for running push/pull

fix: show error message for push/pull when the error does not involve files

---

.github/workflows/closeStaleIssues.yml

Close Stale Issues GHA workflow checks for issues tagged with `waiting for user`.
Issues tagged with `waiting for user` are not automatically closed.
Issues tagged with `waiting for user` are automatically closed after 5 days of inactivity.

chore: close stale issues workflow should include issues with 'waiting for user' tag

---

.github/workflows/runE2ETest.yml

Updates runE2ETest.yml to run E2E tests on macos-latest instead of macos-12.
Mac E2E tests run on macos-12.
Mac E2E tests run on macos-latest.
E2E test run: https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/11073776789 ✅

chore: use macos-latest in runE2ETest.yml

---

.github/workflows/deployRetrieveE2E.yml

- Skips mdDeployRetrieve e2e test if vscodeVersion is not 1.92.2

chore: skip mdDeployRetrieve if vscodeVersion is not 1.92.2

---

.github/workflows/deployRetrieveE2E.yml

- Skips mdDeployRetrieve e2e test on macos

chore: disable mddeployretrieve test on macos

---

package-lock.json
packages/salesforcedx-apex-debugger/package.json
packages/salesforcedx-apex-replay-debugger/package.json
packages/salesforcedx-sobjects-faux-generator/package.json
packages/salesforcedx-test-utils-vscode/package.json
packages/salesforcedx-utils-vscode/package.json
packages/salesforcedx-utils-vscode/test/jest/context/workspaceContextUtil.test.ts
packages/salesforcedx-utils/package.json
packages/salesforcedx-visualforce-language-server/package.json
packages/salesforcedx-visualforce-markup-language-server/package.json
packages/salesforcedx-vscode-apex-debugger/package.json
packages/salesforcedx-vscode-apex-replay-debugger/package.json
packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-expanded/package.json
packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lwc/package.json
packages/salesforcedx-vscode-soql/package.json
packages/salesforcedx-vscode-visualforce/package.json
packages/salesforcedx-vscode/package.json
packages/system-tests/package.json

- Bump major version to 62.0.0
- Bump bundle dependencies for
- @salesforce/core-bundle
-   @salesforce/source-deploy-retrieve-bundle
-   @salesforce/source-tracking-bundle
-   @salesforce/templates-bundle
-   @salesforce/apex-node-bundle
@W-16901209@

feat!: bump major version and bundle deps

---

.github/workflows/coreE2E.yml
.github/workflows/coreE2EredHat.yml
.github/workflows/e2e.yml
.github/workflows/runE2ETest.yml

- Adds new workflow for coreE2E in order to be able to run e2e tests from redhat repo
- Adds redhat tests so they run as part of nightlies
- Modifies runE2ETest.yml to pass the repo as a param
@W-16838814@

chore: first e2e tests in redhat repo

---

packages/salesforcedx-vscode-apex/src/index.ts

Move resolveAnyFoundOrphanLanguageServers outside of client setup Run resolveAnyFoundOrphanLanguageServers in separate tick on main loop
@W-16953996@
Code to locate and resolve orphaned apex language servers was run inside the language client setup, with potential downside of impeding performance.
Code to locate and resolve orphaned apex language servers now runs as the last element of the apex extension activate function. It is also run with a setImmediate so it will run on the next iteration of the main loop.

fix: move resolve orphan apex lang server

---

packages/salesforcedx-vscode-apex/src/languageServer.ts

Adds an additional file watcher that will trigger when an entire folder is deleted.
Depends on a new language server to be included in this PR (see LSP repo for details).
@W-16207484@

fix: add file watcher for folder deletes

---

package-lock.json
package.json
packages/salesforcedx-vscode-apex-debugger/esbuild.config.js
packages/salesforcedx-vscode-apex-replay-debugger/esbuild.config.js
packages/salesforcedx-vscode-apex/esbuild.config.js
packages/salesforcedx-vscode-core/esbuild.config.js
packages/salesforcedx-vscode-core/tsconfig.json
packages/salesforcedx-vscode-lightning/esbuild.config.js
packages/salesforcedx-vscode-lwc/esbuild.config.js
packages/salesforcedx-vscode-lwc/package.json
packages/salesforcedx-vscode-soql/esbuild.config.js
scripts/capture-esbuild-warnings.js

1. externalizes `jest-editor-support` in bundle of lwc because part of its artifacts cannot be bundled. 
2. disallows dynamic imports in codebase
3. detects errors such as unaware unbundleable dependencies during bundling in each commit.
@W-16304508@
Lack of bundling checks, so new changes might break bundling process with no awareness.
More bundling checks in CI.

ci: checks for bundling

---

packages/salesforcedx-utils-vscode/src/services/telemetry.ts
packages/salesforcedx-utils-vscode/test/jest/telemetry/telemetry.test.ts

This PR updates the configuration used to check if telemetry is enable from `enableTelemetry `  -> `telemetryLevel `
[@W-16742651@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000021EuMgYAK/view)
Disabling telemetry was still sending telemetry in vscode.
Disabling telemetry prevent telemetry from being sent in vscode.

fix: use correct telemetry enable setting

---

packages/salesforcedx-vscode-core/esbuild.config.js
packages/salesforcedx-vscode-core/package.json

excluding schema from bundling to avoid warning
This excludes the schema module from bundling so the path is accessible when referencing it from sfdx-project.json.
[@W-16771336@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000021ThG5YAK/view)
Users of extensions were seeing warning `Unable to load schema from '/Users/<user>/.vscode/extensions/salesforce.salesforcedx-vscode-core-61.12.0/node_modules/@salesforce/schemas/project-scratch-def.schema.json` when they open sfdx-project.json
The warning goes away.

fix: excluding schema from bundling to avoid warning

---

.gitignore
package-lock.json
packages/salesforcedx-utils-vscode/package.json
packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-apex/src/commands/apexActionController.ts
packages/salesforcedx-vscode-apex/src/commands/metadataOrchestrator.ts
packages/salesforcedx-vscode-core/package.json

Modifies vscode apex extension to use new LLM endpoint exposed by service-provider
@W-17482303@

feat: use new llm service

---

packages/salesforcedx-vscode-core/package.json

- Makes the constraints in package.json stricter so that `SFDX: Delete This from Project and Org`, `SFDX: Deploy This Source to Org`, `SFDX: Diff File Against Org` and `SFDX: Retrieve This Source from Org` commands don't show up in the context menu for files that aren't meant to be deployed to the org.
@W-17568713@

fix: hide commands outside of forceapp main default

---

packages/salesforcedx-vscode-apex/src/settings.ts
packages/salesforcedx-vscode-apex/test/jest/settings.test.ts

feat: exclude auraenabled as valid annotation
removes auraenabled from valid apex action method annotations list.
[@W-17550288@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000027eEZ9YAM/view)
AuraEnabled was passing eligibility checks
AuraEnabled fails eligibility checks

feat: exclude auraenabled as valid annotation

---

.github/workflows/publishOpenVSX.yml
.github/workflows/publishVSCode.yml

- Remove the CTC open/close from publish to get around issue
- Reference PR from A4D: [chore: remove ctc from publish](https://github.com/forcedotcom/salesforcedx-vscode-einstein-gpt/pull/678#top)

chore: remove ctc from publish

---

packages/salesforcedx-vscode-apex/src/commands/apexActionController.ts
packages/salesforcedx-vscode-apex/src/commands/metadataOrchestrator.ts
packages/salesforcedx-vscode-apex/src/messages/i18n.ja.ts
packages/salesforcedx-vscode-apex/src/messages/i18n.ts
packages/salesforcedx-vscode-apex/src/openApiUtilities/schemas.ts

- Adjusts the element values needed for ESR metadata for 254/TDX 
@W-17571126@

feat: support ESR changes for 254

---

packages/salesforcedx-vscode-apex/src/commands/apexActionController.ts
packages/salesforcedx-vscode-apex/src/commands/metadataOrchestrator.ts
packages/salesforcedx-vscode-apex/src/messages/i18n.ja.ts
packages/salesforcedx-vscode-apex/src/messages/i18n.ts
packages/salesforcedx-vscode-apex/src/openApiUtilities/schemas.ts

- Adds Operations Tag to External Service Registration XML and operationId to yaml within schema tag
@W-17626169@
```
<?xml version="1.0" encoding="UTF-8"?>
<ExternalServiceRegistration xmlns="http://soap.sforce.com/2006/04/metadata">
<description>Property API for managing properties</description>
<label>PropertyAPI</label>
<schema>openapi: 3.0.0
info:
title: Property API
version: &apos;1.0.0&apos;
description: Property API for managing properties
paths:
/PropertyAPI/getPropertyById:
get:
summary: Get property by ID
operationId: getPropertyById
responses:
&apos;200&apos;:
description: Property found
content:
application/json:
schema:
$ref: &apos;#/components/schemas/Property&apos;
/PropertyAPI/createProperty:
post:
summary: Create property
operationId: createProperty
parameters:
- name: …
```

feat: add operations tag to esr xml and operationId to yaml

---

packages/salesforcedx-vscode-apex/src/messages/i18n.ja.ts
packages/salesforcedx-vscode-apex/src/messages/i18n.ts
packages/salesforcedx-vscode-apex/test/jest/commands/metadataOrchestrator.test.ts

chore: fix typo in apex_class_not_valid message

---

packages/salesforcedx-vscode/README.md

Update the Microsoft Marketplace page for the Salesforce Extension Pack so that it says the minimum supported VSCode version is 1.90.0.
@W-17705772@

docs: Update Microsoft Marketplace page for Salesforce Extension Pack

---

packages/salesforcedx-vscode-apex/src/commands/apexActionController.ts

When a new OpenAPI v3 specification is created:
- Calls the "mule-dx-api.open-api-project" command with the OAS document vscode URI if the command is available
- Sends an error to telemetry if the command is not available or the command cannot be executed
@W-17681341@

feat: call Mulesoft ACD extension with command "mule-dx-api.open-api-project" and OAS document vscode URI when new OAS doc created

---

.git2gus/config.json

Updates the `defaultBuild` for Git2Gus to `offcore.tooling.63`.
@W-17722121@

[W-17722121] chore: update git2gus default build for v63

---

packages/salesforcedx-vscode-apex/src/oas/documentProcessorPipeline/ruleset.spectral.ts
packages/salesforcedx-vscode-apex/test/jest/oas/documentProcessingPipeline/ruleset.spectral.test.ts

fix: updating ruleset to find parameter related issue if parameter is defined and tests
It prevents the false positives that were showing up when `parameters` value was not set.
[@ W-17712024@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000028mCCfYAM/view)
`parameters` related errors were showing up even though the property itself was not defined.
`parameters` related errors are not showing up even though the property itself was not defined.

fix: updating ruleset to find parameter related issue if parameter is defined and tests

---

README.md

Changes the unavailable image 
[![Dev Dependencies](https://david-dm.org/forcedotcom/salesforcedx-vscode/dev-status.svg)](contributing/dependencies.md)
to the available image at
[![Dev Dependencies](https://img.shields.io/librariesio/github/forcedotcom/salesforcedx-vscode)](contributing/dependencies.md)

fix(readme): change to img.shields.io because david-dm.org is down

---

packages/salesforcedx-vscode-apex/src/oas/documentProcessorPipeline/ruleset.spectral.ts
packages/salesforcedx-vscode-apex/test/jest/oas/documentProcessingPipeline/ruleset.spectral.test.ts

remove duplicate rule, default oas library already has rule with code: 'operation-operationId'
removes the duplicate rule
[@<Insert GUS WI>@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000029daGNYAY/view)
Two warning were being shown for same error.
One warning shown for missing operation id error.

fix: remove duplicate rule

---

packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-apex/package.nls.ja.json
packages/salesforcedx-vscode-apex/package.nls.json
packages/salesforcedx-vscode-apex/src/commands/apexActionController.ts
packages/salesforcedx-vscode-apex/src/commands/index.ts
packages/salesforcedx-vscode-apex/src/commands/oasDocumentChecker.ts
packages/salesforcedx-vscode-apex/src/commands/oasUtils.ts
packages/salesforcedx-vscode-apex/src/index.ts
packages/salesforcedx-vscode-apex/src/messages/i18n.ja.ts
packages/salesforcedx-vscode-apex/src/messages/i18n.ts
packages/salesforcedx-vscode-apex/src/oas/documentProcessorPipeline/methodValidationStep.ts
packages/salesforcedx-vscode-apex/src/oas/documentProcessorPipeline/oasProcessor.ts
packages/salesforcedx-vscode-apex/src/oas/documentProcessorPipeline/oasValidationStep.ts
packages/salesforcedx-vscode-apex/src/oas/documentProcessorPipeline/processorStep.ts

feat: add logic to rerun validations and show validations in correct file instead of virtual one.
Adds logic to be able to run validation after you make changes, and shows errors in generated files instead of virtual one.
[@W-17681394@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000028co4lYAA/view)
Users could not re-run validations and errors were shown in problems tab but on a virtual URI.
Users can re-run validations and errors are shown in problems tab on actual generated file.

feat: add logic to rerun validations and show validations in correct file instead of virtual one.

---

packages/salesforcedx-vscode-apex/src/commands/apexActionController.ts
packages/salesforcedx-vscode-apex/src/oas/generationStrategy/generationStrategy.ts
packages/salesforcedx-vscode-apex/src/oas/generationStrategy/methodByMethodStrategy.ts

This PR makes operationId and request path deterministic.
The request path will always be either UrlMapping + parameters in path (RestResource cls for tdx) or ClassName + parameters in path (for after tdx).
- required params are always ahead of optional params
The operationId will always be present and the same as the corresponding method name in the apex class
@W-17775794@
@W-17777277@
operationId and request path are generated by LLM, which might not make sense.
operationId and request path are deterministic by the rule above.

feat: determine operationId and request path

---

packages/salesforcedx-vscode-apex/src/settings.ts

@W-17775324@
Only Apex classes with the `with sharing` modifier are eligible for OAS generation.
Apex classes with the `without sharing` or `inherited sharing` modifiers are also eligible for OAS generation.  Apex classes with no sharing modifiers continue to be ineligible.

fix: make 'without sharing' and 'inherited sharing' eligible for OAS generation

---

package-lock.json
packages/salesforcedx-vscode-core/package.json

Bumps the @salesforce/templates dependency to v63.0.1.
@W-17722121@

[W-17722121] chore: bump @salesforce/templates to v63.0.1

---

.github/workflows/runE2ETest.yml

E2E screenshots filename now includes VSCode version of the job.
The nightly build and release E2E tests run on both the latest and minimum supported VSCode versions.  If the same test on the same OS fails for both VSCode versions, only one set of screenshots is produced, and the other job throws an error, because the filenames of the screenshot zip files are the same.  See this run: https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/13378208445
E2E screenshots filename now includes VSCode version of the job.  Both jobs can produce screenshots without errors.

chore: screenshots in E2E tests specify VSCode version in filename

---

.github/workflows/closeStaleIssues.yml
.github/workflows/validateNewIssues.yml
.github/workflows/validateUpdatedIssues.yml

Github issues validation checks for label `type:bug` rather than label `bug`

chore: skip Github issues validation for issues labeled with 'type:bug'

---

packages/salesforcedx-vscode-apex/src/constants.ts

The link to "Set Your Java Version" in error notification now points to the correct URL.
#6098, @W-17856593@

[W-17856593] fix: correct url for 'set your java version' link

---

packages/salesforcedx-vscode-apex/src/commands/oasUtils.ts

Replaces the placeholder id for Mulesoft extension with the real extension id `salesforce.mule-dx-agentforce-api-component`.
@W-17812942@

[W-17812942] fix: use correct id for mulesoft extension

---

packages/salesforcedx-vscode-apex/src/oas/documentProcessorPipeline/ruleset.spectral.ts
packages/salesforcedx-vscode-apex/test/jest/oas/documentProcessingPipeline/ruleset.spectral.test.ts

feat: disabling operation-tags rule
Disables operation-tags rule that was being inherited from spectral library.
[@W-17883790@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002AA4IWYA1/view)
"Operation must have non-empty \"tags\" array" warning were shown.
"Operation must have non-empty \"tags\" array" warning won't be shown.

feat: disabling operation-tags rule

---

packages/salesforcedx-vscode-apex/src/commands/apexActionController.ts

If the user regenerates the OAS doc for an Apex class and chooses to do a manual merge, the problems in the Problems tab will be for the newly generated OAS doc \<ApexClass\>_\<timestamp\>.yaml instead of the original OAS doc \<ApexClass\>.yaml.

fix: problems tab shows problems for newly generated OAS doc with timestamp in manual merge case

---

packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-apex/src/commands/apexActionController.ts
packages/salesforcedx-vscode-apex/src/index.ts
packages/salesforcedx-vscode-core/package.json

- Modifies condition for `SFDX: Validate OpenAPI Document (Beta)` command so it doesn't show up when with Mulesoft Extension is enabled
@W-18034479@
- `SFDX: Validate OpenAPI Document (Beta)` command shows up even with Mulesoft Extension enabled
- `SFDX: Validate OpenAPI Document (Beta)` command doesn't show up when Mulesoft Extension is enabled

fix: W-18034479 - hide validate oas command when mulesoft extension is installed

---

packages/salesforcedx-utils-vscode/test/jest/telemetry/reporters/determineReporters.test.ts

determineReporters.test.ts `should return AppInsights and LogStream reporters...` calls `determineReporters` which calls new on LogStream whose constructor uses fs.createWriteStream.  This results in a file being creates when the test is run.
adds mocks for fs.createWriteStream, based on the ones in LogStream.test.ts 
@W-18117993@
run determineReporters.test.ts `should return AppInsights and LogStream reporters...`, see a file created.
no file created

W-18117993 test: fix mock to avoid writes to the filesystem

---

SHA256.md

adding SHA256.md back from commit before it was removed. I got the file use:
```git checkout 3afafcdc81530083d98e562a5a2f9ddfd55a5b41 SHA256.md```
adds the SHA256 back. 
@W-18160073@
File was deleted in commit: https://github.com/forcedotcom/salesforcedx-vscode/commit/390ee4bb72b0db7fe4cf0b308f18a99006a08590 and was causing merge conflicts when trying to release: https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/14341754952/job/40210926277  
Adding the file back.

fix: W-18160073 - adding SHA256.md back from commit before it was removed

---

packages/salesforcedx-vscode-automation-tests/test/specs/apexLsp.e2e.ts

Notification modal is dead to me, cmd palette quick pick is my new best friend
Fixes the now broken E2E tests for the LSP restart since they no longer use the notification modal but instead use the quick pick bar from the command palette to decide if the artifacts will be cleaned out from the .sfdx folder or not. 
@W-18205398@

W-18205398 Fix: fallout from changing LSP restart function

---

package-lock.json
packages/salesforcedx-apex-replay-debugger/package.json

apex replay debugger error was caused by:
```
"[UriError]: Scheme is missing: {scheme: \"\", authority: \"\", path: \"/Users/madhur.shrivastava/salesforcedx-vscode-automation-tests-redhat/e2e-temp/TempProject-ApexReplayDebugger/.sfdx/tools/debug/logs/07LDP000018XY442AG.log\", query: \"\", fragment: \"\"}"
```
Related issue: https://github.com/eclipse-theia/theia/issues/5308
Restricts the vscode-uri version to <=1.0.6
@W-18257178@
Apex Replay Debugger from a log file was broken and would never stop at the break point in a file.
Apex Replay Debugger works when manually tested.

W-18257178 fix: apex replay debugger error

---

package-lock.json
packages/salesforcedx-vscode-core/package.json

Pulls in the change in https://github.com/forcedotcom/salesforcedx-templates/pull/662
@W-17652496@, @W-17275130@
`npm install` fails in a new Salesforce project
`npm install` works in a new Salesforce project

W-17652496 chore: bump @salesforce/templates to v63.0.4

---

package-lock.json
packages/salesforcedx-vscode-lwc/package.json

Upgrades the **jest-editor-support** dependency from v30.3.1 to v31.1.2 so that the LWC extension is able to activate.

chore: upgrade jest-editor-support dependency to latest version so LWC extension can activate

---

.github/workflows/apexE2E.yml
.github/workflows/coreE2E.yml
.github/workflows/deployRetrieveE2E.yml
.github/workflows/e2e.yml
.github/workflows/lspE2E.yml
.github/workflows/lwcE2E.yml
.github/workflows/runE2ETest.yml
.github/workflows/soqlE2E.yml

Updates vscodeVersion default value to latest instead of stable in e2e related workflows
@W-18483821@
Test run: [Core End to End Tests](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/14936408989) ✅

fix: W-18483821 - use latest instead of stable in e2e related workflows

---

packages/salesforcedx-vscode-lwc/src/commands/lightningLwcPreview.ts
packages/salesforcedx-vscode-lwc/src/testSupport/commands/lwcTestDebugAction.ts
packages/salesforcedx-vscode-lwc/src/testSupport/testRunner/testResultsWatcher.ts
packages/salesforcedx-vscode-lwc/src/testSupport/testRunner/testRunner.ts
packages/salesforcedx-vscode-lwc/src/testSupport/workspace/getLwcTestRunnerExecutable.ts

- Updates code to use vscode api instead of fs in lwc package
@W-18379540@
Test run: [LWC End to End Tests](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/14942482352) ✅

chore: W-18379540 - use vscode api instead of fs in lwc package

---

packages/salesforcedx-vscode-automation-tests/test/specs/apexReplayDebugger.e2e.ts

https://github.com/forcedotcom/salesforcedx-vscode-automation-tests-redhat/pull/56
Recently we changed the SFDX: Turn Off Apex Debug Log for Replay Debugger command to not run the CLI command. This caused some text that was previously shown in the Output Tab to no longer be printed. This PR removed the check for that text from the Apex Replay Debugger E2E test.
Passing E2E test run: https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/15021587317 ✅

fix: remove the check for text that no longer exists from Apex Replay Debugger E2E test

---

packages/salesforcedx-utils-vscode/src/telemetry/reporters/o11yReporter.ts

Add Common Properties to Exception Events in O11yReporter
Changes :
- Modified `sendExceptionEvent` method to include aggregated logging properties
- Added the following properties to exception events:
- System information (OS, platform version, memory, CPU)
- VS Code specific data (machine ID, session ID, version)
- User context (user ID, session ID)
- Internal properties (for internal hosts)
- Maintained existing organization properties (orgId, orgShape, devHubId) and telemetry tags
Why :
This change ensures consistent telemetry data across all event types. Previously, exception events only included organization-related properties, while regular telemetry events included a comprehensive set of properties. This inconsistency made it harder to correlate exceptions with system state and …

@W-18524127 chore: add common properties to exception events in O11yReporter

---

packages/salesforcedx-sobjects-faux-generator/src/generator/fauxClassGenerator.ts
packages/salesforcedx-sobjects-faux-generator/test/jest/generator/fauxClassGenerator.test.ts

Adds missing await
Test run: [Core End to End Tests](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/15122787289) ✅

chore: await reset output folder

---

eslint.config.mjs
package.json
scripts/installVSIXFromBranch.ts

This pull request introduces a new script for testing VSIX files, updates the ESLint configuration to include additional scripts, and adds a new npm script for testing VSIX installations. The most significant changes are grouped below for clarity.
* Added a new script `scripts/installVSIXFromBranch.ts` to automate the process of downloading, uninstalling, and installing Salesforce VSIX extensions for testing. The script identifies the latest successful GitHub workflow run for the current branch, downloads related VSIX files, and installs them in the specified IDE. It also handles cleanup of old extensions.
* Updated `eslint.config.mjs` to include the new script `scripts/installVSIXFromBranch.ts` and other related scripts in the linting configuration.
* Added a new npm script `test-vsix` …

chore: add script to install vsixes from last commit workflow from branch

---

.github/actions/validate-issue/src/index.ts

VS Code minor release number raised into 3 digits now (current latest version is _v1.**100**.2_).
Updated the `vscodeVersionRegex` to allow minor releases with 3 digits.
None.
- Validations are passing only for VS Cpde Versions having 2-digits in the minor release: _"v1.99.1"_
- Reporting issues with _"**VS Code Version:** v1.100.2"_ value would fail the validation check, and issue gets marked with the `label:missing required information` label (see [this job run results](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/15215888713/job/42801186936)).
Validation should pass for _"**VS Code Version:** v1.100.2"_ value.

fix: update vscodeVersionRegex to support minor releases with 3-digits (e.g. "v1.100.2")

---

packages/salesforcedx-vscode-apex/package.json

Add configuration to the apex extension so it will begin reporting telemetry to both o11y/splunk & appInsights 
@W-18726739@
Telemetry for Apex extension & Apex LSP only goes to appinsights
Telemetry for Apex extension & Apex LSP only goes to both appinsights & olly
- Downloaded vsix and verified that on install apex extension starts as usual and AI data is being reported.

@W-18726739 chore: add o11y reporting apex extension

---

packages/salesforcedx-utils-vscode/src/helpers/traceFlags.ts
packages/salesforcedx-vscode-core/src/commands/startApexDebugLogging.ts
packages/salesforcedx-vscode-core/src/commands/stopApexDebugLogging.ts
packages/salesforcedx-vscode-core/src/index.ts

there's some cleaner non-query ways to get a userId.  since traceflags requires a Connection, asking for a username to query for a userId is kinda silly...it's the one for the connection.
This will preclude managing other users' trace flags, but we don't we have that requirement.  TraceFlags class was built to do more than we need.

refactor: userId without query

---

package-lock.json
packages/salesforcedx-vscode-apex-replay-debugger/package.json
packages/salesforcedx-vscode-apex/package.json

This pull request updates the dependency version for `@salesforce/apex-node-bundle` in two package files to ensure compatibility with the latest features and fixes.
Dependency updates:
* [`packages/salesforcedx-vscode-apex-replay-debugger/package.json`](diffhunk://#diff-8e3011a2d03be5d9d45a26ed3196a4ce5ba9fc9ce4423de8d832d2943f8c7ec3L27-R27): Updated `@salesforce/apex-node-bundle` from version `^8.1.26` to `^8.2.0`.
* [`packages/salesforcedx-vscode-apex/package.json`](diffhunk://#diff-12a773ded187140236b6d2177f127cf2097bc2ae1f02a413cc096b58a58201dcL29-R29): Updated `@salesforce/apex-node-bundle` from version `^8.1.26` to `^8.2.0`.
@W-18885359@

fix: W-18885359 - allow retries upon connection timeouts when running apex tests

---

packages/salesforcedx-vscode-core/src/commands/projectGenerateManifest.ts
packages/salesforcedx-vscode-core/src/messages/i18n.ts

This pull request refactors and improves the `GenerateManifestExecutor` class and related functionality in the `projectGenerateManifest.ts` file. The changes enhance user input handling, simplify the code by removing unused methods, and add a new user-facing message for cancellation scenarios.
* Removed the `openUntitledDocument` method, as it is no longer needed. The logic now ensures that the manifest is either saved with a user-provided name or a default name.
* Updated the `responseText` property in the `GenerateManifestExecutor` class to be non-optional, simplifying its usage and ensuring it is always a string.
* Added a check to handle user cancellation (e.g., pressing Escape) when entering a filename. If the input is canceled, a warning message is displayed, and the process stops. …

fix: W-18939319 - manifest generation is cancelled when escaping

---

packages/salesforcedx-vscode-apex/src/commands/apexTestRunCodeAction.ts

fix a types bug that **probably** causes apex test diagnostics to not be applied to a file.  I don't know how to reproduce this or exactly what it should look like, but I know the code is wrong!
@W-18989201@

W-18989201 fix: file parsing bug

---

eslint.config.mjs
packages/salesforcedx-apex-debugger/src/adapter/apexDebug.ts
packages/salesforcedx-apex-debugger/src/context/isvContextUtil.ts
packages/salesforcedx-apex-debugger/test/unit/adapter/apexDebugVariablesHandling.test.ts
packages/salesforcedx-utils-vscode/src/cli/commandExecutor.ts
packages/salesforcedx-utils-vscode/src/services/telemetry.ts
packages/salesforcedx-utils/src/cli/cliCommandExecutor.ts
packages/salesforcedx-visualforce-language-server/src/languageModelCache.ts
packages/salesforcedx-vscode-visualforce/src/tagClosing.ts

enforce consisteny with how we do undefined comparisons.
a bit less code

refactor: simplify undefined checks

---

scripts/change-log-generator-utils.js

Changelogs automatically generated by the **generateChangelog.yml** GHA workflow contain the contents of the previous changelog underneath new content for the current release.
Changelogs automatically generated by the **generateChangelog.yml** GHA workflow contain only new content for the current release.

chore: update change-log-generator-utils.js so that new changelogs for each release do not include the content of the previous changelog

---

.github/workflows/dependabot-auto-merge.yml

Adds support for auto merging dependabot PRs if all checks (including e2e) pass.
@W-19047827@
Engineers had to manually merge in dependabot PRs
Dependabot workflow will try and merge any open dependabot PRs hourly (restricted it to business hours in case something goes wrong).

W-19047827: feat: adding auto-merge for dependabot PRs if checks pass

---

.github/workflows/cleanupDeletedScratchOrgs.yml

Every time a new scratch org is created from the svcideebot dev hub, a scratch org info entry is created in the svcideebot org.  Each E2E test run creates and deletes a scratch org, generating over 50 scratch org info entries.  In the past, we have been manually running a query to delete the scratch org infos from the org whenever we get the "storage limit exceeded" error, but this is becoming a much more frequent chore now that E2E runs on every commit.  Therefore, I created a new GHA workflow that automatically runs the query to do the cleanup for us once per day.
Here's a successful run of the workflow: https://github.com/daphne-sfdc/salesforcedx-vscode-cleanup-deleted-scratch-orgs/actions/runs/16427936296
@W-19101015@

[W-19101015] ci: delete scratch org infos for deleted orgs in svcideebot org automatically once per day to avoid storage limit exceeded error

---

package-lock.json
package.json
packages/salesforcedx-apex-replay-debugger/package.json
packages/salesforcedx-utils-vscode/package.json
packages/salesforcedx-utils-vscode/src/helpers/activationTracker.ts
packages/salesforcedx-utils-vscode/src/services/telemetry.ts
packages/salesforcedx-utils-vscode/src/types/index.ts
packages/salesforcedx-utils-vscode/test/jest/helpers/activationTrackerClass.test.ts
packages/salesforcedx-utils-vscode/test/jest/telemetry/telemetry.test.ts
packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-apex/test/jest/telemetry/mockTelemetryService.ts
packages/salesforcedx-vscode-core/package.json

Adds backwards compatibility to the changes we introduced for the telemetry service. 
@W-19136990@
Only had the new methods and nothin else
Now works if you pass in "hrtime(): [number, number]" OR "now(): number"

W-19136990: Backwards compatibility i.e. fixing telemetry service

---

package-lock.json
packages/salesforcedx-utils-vscode/src/messages/i18n.ts
packages/salesforcedx-vscode-apex-replay-debugger/src/messages/i18n.ts
packages/salesforcedx-vscode-automation-tests/package.json
packages/salesforcedx-vscode-automation-tests/test/specs/anInitialSuite.e2e.ts
packages/salesforcedx-vscode-automation-tests/test/specs/apexReplayDebugger.e2e.ts
packages/salesforcedx-vscode-automation-tests/test/specs/runApexTests.e2e.ts
packages/salesforcedx-vscode-automation-tests/test/specs/trailApexReplayDebugger.e2e.ts
packages/salesforcedx-vscode-core/src/commands/startApexDebugLogging.ts
packages/salesforcedx-vscode-core/src/commands/stopApexDebugLogging.ts
packages/salesforcedx-vscode-core/src/messages/i18n.ts
packages/salesforcedx-vscode-core/src/utils/channelUtils.ts

This pull request updates the messaging and logging behavior in the Apex Replay Debugger extension and its associated tests. The most significant changes include refining message keys, improving test assertions for command outputs, and enhancing logging functionality with additional telemetry and notifications.
* [`packages/salesforcedx-vscode-apex-replay-debugger/src/messages/i18n.ts`](diffhunk://#diff-df1010c2f1fd5c69f6839e120a387d5e7d671c4e4c9a4be369968265de74f881L29-R29): Changed the `long_command_end` message from "Ending" to "Ended" for consistency in command completion messages.
* [`packages/salesforcedx-vscode-automation-tests/test/specs/apexReplayDebugger.e2e.ts`](diffhunk://#diff-f32189fe95c6c0b0de8ffdf22c01a12a3506f444f9d7e66b5e01257368cf6d83L106-R106): Updated test assertions …

chore: W-19157078 - fix finish log for turn on apex debug log

---

packages/salesforcedx-vscode-automation-tests/test/specs/runApexTests.e2e.ts

Gets rid of the following error that was causing **runApexTests.e2e.ts** to fail:
``` 
✘ Run a test that fails and fix it (9715ms)
Error: element click intercepted: Element <div class="monaco-list-row" role="option" data-index="2" data-last-element="false" data-parity="even" aria-setsize="15" aria-posinset="3" id="list_id_9_2" aria-label="AccountService.cls-meta.xml" aria-level="1" draggable="false" style="top: 44px; height: 22px;">...</div> is not clickable at point (513, 84). Other element would receive the click: <input class="input" autocorrect="off" autocapitalize="off" spellcheck="false" type="text" wrap="off" aria-label="Type to narrow down results. - Open File" role="textbox" aria-haspopup="menu" aria-autocomplete="list" aria-describedby="quickInput_message" …
```

[W-19387779] ci: runApexTests.e2e.ts works on Mac again

---

packages/salesforcedx-vscode-apex-debugger/esbuild.config.mjs
packages/salesforcedx-vscode-apex-replay-debugger/esbuild.config.mjs
packages/salesforcedx-vscode-apex/esbuild.config.mjs
packages/salesforcedx-vscode-core/esbuild.config.mjs
packages/salesforcedx-vscode-lightning/esbuild.config.mjs
packages/salesforcedx-vscode-lwc/esbuild.config.mjs

This pull request updates the copyright year in the `esbuild.config.mjs` files across several packages from 2024 to 2025. No functional or code logic changes are included; this is a standard annual copyright update.

chore: update date in copyright header

---

packages/salesforcedx-vscode-core/src/commands/sourceDiff.ts

This pull request refactors the handling of the `selectedPath` property in the `handleCacheResults` function within `sourceDiff.ts`. The main goal is to simplify the logic for processing single and multiple file paths by normalizing `selectedPath` to always be an array, which improves code readability and maintainability.
Refactoring and code simplification:
* Normalized `selectedPath` to always be an array (`paths`), removing separate checks for string and array types, which streamlines the logic for both individual and multiple file diffs.
* Updated calls to `diffOneFile` and `diffMultipleFiles` to use the normalized `paths` variable, ensuring consistent handling of file paths regardless of the input type.

chore: fix for diff file

---

packages/salesforcedx-vscode-core/src/orgPicker/orgList.ts
packages/salesforcedx-vscode-core/test/jest/orgPicker/orgList.test.ts

This pull request improves how org selections are parsed and handled in the org picker logic, and adds comprehensive tests to ensure correct behavior for various selection formats, including cases with multiple aliases, dashes, and expired indicators.
* Enhanced the parsing logic in `OrgList` to accurately extract the username or alias from complex selection strings, including those with multiple dashes, comma-separated aliases, and expired indicators. (`orgList.ts`)
* Added a suite of tests for the `setDefaultOrg` method to verify correct command execution for SFDX commands, organization selections with various alias and username formats, and handling of expired org indicators. (`orgList.test.ts`)
* Included tests for edge cases such as selections with no alias, multiple aliases, complex …

fix: W-19459990 - org picker supports aliases with dashes

---

packages/salesforcedx-vscode-core/src/commands/templates/apexGenerateClass.ts
packages/salesforcedx-vscode-core/src/commands/templates/apexGenerateUnitTestClass.ts
packages/salesforcedx-vscode-core/src/util/types.ts
packages/salesforcedx-vscode-core/test/jest/commands/templates/apexGenerateClass.test.ts
packages/salesforcedx-vscode-core/test/jest/commands/templates/apexGenerateUnitTestClass.test.ts

Fixes an issue where when creating an apex class/apex unit test class would overwrite existing class in the same directory with the same name without any warning when invoked from the context menu. The same command would work as expected when invoked from the command palette.
When invoking the command from the right-click VSCode context menu, the `fsPath` property of the URI argument is being concatenated with the relative `classes` folder path to derive the path of the file to create. The `fsPath` itself is the full path of the file being created, hence the final concatenated path is built incorrectly. This path is then used by the `OverwriteComponentPrompt` post conditions checker to check if the file with the same name exists in the same path which causes the overwrite prompt to not …

fix(create apex class): Apex Class commands overwriting existing files with no warning

---

packages/salesforcedx-vscode-apex-debugger/README.md

Removes the "DO NOT INSTALL THIS EXTENSION DIRECTLY. Install the complete [Salesforce Extension Pack](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode) instead." disclaimer in the README for the Apex Interactive Debugger extension.
#6450

docs: remove incorrect disclaimer in Apex Interactive Debugger README

---

.git2gus/config.json

What does this PR do?
Updates the defaultBuild for Git2Gus to offcore.tooling.65.
What issues does this PR fix or reference?
[@W-19704215@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002M9aKZYAZ/view)

chore: update git2gus v65 - W-19704215

---

packages/salesforcedx-utils-vscode/src/context/workspaceContextUtil.ts
packages/salesforcedx-utils-vscode/src/helpers/traceFlags.ts
packages/salesforcedx-utils-vscode/src/index.ts
packages/salesforcedx-utils-vscode/src/messages/i18n.ts
packages/salesforcedx-utils-vscode/test/jest/context/workspaceContextUtil.test.ts
packages/salesforcedx-vscode-core/src/commands/auth/authParamsGatherer.ts
packages/salesforcedx-vscode-core/src/commands/auth/orgLoginWeb.ts
packages/salesforcedx-vscode-core/src/context/workspaceContext.ts
packages/salesforcedx-vscode-core/src/index.ts

mostly for CodeBuilder, workspaceContextUtils prompts the user to reauth when the token is expired.
- only happens for non-refreshable tokens
- presets the instanceurl/alias to avoid making the user do anything
secondary
- reduce some getConnection calls by refactoring the traceFlag stuff (becuase it's also part of ext activation)
- moves the orgLogin command very early in the ext activation
@W-19787780@

fix: prompt reauth for non-refreshable access tokens W-19787780
