forcedotcom/salesforcedx-vscode

.appveyor.yml
README.md
appveyor.yml

Enable AppVeyor for Windows builds

---

packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-visualforce/package.json
packages/salesforcedx-vscode/package.json

Updates the extensions' descriptions to match Salesforce product names.
@W-4198892@

Update descriptions for VS Code extensions

---

.appveyor.yml

This fixes AppVeyor to run all tests.

Fix AppVeyor to run all tests

---

packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-core/src/index.ts

Only show the commands when the sfdx-project.json file is present.
@W-4175532@

Use dynamic context for command activation

---

packages/salesforcedx-vscode-apex/src/languageServer.ts

@W-4199304@
Deletes old apex.db upon before launching the language server
Previously the DB used the full file path which caused some conflicts. This will ensure we start fresh with each launch

Delete old db before launching workspace

---

.vscode/launch.json
docs/developing.md
packages/salesforcedx-vscode-apex-debugger/README.md
packages/salesforcedx-vscode-apex-debugger/package.json
packages/salesforcedx-vscode-apex-debugger/package.nls.json
packages/salesforcedx-vscode-apex-debugger/src/adapter/apexDebug.ts
packages/salesforcedx-vscode-apex-debugger/src/core/sessionService.ts
packages/salesforcedx-vscode-apex-debugger/src/index.ts
packages/salesforcedx-vscode-apex-debugger/src/messages/i18n.ts
packages/salesforcedx-vscode-apex-debugger/src/messages/index.ts
packages/salesforcedx-vscode-apex-debugger/src/utils/commandOutput.ts
packages/salesforcedx-vscode-apex-debugger/test/integration/adapter.test.ts
packages/salesforcedx-vscode-apex-debugger/test/unit/adapter/apexDebug.test.ts
packages/salesforcedx-vscode-apex-debugger/test/unit/adapter/apexDebugForTest.ts
packages/salesforcedx-vscode-apex-debugger/test/unit/core/sessionService.test.ts
packages/salesforcedx-vscode-apex-debugger/tsconfig.json

Implements a debugger extension that can start and stop an Apex Debugger session from an SFDX workspace.

Start & stop Apex Debugger session

---

CHANGELOG.md
packages/salesforcedx-vscode-apex/README.md

Adds CHANGELOG.md file for extension pack (all extensions' change log entries will go here); adds entries for August 10 release (40.5.0).
@W-4216507@

Create CHANGELOG.md and add initial entries

---

packages/salesforcedx-vscode-apex-debugger/package.json
packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-visualforce/package.json

Also, remove dependencies from modules that do not need it.

Remove double dependencies in both devDependencies and dependencies

---

packages/salesforcedx-utils-vscode/package.json

Add coverage report to util module

---

packages/salesforcedx-vscode-apex-debugger/package.json
packages/salesforcedx-vscode-apex-debugger/src/adapter/apexDebug.ts
packages/salesforcedx-vscode-apex-debugger/src/constants.ts
packages/salesforcedx-vscode-apex-debugger/src/core/index.ts
packages/salesforcedx-vscode-apex-debugger/src/core/sessionService.ts
packages/salesforcedx-vscode-apex-debugger/src/core/streamingClient.ts
packages/salesforcedx-vscode-apex-debugger/src/core/streamingService.ts
packages/salesforcedx-vscode-apex-debugger/src/messages/i18n.ts
packages/salesforcedx-vscode-apex-debugger/src/utils/commandOutput.ts
packages/salesforcedx-vscode-apex-debugger/test/unit/adapter/apexDebug.test.ts
packages/salesforcedx-vscode-apex-debugger/test/unit/adapter/apexDebugForTest.ts
packages/salesforcedx-vscode-apex-debugger/test/unit/core/sessionService.test.ts
packages/salesforcedx-vscode-apex-debugger/test/unit/core/streamingClient.test.ts
packages/salesforcedx-vscode-apex-debugger/test/unit/core/streamingService.test.ts
packages/salesforcedx-vscode-apex-debugger/typings/modules/faye/index.d.ts

Connect to Streaming API Apex Debugger channels when starting a debugging session in VSCode. Disconnect from Streaming API Apex Debugger channels when terminating a debugging session in VSCode.
@W-4178571@

Connect & disconnect Streaming API

---

packages/salesforcedx-vscode-core/src/commands/forceApexClassCreate.ts

Fixes right click open - doing this in a separate PR so individual commands can be reverted out if needed.
@W-4197613@

Fix open file after right click create

---

packages/salesforcedx-vscode/CHANGELOG.md

Adds description of features to be released for August 24, 2017.

Update changelog with Changed and Added features

---

.appveyor.yml
.travis.yml
docs/tests.md
package.json
packages/salesforcedx-utils-vscode/package.json
packages/salesforcedx-vscode-apex/coverconfig.json
packages/salesforcedx-vscode-core/coverconfig.json
packages/salesforcedx-vscode-lightning/coverconfig.json
packages/salesforcedx-vscode-visualforce/coverconfig.json
packages/system-tests/package.json
packages/system-tests/src/index.ts
scripts/instrument-salesforcedx-vscode-extensions.js
scripts/remap-coverage.js

* Instruments the code prior to running the system tests 
* Runs the system tests with the instrumented code
* Remaps the coverage info to account for JS <-> TS.
W-4254205

Add code coverage from system tests

---

.vscode/launch.json
packages/salesforcedx-apex-debugger/src/adapter/apexDebug.ts
packages/salesforcedx-apex-debugger/src/breakpoints/lineBreakpoint.ts
packages/salesforcedx-apex-debugger/src/core/breakpointService.ts
packages/salesforcedx-apex-debugger/src/core/index.ts
packages/salesforcedx-apex-debugger/src/messages/i18n.ts
packages/salesforcedx-apex-debugger/test/integration/adapter.test.ts
packages/salesforcedx-apex-debugger/test/unit/adapter/apexDebug.test.ts
packages/salesforcedx-apex-debugger/test/unit/adapter/apexDebugForTest.ts
packages/salesforcedx-apex-debugger/test/unit/core/breakpointService.test.ts
packages/salesforcedx-apex-debugger/test/unit/core/streamingService.test.ts
packages/salesforcedx-vscode-apex-debugger/package.json
packages/salesforcedx-vscode-apex-debugger/src/index.ts
packages/salesforcedx-vscode-apex/src/constants.ts
packages/salesforcedx-vscode-apex/src/index.ts

Configure Apex Debugger line breakpoints by acquiring typerefs and valid lines from Apex Language Server and using Tooling API to operate with ApexDebuggerBreakpoint objects.
@W-4189777, W-4178585@

Configure line breakpoint

---

packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-core/package.nls.json
packages/salesforcedx-vscode-core/src/commands/forceLightningInterfaceCreate.ts
packages/salesforcedx-vscode-core/src/commands/index.ts
packages/salesforcedx-vscode-core/src/index.ts
packages/salesforcedx-vscode-core/src/messages/i18n.ts
packages/system-tests/scenarios/scaffolding.test.ts

Adds lightning interface command to the palette
@W-4197643@

Add lightning interface command

---

scripts/publish.js

Need to use parseInt before doing a comparison with <

Fix check version error

---

package.json
packages/salesforcedx-apex-debugger/package.json
packages/salesforcedx-utils-vscode/package.json
packages/salesforcedx-vscode-apex-debugger/package.json
packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-visualforce/package.json
packages/salesforcedx-vscode/package.json
packages/system-tests/package.json
scripts/publish.js
scripts/reformat-with-prettier.js

This is the corresponding entry in the develop branch that needs to be done to facilitate merger on Thursday. See #80.

Reformat with prettier after lerna publish (develop branch)

---

packages/salesforcedx-apex-debugger/package.json

Prune apex-debugger module similar to utils module.
@W-4264167@

Add prune command to debugger module

---

packages/salesforcedx-vscode/CHANGELOG.md

Updates the changelog with the new Lightning commands.

Update changelog with Added features

---

packages/salesforcedx-apex-debugger/package.json
packages/salesforcedx-apex-debugger/src/adapter/apexDebug.ts
packages/salesforcedx-apex-debugger/src/commands/baseCommand.ts
packages/salesforcedx-apex-debugger/src/commands/forceOrgDisplay.ts
packages/salesforcedx-apex-debugger/src/commands/index.ts
packages/salesforcedx-apex-debugger/src/commands/runCommand.ts
packages/salesforcedx-apex-debugger/src/core/index.ts
packages/salesforcedx-apex-debugger/src/core/streamingClient.ts
packages/salesforcedx-apex-debugger/src/core/streamingService.ts
packages/salesforcedx-apex-debugger/test/unit/adapter/apexDebug.test.ts
packages/salesforcedx-apex-debugger/test/unit/adapter/apexDebugForTest.ts
packages/salesforcedx-apex-debugger/test/unit/commands/forceOrgDisplay.test.ts
packages/salesforcedx-apex-debugger/test/unit/commands/runCommand.test.ts
packages/salesforcedx-apex-debugger/test/unit/core/streamingService.test.ts
packages/salesforcedx-utils-vscode/src/cli/commandOutput.ts

Allow Apex Debugger extension to run to next breakpoint or end of debugged request.
@W-4178600@

Debugger run command

---

.travis.yml
packages/system-tests/package.json

trigger build on new PR with electron dependency

Add electron dependency

---

packages/salesforcedx-apex-debugger/src/adapter/apexDebug.ts
packages/salesforcedx-apex-debugger/src/commands/baseCommand.ts
packages/salesforcedx-apex-debugger/src/commands/index.ts
packages/salesforcedx-apex-debugger/src/commands/stepCommands.ts
packages/salesforcedx-apex-debugger/test/unit/adapter/apexDebug.test.ts
packages/salesforcedx-apex-debugger/test/unit/adapter/apexDebugForTest.ts
packages/salesforcedx-apex-debugger/test/unit/commands/baseCommand.test.ts
packages/salesforcedx-apex-debugger/test/unit/commands/runCommand.test.ts
packages/salesforcedx-apex-debugger/test/unit/commands/stepCommands.test.ts

Add step in-out-over commands to debugger

---

packages/salesforcedx-apex-debugger/src/adapter/apexDebug.ts
packages/salesforcedx-apex-debugger/src/commands/index.ts
packages/salesforcedx-apex-debugger/src/commands/protocol.ts
packages/salesforcedx-apex-debugger/src/commands/stateCommand.ts
packages/salesforcedx-apex-debugger/src/core/breakpointService.ts
packages/salesforcedx-apex-debugger/src/core/streamingClient.ts
packages/salesforcedx-apex-debugger/src/core/streamingService.ts
packages/salesforcedx-apex-debugger/test/unit/adapter/apexDebug.test.ts
packages/salesforcedx-apex-debugger/test/unit/adapter/apexDebugForTest.ts
packages/salesforcedx-apex-debugger/test/unit/commands/stateCommand.test.ts
packages/salesforcedx-apex-debugger/test/unit/core/breakpointService.test.ts
packages/salesforcedx-apex-debugger/test/unit/core/streamingClient.test.ts
packages/salesforcedx-apex-debugger/test/unit/core/streamingService.test.ts

Show stacktrace of Apex Debugger stopped requests (up to 2).
@W-4178724@

Debugger stack trace

---

packages/salesforcedx-apex-debugger/package.json
packages/salesforcedx-apex-debugger/src/adapter/apexDebug.ts
packages/salesforcedx-apex-debugger/src/core/breakpointService.ts
packages/salesforcedx-apex-debugger/test/unit/adapter/apexDebug.test.ts
packages/salesforcedx-apex-debugger/test/unit/core/breakpointService.test.ts

Handle some Apex Debugger events that print to VS Code debug console.
@W-4179020, W-4179047@

Handle events Debug, SystemGack, ApexException, & a few more.

---

packages/salesforcedx-apex-debugger/src/adapter/apexDebug.ts
packages/salesforcedx-apex-debugger/test/unit/adapter/apexDebug.test.ts
packages/salesforcedx-apex-debugger/test/unit/adapter/apexDebugForTest.ts

Use one-based thread ID that is unique per debugger session.
@W-4297137@

Fix debugger thread ID

---

packages/salesforcedx-utils-vscode/src/cli/commandOutput.ts
packages/salesforcedx-vscode-apex-debugger/package.json
packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-core/package.nls.json
packages/salesforcedx-vscode-core/src/commands/forceDebuggerStop.ts
packages/salesforcedx-vscode-core/src/commands/index.ts
packages/salesforcedx-vscode-core/src/index.ts
packages/salesforcedx-vscode-core/test/commands/forceDebuggerStop.test.ts

Query for active apex debugger session and update its status to detach. 
@W-4288245@

Debugger stop cmd

---

packages/salesforcedx-apex-debugger/src/adapter/apexDebug.ts
packages/salesforcedx-apex-debugger/src/constants.ts
packages/salesforcedx-apex-debugger/src/messages/i18n.ts
packages/salesforcedx-apex-debugger/test/unit/adapter/apexDebug.test.ts
packages/salesforcedx-vscode-apex-debugger/src/index.ts

Log warning message to debug console if class/trigger file is changed.
@W-4255647@

Apex Debugger file change warning

---

packages/salesforcedx-vscode-core/src/commands/commands.ts

Changes glob pattern from listing all paths with keyword to paths with keyword as last fragment
@W-4271155@

Glob should list paths directly to folders with specified key word

---

packages/salesforcedx-vscode-core/package.json
packages/system-tests/scenarios/scaffolding.test.ts
packages/system-tests/src/areas/common.ts

Add when clause to alias:list and org:display
Commands show up with no sfdx project and error out if ran

Add when clause for alias list and org display commands

---

scripts/publish.js

Validates git tags and release version before publishing

Validate tag and release version before publishing

---

scripts/publish.js

Ensure publish script is run on release branch matching the env variable

Verify script is run on release branch

---

packages/salesforcedx-vscode/CHANGELOG.md

Updates the CHANGELOG.md for 40.12.0.

Nick/update changelog 40.12.0

---

packages/salesforcedx-sobjects-faux-generator/package.json
packages/salesforcedx-vscode-apex/package.json

Puts secondary level packages as top-level dependencies.
Moves real dependencies from `devDepedencies` section to `dependencies` section.
@W-4345609@

Fix packaging issue

---

packages/salesforcedx-vscode-core/src/messages/i18n.ts

This removes the extra "Press Enter to ..." showing in InputBoxOptions. This message comes for free with InputBoxOptions already which is why it came up twice.
@w-4285382@

Remove extra directions for input box

---

package.json

Add stream flag to all the test script commands
Fix travis timeouts due to lack of output by having lerna stream the output. Need to see if output is streamed in order with concurrency flag set to 1

Add stream flag to test scripts

---

.appveyor.yml
.vscode/launch.json
packages/salesforcedx-apex-debugger/package.json
packages/salesforcedx-apex-debugger/src/adapter/apexDebug.ts
packages/salesforcedx-apex-debugger/src/commands/baseCommand.ts
packages/salesforcedx-apex-debugger/src/commands/frameCommand.ts
packages/salesforcedx-apex-debugger/src/commands/index.ts
packages/salesforcedx-apex-debugger/src/commands/protocol.ts
packages/salesforcedx-apex-debugger/src/commands/referencesCommand.ts
packages/salesforcedx-apex-debugger/test/unit/adapter/apexDebug.test.ts
packages/salesforcedx-apex-debugger/test/unit/adapter/apexDebugForTest.ts
packages/salesforcedx-apex-debugger/test/unit/adapter/apexDebugVariablesHandling.test.ts
packages/salesforcedx-apex-debugger/test/unit/commands/baseCommand.test.ts
packages/salesforcedx-apex-debugger/test/unit/commands/frameCommand.test.ts
packages/salesforcedx-apex-debugger/test/unit/commands/referencesCommand.test.ts
packages/salesforcedx-utils-vscode/package.json
packages/salesforcedx-utils-vscode/src/test/testrunner.ts
packages/salesforcedx-vscode-apex-debugger/package.json
packages/salesforcedx-vscode-apex-debugger/package.nls.json

This PR adds variables support to the debugger. Supported variable types are objects, collections and map. Whatever is returned from the Apex debugger will be shown.
* Editing of variables (not supported)

Variables support for debugger

---

packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-core/package.nls.json
packages/salesforcedx-vscode-core/src/commands/forceApexExecute.ts
packages/salesforcedx-vscode-core/src/commands/index.ts
packages/salesforcedx-vscode-core/src/index.ts
packages/salesforcedx-vscode-core/src/messages/i18n.ts
packages/system-tests/scenarios/forceApexExecuteUi.test.ts

Add execute anonymous apex commands to the palette
#66

Added Anonymous Apex execution

---

packages/system-tests/package.json

Pin types/webdriverio version so it can compile successfully during the release tomorrow.

Pin webdriverio version

---

packages/salesforcedx-vscode-apex-debugger/package.json
packages/salesforcedx-vscode/package.json

Add publish command to vscode-apex-debugger and include it in the extension pack.

Make debugger publishable

---

.appveyor.yml
.travis.yml
packages/salesforcedx-utils-vscode/test/cli/commandExecutorTest.ts
packages/salesforcedx-vscode-core/test/channels/index.test.ts

Changes travis.yml to use the latest version of the CLI
Part of the preparation for the V6 CLI.

Update travis.yml and appveyor.yml to use latest CLI

---

.codecov.yml

I made a mistake in the format of the .codecov.yml file. It needs to have the `coverage:` header.

Ignore files from coverage

---

packages/salesforcedx-vscode-apex-debugger/package.json
packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-visualforce-next/package.json
packages/salesforcedx-vscode-visualforce/package.json
packages/salesforcedx-vscode/package.json

Remove preview flag from package.json
@W-4333752@

Remove preview

---

packages/salesforcedx-vscode/CHANGELOG.md

Adds an entry to our changelog to describe the feature.
#180

Add visualforce completion feature

---

packages/salesforcedx-vscode-visualforce/package.json

We are aware we are using a proposed API for the color preview but there is no loss of functionality for now.
#180

Remove "enableProposedApi": true

---

.appveyor.yml
.travis.yml

Add vscode:package for appveyor and travis so we can verify the ability to package

Verify vscode:package as part of autobuilds

---

package.json

Upgrade lerna to latest version

---

packages/salesforcedx-apex-debugger/src/adapter/apexDebug.ts
packages/salesforcedx-apex-debugger/test/unit/adapter/apexDebugVariablesHandling.test.ts

Paginate collections

---

packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-core/src/index.ts

Remove extra comma in activation, set setContext key to explicit boolean
Fix commands not showing up when running as vsix

Remove extra comma in activation, set setContext key to explicit boolean

---

packages/salesforcedx-vscode-apex-debugger/README.md

Adds doc for [PR #218](https://github.com/forcedotcom/salesforcedx-vscode/pull/218).
@W-4518620@

Add doc for exception breakpoints

---

packages/salesforcedx-apex-debugger/test/integration/config/variables/source/permissionsets/DebugApex.permissionset-meta.xml

Update debugger permission set metadata due to a new permission dependency in Spring '18.

Update debugger permission set metadata

---

packages/salesforcedx-vscode-apex-debugger/README.md

* Fixes the GitHub URL for this extension
* Updates the prerequisites to show the apex extension as a dependency rather than listing apex-debugger as its own prereq

Fix dependency and GitHub URL

---

packages/salesforcedx-sobjects-faux-generator/src/constants.ts
packages/salesforcedx-sobjects-faux-generator/src/describe/sObjectDescribe.ts
packages/salesforcedx-vscode-core/src/constants.ts
packages/salesforcedx-vscode-core/src/index.ts
packages/salesforcedx-vscode-core/test/logging/index.test.ts
packages/system-tests/scenarios/integratedTerminal.test.ts
packages/system-tests/src/spectron/client.ts

Add logging to API calls made from VS Code for commands palette commands and for commands executed through the integrated terminal
@W-4351074@, @W-4497742@

[WIP] James/api logging

---

packages/salesforcedx-vscode-lwc/src/index.ts

Clarify what core means for LWC

---

packages/salesforcedx-vscode-replay-debugger/test/unit/adapter/debugConfigurationProvider.test.ts

This change fixes a compile issue that was happening due to the casing of the "d" in debugConfigurationProvider being upper case.
This allows the project to compile. (npm run compile was failing).

Fix the casing so the test file will compile

---

packages/salesforcedx-vscode-lwc/package.json
packages/salesforcedx-vscode-lwc/src/index.ts

We moved the functionality into the lwc-language-server module so we can just reference it and do the checks from there.

Simplify checks for activating LWC

---

packages/salesforcedx-vscode/CHANGELOG.md

Updates Changelog for v41.17.0 release
Updates Changelog

Update changelog for v41.17.0

---

packages/salesforcedx-vscode-lwc/package.json
scripts/install-vsix-dependencies.js

Upgrade LWC to use 14.0.1

---

.vscode/launch.json
packages/salesforcedx-vscode-lwc/package.json
packages/salesforcedx-vscode-lwc/src/constants.ts
packages/salesforcedx-vscode-lwc/src/index.ts
packages/salesforcedx-vscode-lwc/test/eslint.test.ts
packages/system-tests/assets/sfdx-simple/.vscode/settings.json
scripts/run-test-with-top-level-extensions.js

Bundles the necessary eslint plug-ins for LWC.
@W-4615981@

Bundle eslint and eslint-plugin-lwc

---

packages/salesforcedx-vscode/CHANGELOG.md

Updates the changelog for release 41.18.0

Update CHANGELOG.md for v41.18.0

---

packages/salesforcedx-vscode-core/README.md

Explains how to edit workspace settings, and how to change where Salesforce CLI success messages display.
@W-4440104@
https://github.com/forcedotcom/salesforcedx-vscode/pull/259

Explain how to change the success message display

---

.circleci/config.yml

Just a test to trigger a build on Circle CI.

[WIP] Add environment variables to Circle CI 2.0

---

packages/salesforcedx-vscode-lwc/package.json
packages/salesforcedx-vscode-lwc/src/index.ts

Upgrade the LWC Language Server to 1.0.1 and also prepare this extension for publishing.

Upgrade the LWC Language Server

---

packages/salesforcedx-slds-linter/src/server/index.ts

When editing a .html file, sometimes you will see errors of the form
```
[Error - 10:25:47] Request textDocument/codeAction failed.
Message: Request textDocument/codeAction failed with message: Cannot read property '0' of undefined
Code: -32603 
``` in the Output > SLDS Language Server window.
@W-4635151@

Check for .code property before proceeding

---

packages/salesforcedx-vscode-lwc/package.json

Upgrade LWC language server

---

packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-core/package.nls.json
packages/salesforcedx-vscode-core/src/commands/forceApexTestRun.ts
packages/salesforcedx-vscode-core/src/commands/forceApexTestRunCodeAction.ts
packages/salesforcedx-vscode-core/src/commands/index.ts
packages/salesforcedx-vscode-core/src/index.ts
packages/salesforcedx-vscode-core/src/messages/i18n.ts
packages/salesforcedx-vscode-core/test/commands/forceApexTestRun.test.ts
packages/salesforcedx-vscode-core/test/commands/forceApexTestRunCodeAction.test.ts

Adds SFDX command to invoke Apex test run code actions (little lightbulb in an editor): (1) run all tests in a class and (2) run a single test method.
@W-4654445@
How is `packages/salesforcedx-vscode-apex/out/apex-jorje-lsp.jar` updated?

Apex Run Test Code Actions

---

packages/salesforcedx-vscode-lwc/package.json

Update LWC to 0.16.3. This version contains some fixes to the typings.d.ts files.

Update LWC to 0.16.3

---

packages/salesforcedx-vscode/CHANGELOG.md

Updates changelog for v42.2.0 release.

Update CHANGELOG.md for v42.2.0

---

packages/salesforcedx-vscode-apex/README.md
packages/salesforcedx-vscode-core/README.md

* Adds doc for code action to run Apex tests (added in PR #291)
* Adds doc for Find All References for Apex class variables (the public-facing name for Apex fields) and Apex properties (added in PR #292)
https://github.com/forcedotcom/salesforcedx-vscode/pull/291
https://github.com/forcedotcom/salesforcedx-vscode/pull/292
https://github.com/forcedotcom/salesforcedx-vscode/pull/296
@W-4654445, W-4681566@

Ruth/docs for v42.2.0

---

packages/salesforcedx-vscode-lwc/README.md
packages/salesforcedx-vscode-lwc/package.json

Explain that this extension is under closed pilot.

Explain that this extension is under closed pilot

---

packages/system-tests/scenarios/forceApexExecuteUi.test.ts
packages/system-tests/scenarios/forceSoqlQueryUi.test.ts
packages/system-tests/scenarios/integratedTerminal.test.ts
packages/system-tests/src/areas/common.ts

It includes fixes to integration tests by addressing UI changes on vscode.
It fixes integration tests that are currently failing in appveyor.
@W-4691478@

Fix UI test failures from VS Code 1.20

---

packages/salesforcedx-vscode-core/test/commands/commands.test.ts
packages/salesforcedx-vscode-lwc/src/index.ts
packages/system-tests/assets/sfdx-simple/.forceignore
packages/system-tests/package.json
packages/system-tests/scenarios/scaffolding.test.ts
scripts/download-vscode-for-system-tests.js
scripts/install-vsix-dependencies.js

Adds a Spectron test for LWC.
@W-4656757, W-4562973@

Add LWC Bundle test

---

packages/salesforcedx-vscode-replay-debugger/package.json
packages/salesforcedx-vscode-replay-debugger/package.nls.json
packages/salesforcedx-vscode-replay-debugger/src/breakpoints/checkpointService.ts
packages/salesforcedx-vscode-replay-debugger/src/breakpoints/index.ts
packages/salesforcedx-vscode-replay-debugger/src/index.ts

It's only an empty view. The ability to add stuff to it comes later. 
@W-4719033@

Add checkpoints panel to debug view

---

packages/salesforcedx-vscode-lwc/src/index.ts
packages/salesforcedx-vscode-lwc/test/eslint.test.ts
packages/system-tests/assets/sfdx-simple/.vscode/settings.json

Remove integrated terminal settings
Keep system-tests workspace clean

Remove settings added to system-tests

---

packages/salesforcedx-vscode/CHANGELOG.md

Updates the changelog for release v42.4.0

Update changelog for v42.4.0 release

---

packages/salesforcedx-vscode-replay-debugger/src/adapter/apexReplayDebug.ts
packages/salesforcedx-vscode-replay-debugger/src/core/logContext.ts
packages/salesforcedx-vscode-replay-debugger/src/core/logContextUtil.ts
packages/salesforcedx-vscode-replay-debugger/src/index.ts
packages/salesforcedx-vscode-replay-debugger/src/states/frameEntryState.ts
packages/salesforcedx-vscode-replay-debugger/src/states/logEntryState.ts
packages/salesforcedx-vscode-replay-debugger/test/unit/core/logContext.test.ts
packages/salesforcedx-vscode-replay-debugger/test/unit/states/frameEntryState.test.ts
packages/salesforcedx-vscode-replay-debugger/test/unit/states/logEntryState.test.ts

Handle spaces in file path

---

packages/salesforcedx-sobjects-faux-generator/test/integration/config/simpleObjectAndField/objects/MyCustomObject2__c/MyCustomObject2__c.object-meta.xml
packages/salesforcedx-sobjects-faux-generator/test/integration/config/simpleObjectAndField/objects/MyCustomObject3__c/MyCustomObject3__c.object-meta.xml
packages/salesforcedx-sobjects-faux-generator/test/integration/config/simpleObjectAndField/objects/MyCustomObject__c/MyCustomObject__c.object-meta.xml
packages/salesforcedx-vscode-apex/syntaxes/apex.tmLanguage

Add initial support for Apex Switch Statements. We are starting off first by ensuring that line breakpoints work in the interactive debugger.
@W-4677434@

Support line breakpoints in Apex switch statements

---

packages/salesforcedx-vscode/CHANGELOG.md

Updates the changelog for v42.5.0 release

Update changelog for release v42.5.0

---

packages/salesforcedx-vscode-apex/README.md
packages/salesforcedx-vscode-core/README.md

Updates docs for this week's changes.
I removed the reference to the GIF for running Apex tests, because I didn't have time to create a new one.
https://github.com/forcedotcom/salesforcedx-vscode/pull/310
https://github.com/forcedotcom/salesforcedx-vscode/pull/324
@W-4549175, W-4511260@

Update docs for v42.5.0

---

packages/salesforcedx-vscode/CHANGELOG.md

Updates the changelog for release v42.7.0

Update changelog for release v42.7.0

---

packages/salesforcedx-vscode/CHANGELOG.md

Updates the changelog for changes that are part of v42.8.0 release

Updating changelog for release v42.8.0

---

packages/salesforcedx-vscode-core/src/constants.ts
packages/salesforcedx-vscode-replay-debugger/adaptertest/unit/adapter/apexReplayDebug.test.ts
packages/salesforcedx-vscode-replay-debugger/adaptertest/unit/core/logContext.test.ts
packages/salesforcedx-vscode-replay-debugger/src/adapter/apexReplayDebug.ts
packages/salesforcedx-vscode-replay-debugger/src/core/logContext.ts
packages/salesforcedx-vscode-replay-debugger/src/core/logContextUtil.ts
packages/salesforcedx-vscode-replay-debugger/src/messages/i18n.ts

Parse the log levels in a debug log and inform user if they don't meet the requirements of apex code and visualforce at the finest level.
@W-4817382@

Check apex code and visualforce log levels on launch

---

packages/salesforcedx-vscode/CHANGELOG.md

Updates the changelog for release v42.10.0

Update changelog for v42.10.0 release

---

packages/salesforcedx-vscode/CHANGELOG.md

Updates the changelog for v42.11.0 release.

Update changelog for release v42.11.0

---

package.json
packages/salesforcedx-vscode-replay-debugger/adaptertest/unit/states/variableAssignmentState.test.ts
packages/salesforcedx-vscode-replay-debugger/src/adapter/apexReplayDebug.ts
packages/salesforcedx-vscode-replay-debugger/src/core/logContext.ts
packages/salesforcedx-vscode-replay-debugger/src/states/variableAssignmentState.ts
packages/salesforcedx-vscode-replay-debugger/src/states/variableBeginState.ts

Shows nested variables for top level variables and some inner variables depending on the information given. Selectively avoids collections for right now.
@W-4814879@

Add basic nested variables

---

packages/salesforcedx-vscode-core/src/messages/i18n.ts

Updates error label for Salesforce CLI

Update cli label

---

packages/salesforcedx-apex-debugger/test/integration/adapter.test.ts

Disable apex interactive debugger integration test

---

packages/salesforcedx-vscode/CHANGELOG.md

Updates the changelog for release v42.12.0

Update changelog for release v42.12.0

---

packages/salesforcedx-vscode-core/src/commands/isvdebugging/bootstrapCmd.ts
packages/salesforcedx-vscode-core/test/commands/isvdebugger/bootstrapCmd.test.ts

Fixes the folder location of the launch.json file.
@W-4894080@

Fix launch.json folder

---

packages/salesforcedx-vscode-core/package.json

This PR contains the latest Apex LS jar.
This includes the fix for the exception that occurs when the namespace field is missing from sfdx-project.json
@W-4931907@

Handle missing "namespace" case in sfdx-project.json for Apex LS

---

packages/salesforcedx-vscode/CHANGELOG.md

Update changelog for v42.13.0 release

Update changelog for v42.13.0 release

---

packages/salesforcedx-vscode-replay-debugger/adaptertest/unit/states/variableAssignmentState.test.ts

Adds more test coverage for log lines involving nested static variables
@W-4902087@

Tests for nested static variables

---

packages/salesforcedx-vscode/CHANGELOG.md

Updates changelog for release v42.14.0
Documentation.

Update changelog for release v42.14.0

---

packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-core/src/commands/forceApexExecute.ts
packages/salesforcedx-vscode-core/src/commands/forceProjectCreate.ts
packages/salesforcedx-vscode-core/src/commands/isvdebugging/bootstrapCmd.ts
packages/salesforcedx-vscode-core/src/messages/i18n.ts
packages/salesforcedx-vscode-core/src/messages/index.ts
packages/salesforcedx-vscode-core/test/commands/isvdebugger/bootstrapCmd.test.ts

Pre-populate the project name inbox with the org name.
W-4681065

User org name as default project name.

---

packages/salesforcedx-vscode-replay-debugger/adaptertest/unit/states/variableAssignmentState.test.ts
packages/salesforcedx-vscode-replay-debugger/adaptertest/unit/states/variableBeginState.test.ts
packages/salesforcedx-vscode-replay-debugger/src/states/variableAssignmentState.ts
packages/salesforcedx-vscode-replay-debugger/src/states/variableBeginState.ts

Fixes an issue where reference reassignment does not work properly when reassigning a variable sharing a container to a new reference.
@W-4974520@

Variable reassignment on new reference bug fix

---

packages/salesforcedx-vscode/CHANGELOG.md

Updates the Changelog for release v42.16.0

Update changelog for release v42.16.0

---

packages/salesforcedx-vscode-lwc-next/package.json
packages/salesforcedx-vscode-lwc-next/package.nls.json
packages/salesforcedx-vscode-lwc-next/src/commands/forceLightningLwcCreate.ts
packages/salesforcedx-vscode-lwc-next/src/index.ts
packages/salesforcedx-vscode-lwc-next/src/messages/i18n.ts
packages/system-tests/scenarios/scaffolding.test.ts

* Auto generation of d.ts files from the Apex Language Server jar
* Upgrade the LWC Language Server to 1.40.0
* Change command to use new force:lightning:component:create --type web
* Disable tests until we have 214 available
@W-4845577@

Add Summer '18 LWC features

---

packages/salesforcedx-vscode-core/src/commands/isvdebugging/bootstrapCmd.ts

Replace + sign in org name when creating the default project name.
W-4991435

Replace + in project name for bootstrap command

---

packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-apex/syntaxes/apex.tmLanguage

* Update to a salesforce uuid for language grammar file
* Support trigger syntax (keywords, context variables, etc)
* Support annotation (@isTest, @AuraEnabled, etc)
* SOQL enhancements
@W-4997762, W-4998647@

Language grammar support for annotations & triggers

---

packages/salesforcedx-vscode-replay-debugger/OSSREADME.json
packages/salesforcedx-vscode-replay-debugger/package.json
packages/salesforcedx-vscode-replay-debugger/package.nls.json
packages/salesforcedx-vscode-replay-debugger/src/adapter/debugConfigurationProvider.ts
packages/salesforcedx-vscode-replay-debugger/src/commands/launchFromLogFile.ts
packages/salesforcedx-vscode-replay-debugger/src/index.ts
packages/salesforcedx-vscode-replay-debugger/syntaxes/apexlog.tmLanguage.json
packages/salesforcedx-vscode-replay-debugger/test/unit/adapter/debugConfigurationProvider.test.ts

Launch replay debugger for current log file

---

packages/salesforcedx-apex-debugger/src/adapter/apexDebug.ts
packages/salesforcedx-apex-debugger/test/unit/adapter/apexDebugVariablesHandling.test.ts
packages/salesforcedx-vscode-replay-debugger/adaptertest/unit/states/variableAssignmentState.test.ts
packages/salesforcedx-vscode-replay-debugger/src/adapter/apexReplayDebug.ts

Allow variables to be copied to clipboard

---

packages/salesforcedx-vscode-apex-debugger/README.md

Adds a note about disabling the Live Share extension before using the Apex Debugger.
@W-5001188@

Add note about disabling Live Share

---

packages/salesforcedx-apex-debugger/package.json
packages/salesforcedx-slds-linter/package.json
packages/salesforcedx-vscode-apex-debugger/package.json
packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lwc-next/package.json
packages/salesforcedx-vscode-lwc/package.json
packages/salesforcedx-vscode-replay-debugger/package.json
packages/salesforcedx-vscode-visualforce/package.json
packages/system-tests/package.json

Brings in https://github.com/Microsoft/vscode-extension-vscode/issues/106
@W-4979583@

Upgrade vscode dev-dependency to 1.1.17

---

.vscode/launch.json
packages/salesforcedx-vscode-core/src/index.ts
packages/salesforcedx-vscode-replay-debugger/README.md
packages/salesforcedx-vscode-replay-debugger/package.json
packages/salesforcedx-vscode-replay-debugger/src/index.ts
packages/salesforcedx-vscode-replay-debugger/test/unit/checkpoints/checkpointService.test.ts

Changes the extension name. I'm not changing the folder name yet; I think that can be done when the adapter is separated from the extension.
@W-5014405@

Rename replay debugger

---

packages/salesforcedx-vscode-core/src/commands/isvdebugging/bootstrapCmd.ts
packages/salesforcedx-vscode-core/src/messages/i18n.ts
packages/salesforcedx-vscode-core/test/commands/isvdebugger/bootstrapCmd.test.ts

This changes the ISV bootstrap command to clean up any temp. files that were created/downloaded as part of retrieving and converting code.
@W-4963327@

Cleanup temp. files when done

---

packages/salesforcedx-vscode-replay-debugger/adaptertest/unit/states/variableAssignmentState.test.ts
packages/salesforcedx-vscode-replay-debugger/src/states/variableAssignmentState.ts

Changes strings being shown in double quotes to single quotes and refactors the copying of a reference container that was lost in a rebase
@W-4995429@

Single quote strings and refactor common code

---

packages/salesforcedx-vscode-core/src/commands/isvdebugging/bootstrapCmd.ts

This avoids the empty isvdebugger leftover folder after cleanup.
@W-4963327@

Move temp folder into tools

---

packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-core/src/commands/isvdebugging/bootstrapCmd.ts

This disables the SFDX source commands when inside an ISV project.
@W-4966748@

Prevent SFDX source commands from appearing in ISV project

---

packages/salesforcedx-vscode-core/README.md
packages/salesforcedx-vscode-core/src/messages/i18n.ts
packages/salesforcedx-vscode-core/test/channels/index.test.ts

Rename 'Salesforce DX CLI' >> 'Salesforce CLI'

---

packages/salesforcedx-vscode-apex-debugger/README.md
packages/salesforcedx-vscode/CHANGELOG.md

Update CHANGELOG for 42.18.0 release

Update CHANGELOG for 42.18.0 release

---

packages/salesforcedx-vscode-apex-replay-debugger/src/messages/i18n.ts

Updates the UI text for two strings.
@W-5047544@

Update UI Text

---

packages/salesforcedx-vscode-core/src/commands/forceStartApexDebugLogging.ts
packages/salesforcedx-vscode-core/src/commands/forceStopApexDebugLogging.ts
packages/salesforcedx-vscode-core/src/commands/index.ts
packages/salesforcedx-vscode-core/src/index.ts
packages/salesforcedx-vscode-core/src/traceflag/developerLogTraceFlag.ts
packages/salesforcedx-vscode-core/test/commands/forceStopApexDebugLogging.test.ts
packages/salesforcedx-vscode-core/test/traceflag/DeveloperLogTraceFlag.test.ts

Delete the traceflag that was created/updated by the turn on command instead of updating the levels to whatever they were set to previously.
@W-4715221@

Turn off logging will delete the traceflag

---

packages/salesforcedx-vscode-apex-debugger/README.md

After #454, Live Share is now working for the debuggers.
#454

Remove note about limitations of Live Share

---

packages/salesforcedx-vscode-lwc-next/package.json
packages/salesforcedx-vscode-lwc/package.json

Bump lwc-language-server to 1.5.1
W-5028685

Bump lwc-language-server to 1.5.1

---

README.md
packages/salesforcedx-vscode/CHANGELOG.md

Update changelog for 43.2.0 release

Update changelog for 43.2.0 release

---

.github/ISSUE_TEMPLATE/Bug_report.md
.github/ISSUE_TEMPLATE/Feature_request.md

Adds a second issue template for feature requests.
N/A

Added feature request template

---

packages/salesforcedx-vscode-apex-replay-debugger/README.md

Adds log level requirements for Replay Debugger.
n/a

Add log level requirements

---

packages/salesforcedx-vscode/CHANGELOG.md

Updates the changelog for release v43.3.0

Updating changelog for release v43.3.0

---

docs/localization.md
packages/salesforcedx-apex-debugger/src/messages/index.ts
packages/salesforcedx-apex-replay-debugger/src/messages/index.ts
packages/salesforcedx-slds-linter/src/messages/index.ts
packages/salesforcedx-sobjects-faux-generator/src/messages/index.ts
packages/salesforcedx-vscode-apex-debugger/src/messages/index.ts
packages/salesforcedx-vscode-apex-replay-debugger/src/messages/index.ts
packages/salesforcedx-vscode-apex/src/messages/index.ts
packages/salesforcedx-vscode-apex/src/requirements.ts
packages/salesforcedx-vscode-lwc-next/src/index.ts
packages/salesforcedx-vscode-lwc-next/src/messages/index.ts
packages/salesforcedx-vscode-lwc/src/index.ts
packages/salesforcedx-vscode-lwc/src/messages/index.ts
packages/system-tests/src/spectron/application.ts

Address the type changes due to https://github.com/DefinitelyTyped/DefinitelyTyped/commit/09ff4cfc0a0677e498f537640dfefa7fb40fbba1#diff-8811b50169fd98160ad78b073b4d0163
@W-5086993@

Address more precise types from @types/node

---

packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode/CHANGELOG.md

Update apex-tmlanguage to 1.0.2
@W-4997695, W-4998665, W-4998669@

Update apex-tmlanguage to 1.0.2

---

.prettierignore
packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-apex/snippets/apex.json

Adds code snippets to the apex extension.
N/A

Added Apex Code Snippets

---

packages/salesforcedx-vscode-apex/snippets/apex.json

This matches our generator and also from conversations with Chris Peterson, this is a good style to nudge people to.
@W-5064232@

Add with sharing to the Apex class snippets

---

packages/salesforcedx-vscode-apex/README.md
packages/salesforcedx-vscode/CHANGELOG.md

Updates changelog for release v43.4.0

Changelog for release v43.4.0

---

packages/salesforcedx-vscode/CHANGELOG.md

Updates the changelog for release v43.5.0

Update changelog for release v43.5.0

---

packages/salesforcedx-apex-replay-debugger/package.json
packages/salesforcedx-apex-replay-debugger/src/adapter/apexReplayDebug.ts
packages/salesforcedx-apex-replay-debugger/src/breakpoints/index.ts
packages/salesforcedx-apex-replay-debugger/src/commands/apexExecutionOverlayResultCommand.ts
packages/salesforcedx-apex-replay-debugger/src/commands/index.ts
packages/salesforcedx-apex-replay-debugger/src/core/heapDump.ts
packages/salesforcedx-apex-replay-debugger/src/core/index.ts
packages/salesforcedx-apex-replay-debugger/src/core/logContext.ts
packages/salesforcedx-apex-replay-debugger/src/messages/i18n.ts
packages/salesforcedx-apex-replay-debugger/test/integration/adapter.test.ts
packages/salesforcedx-apex-replay-debugger/test/unit/adapter/apexReplayDebug.test.ts
packages/salesforcedx-apex-replay-debugger/test/unit/commands/apexExecutionOverlayResultCommand.test.ts
packages/salesforcedx-apex-replay-debugger/test/unit/core/logContext.test.ts
packages/salesforcedx-vscode-apex-replay-debugger/src/breakpoints/checkpointService.ts
packages/salesforcedx-vscode-apex-replay-debugger/src/index.ts
packages/salesforcedx-vscode-apex-replay-debugger/test/unit/checkpoints/checkpointService.test.ts

This PR contains the necessary changes to scan the log for heap_dump lines and make the necessary calls, on initialize request, to pull the heap dumps to the client.
@W-5068047@

Rest call to get heapdumps, initial

---

packages/salesforcedx-vscode/CHANGELOG.md

Updates the changelog for v43.6.0

Update changelog for v43.6.0 release

---

packages/salesforcedx-apex-replay-debugger/src/adapter/apexReplayDebug.ts
packages/salesforcedx-apex-replay-debugger/src/constants.ts
packages/salesforcedx-apex-replay-debugger/src/core/handles.ts
packages/salesforcedx-apex-replay-debugger/src/core/heapDumpService.ts
packages/salesforcedx-apex-replay-debugger/src/core/logContext.ts
packages/salesforcedx-apex-replay-debugger/src/messages/i18n.ts
packages/salesforcedx-apex-replay-debugger/test/unit/adapter/apexReplayDebug.test.ts
packages/salesforcedx-apex-replay-debugger/test/unit/adapter/apexReplayDebugVariablesHandling.test.ts
packages/salesforcedx-apex-replay-debugger/test/unit/core/logContext.test.ts

Show non-static heapdump variables in an Apex class for topmost frame

---

.appveyor.yml
docs/tests.md

Add docs for the test and make it so that failing build doesnt block artifact upload
@W-5029369@

Update test doc and make build fail after uploading artifacts

---

packages/salesforcedx-apex-replay-debugger/src/core/heapDumpService.ts
packages/salesforcedx-apex-replay-debugger/src/core/logContext.ts
packages/salesforcedx-apex-replay-debugger/src/core/logContextUtil.ts
packages/salesforcedx-apex-replay-debugger/src/states/variableBeginState.ts
packages/salesforcedx-apex-replay-debugger/test/unit/adapter/apexReplayDebugVariablesHandling.test.ts

Show static primitives for topmost frame

---

packages/salesforcedx-vscode/CHANGELOG.md

Updates the changelog for release v43.8.0

Update changelog for release v43.8.0

---

packages/salesforcedx-apex-replay-debugger/src/commands/apexExecutionOverlayResultCommand.ts
packages/salesforcedx-apex-replay-debugger/src/core/heapDumpService.ts
packages/salesforcedx-apex-replay-debugger/test/unit/adapter/apexReplayDebugVariablesHandling.test.ts

Most of the logic was already in place. I did a bunch of refactoring so I can call the same methods for parent and child variables.
@W-5068072@

Show child variables of an object

---

.gitignore
packages/salesforcedx-vscode-apex/snippets/apex.json

collections (list, map, set) instantiations
Aura Exceptions and Methods
Custom Exceptions
Test method/Test setup and user creation utilities

add methods for aura, testing, and collections

---

packages/salesforcedx-vscode-core/src/index.ts

Previously, the command code was not properly wired and selecting
`SFDX: Deploy This Source File To Org` from the right click menu resulted in no action.
@W-5070947@

Fix SFDX: Deploy This Source File To Org

---

packages/salesforcedx-vscode/CHANGELOG.md

Updates the changelog for v43.10.0 release

Update changelog for v43.10.0 release

---

packages/salesforcedx-vscode/CHANGELOG.md

Updates the changelog for release v43.11.0

Update changelog for release v43.11.0

---

packages/salesforcedx-vscode/CHANGELOG.md

Update changelog for release v43.12.0

Update changelog for release v43.12.0

---

.prettierrc
package.json
scripts/reformat-with-prettier.js

Updates the version of prettier to 1.6.0 to address reformat diffs.
Porting change from develop branch (#561)

Update format configuration for prettier (port)

---

packages/salesforcedx-vscode-core/src/commands/forceApexClassCreate.ts
packages/salesforcedx-vscode-core/src/index.ts
packages/salesforcedx-vscode-core/src/telemetry/telemetry.ts
packages/salesforcedx-vscode-core/test/telemetry/index.test.ts

Prevents metrics from being logged from development environments
@W-5335810@

Prevent metrics being logged from development environments

---

packages/salesforcedx-vscode-core/README.md

Adds documentation for the Apex Tests view.
@W-5188308@

Add doc for Apex Tests sidebar

---

packages/salesforcedx-vscode/CHANGELOG.md

Updates the changelog for release v43.13.0

Update changelog for release v43.13.0

---

packages/salesforcedx-vscode-lwc-next/package.json

Bump LWC version for internal testing

---

.appveyor.yml
package.json
packages/salesforcedx-sobjects-faux-generator/test/integration/fauxGenerate.test.ts
packages/salesforcedx-sobjects-faux-generator/test/integration/sObjectDescribe.test.ts
packages/system-tests/package.json
packages/system-tests/src/helpers/screenshot.ts

Re-enables system tests and addresses an api issue with spectron & electron 2.0+
@W-5335782@

Re-enable system tests

---

packages/salesforcedx-vscode/CHANGELOG.md

Update changelog for release v43.14.0

Update changelog for release v43.14.0

---

packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-core/package.nls.json
packages/salesforcedx-vscode-core/src/commands/forceSourceDelete.ts
packages/salesforcedx-vscode-core/src/commands/index.ts
packages/salesforcedx-vscode-core/src/index.ts
packages/salesforcedx-vscode-core/src/messages/i18n.ts
packages/salesforcedx-vscode-core/test/commands/forceSourceDelete.test.ts

Adds a new `SFDX: Delete from Project and Org` command
W-5070968

Add SFDX: Delete Source from Org command

---

packages/salesforcedx-apex-replay-debugger/src/adapter/apexReplayDebug.ts

Allow breakpoints to be set and hit after heapdumps have been fetched

---

packages/salesforcedx-vscode/CHANGELOG.md

Updates the changelog for release v43.15.0

Update changelog for release v43.15.0

---

packages/salesforcedx-vscode-core/src/commands/forceApexExecute.ts

This PR fixes the wrong error output when running the Execute Anonymous Apex command.
W-5347904

Cleaning up Apex Execute

---

packages/salesforcedx-sobjects-faux-generator/src/messages/i18n.ts
packages/salesforcedx-vscode-core/package.nls.json
packages/salesforcedx-vscode-core/src/messages/i18n.ts

Updates all references to scratch org to be more generic.

Removed all scratch org references

---

packages/salesforcedx-vscode/CHANGELOG.md

Updates the changelog for release v43.16.0

Update changelog for release v43.16.0

---

packages/salesforcedx-vscode-core/package.nls.json

I didn't notice this message back when Alli submitted her PR to add this text.
PR #604

Fix capitalization of "This"

---

packages/salesforcedx-vscode-apex/src/views/readableApexTestRunExecutor.ts

Updates the test status notification with 'failed to execute' on an unsuccessful run.
W-5374751

Updates message dialog with test status

---

.npmrc
packages/salesforcedx-vscode-lwc-next/package.json
packages/salesforcedx-vscode-lwc/package.json

This prepares it for Winter '19.
@W-548748@

Bump LWC language server option

---

packages/salesforcedx-vscode/CHANGELOG.md

Updates changelog for release v43.19.0

Update changelog for release v43.19.0

---

packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-core/package.nls.json

This removes the feature flag for org based development commands, making them available to everyone as open beta. These commands are also in open beta for sfdx cli.
@W-5514110@

Open beta for org based development commands

---

packages/salesforcedx-vscode/CHANGELOG.md

Update changelog for release v44.2.0

Update changelog for release v44.2.0

---

packages/salesforcedx-vscode/CHANGELOG.md

Changelog updates for release v44.3.0

Update changelog for release v44.3.0

---

package.json

Fixes a typo in a package.json script
-.-

typo in script

---

README.md

I know that "An" is capitalized in the session title, but I uncapitalized it in the heading since our style guidelines say to not capitalize articles.
Makes minor edits to intro text for Dreamforce video.
n/a

Edit intro text for DF video

---

packages/salesforcedx-vscode/CHANGELOG.md

Update changelog for release v44.4.0

Update changelog for release v44.4.0

---

packages/salesforcedx-vscode-lwc-next/package.json
packages/salesforcedx-vscode-lwc-next/src/commands/forceLightningLwcCreate.ts
packages/salesforcedx-vscode-lwc-next/src/index.ts

Changes the folder to lwc
@W-5501730@

LWC folder rename

---

package.json
packages/salesforcedx-vscode-core/OSSREADME.json
packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-core/src/telemetry/telemetry.ts
packages/salesforcedx-vscode-core/src/telemetry/telemetryReporter.ts
packages/salesforcedx-vscode-core/test/telemetry/index.test.ts
packages/salesforcedx-vscode/package.json

This pr updates the `vscode-extension-telemetry` to collect data for unique users through `UserID` and `SessionID` and populate AppInsights reports with this information. With this pr, the extension is included as a file in our project until it is possible to merge these changes into the official Microsoft extension.
@W-5313565@

Set UserID and SessionID in AppInsights Telemetry 

---

packages/salesforcedx-vscode/CHANGELOG.md

Updates the changelog for release v44.5.0

Update changelog for release v44.5.0

---

packages/salesforcedx-vscode-core/package.json

Adds JSON schema validation for `sfdx-project.json` files and `*-scratch-def.json` files.
@W-4541490@, #287

Added JSON schema validation for sfdx-project.json and scratch def files

---

packages/salesforcedx-vscode/CHANGELOG.md

Updates changelog for release v44.6.0

Update changelog for release v44.6.0

---

packages/salesforcedx-vscode-core/src/commands/forceSourceDeploy.ts

Updates the api used to set the workspace path when running source:deploy.
@W-5608272@, #737, #734

Update api used to get workspace path on source:deploy

---

packages/salesforcedx-vscode/CHANGELOG.md

Updates the changelog for release v44.7.0

Update changelog for release v44.7.0

---

packages/salesforcedx-vscode-apex-debugger/README.md
packages/salesforcedx-vscode-apex/README.md
packages/salesforcedx-vscode-core/README.md
packages/salesforcedx-vscode-lightning/README.md
packages/salesforcedx-vscode-visualforce/README.md

Consistent formatting in readmes

---

packages/salesforcedx-vscode/CHANGELOG.md

Updates the changelog for release v44.8.0

Update changelog for release v44.8.0

---

packages/salesforcedx-vscode-core/package.json

Changes context menu detection for 218, based on #698

[DO NOT MERGE ] Updates context menu selection to new folder naming convention

---

packages/salesforcedx-vscode-core/README.md
packages/salesforcedx-vscode-core/package.nls.json
packages/salesforcedx-vscode-core/src/messages/i18n.ts
packages/system-tests/scenarios/scaffolding.test.ts

This PR updates the Lightning command text to Aura as part of the LWC rollout.
@W-5637607@

Update lightning component command text

---

packages/salesforcedx-vscode/CHANGELOG.md

Updates the changelog for release 44.10.0

Update changelog for release v44.10.0

---

packages/salesforcedx-vscode-lwc-next/package.json
packages/salesforcedx-vscode-lwc-next/src/index.ts

update lwc-language-server to 1.8.1

chore: update lsp to 1.8.0

---

packages/salesforcedx-vscode-core/package.json

Sets the `.forceignore` file to use the `ignore` language type.

Set forceignore to ignore language

---

packages/salesforcedx-vscode-apex/src/views/testOutlineProvider.ts

Fix sorting of test class names in Apex test sidebar
@W-5652397@

Fix sorting tests in Apex test sidebar

---

packages/salesforcedx-vscode-lwc/package.json

Adds missing publishing scripts in lwc extension.
@W-5678743@

Add missing publishing scripts to lwc

---

README.md
packages/salesforcedx-vscode-lightning/README.md
packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lwc/README.md
packages/salesforcedx-vscode-lwc/package.json
packages/salesforcedx-vscode/README.md

Rebase of PR #806 
Revised titles for the extensions and references to "Lightning Components" to distinguish between Aura components and Lightning web components.
@W-5529241@

Branding updates for LWC release

---

package.json
packages/salesforcedx-apex-debugger/package.json
packages/salesforcedx-apex-debugger/tsconfig.json
packages/salesforcedx-apex-replay-debugger/package.json
packages/salesforcedx-apex-replay-debugger/tsconfig.json
packages/salesforcedx-slds-linter/package.json
packages/salesforcedx-sobjects-faux-generator/package.json
packages/salesforcedx-sobjects-faux-generator/tsconfig.json
packages/salesforcedx-utils-vscode/package.json
packages/salesforcedx-utils-vscode/tsconfig.json
packages/salesforcedx-visualforce-language-server/package.json
packages/salesforcedx-visualforce-language-server/src/modes/javascriptMode.ts
packages/salesforcedx-visualforce-language-server/tsconfig.json
packages/salesforcedx-visualforce-markup-language-server/package.json
packages/salesforcedx-vscode-apex-replay-debugger/tsconfig.json
packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-core/src/context/workspaceOrgType.ts
packages/salesforcedx-vscode-core/test/context/workspaceOrgType.test.ts
packages/salesforcedx-vscode-core/tsconfig.json
packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lwc/package.json
packages/salesforcedx-vscode-visualforce/package.json
packages/salesforcedx-vscode-visualforce/tsconfig.json
packages/system-tests/package.json
tslint.json

* Update typescript to 3.1.6 to match @salesforce/core
* Update @salesforce/core to 1.0.1

Bump typescript and @salesforce/core versions

---

lerna.json
packages/salesforcedx-apex-debugger/package.json
packages/salesforcedx-apex-replay-debugger/package.json
packages/salesforcedx-slds-linter/package.json
packages/salesforcedx-sobjects-faux-generator/package.json
packages/salesforcedx-utils-vscode/package.json
packages/salesforcedx-visualforce-language-server/package.json
packages/salesforcedx-visualforce-markup-language-server/package.json
packages/salesforcedx-vscode-apex-debugger/package.json
packages/salesforcedx-vscode-apex-replay-debugger/package.json
packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lwc/package.json
packages/salesforcedx-vscode-visualforce/package.json
packages/salesforcedx-vscode/package.json
packages/system-tests/package.json

Fixes some merge conflicts in develop branch.

Fix some merge conflicts for v44.11.0

---

packages/salesforcedx-vscode-lwc/README.md

Fixes a broken link in the LWC README.
n/a

Remove space that breaks link

---

.appveyor.yml

Disables vscode-insiders build in appveyor

Stop running vscode-insiders build

---

packages/salesforcedx-vscode-apex-debugger/src/index.ts
packages/salesforcedx-vscode-apex-debugger/src/telemetry/telemetry.ts
packages/salesforcedx-vscode-apex-debugger/test/unit/telemetry/telemetry.test.ts
packages/salesforcedx-vscode-apex-replay-debugger/src/index.ts
packages/salesforcedx-vscode-apex-replay-debugger/src/telemetry/telemetry.ts
packages/salesforcedx-vscode-apex-replay-debugger/test/unit/telemetry/telemetry.test.ts
packages/salesforcedx-vscode-core/src/index.ts
packages/salesforcedx-vscode-core/src/telemetry/telemetry.ts
packages/salesforcedx-vscode-core/test/telemetry/index.test.ts
packages/salesforcedx-vscode-lightning/src/index.ts
packages/salesforcedx-vscode-lightning/src/telemetry/telemetry.ts
packages/salesforcedx-vscode-lightning/test/unit/telemetry/telemetry.test.ts
packages/salesforcedx-vscode-lwc/src/index.ts
packages/salesforcedx-vscode-lwc/src/telemetry/telemetry.ts
packages/salesforcedx-vscode-lwc/test/unit/telemetry/telemetry.test.ts
packages/salesforcedx-vscode-visualforce/src/extension.ts
packages/salesforcedx-vscode-visualforce/src/telemetry/telemetry.ts
packages/salesforcedx-vscode-visualforce/test/unit/telemetry/telemetry.test.ts

Adds logging to track the time it takes every extension to activate. This is the first set of changes on performance enhancements.
@W-5702036@

Log activation time per extension

---

packages/salesforcedx-sobjects-faux-generator/package.json
packages/salesforcedx-utils-vscode/package.json
packages/salesforcedx-vscode-core/package.json

Fixes a missing dependency when building the vsix files.

Fix path-exists missing dependency

---

packages/salesforcedx-sobjects-faux-generator/package.json
packages/salesforcedx-utils-vscode/package.json
packages/salesforcedx-vscode-core/package.json

Porting PR #855 to release/v44.15.0 branch
@W-5750370@

Fix vsix files missing some modules (#855)

---

packages/salesforcedx-vscode/CHANGELOG.md

Updates the changelog for release v44.15.0. Also includes changes released on v44.11.0

Update changelog for release v44.15.0

---

packages/salesforcedx-visualforce-language-server/package.json

Removes duplicate typescript dependency.

Fix merge conflict

---

packages/salesforcedx-vscode-core/src/commands/forceApexLogGet.ts
packages/salesforcedx-vscode-core/test/commands/forceApexLogGet.test.ts

Adds LogUser Name and status to debug log entries. Original PR #838 opened by @maaaaarco 
#834

Add Username to Apex Debug Log entries

---

packages/salesforcedx-vscode-core/src/context/workspaceOrgType.ts
packages/salesforcedx-vscode-core/src/telemetry/telemetry.ts
packages/salesforcedx-vscode-core/test/context/workspaceOrgType.test.ts

Porting PR #868 to `release/v44.16.0` branch.
@W-5767373@

Handle cli errors when loading workspace context (#868)

---

packages/salesforcedx-vscode/CHANGELOG.md

Updates the changelog for release v44.16.0

Update changelog for release v44.16.0

---

packages/salesforcedx-vscode-apex/package.json

Update LSP Jar and vscode language client version for salesforcedx-vscode-apex package.
Add LSP support to rename the containing file and the metadata file  when renaming a top-level type.
@W-5613486@

Rename file containing top-level type and corresponding metadata file when renaming a top-level type

---

packages/salesforcedx-vscode-core/package.json

Updates adm-zip version to the latest (0.4.13) since previous versions are flagged as insecure. It also turns out this fixes our test issue catched by our vscode insiders builds.
@W-5694513@

Update adm-zip version to 0.4.13

---

packages/salesforcedx-vscode/CHANGELOG.md

Updates the changelog for release v44.17.0

Update changelog for v44.17.0

---

contributing/tests.md

Ports changes made in https://github.com/forcedotcom/salesforcedx-vscode/pull/882/ over to the docs branch.

Port doc changes made in 'docs/tests.md' to 'contributing/tests.md'

---

packages/salesforcedx-vscode/CHANGELOG.md

Updates changelog for release v44.18.0

Update changelog for release v44.18.0

---

packages/salesforcedx-vscode-core/package.nls.json

This PR updates the command palette text to be 'SFDX: Set a Default Org'
Org Picker UI #944
@W-5459244@

Update org picker command palette text

---

packages/salesforcedx-vscode-core/src/commands/commands.ts
packages/salesforcedx-vscode-core/src/commands/forceApexClassCreate.ts
packages/salesforcedx-vscode-core/src/commands/forceApexLogGet.ts
packages/salesforcedx-vscode-core/src/commands/forceApexTriggerCreate.ts
packages/salesforcedx-vscode-core/src/commands/forceAuthWebLogin.ts
packages/salesforcedx-vscode-core/src/commands/forceDebuggerStop.ts
packages/salesforcedx-vscode-core/src/commands/forceGenerateFauxClasses.ts
packages/salesforcedx-vscode-core/src/commands/forceLightningAppCreate.ts
packages/salesforcedx-vscode-core/src/commands/forceLightningComponentCreate.ts
packages/salesforcedx-vscode-core/src/commands/forceLightningEventCreate.ts
packages/salesforcedx-vscode-core/src/commands/forceLightningInterfaceCreate.ts
packages/salesforcedx-vscode-core/src/commands/forceProjectCreate.ts
packages/salesforcedx-vscode-core/src/commands/forceSourceDeploy.ts
packages/salesforcedx-vscode-core/src/commands/forceStartApexDebugLogging.ts
packages/salesforcedx-vscode-core/src/commands/forceStopApexDebugLogging.ts
packages/salesforcedx-vscode-core/src/commands/forceVisualforceComponentCreate.ts
packages/salesforcedx-vscode-core/src/commands/forceVisualforcePageCreate.ts
packages/salesforcedx-vscode-core/src/commands/isvdebugging/bootstrapCmd.ts
packages/salesforcedx-vscode-core/src/telemetry/telemetry.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceGenerateFauxClasses.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/telemetry/index.test.ts

Tracks execution time for command execution.
@W-5825408@

Added execution time to command execution telemetry

---

packages/salesforcedx-vscode/package.json

Adds lwc extension to our extension pack.
@W-5639227@

Add LWC to extension pack

---

packages/salesforcedx-vscode-apex/src/index.ts
packages/salesforcedx-vscode-apex/src/views/testRunner.ts
packages/salesforcedx-vscode-apex/test/vscode-integration/views/testOutline.test.ts
packages/salesforcedx-vscode-core/src/commands/forceApexTestRun.ts
packages/salesforcedx-vscode-core/src/commands/forceApexTestRunCodeAction.ts
packages/salesforcedx-vscode-core/src/constants.ts
packages/salesforcedx-vscode-core/src/index.ts
packages/salesforcedx-vscode-core/src/settings/sfdxCoreSettings.ts

Running tests from the test sidebar now outputs code coverage if a user has the code coverage setting turned on.
W-5296419
#962

Running tests in the test side bar honors code coverage setting

---

scripts/run-vscode-integration-tests-with-top-level-extensions.js

Move string inside of quotes

---

packages/salesforcedx-vscode/package.json

@W-5639227@
Porting this change done in release/v45.1.0 into develop

Add LWC to extension pack (#1015)

---

packages/salesforcedx-vscode/CHANGELOG.md

Updates the changelog for release v45.1.0

Changelog for release v45.1.0

---

packages/salesforcedx-vscode-lwc/README.md

@W-5820304@
Porting this change done in release/v45.1.0 into develop

Update LWC README.md (#1019)

---

packages/salesforcedx-vscode-lwc/package.json

Removes the preview tag for the market place listing of LWC extension
@W-5845478@

Remove preview tag in marketplace for LWC extension

---

packages/salesforcedx-vscode-lwc/package.json

Porting PR #1040 to release branch v45.2.0
@W-5845478@

Remove preview tag in marketplace for LWC extension (#1040)

---

docs/articles/user-guide/default-org.md

Ports documentation fix done for release v45.2.0

Use correct icon for org picker

---

packages/salesforcedx-vscode/CHANGELOG.md

Updates the changelog for release v45.2.0

Update changelog for release v45.2.0

---

docs/_config.yml
docs/_includes/banner-alert.html
docs/_includes/sidebar.html
docs/_layouts/default.html
docs/articles/getting-started/install.md
docs/articles/getting-started/migrate-from-forcecom-ide.md
docs/articles/user-guide/org-development-model.md
docs/assets/styles/docs.css
docs/index.md

Porting PR #1054  to fix doc asset paths

Fixed docs path issues

---

docs/_includes/sidebar.html

Fixed url path

---

README.md

This PR updates the a broken link to the publishing doc in our readme.

Updated reference to publishing doc

---

docs/_includes/sidebar.html
docs/_layouts/default.html

Updates algolia docs search to correct account, adds analytics.
@W-5868716@

Updates Docs Search & Add Analytics

---

packages/salesforcedx-vscode-core/src/constants.ts

Updates the link to github pages for the telemetry info.
@W-5868790@

Changed telemetry url to github pages

---

packages/salesforcedx-vscode-core/src/constants.ts

Ports PR #1059 for release 45.3.0
@W-5868790@

Changed telemetry url to github pages (#1059)

---

packages/salesforcedx-vscode-core/package.nls.json

Ports PR #1080 to release v45.3.0
@W-5861128@

Revise setting description for sobject refresh on startup (#1080)

---

docs/articles/getting-started/first-project.md
docs/articles/getting-started/settings.md
docs/articles/troubleshooting.md
packages/salesforcedx-vscode-lwc/README.md

Fixes some minor doc issues.
@W-5858176@

[WIP] Ruth/v45.3.0

---

docs/articles/getting-started/first-project.md
docs/articles/getting-started/settings.md
docs/articles/troubleshooting.md
packages/salesforcedx-vscode-lwc/README.md

Ports PR #1064 for release 45.3.0
@W-5858176@

Fix some minor doc issues (#1064)

---

packages/salesforcedx-vscode/CHANGELOG.md

Update changelog for release v45.3.0

Updates changelog for release 45.3.0

---

docs/articles/troubleshooting.md
packages/salesforcedx-vscode-apex/src/constants.ts
packages/salesforcedx-vscode-apex/src/messages/i18n.ts
packages/salesforcedx-vscode-apex/src/requirements.ts

Updates Salesforce Apex extension errors to include a link to our documentation when Java is not correctly set up. It also updates our set up documentation to make it a bit more clear how to configure the extension.
@W-5906704@

Update messages related to java setup to include link to our docs

---

.appveyor.yml
config/mochaConfig.json
packages/salesforcedx-apex-debugger/package.json
packages/salesforcedx-apex-replay-debugger/package.json
packages/salesforcedx-slds-linter/package.json
packages/salesforcedx-slds-linter/test/vscode-integration/index.ts
packages/salesforcedx-sobjects-faux-generator/package.json
packages/salesforcedx-vscode-apex-debugger/package.json
packages/salesforcedx-vscode-apex-replay-debugger/package.json
packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-apex/test/vscode-integration/index.ts
packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-core/test/vscode-integration/index.ts
packages/salesforcedx-vscode-core/test/vscode-integration/orgPicker/orgList.test.ts
packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lightning/test/vscode-integration/deprecatedClassName.test.ts
packages/salesforcedx-vscode-lightning/test/vscode-integration/index.ts
packages/salesforcedx-vscode-lwc/package.json
packages/salesforcedx-vscode-lwc/test/vscode-integration/index.ts
packages/salesforcedx-vscode-visualforce/package.json
packages/salesforcedx-vscode-visualforce/test/vscode-integration/index.ts
packages/system-tests/package.json
scripts/run-vscode-integration-tests-with-top-level-extensions.js

Port PR #1128 to release v45.5.0
@W-5917635@

Configuration changes to fix issues with appveyor builds (#1128)

---

packages/salesforcedx-vscode/CHANGELOG.md

Updates the changelog for release 45.5.0.
I'm updating it directly into the `develop` branch this time since I wasn't able to merge it into the release branch this week.

Changelog for release v45.5.0

---

packages/salesforcedx-vscode-core/src/index.ts
packages/salesforcedx-vscode-core/src/telemetry/telemetryReporter.ts

Add CPUS and total system memory to our extension telemetry
W-5870048

Add CPUs and total system memory 

---

packages/salesforcedx-vscode/CHANGELOG.md

Updates the changelog for release v45.6.0

Update changelog for v45.6.0 release

---

packages/salesforcedx-vscode-apex/src/index.ts
packages/salesforcedx-vscode-apex/src/languageClientUtils.ts
packages/salesforcedx-vscode-apex/src/languageServer.ts
packages/salesforcedx-vscode-apex/src/telemetry/telemetry.ts

Update Apex LSP to send telemetry data to AppInsights
@W-5842272@

Send telemetry data to AppInsights for Apex LSP

---

scripts/publish.js

Updates our publish script to use nodejs version 10.2.0 and removes steps that are now obsolete as a result of upgrading to a newer prettier version.
@W-5942633@

Update node version check and remove unneccesary steps in publish script

---

packages/salesforcedx-vscode-apex/snippets/apex.json

Porting PR #1153 in order to run all our automation.
Replaces the indentation inside the snippets code to \t to allow VSCode to recognize it as indentation and replace it for the user's configured preference.
#1152

Modified apex snippets to respect user's indentation configuration

---

packages/salesforcedx-vscode-core/src/messages/i18n.ts

@AnanyaJha - Here are a couple of small edits to the messages you added.
#1139

Edit messages for Set Default Org

---

packages/salesforcedx-utils-vscode/src/cli/deployResultParser.ts
packages/salesforcedx-vscode-core/src/commands/baseDeployCommand.ts
packages/salesforcedx-vscode-lwc/src/commands/forceLightningLwcCreate.ts

JSON response slightly differs with oclif - updating the parser to handle pre and post oclif.
W-5944509

Fix deployResultParser for oclif compatibility 

---

packages/salesforcedx-vscode/CHANGELOG.md

Update changelog for release 45.7.0

Update changelog for release v45.7.0

---

package.json

Adds a system-test only scope so lerna doesn't look for the script in all the packages
@W-5959903@

Added system-test only scope

---

packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lightning/package.nls.json
packages/salesforcedx-vscode-lightning/src/commands/quickpick/quickpick.ts
packages/salesforcedx-vscode-lwc/package.json

- Bug fixes for windows
- Add preview preferences for lightning explorer

Update lightning LSPs to 2.0.9

---

packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lightning/package.nls.json
packages/salesforcedx-vscode-lightning/src/commands/quickpick/quickpick.ts
packages/salesforcedx-vscode-lwc/package.json

Ports PR #1197 to develop branch

Port: Update lightning LSPs to 2.0.9 (#1197)

---

packages/salesforcedx-apex-debugger/package.json
packages/salesforcedx-test-utils-vscode/package.json
packages/salesforcedx-utils-vscode/test/unit/cli/commandExecutorTest.ts
packages/salesforcedx-vscode-apex-debugger/package.json
packages/salesforcedx-vscode-apex-replay-debugger/package.json
packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-core/test/vscode-integration/channels/index.test.ts
packages/salesforcedx-vscode-visualforce/package.json

Fixes merge issues with the new `salesforcedx-test-utils-vscode` package.

Fix test-utils merge

---

packages/salesforcedx-vscode/CHANGELOG.md

Updates the changelog for release 45.9.0

Update changelog release 45.9.0

---

packages/salesforcedx-vscode-lwc/src/commands/forceLightningLwcCreate.ts

Makes the log name unique so i can track them seperately

Changed LWC create name to be unique

---

packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lwc/package.json

Update aura and lwc language server to version 2.1.0 which does not sets configs in settings.json

Only changes to fix issues with settings.json

---

packages/salesforcedx-vscode/CHANGELOG.md

Updates changelog for release v45.10.0

Update changelog release 45.10.0

---

packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lightning/package.nls.json
packages/salesforcedx-vscode-lightning/src/commands/quickpick/quickpick.ts
packages/salesforcedx-vscode-lightning/src/dxsupport/waitForDX.ts
packages/salesforcedx-vscode-lightning/src/index.ts
packages/salesforcedx-vscode-lightning/src/telemetry/telemetry.ts
packages/salesforcedx-vscode-lightning/src/views/component-tree-provider.ts
packages/salesforcedx-vscode-lightning/test/vscode-integration/telemetry/telemetry.test.ts
packages/salesforcedx-vscode-lightning/tsconfig.json
packages/salesforcedx-vscode-lwc/package.json
packages/salesforcedx-vscode-lwc/src/index.ts
packages/salesforcedx-vscode-lwc/src/telemetry/telemetry.ts
packages/salesforcedx-vscode-lwc/test/vscode-integration/telemetry/telemetry.test.ts
packages/salesforcedx-vscode-lwc/tsconfig.json

Updates the activation events for lightning and lwc extensions. Address the compilation issue with open dependency.
@W-6075727@

Add new activation logic for lightning and lwc extensions (#1253)

---

packages/salesforcedx-vscode-apex/src/codecoverage/colorizer.ts
packages/salesforcedx-vscode-apex/src/index.ts

Updates to apex extension to use workspace api and update label name in colorizer code.
@W-6076333@, @W-6017035@

Use vscode workspace api. Update colorizer label name

---

packages/salesforcedx-vscode/CHANGELOG.md

Updates changelog for version 45.12.0

Update changelog for version 45.12.0

---

packages/salesforcedx-vscode-apex-debugger/src/adapter/debugConfigurationProvider.ts
packages/salesforcedx-vscode-apex-debugger/test/vscode-integration/adapter/MockApexExtension.ts
packages/salesforcedx-vscode-apex-replay-debugger/src/adapter/debugConfigurationProvider.ts
packages/salesforcedx-vscode-apex-replay-debugger/src/index.ts
packages/salesforcedx-vscode-apex-replay-debugger/test/vscode-integration/adapter/MockApexExtension.ts
packages/salesforcedx-vscode-apex/src/index.ts

Fixes apex debugger and replay debugger not getting the latest status of the Apex Language Server.
#1289

Fix debuggers to get latest  status on apex language server

---

docs/articles/getting-started/install.md
docs/articles/troubleshooting.md
packages/salesforcedx-vscode/CHANGELOG.md

Update changelogs and docs for release v45.13.1

Update changelogs for release v45.13.1

---

docs/articles/getting-started/install.md
docs/articles/troubleshooting.md
packages/salesforcedx-vscode/CHANGELOG.md

Update changelogs for release v45.13.1
Update changelogs for release v45.13.1

Update changelogs for release v45.13.0 (#1301)

---

CHANGELOG.md

Adds a file at the root that links to the changelog.
#1292

Added root changelog

---

.gitignore
contributing/developing.md

We updated to Node 10 but we left some dangling comments. This could be confusing to new users getting started on the project.
N/A.

Update references to use Node 10

---

packages/salesforcedx-vscode-apex-debugger/src/adapter/debugConfigurationProvider.ts
packages/salesforcedx-vscode-apex-debugger/test/vscode-integration/adapter/MockApexExtension.ts
packages/salesforcedx-vscode-apex-replay-debugger/src/adapter/debugConfigurationProvider.ts
packages/salesforcedx-vscode-apex-replay-debugger/src/index.ts
packages/salesforcedx-vscode-apex-replay-debugger/test/vscode-integration/adapter/MockApexExtension.ts
packages/salesforcedx-vscode-apex/src/index.ts

Follow up to the feedback provided in PR #1290, this PR updates the name for the api exposed by `salesforcedx-vscode-apex`.
@W-6083478@

Update api name from apex extension

---

packages/salesforcedx-vscode/CHANGELOG.md

Updates the changelog for release v45.14.0

Update changelog for release v45.14.0

---

packages/salesforcedx-vscode-core/src/orgPicker/orgList.ts
packages/salesforcedx-vscode-core/test/vscode-integration/orgPicker/orgList.test.ts

Release port of #1338 
W-6143678

Show all the org auth/creation options in picker regardless of auth status (release port)

---

packages/salesforcedx-vscode/CHANGELOG.md

Update changelog for release 45.15.0

Update changelog for release 45.15.0

---

packages/salesforcedx-vscode-core/src/orgBrowser/metadataCmp.ts

This PR addresses the issues found during QA- no components found for a given metadata type and the correct metadata name for Report.

[Org Browser] Fix for no components present

---

packages/salesforcedx-vscode/CHANGELOG.md

Update changelog for release 45.15.1

Update changelog for release 45.15.1

---

packages/salesforcedx-vscode-lightning/package.json

Quick fix to enable lightning quick open command for internal development.
@W-6151369@

Quick fix to enable lightning quick open command

---

packages/system-tests/scenarios/forceApexExecuteUi.test.ts
packages/system-tests/scenarios/scaffolding.test.ts

Updates the wait method used between data inputs for system tests. This will speed up our system tests and help solve the current timeouts.

Speed up system tests

---

docs/articles/getting-started/install.md
packages/salesforcedx-vscode-apex/package.nls.json
packages/salesforcedx-vscode/README.md

Updates the Java messaging to be consistent with what the extensions currently support (Java 8 or Java 11).
@W-6202741@

Update Java versions across our docs

---

packages/salesforcedx-vscode-lightning/package.json

Enable lightning quick open command for internal dev mode.
@W-6151369@

Quick fix to enable lightning quick open command (#1365)

---

packages/salesforcedx-vscode-core/src/context/workspaceOrgType.ts

This PR adds telemetry to capture information on workspaceOrgType context switching failing due to a username being present instead of an alias. It also increases the retry period to address auth info file latency issues to 6 seconds.

Addressed workspaceOrgType context issues

---

packages/salesforcedx-vscode-lightning/src/index.ts
packages/salesforcedx-vscode-lwc/src/index.ts

Fix language server crashes due to older version of node on file system
fixes #1267

fix language server crashes

---

docs/articles/getting-started/migrate-from-forcecom-ide.md

Port of PR #1400 to release branch. Addresses broken links in Migrate from Force.com IDE article.
@W-6241272@

Fix broken links in Migrate from Force.com IDE article (#1400)

---

packages/salesforcedx-vscode-core/src/context/workspaceOrgType.ts

This PR adds telemetry for context switching issues.

Port to develop: Addressed workspaceOrgType context issues 

---

packages/salesforcedx-vscode/CHANGELOG.md

Updates the changelog for release v46.2.0.

Update changelog for release 46.2.0

---

.vscode/launch.json

Updates the project's launch configurations, fixing the issues with running tests from vscode and attaching the debugger to the test execution.
@W-6268305@

Update launch configurations to fix issues with debugging tests

---

packages/salesforcedx-vscode/CHANGELOG.md

Update changelog for release/v46.3.0
Updates the changelog for the next release

Update changelog for release/v46.3.0

---

packages/salesforcedx-vscode/CHANGELOG.md

Port changelog update to release/v46.3.0
Update changelog for release/v46.3.0

Update changelog for release/v46.3.0 (#1434)

---

package.json
scripts/download-vscode-for-system-tests.js

Update webpack-cli that fixes Windows crashing issue
Update eslint & eslint-config-prettier to latest versions which fixes vulnerability with regex expressions
Update vscode download script to address file path not using the correct separators in Windows
@W-6307711@

Update build & dev dependencies

---

packages/salesforcedx-vscode-core/package.json

The latest version of sfdx-core contains a fix for an issue found in the next update for VS Code.
W-6236434

Use sfdx-core 2.0.1

---

packages/salesforcedx-vscode/CHANGELOG.md

Update changelog for release/v46.4.0

Update changelog for release v46.4.0

---

packages/salesforcedx-vscode-core/src/messages/i18n.ts

Update label for scratch org creation issue. Follow up to PR #1456 
@W-6289619@

Update error message label for org create parse issue

---

packages/salesforcedx-vscode/CHANGELOG.md

Updated changelog to include release notes for 46.5.0.

changelog made

---

packages/salesforcedx-vscode-core/test/vscode-integration/settings/pushOrDeployOnSave.test.ts

Fix a test that was based on the assumption of an extra telemetryService call.

Test update for deploy on save changes

---

packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-core/package.nls.json
packages/salesforcedx-vscode-core/resources/dark/retrieve.svg
packages/salesforcedx-vscode-core/resources/light/retrieve.svg
packages/salesforcedx-vscode-core/src/commands/forceSourceRetrieve.ts
packages/salesforcedx-vscode-core/src/commands/index.ts
packages/salesforcedx-vscode-core/src/index.ts
packages/salesforcedx-vscode-core/src/messages/i18n.ts
packages/salesforcedx-vscode-core/src/orgBrowser/metadataCmp.ts
packages/salesforcedx-vscode-core/src/orgBrowser/nodeTypes.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceListMetadata.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceSourceRetrieve.test.ts

This PR retrieves individual metadata components from the org using an inline icon in the org browser.
@W-5768040@

[Org Browser] Retrieve Source from Org

---

packages/salesforcedx-vscode/CHANGELOG.md

Update changelog for release 46.6.0

---

packages/salesforcedx-vscode-core/src/orgBrowser/metadataCmp.ts
packages/salesforcedx-vscode-core/test/vscode-integration/orgBrowser/metadataCmp.test.ts

Only allow unmanaged components. i.e. components in unmanaged packages or no package at all.
W-6358467

Only allow unmanaged components

---

packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-core/package.nls.json

Update the org browser flag to give a description and surface changing the value through the settings UI.
W-6369516

Update Org Browser setting description and surface setting through UI

---

packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-core/package.nls.json

Merge setting change to release.
#1498

Merge setting update to release

---

packages/salesforcedx-vscode/CHANGELOG.md

Update changelog for release 46.7.0

---

packages/salesforcedx-vscode/CHANGELOG.md

Changelog for release v46.7.0

---

packages/salesforcedx-vscode/CHANGELOG.md

Update changelog for release 46.8.0

Changelog for release 46.8.0

---

packages/salesforcedx-vscode/CHANGELOG.md

Update changelog with core activation fix

Update changelog with core activation fix

---

packages/salesforcedx-vscode-core/src/commands/forceDescribeMetadata.ts
packages/salesforcedx-vscode-core/src/commands/forceListMetadata.ts
packages/salesforcedx-vscode-core/src/orgBrowser/metadataOutlineProvider.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceDescribeMetadata.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceListMetadata.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/orgBrowser/metadataCmp.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/orgBrowser/metadataType.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/orgBrowser/outlineProvider.test.ts

Port to release handle errors in org browser

---

packages/salesforcedx-vscode/CHANGELOG.md

Update changelog for relase 46.9.0

Changelog for release 46.9.0

---

packages/salesforcedx-vscode/CHANGELOG.md

Changelog for release 46.9.0 (#1540)

---

packages/salesforcedx-vscode/CHANGELOG.md

Updates changelog for release v46.10.0

Update changelog for release v46.10.0

---

packages/salesforcedx-vscode-core/package.nls.json

Fixed broken doc link under the org browser setting.

Org browser doc link fix

---

packages/salesforcedx-vscode-core/src/commands/commands.ts
packages/salesforcedx-vscode-core/src/commands/forceSourceRetrieveCmp.ts
packages/salesforcedx-vscode-core/src/telemetry/index.ts
packages/salesforcedx-vscode-core/src/telemetry/telemetry.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceSourceRetrieveCmp.test.ts

Adding telemetry for org browser to gain insight into most retrieved types.  
W-6455428

Add retrieved types when retrieving components with org browser 

---

packages/salesforcedx-utils-vscode/src/cli/diffResultParser.ts
packages/salesforcedx-utils-vscode/src/cli/index.ts
packages/salesforcedx-utils-vscode/test/unit/cli/diffResultParser.test.ts
packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-core/package.nls.json
packages/salesforcedx-vscode-core/src/commands/forceSourceDiff.ts
packages/salesforcedx-vscode-core/src/commands/index.ts
packages/salesforcedx-vscode-core/src/index.ts
packages/salesforcedx-vscode-core/src/messages/i18n.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceSourceDiff.test.ts

Exposes a new menu command to trigger a diff of the currently opened file against the org the user has authenticated to.
FYI: I'm still working out the tests but this part is ready for review.
@W-6393758@

Allow diffing local metadata against an org

---

packages/salesforcedx-vscode/CHANGELOG.md

Updates the change log for release v46.11.0

Update change log for release v46.11.0

---

.appveyor.yml
packages/salesforcedx-sobjects-faux-generator/package.json

Disable unreliable tests in autobuilds while we work on replacing them in another PR.

Disable running unreliable tests in appveyor

---

CONTRIBUTING.md

This PR updates a broken link to our developing doc.

Update broken doc link for developing

---

packages/salesforcedx-vscode/CHANGELOG.md

Updates the change log for release v46.12.0

Update change log for release v46.12.0 

---

packages/salesforcedx-vscode-apex/package.json

Update to the latest version of apex-tmlanguage which addresses the following syntax highlighting issues:
- String when clauses in switch statements
- Block comments without spaces
- Apex namespaces e.g. System.<>, Test.<>
#921 , #967 
@W-5804153, W-5803883@

Update to v1.2.0 of apex-tmlanguage

---

packages/salesforcedx-vscode/CHANGELOG.md

Changelog for v46.13.0

---

docs/_data/sidebar.yml
docs/articles/user-guide/remote-development.md

Update remote development doc titles

Update remote development doc titles

---

packages/salesforcedx-vscode-lwc/README.md

Removed reference to SLDS in LWC Extension

---

packages/salesforcedx-utils-vscode/test/unit/date/format.test.ts

Test fixes needed based on feedback from PR #1652 
@W-6587405@

Fix regex for hour in time conversions

---

docs/articles/apex/writing.md

Adds a reference to Intellisense's documentation for changing the setting `editor.suggestSelection`.
@W-6035054@
https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000006JN9OIAW/view

Apex auto-complete doc update for pre-selection behavior

---

packages/salesforcedx-vscode-lightning/README.md

Follow up to PR #1657 , this fixes the lightning extension readme
#1515 , @W-6390175@

Remove SLDS reference from lightning extension

---

packages/salesforcedx-vscode/CHANGELOG.md

Update the changelog for release 46.15.0

Changelog for release v46.15.0

---

packages/salesforcedx-sobjects-faux-generator/src/constants.ts
packages/salesforcedx-sobjects-faux-generator/src/generator/fauxClassGenerator.ts
packages/salesforcedx-sobjects-faux-generator/test/unit/fauxClassGenerator.test.ts
packages/salesforcedx-vscode-apex/src/commands/forceGenerateFauxClasses.ts
packages/salesforcedx-vscode-apex/src/messages/i18n.ts
packages/salesforcedx-vscode-apex/test/vscode-integration/commands/forceGenerateFauxClasses.test.ts

Port Select SObject Category to release/v46.16.0
#1679

Port Select SObject Category to release/v46.16.0

---

packages/salesforcedx-vscode/CHANGELOG.md

Change log v46.16.0

---

packages/salesforcedx-vscode-core/package.json

Enables the diff command to be in the File Explorer right-click menu.
#1666 , @W-6695456@

Add Diff command to the File Explorer right-click menu

---

packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-core/package.nls.json
packages/salesforcedx-vscode-core/src/index.ts

Add missing api methods to the internal development mode which cause the Apex extension to fail during activation
@W-6695536@, #1670 , #1678

Fix internal development mode causing Apex extension issues

---

packages/salesforcedx-vscode-core/src/commands/forceProjectCreate.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceProjectCreate.test.ts

Fix for overwrite label.
@W-6741386@
https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B000000770BVIAY/view

Fix for overwrite label

---

docs/_articles/en/user-guide/deploy-on-save.md
docs/_articles/en/user-guide/development-models.md
docs/_data/sidebar.yml

Fixes docs sidebar

---

packages/salesforcedx-vscode/CHANGELOG.md

Changelog v47.1.0

---

packages/salesforcedx-vscode-core/src/commands/forceProjectCreate.ts
packages/salesforcedx-vscode-core/src/commands/isvdebugging/bootstrapCmd.ts
packages/salesforcedx-vscode-core/src/commands/util/projectTemplateEnum.ts
packages/salesforcedx-vscode-core/src/messages/i18n.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceProjectCreate.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/isvdebugger/bootstrapCmd.test.ts

Expose the template input in project create added to templates repo.
Created out of PR #1691 in order to run all our automation.
W-6558148

Analytics templates

---

packages/salesforcedx-vscode/CHANGELOG.md

Change log for release v47.2.0

---

docs/_articles/jp/user-guide/deploy-on-save.md
docs/_articles/jp/user-guide/development-models.md
docs/_articles/jp/user-guide/prettier.md
docs/_articles/jp/user-guide/vscode-commands.md

Adds missing articles to the User Guide section for japanese

Fix jp User Guide section

---

docs/_articles/jp/user-guide/deploy-on-save.md
docs/_articles/jp/user-guide/development-models.md
docs/_articles/jp/user-guide/prettier.md
docs/_articles/jp/user-guide/vscode-commands.md

Porting PR #1719 into develop branch
@W-6801421@

Fix Japanese User Guide section (#1719)

---

.circleci/config.yml

Update cache key for CircleCI to clear cache.

Update cache key for CircleCI

---

.circleci/config.yml
package.json

Temporarily disable caching in CircleCI builds until issue with module resolved.
W-6815766

Temporarily disable caching in CircleCI builds

---

docs/_articles/en/lwc/localdev.md
docs/_articles/jp/lwc/localdev.md

Add back some doc updates for local dev that were dropped

local dev doc

---

docs/_articles/en/lwc/localdev.md
docs/_articles/jp/lwc/localdev.md

cherry pick local dev doc fixes

---

packages/salesforcedx-vscode/CHANGELOG.md

Change log entries for 47.3.0 release

Changelog Updates

---

.circleci/config.yml

Reenable dependency cache in circle ci builds
W-6815766

Reenable dependency cache in circle ci builds

---

docs/_articles/en/soql/writing.md

Fixed typo on command

---

packages/salesforcedx-vscode/CHANGELOG.md

Update changelog for v47.5.0

---

packages/salesforcedx-vscode-apex/package.nls.json

Removed the unnecessary legal description in the setting

Removed long description

---

packages/salesforcedx-vscode-apex/test/vscode-integration/requirements.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceProjectCreate.test.ts

Explicitly set execPath for use by 'Java Requirements Test'.
https://gus.lightning.force.com/lightning/r/a07B0000007dIlnIAE/view
@W-6889418@

Fix Java Requirements Test

---

docs/_layouts/default.html

fixed local header links

---

packages/salesforcedx-vscode/CHANGELOG.md

Change Log for v47.9.0

---

packages/salesforcedx-vscode/CHANGELOG.md

Update to release date for v47.9.0.

Update release date

---

packages/salesforcedx-vscode-lightning/package.json

revert lwc-language-server dependency to the previous version.
#1832 
#1839

set explicit version for lwc dev server (#1836)

---

packages/salesforcedx-vscode/CHANGELOG.md

Creates changelog for release v 47.10.0

Changelog v47.10.0

---

.circleci/config.yml

* Add jobs to build and test on Windows using CircleCI
* W-6746995

Implement Windows build/test for CircleCI.

---

packages/salesforcedx-vscode/CHANGELOG.md

This PR contains the changelog for release v47.14.0

Changelog release v47.14.0

---

docs/_articles/en/getting-started/java-setup.md
packages/salesforcedx-vscode-apex/package.nls.json

Documentation updates based on feedback on #1869 
@W-7109166@

Doc updates based on feedback

---

packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-core/package.nls.json
packages/salesforcedx-vscode-core/src/commands/index.ts
packages/salesforcedx-vscode-core/src/commands/templates/baseTemplateCommand.ts
packages/salesforcedx-vscode-core/src/commands/templates/forceAnalyticsTemplateCreate.ts
packages/salesforcedx-vscode-core/src/commands/templates/index.ts
packages/salesforcedx-vscode-core/src/commands/templates/metadataTypeConstants.ts
packages/salesforcedx-vscode-core/src/commands/util/sourcePathStrategies.ts
packages/salesforcedx-vscode-core/src/index.ts
packages/salesforcedx-vscode-core/src/messages/i18n.ts
packages/salesforcedx-vscode-core/src/util/metadataDictionary.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/templates/forceAnalyticsTemplateCreate.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/util/sourcePathStrategies.test.ts

utilizes the force:analytics:template:create command through vs code
W-6820310 - User Story - [SFDX] Create sample templates for use in projects

Wdxsampletemplate

---

packages/salesforcedx-vscode-apex/package.json

Add a minimum value constraint for the java memory configuration setting.
W-7109166

Added a minimum constraint for java memory config.

---

docs/_articles/en/getting-started/java-setup.md

Updates the header for the Advanced Setup section on Java Setup doc.
@W-7109166@

Fix section header

---

packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lightning/test/unit/package/packageDependencies.test.ts
packages/salesforcedx-vscode-lwc/test/unit/package/packageDependencies.test.ts

add test to check that dependencies on any of the lsp packages use exact version ranges (no ^ or ~).
@W-7129288@

unit tests for lwc/aura lsp dependency versions

---

packages/salesforcedx-vscode-apex/src/messages/i18n.ts

This PR updates the error message that gets displayed when an unsupported version of Java is detected to include Java 8 and Java 11
@W-6267831@

Update error message to support java8 and java11

---

packages/salesforcedx-vscode-lwc/test/vscode-integration/jsconfig.test.ts

Added integration test cases for jsconfig.json
@W-7133293@

[W-7133293] Add jsconfig.json Integration Tests

---

packages/salesforcedx-vscode-lwc/test/tslint.json
packages/salesforcedx-vscode-lwc/test/vscode-integration/jsconfig.test.ts

Changed test cases back to default timeout
Updated wait for config logic.
Test cases expect one write per update.
@W-7133293@

Refactor jsconfig integration tests

---

docs/_articles/en/user-guide/source-diff.md

Add Custom Labels to the list of supported metadata for Source Diff.

Add custom labels to supported metadata

---

packages/salesforcedx-vscode-apex/package.json

Ports changes in PR #1973 to the release/v48.1.0 branch

Port 1973 to release branch

---

contributing/publishing.md
package.json
scripts/download-vsix-from-circleci.js
scripts/publish-circleci.js
scripts/publish-utils.js

Porting PR #1954 to the release branch for 48.1.0
@W-7188372@

Publishing script that uses the artifacts from CircleCI (#1954)

---

packages/salesforcedx-vscode-core/src/messages/i18n.ts

Update conflict detection messages.

Updated conflict detection messages.

---

docs/_data/sidebar.yml

Updates sidebar items that we missed updating to use code ja.
@W-7227338@

Update sidebar items to use ja instead of jp

---

docs/_articles/en/user-guide/detect-conflicts.md
docs/_articles/en/user-guide/development-models.md

Minor doc fixes in conflict detection docs

Minor doc fixes for conflict detection

---

.git2gus/config.json

Adds git2gus mappings based on this doc - https://salesforce.quip.com/QyzhAreppMj0
This add the functionality to map github issues with GUS products and create different types of work items.
@W-7125394@

Changing git2gus mapping based on Stephanie's doc @W-7125394@

---

packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lightning/test/vscode-integration/telemetry/telemetry.test.ts
packages/salesforcedx-vscode-lwc/package.json
packages/salesforcedx-vscode-lwc/test/vscode-integration/commands/forceLightningLwcOpen.test.ts
packages/salesforcedx-vscode-lwc/test/vscode-integration/commands/forceLightningLwcPreview.test.ts
packages/salesforcedx-vscode-lwc/test/vscode-integration/commands/forceLightningLwcStart.test.ts
packages/salesforcedx-vscode-lwc/test/vscode-integration/telemetry/telemetry.test.ts
packages/salesforcedx-vscode-lwc/test/vscode-integration/testSupport/commands/forceLwcTestDebugAction.test.ts
packages/salesforcedx-vscode-lwc/test/vscode-integration/testSupport/commands/forceLwcTestRunAction.test.ts
packages/salesforcedx-vscode-lwc/test/vscode-integration/testSupport/mocks/index.ts
packages/salesforcedx-vscode-lwc/test/vscode-integration/testSupport/testExplorer/testOutlineProvider.test.ts
packages/salesforcedx-vscode-lwc/test/vscode-integration/testSupport/testIndexer/lwcTestIndexer.test.ts
packages/salesforcedx-vscode-lwc/test/vscode-integration/testSupport/testRunner/index.test.ts
packages/salesforcedx-vscode-lwc/test/vscode-integration/testSupport/testRunner/taskService.test.ts
packages/salesforcedx-vscode-lwc/test/vscode-integration/testSupport/testRunner/testWatcher.test.ts
packages/system-tests/assets/lwc-recipes/force-app/main/default/lwc/jsconfig.json

Upgrade the Sinon types for lwc and lightning
I only did the lightning packages as doing them all turned into a very long process. There's about 1200 that need converting and some require code changes. Overall, its probably 200+ files and 2000+ code line changes to make happen. 
So we should probably do it incrementally by package. 
@W-7247400@
@types/sinon was ^2.3.2
Now @types/sinon is ^7.5.1 which is the latest.

Sinon types lwc

---

scripts/create-release-branch.js
scripts/download-vsix-from-circleci.js
scripts/publish-circleci.js
scripts/validation-utils.js

Follow-up items for the publishing script based on last week's release.
1. Add pre-validation step for checking environment variables.
1. Add install steps for required tools.
1. Add additional check for tool installations (Jason was having issues after switching node versions)
@W-7250936@

Update publish script pre-requisite logic & validation phase

---

scripts/cleanup-release-branch-after-release-issues.js

Resets the environment if a failed there was a failed publish script run
@W-7250960@

Scripts to cleanup after a failed publish run

---

docs/_articles/en/user-guide/prettier.md

-- Add Dang Mai as the contributor of Prettier Apex plugin
-- Edit existing content
W-7265081

Update contributor info for Prettier Apex plugin

---

scripts/publish-circleci.js

Fix undefined `nextVersion` variable on publish script
@W-7250936@

Quick fix to publish script

---

docs/_articles/ja/user-guide/detect-conflicts.md

Fixes broken Conflict Detection docs for Japanese language
@W-7270851@

Add detect conflicts to Japanese articles

---

docs/_articles/ja/user-guide/detect-conflicts.md

Porting PR #2040 to the develop branch
@W-7270851@

Add detect conflicts to Japanese articles (#2040)

---

.github/workflows/create-release-branch.yml
contributing/publishing.md
scripts/create-release-branch.js

Adds a GitHub action for running the release branch creation script. Triggered with a [repository_dispatch](https://developer.github.com/v3/repos/#create-a-repository-dispatch-event)

Create release branch action

---

scripts/cleanup-release-branch-after-release-issues.js
scripts/create-release-branch.js
scripts/download-vscode.js
scripts/download-vsix-from-circleci.js
scripts/logger-util.js
scripts/publish-circleci.js
scripts/publish-vsix.js
scripts/validation-utils.js

Making some art out of the publishing logs. Wrapped these logging changes in a logger-util class in case someone ever needs to turn off the colors or we want to change them going forward.
@W-7250940@

Publishing Logging Updates

---

packages/salesforcedx-utils-vscode/src/cli/index.ts
packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-core/package.nls.json
packages/salesforcedx-vscode-core/src/commands/forceSourceDeploySourcePath.ts
packages/salesforcedx-vscode-core/src/constants.ts
packages/salesforcedx-vscode-core/src/deploys/deployUtil.ts
packages/salesforcedx-vscode-core/src/deploys/index.ts
packages/salesforcedx-vscode-core/src/deploys/toolingDeploy.ts
packages/salesforcedx-vscode-core/src/deploys/toolingDeployResultParser.ts
packages/salesforcedx-vscode-core/src/messages/i18n.ts
packages/salesforcedx-vscode-core/src/settings/index.ts
packages/salesforcedx-vscode-core/src/settings/sfdxCoreSettings.ts
packages/salesforcedx-vscode-core/src/util/authInfo.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceAuthDevHub.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/deploys/toolingDeploy.test.ts
packages/salesforcedx-vscode-core/test/vscode-integration/deploys/toolingDeployParser.test.ts

Ports PR #2052 to the release branch for 48.6.0
@W-6531270@

Single Apex Class file deploys through Tooling API (#2052)

---

scripts/cleanup-release-branch-after-release-issues.js
scripts/create-release-branch.js
scripts/download-vscode.js
scripts/download-vsix-from-circleci.js
scripts/logger-util.js
scripts/publish-circleci.js
scripts/publish-vsix.js
scripts/validation-utils.js

Port logging changes to release branch from #2063.

Publishing Logging Updates (#2063)

---

scripts/change-log-generator.js

I ran into some issues executing the change log script and had to make a few changes to it. This PR updates the file permissions to be able to execute the script. Adds the nodejs shebang and some configuration for it to stop executing if an error is thrown.
@W-7323334@

Update changelog script

---

packages/salesforcedx-vscode/CHANGELOG.md

Update changelog for release v48.6.0

---

docs/_articles/en/user-guide/perf-enhancements.md
docs/_articles/ja/user-guide/perf-enhancements.md
docs/_data/sidebar.yml

Documentation on how to enable the deploy/retrieve performance enhancements.
@W-6531270@

Documentation on performance enhancement changes

---

docs/_articles/en/user-guide/perf-enhancements.md
docs/_articles/ja/user-guide/perf-enhancements.md
packages/salesforcedx-vscode/CHANGELOG.md

Minor fixes to changelog and title of perf enhancements doc.

Minor tweaks after release

---

docs/_articles/en/lwc/linting.md
docs/_data/sidebar.yml

Adds new linting topic to LWC docs on VS Code site.

Add linting topic to LWC parent.

---

packages/salesforcedx-sobjects-faux-generator/package.json
packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-core/package.json

Need to update this to match with the version we'll use in the Deploy/Retrieve library or we'll start running into issues with different types, objects, etc.
@W-7337653@

Update to latest version of @salesforce/core

---

packages/salesforcedx-apex-debugger/src/adapter/apexDebug.ts
packages/salesforcedx-apex-debugger/src/messages/i18n.ts
packages/salesforcedx-apex-debugger/test/unit/adapter/apexDebug.test.ts

This PR ports the interactive debugger changes to the release branch.

Port  #2078 to release branch

---

packages/salesforcedx-vscode-lightning/package.json

Upgrades to the latest version of the Lightning and LWC Language Servers
@W-7350920
Older version of the LSP
New fancy features!

Upgrade to latest LSP extensions

---

packages/salesforcedx-vscode/CHANGELOG.md

v48.7.0 Changelog

---

docs/_articles/ja/lwc/linting.md

Adds missing article to LWC topic in Japanese version of the site. Follow up to PR 2060.
@W-7355942@

Create missing article for lwc in japanese site

---

docs/_articles/ja/lwc/linting.md

Porting PR #2091 to develop branch
@W-7355942@

Create missing article for lwc in japanese site (#2091)

---

.vscode/launch.json
packages/salesforcedx-vscode-lwc/package.json
packages/salesforcedx-vscode-lwc/test/vscode-integration/activation/activationMode.test.ts
packages/salesforcedx-vscode-lwc/test/vscode-integration/hover.test.ts

Upgrades LWC extension to the latest LSP's for LWC and Lightning
@W-7350920@
Using 2.2.17
Using 2.3.6

Upgrade the LWC extension too

---

packages/salesforcedx-vscode/CHANGELOG.md

Change log for 48.8.0

---

docs/_articles/en/user-guide/prettier.md

Updates the requirements for setting up Apex Prettier.
#2079, @W-7391215@

Update apex prettier setup requirements

---

packages/salesforcedx-vscode/CHANGELOG.md

Changelog for 48.9.0

---

packages/salesforcedx-vscode/CHANGELOG.md

Change log for v48.10.0

---

docs/_articles/en/user-guide/perf-enhancements.md
docs/_articles/ja/user-guide/perf-enhancements.md

Update the perf enhancements doc with the list of supported metadata types.
@W-7417056@

Update performance enhancements docs

---

README.md

- Remove the AppVeyor build badge
@W-7431981@

Removed AppVeyor badge

---

docs/_articles/en/apex/testing.md

Correct the broken link for Java Setup in Apex Testing.
W-7432905
#2108, @W-7432905@

Update Java Setup link

---

packages/salesforcedx-vscode/CHANGELOG.md

Changelog updated for release v48.13.0

Changelog updates for release v48.13.0

---

packages/salesforcedx-sobjects-faux-generator/package.json
packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-core/package.json

Update to latest versions of @salesforce/core & @salesforce/source-deploy-retrieve
@W-7519994@

Update to latest versions of @salesforce/core & @salesforce/source-deploy-retrieve

---

.circleci/config.yml

Updates CircleCI config to release from master branch.
@W-7504646@

Release configuration

---

packages/salesforcedx-vscode/CHANGELOG.md

Changelog updated for release v48.14.0

Initial changelog

---

.circleci/config.yml

Disable the circleci gus management steps since the integration user is blocked.

Disable gus management step

---

.circleci/config.yml

Update install step on publish job

Update npm install for publish job

---

.circleci/config.yml

More changes to the install phase.

Modify install

---

.circleci/config.yml

Fix compile issues in publish job. Add skip option for change management creation.

Fix compile issues in publish job

---

packages/salesforcedx-sobjects-faux-generator/package.json
packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-core/package.json

Update to the latest versions of `@salesforce/core` and `source-deploy-retrieve`
@W-7541165@

Update to @salesforce/core 2.4.1 & latest version of deploy-retrieve @W-7541165@

---

packages/salesforcedx-vscode-lwc/src/commands/forceLightningLwcStart.ts
packages/salesforcedx-vscode-lwc/src/messages/i18n.ts
packages/salesforcedx-vscode-lwc/test/vscode-integration/commands/forceLightningLwcStart.test.ts

Provide a better error message when scratch org expires
@W-7485707@

Local Dev Scratch Org expire message @W-7485707@

---

packages/salesforcedx-vscode/CHANGELOG.md

Changelog updated for release v48.14.0

Change log for v48.15.0

---

.github/CODEOWNERS
docs/package.json
lerna.json
packages/salesforcedx-apex-debugger/package.json
packages/salesforcedx-apex-replay-debugger/package.json
packages/salesforcedx-sobjects-faux-generator/package.json
packages/salesforcedx-test-utils-vscode/package.json
packages/salesforcedx-utils-vscode/package.json
packages/salesforcedx-visualforce-language-server/package.json
packages/salesforcedx-visualforce-markup-language-server/package.json
packages/salesforcedx-vscode-apex-debugger/package.json
packages/salesforcedx-vscode-apex-replay-debugger/package.json
packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lwc/package.json
packages/salesforcedx-vscode-lwc/src/commands/forceLightningLwcStart.ts
packages/salesforcedx-vscode-lwc/src/messages/i18n.ts
packages/salesforcedx-vscode-lwc/test/vscode-integration/commands/forceLightningLwcStart.test.ts
packages/salesforcedx-vscode-visualforce/package.json
packages/salesforcedx-vscode/CHANGELOG.md
packages/salesforcedx-vscode/package.json
packages/system-tests/package.json

Release v48.15.0

---

contributing/telemetry.md
docs/package.json
lerna.json
packages/salesforcedx-apex-debugger/package.json
packages/salesforcedx-apex-replay-debugger/package.json
packages/salesforcedx-sobjects-faux-generator/package.json
packages/salesforcedx-test-utils-vscode/package.json
packages/salesforcedx-utils-vscode/package.json
packages/salesforcedx-visualforce-language-server/package.json
packages/salesforcedx-visualforce-markup-language-server/package.json
packages/salesforcedx-vscode-apex-debugger/package.json
packages/salesforcedx-vscode-apex-replay-debugger/package.json
packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-core/src/util/cliConfiguration.ts
packages/salesforcedx-vscode-core/test/vscode-integration/util/cliConfiguration.test.ts
packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lwc/package.json
packages/salesforcedx-vscode-visualforce/package.json
packages/salesforcedx-vscode/package.json
packages/system-tests/package.json

Release 48.17.0 that addresses an issue with extension activating when a user is in an old CLI version.

Merge 48.17.0

---

.git2gus/config.json
docs/package.json
lerna.json
packages/salesforcedx-apex-debugger/package.json
packages/salesforcedx-apex-replay-debugger/package.json
packages/salesforcedx-sobjects-faux-generator/package.json
packages/salesforcedx-test-utils-vscode/package.json
packages/salesforcedx-utils-vscode/package.json
packages/salesforcedx-utils-vscode/src/cli/commandOutput.ts
packages/salesforcedx-visualforce-language-server/package.json
packages/salesforcedx-visualforce-markup-language-server/package.json
packages/salesforcedx-vscode-apex-debugger/package.json
packages/salesforcedx-vscode-apex-replay-debugger/package.json
packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lwc/package.json
packages/salesforcedx-vscode-lwc/src/commands/forceLightningLwcPreview.ts
packages/salesforcedx-vscode-lwc/test/vscode-integration/commands/forceLightningLwcPreview.test.ts
packages/salesforcedx-vscode-visualforce/package.json
packages/salesforcedx-vscode/CHANGELOG.md
packages/salesforcedx-vscode/package.json
packages/system-tests/package.json

Merge 48.18.0

---

packages/salesforcedx-vscode/CHANGELOG.md

Changelog for version 48.19.0

---

.circleci/config.yml

Fixes cron job that creates the weekly release branch.
@W-7672593@

Fix release branch creation automation

---

packages/salesforcedx-utils-vscode/src/helpers/index.ts
packages/salesforcedx-utils-vscode/src/helpers/validations.ts
packages/salesforcedx-utils-vscode/test/unit/helpers/validations.test.ts
packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-core/package.nls.json
packages/salesforcedx-vscode-core/src/commands/forcePackageInstall.ts
packages/salesforcedx-vscode-core/src/commands/index.ts
packages/salesforcedx-vscode-core/src/constants.ts
packages/salesforcedx-vscode-core/src/index.ts
packages/salesforcedx-vscode-core/src/messages/i18n.ja.ts
packages/salesforcedx-vscode-core/src/messages/i18n.ts
packages/salesforcedx-vscode-core/test/vscode-integration/commands/forcePackageInstall.test.ts

Port PR #2236 to enable tests runs. It also adds package id validation to the command.
@W-7660006@

2140 package install

---

docs/_articles/en/user-guide/vscode-commands.md
packages/salesforcedx-test-utils-vscode/package.json
packages/salesforcedx-utils-vscode/package.json
packages/salesforcedx-vscode-core/src/messages/i18n.ts
packages/salesforcedx-vscode/CHANGELOG.md

Porting a doc PR from last release

Documentation review

---

docs/_articles/en/user-guide/perf-enhancements.md
docs/_articles/ja/user-guide/perf-enhancements.md

Update list of supported metadata for performance enhancements

Update supported metadata list

---

SHA256.md
docs/_articles/en/user-guide/perf-enhancements.md
docs/_articles/ja/user-guide/perf-enhancements.md
docs/package.json
lerna.json
packages/salesforcedx-apex-debugger/package.json
packages/salesforcedx-apex-replay-debugger/package.json
packages/salesforcedx-sobjects-faux-generator/package.json
packages/salesforcedx-test-utils-vscode/package.json
packages/salesforcedx-utils-vscode/package.json
packages/salesforcedx-visualforce-language-server/package.json
packages/salesforcedx-visualforce-markup-language-server/package.json
packages/salesforcedx-vscode-apex-debugger/package.json
packages/salesforcedx-vscode-apex-replay-debugger/package.json
packages/salesforcedx-vscode-apex/package.json
packages/salesforcedx-vscode-core/package.json
packages/salesforcedx-vscode-lightning/package.json
packages/salesforcedx-vscode-lwc/package.json
packages/salesforcedx-vscode-visualforce/package.json
packages/salesforcedx-vscode/CHANGELOG.md
packages/salesforcedx-vscode/package.json
packages/system-tests/package.json

Ports changes that were part of the release, but not develop.

Port changes from release v48.21.0 to develop

---

.circleci/config.yml

Streamlines the .circleci/config.yml to use our orb.
Part of internal safety checks for releasing.

Use the change-case-management-orb
