forcedotcom/salesforcedx-vscode

packages/salesforcedx-vscode-lwc/src/service/devServerService.ts, packages/salesforcedx-vscode-lwc/test/unit/service/devServerService.test.ts, packages/salesforcedx-vscode-lwc/test/vscode-integration/commands/forceLightningLwcStart.test.ts
Remove the ansi characters from the base url in local dev server.
#2284 , @W-7737619@
=> Clean up local dev base url

packages/salesforcedx-vscode-lightning/test/vscode-integration/hover.test.ts, packages/salesforcedx-vscode-lwc/test/vscode-integration/hover.test.ts
Fix integration test flappers in Aura/LWC
@W-7736674@
=> Fix integration test flappers in Aura/LWC

docs/package.json, lerna.json, packages/salesforcedx-apex-debugger/package.json, packages/salesforcedx-apex-replay-debugger/package.json, packages/salesforcedx-sobjects-faux-generator/package.json, packages/salesforcedx-test-utils-vscode/package.json, packages/salesforcedx-utils-vscode/package.json, packages/salesforcedx-visualforce-language-server/package.json, packages/salesforcedx-visualforce-markup-language-server/package.json, packages/salesforcedx-vscode-apex-debugger/package.json, packages/salesforcedx-vscode-apex-replay-debugger/package.json, packages/salesforcedx-vscode-apex/package.json, packages/salesforcedx-vscode-core/package.json, packages/salesforcedx-vscode-lightning/package.json, packages/salesforcedx-vscode-lwc/package.json, packages/salesforcedx-vscode-visualforce/package.json, packages/salesforcedx-vscode/package.json, packages/system-tests/package.json
Update to 48.22.0 so this week's release branch gets created as 48.23.0
=> Update package versions to 48.22.0

packages/salesforcedx-vscode-apex/snippets/apex.json
Porting PR #2262 to rebase and run all tests before merging it. It adds new code snippets for Apex
* Improve for loop snippets by adding type
- Separated the type from the variable.
- In the case of the soql loop the type will default to SObject.
* Change default loop value to condition
Default condition value is now 'condition' instead of 'true'.
This should be more descriptive and will prevent the edge case
of the default not being chnaged and an infinte loop occuring.
* Add more if statement snippets
- ifelse, ifnull, ifnotnull and ter (ternary).
* Add snippets for various system.assert cases
- System.assert(false, message);
- System.assertEqual(expected, actual);
- System.assertNotEqual(expected, actual);
- System.assertEqual(null, actual):
- System.assertNotEqual(null, actual):
* Add …
=> Add new Apex code snippets

packages/salesforcedx-vscode-apex/snippets/apex.json
* Improve for loop snippets
* Change default loop value to condition
* Add more if statement snippets
* Add snippets for various system.assert cases
* Add New constructor, New Object, Field, New Method, New Static Method.
* Add for loop snippet to iterate over a map
* Add snippet to create a map from a list of records
* Add snippet to create a set of ids from a list of records
Ports the original PR into release/v48.23.0 branch
#2261, @W-7709851@
=> Add new Apex code snippets (#2301)

packages/salesforcedx-sobjects-faux-generator/package.json, packages/salesforcedx-vscode-apex/package.json, packages/salesforcedx-vscode-core/package.json, packages/salesforcedx-vscode-core/src/commands/forceSourceDeploySourcePath.ts, packages/salesforcedx-vscode-core/src/commands/forceSourceRetrieveSourcePath.ts, packages/salesforcedx-vscode-core/src/commands/util/betaDeployRetrieve.ts, packages/salesforcedx-vscode-core/src/commands/util/libraryCommandlet.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/util/betaDeployRetrieve.test.ts
Adds telemetry for the number and types of components being deployed and retrieved.
@W-7759892@
=> Telemetry for metadata type/component count for beta deploy/retrieve @W-7759892@

packages/salesforcedx-vscode/CHANGELOG.md
Adds the changelog for v48.23.0
=> Changelog for v48.23.0

.circleci/config.yml
Unblock case management plugin not getting installed
=> Update case management setup

package.json
Port - lock Snyk version 1.358.0 (#2313)
=> Port - lock Snyk version 1.358.0 (#2313)

.circleci/config.yml, packages/salesforcedx-sobjects-faux-generator/package.json, packages/salesforcedx-vscode-apex/package.json, packages/salesforcedx-vscode-core/package.json
Pin @salesforce/kit since newer version causing compile issues until we update typescript.
=> Pin @salesforce/kit

.circleci/config.yml, SHA256.md, packages/salesforcedx-sobjects-faux-generator/package.json, packages/salesforcedx-vscode-apex/package.json, packages/salesforcedx-vscode-core/package.json, packages/salesforcedx-vscode/CHANGELOG.md
Port 48.23.0 changes back to develop
=> Port 48.23.0 changes back to develop

docs/_articles/en/apex/interactive-debugger.md
Update whitelist to allowlist per [Inclusive Content Initiative](https://salesforce.quip.com/fyWbAlOLjQap#MdLACAT8nll) 
=> Update whitelist to allowlist

packages/salesforcedx-vscode-core/package.json, packages/salesforcedx-vscode-core/src/commands/forceSourceDeploySourcePath.ts, packages/salesforcedx-vscode-core/src/commands/forceSourceRetrieveSourcePath.ts, packages/salesforcedx-vscode-core/src/commands/util/libraryCommandlet.ts, packages/salesforcedx-vscode-core/src/commands/util/libraryDeployResultParser.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceSourceDeploySourcePath.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceSourceRetrieveSourcePath.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/util/libraryDeployResultParser.test.ts
Add support for namespaces on deploy/retrieve operations for the beta perf enhancements. This also fixes an error with parsing results in specific scenarios.
#2188, #2281 , @W-7793005@
=> @W-7793005@ Support namespaces on beta deploy/retrieve

packages/salesforcedx-vscode-core/package.json, packages/salesforcedx-vscode-core/src/commands/forceSourceDeploySourcePath.ts, packages/salesforcedx-vscode-core/src/commands/forceSourceRetrieveSourcePath.ts, packages/salesforcedx-vscode-core/src/commands/util/libraryCommandlet.ts, packages/salesforcedx-vscode-core/src/commands/util/libraryDeployResultParser.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceSourceDeploySourcePath.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceSourceRetrieveSourcePath.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/util/libraryDeployResultParser.test.ts
Porting PR #2330 to release 48.24.0
@W-7793005@
=> Support namespaces on beta deploy/retrieve (#2330)

docs/_articles/en/getting-started/recommended-extensions.md
This PR updates the documentation pointing out that prettier-plugin-apex is now available. Given now it already passed v1.0.
#2328
Documentation, no functionality changed.
=> #2328: update to prettier-plugin-apex

.circleci/config.yml, .vscode/tasks.json, scripts/create-release-branch-workflow.sh, scripts/publish-workflow.sh
1. Changes YAML anchors into commands. Eventually we will want to move some of these commands into an orb for easy reuse across repos.
1. Adds a new executor to replace the "defaults" YAML anchor.
1. Adds Slack integration for visibility into job status, errors, and successes for publish and release branch creation workflows.
1. Changes the release strategy from publishing when a merge happens into master to publishing via a pipeline strategy using parameters and API calls.
1. On publish and release branch creation, adds a "hold" job that requires approval in CircleCi. This helps prevent any accidental or malicious API calls.
1. Adds tasks for easy API calls in expected formats.
1. Adds a workflow for creating the release branch via an API call. This will allow us to easily run through …
=> CircleCi Config Improvements @W-7721208@

docs/package.json, lerna.json, packages/salesforcedx-apex-debugger/package.json, packages/salesforcedx-apex-replay-debugger/package.json, packages/salesforcedx-sobjects-faux-generator/package.json, packages/salesforcedx-test-utils-vscode/package.json, packages/salesforcedx-utils-vscode/package.json, packages/salesforcedx-visualforce-language-server/package.json, packages/salesforcedx-visualforce-markup-language-server/package.json, packages/salesforcedx-vscode-apex-debugger/package.json, packages/salesforcedx-vscode-apex-replay-debugger/package.json, packages/salesforcedx-vscode-apex/package.json, packages/salesforcedx-vscode-core/package.json, packages/salesforcedx-vscode-lightning/package.json, packages/salesforcedx-vscode-lwc/package.json, packages/salesforcedx-vscode-visualforce/package.json, packages/salesforcedx-vscode/package.json, packages/system-tests/package.json
Release task to update version of packages to 49.x.x
=> Update version to 49.x.x

.circleci/config.yml
Release task. Updating the github deploy key value to the latest generated key.
=> Update github key value

packages/salesforcedx-vscode-lwc/src/testSupport/commands/forceLwcTestDebugAction.ts, packages/salesforcedx-vscode-lwc/src/testSupport/workspace/getCliArgsFromJestArgs.ts, packages/salesforcedx-vscode-lwc/test/vscode-integration/testSupport/commands/forceLwcTestDebugAction.test.ts, packages/salesforcedx-vscode-lwc/test/vscode-integration/testSupport/mocks/index.ts, packages/salesforcedx-vscode-lwc/test/vscode-integration/testSupport/mocks/vscodeConfiguration.ts, packages/salesforcedx-vscode-lwc/test/vscode-integration/testSupport/workspace/getCliArgsFromJestArgs.test.ts
Port Xyc/fix preview javascript debugger #2345 to release/v49.1.0
=> Port Xyc/fix preview javascript debugger to release/v49.1.0

packages/salesforcedx-vscode-core/package.json, packages/salesforcedx-vscode-core/package.nls.json, packages/salesforcedx-vscode-core/src/commands/forceApexExecute.ts, packages/salesforcedx-vscode-core/src/constants.ts, packages/salesforcedx-vscode-core/src/settings/sfdxCoreSettings.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceApexExecute.test.ts
This PR adds a flag so users can revert back to the original CLI implementation of Apex commands if needed
@W-7826660@
=> Added a flag to control usage of Apex library

packages/salesforcedx-vscode-core/package.json, packages/salesforcedx-vscode-core/package.nls.json, packages/salesforcedx-vscode-core/src/commands/forceApexExecute.ts, packages/salesforcedx-vscode-core/src/commands/forceSourceDeploySourcePath.ts, packages/salesforcedx-vscode-core/src/commands/forceSourceRetrieveSourcePath.ts, packages/salesforcedx-vscode-core/src/commands/util/apexLibraryExecutor.ts, packages/salesforcedx-vscode-core/src/commands/util/apexLibraryResultFormatter.ts, packages/salesforcedx-vscode-core/src/commands/util/deployRetrieveLibraryExecutor.ts, packages/salesforcedx-vscode-core/src/commands/util/index.ts, packages/salesforcedx-vscode-core/src/commands/util/libraryCommandlet.ts, packages/salesforcedx-vscode-core/src/constants.ts, packages/salesforcedx-vscode-core/src/diagnostics/diagnostics.ts, packages/salesforcedx-vscode-core/src/diagnostics/index.ts, packages/salesforcedx-vscode-core/src/messages/i18n.ts, packages/salesforcedx-vscode-core/src/settings/sfdxCoreSettings.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceApexExecute.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/util/apexLibraryExecutor.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/util/apexLibraryResultFormatter.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/util/deployRetrieveLibraryExecutor.test.ts
This PR ports [#2291 ](https://github.com/forcedotcom/salesforcedx-vscode/commit/e2142ddb70fe4b3c273679f7b60cffd8acd62339) and [#2349 ](https://github.com/forcedotcom/salesforcedx-vscode/commit/cae635d478fec927686581698ab6ebebc069b867) to the release branch
=> Port Apex Execute changes to release/v49.1.0

scripts/create-release-branch.js
Update create release branch script so the commit for updating the release version is created against the develop branch before creating the release branch.
=> Update release branch script to create version update commit in develop

.circleci/config.yml, package.json, packages/salesforcedx-visualforce-markup-language-server/tsconfig.json
Update snyk version
@W-7854057@
=> Update snyk to 1.364.0

packages/salesforcedx-vscode-core/src/commands/forceApexExecute.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceApexExecute.test.ts
Ports #2370 to release branch
#2369
=> Port Exec Anonymous Fix to Release 49.2.0

packages/salesforcedx-vscode/CHANGELOG.md
=> Changelog 49.2.0

docs/_articles/en/user-guide/remote-development.md, docs/_data/sidebar.yml
Adds docs for using VS Code remote dev with WSL2.
=> Added docs for remote dev using WSL2

packages/salesforcedx-vscode/CHANGELOG.md
=> Changelog updates for v49.4.0

docs/Gemfile.lock, docs/_articles/en/user-guide/remote-development.md, docs/_data/sidebar.yml, docs/package.json, lerna.json, packages/salesforcedx-apex-debugger/package.json, packages/salesforcedx-apex-replay-debugger/package.json, packages/salesforcedx-sobjects-faux-generator/package.json, packages/salesforcedx-test-utils-vscode/package.json, packages/salesforcedx-utils-vscode/package.json, packages/salesforcedx-visualforce-language-server/package.json, packages/salesforcedx-visualforce-markup-language-server/package.json, packages/salesforcedx-vscode-apex-debugger/package.json, packages/salesforcedx-vscode-apex-replay-debugger/package.json, packages/salesforcedx-vscode-apex/package.json, packages/salesforcedx-vscode-apex/snippets/apex.json, packages/salesforcedx-vscode-apex/src/commands/forceGenerateFauxClasses.ts, packages/salesforcedx-vscode-apex/src/commands/index.ts, packages/salesforcedx-vscode-apex/test/vscode-integration/commands/forceGenerateFauxClasses.test.ts, packages/salesforcedx-vscode-core/package.json, packages/salesforcedx-vscode-lightning/package.json, packages/salesforcedx-vscode-lwc/package.json, packages/salesforcedx-vscode-soql/package.json, packages/salesforcedx-vscode-soql/src/client/client.ts, packages/salesforcedx-vscode-soql/src/index.ts, packages/salesforcedx-vscode-visualforce/package.json, packages/salesforcedx-vscode/CHANGELOG.md, packages/salesforcedx-vscode/package.json, packages/system-tests/package.json
Port commits from release branch v49.5.0 to master.
=> Port changes for release v49.5.0

packages/salesforcedx-vscode/README.md
Update the VS Code Extension pack marketplace listing to include the SLDS Validator extension
@W-7972062@
=> Update to include SLDS Validator

packages/salesforcedx-vscode-lightning/package.json, packages/salesforcedx-vscode-lightning/test/vscode-integration/intellisense.test.ts, packages/salesforcedx-vscode-lwc/package.json, packages/salesforcedx-vscode-lwc/test/vscode-integration/hover.test.ts, packages/salesforcedx-vscode-lwc/test/vscode-integration/jsconfig.test.ts, packages/salesforcedx-vscode-lwc/test/vscode-integration/navigation.test.ts, packages/salesforcedx-vscode-soql/src/client/client.ts, packages/salesforcedx-vscode-soql/src/editor/soqlEditorProvider.ts, packages/salesforcedx-vscode-soql/src/index.ts
Use the latest versions of aura and lwc language servers
@W-7982297@
=> Update to latest version of lwc and aura lang servers

packages/salesforcedx-vscode/CHANGELOG.md
Ports changelog updates for 49.6.0
=> Port Changelog Updates for 49.6.0

packages/salesforcedx-vscode/CHANGELOG.md
Ports changelog updates from 49.6.0
=> Port Changelog Updates from v49.6.0

.circleci/config.yml, .gitignore, CONTRIBUTING.md, contributing/developing.md, contributing/publishing.md, scripts/publish-workflow.sh
1. Update circleci configs to use main instead of master.
2. Update publishing script to use main.
3. Update some docs to use main instead of master.
@W-8017900@
=> Update Publishing to use Main & Update Docs

packages/salesforcedx-vscode/CHANGELOG.md
=> chore: fix changelog

CONTRIBUTING.md
Addresses feedback from PR #2433 around documentation updates.
@W-8001201@
=> Documentation Updates for Contributing

package.json, packages/salesforcedx-sobjects-faux-generator/src/generator/fauxClassGenerator.ts, packages/salesforcedx-sobjects-faux-generator/src/index.ts, packages/salesforcedx-sobjects-faux-generator/test/integration/fauxGenerate.test.ts, packages/salesforcedx-vscode-apex/src/commands/forceGenerateFauxClasses.ts, packages/salesforcedx-vscode-apex/test/vscode-integration/commands/forceGenerateFauxClasses.test.ts
=> fix: create minimal sobject refresh on activation

docs/_articles/en/getting-started/recommended-extensions.md
Updates the recommended extensions doc to link to the marketplace.
=> Adds Links to VS Code Marketplace Extensions

packages/salesforcedx-vscode/CHANGELOG.md
=> chore: changelog 49.8.0

packages/salesforcedx-vscode/CHANGELOG.md
Adds the scaffolding changes to the 49.8.0 changelog
=> chore: changelog 49.8.0 updates

packages/salesforcedx-vscode-lightning/package.json, packages/salesforcedx-vscode-lwc/package.json
Update to the latest LWC and Aura language server
@W-8057966@
=> chore: update to latest lang server version

packages/salesforcedx-vscode-lightning/package.json, packages/salesforcedx-vscode-lwc/package.json
Port PR #2495 to release 49.9.0
@W-8057966@
=> chore: update to latest lwc/aura lang server version (#2495)

packages/salesforcedx-vscode-core/package.json
Adding function start command to command palette; Remove function invoke command from command palette.
@W-7958829@
=> fix: function command palette changes

packages/salesforcedx-vscode-core/src/settings/sfdxCoreSettings.ts
Turns off functions by default
@W-7958774@
Functions turned on by default
Functions turned off by default
=> fix: Turning off functions by default @W-7958774@

packages/salesforcedx-vscode-core/src/messages/i18n.ts, packages/salesforcedx-vscode-core/src/orgPicker/orgList.ts, packages/salesforcedx-vscode-core/test/vscode-integration/orgPicker/orgList.test.ts
Original PR #2485 
#2484, @W-8046510@
=> Expired orgs in orgpicker

packages/salesforcedx-vscode/CHANGELOG.md
=> chore: changelog 49.9.0

packages/salesforcedx-vscode-lwc/test/vscode-integration/intellisense.test.ts
Skip unreliable LWC lang server tests
@W-8068290@
=> fix: skip unreliable tests

packages/salesforcedx-vscode-lwc/test/vscode-integration/intellisense.test.ts
Ports skipped tests to main
@W-8068290@
=> fix: skip unreliable tests (#2508)

packages/salesforcedx-vscode/CHANGELOG.md
=> chore: changelog v49.10.0

packages/salesforcedx-vscode-core/package.json, packages/salesforcedx-vscode-core/src/channels/channelService.ts, packages/salesforcedx-vscode-core/src/commands/functions/forceFunctionStart.ts, packages/salesforcedx-vscode-core/src/commands/functions/forceFunctionStop.ts, packages/salesforcedx-vscode-core/src/commands/functions/functionService.ts, packages/salesforcedx-vscode-core/src/messages/i18n.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/functions/forceFunctionInvokeCodeLensProvider.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/functions/forceFunctionStart.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/functions/forceFunctionStop.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/functions/mockExecution.ts, packages/system-tests/assets/sfdx-simple/functions/demoFunction/package.json, packages/system-tests/assets/sfdx-simple/functions/demoJavaScriptFunction/.eslintrc, packages/system-tests/assets/sfdx-simple/functions/demoJavaScriptFunction/README.md, packages/system-tests/assets/sfdx-simple/functions/demoJavaScriptFunction/function.toml, packages/system-tests/assets/sfdx-simple/functions/demoJavaScriptFunction/index.js, packages/system-tests/assets/sfdx-simple/functions/demoJavaScriptFunction/package.json, packages/system-tests/assets/sfdx-simple/functions/demoJavaScriptFunction/test/unitTests.js
Start / Stop functions locally
@W-7958829@
=> Function start/stop commands

docs/_articles/en/index.md
Refreshed videos to current resources from last DF, TDX and a few others.  Changed the section name to just "Videos" since it spans more than DF
@W-8092974@
=> Refreshing the Videos

packages/salesforcedx-vscode-core/package.json, packages/salesforcedx-vscode-core/package.nls.json, packages/salesforcedx-vscode-core/src/commands/forceOrgDelete.ts, packages/salesforcedx-vscode-core/src/commands/forceOrgList.ts, packages/salesforcedx-vscode-core/src/commands/index.ts, packages/salesforcedx-vscode-core/src/commands/util/index.ts, packages/salesforcedx-vscode-core/src/commands/util/parameterGatherers.ts, packages/salesforcedx-vscode-core/src/index.ts, packages/salesforcedx-vscode-core/src/messages/i18n.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceOrgDelete.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceOrgList.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/util/parameterGatherers.test.ts
Adds a few label updates to PR #2505 
#945, @W-8065926@
=> Delete clean org commands

packages/salesforcedx-vscode-apex/package.json
Updates the apex-tmlanguage dependency for changes with the [Safe Navigation Operator](https://releasenotes.docs.salesforce.com/en-us/winter21/release-notes/rn_apex_SafeNavigationOperator.htm). This change includes the following updates for Apex syntax highlighting:
- Switch statements with the safe navigation operator
- Member Access token changes with the safe navigation operator
- SOQL Binding with the safe navigation operator (note: currently not supported. The Safe Navigation Operator will be supported with SOQL bindings at a later date)
@W-7963330@
=> fix: update apex syntax highlighting for safe navigation operator (@W-7963330)

packages/salesforcedx-vscode/CHANGELOG.md
Change log updates for 49.11.0.
=> chore: changelog updates for v49.11.0

packages/salesforcedx-vscode-core/test/vscode-integration/util/authInfo.test.ts, packages/salesforcedx-vscode-soql/package.json
Contribute textmate grammar on SOQL extension for SOQL language files
@W-7736409@
=> feat(soql): add textmate grammar for soql files

packages/salesforcedx-vscode-core/package.json, packages/salesforcedx-vscode-core/package.nls.json
Adds a feature flag for functions support
@W-7958729@
N/A
=> feat: adding functions feature flag @W-7958729@

docs/_articles/en/user-guide/prettier.md
Remove period after npm install command.
Merge PR for contribution by @thejohncotton in #2559 to run build checks.
=> Merge PR for #2559 (Update prettier.md)

packages/salesforcedx-vscode/CHANGELOG.md
This PR adds the changelog for release v49.12.0
=> chore: Add changelog for release v49.12.0

packages/salesforcedx-vscode/CHANGELOG.md
Adding #2586 to 49.12.0 changelog
=> docs(changelog): add prettier doc update to 49.12.0 changelog

docs/_articles/en/index.md
Added video that illustrates how to get started with LWC Local Dev
@W-8146332@
no lwc video
lwc video
=> Added an LWC local dev video

packages/salesforcedx-vscode-core/src/commands/forceProjectCreate.ts, packages/salesforcedx-vscode-core/src/commands/templates/libraryBaseTemplateCommand.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceProjectCreate.test.ts
Add telemetry to log the template that "SFDX: Create Project" uses.
@W-7962453@
=> chore: add additional telemetry for project create

packages/salesforcedx-vscode-lightning/package.json, packages/salesforcedx-vscode-lwc/package.json, packages/salesforcedx-vscode-lwc/test/vscode-integration/hover.test.ts, packages/salesforcedx-vscode-lwc/test/vscode-integration/intellisense.test.ts
Updating to the latest version of the aura and lwc language server which includes fixes for auto completes.
#2322 , #2584 , @W-8188221@
=> chore: update to latest lightning & lwc language servers

packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceSourceRetrieveMetadata/forceSourceRetrieveCmp.test.ts
Fix core integration test suite.
@LisandroFernandezSF @lcampos fyi, I noticed that core integration tests in circleci builds in `develop` branch are failing starting from https://app.circleci.com/pipelines/github/forcedotcom/salesforcedx-vscode/2476/workflows/562cc1d5-4d3f-4fbe-a7d8-03460f15c9ae/jobs/13506/steps. However CircleCI is not reporting the test failures. Instead it's showing fewer tests (335 tests, which should be 800+) passing.
@<Insert GUS WI>@
=> test: fix core integration tests

.circleci/config.yml
1. Adds RELEASE_VERSION logic for publish-workflow.
2. Fixes post-publish merge logic.
@W-8190683@
=> chore: fix circleci publish-workflow for merging and publishing (@W-8190683)

docs/_articles/en/getting-started/recommended-extensions.md
Added note on the Expanded pack of the extensions, added ESLint and removed Git-related ones to keep it focused on extensions that specific to SF dev
@W-8204552@
=> Recommended extensions Update to SF resources only

packages/salesforcedx-vscode-apex/test/vscode-integration/views/testOutlineNamespace.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceSourceRetrieveMetadata/describers.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/util/postconditionCheckers.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/util/authInfo.test.ts
Updates remaining tests to use createSandbox()
@W-8205877@
=> fix: update tests to use sinon createSandbox()

packages/salesforcedx-vscode-core/package.json
Update to the latest version of the templates library (v50.1.0)
@W-8211980@
=> chore: update to latest version of @salesforce/templates

.circleci/config.yml, scripts/create-release-branch.js, scripts/publish-circleci.js
Update scripts doing commits to follow the new commitizen format
@W-8212538@
=> fix: update scripts doing commits to follow commitizen format

packages/salesforcedx-vscode/CHANGELOG.md
=> docs(changelog): initial changelog

packages/salesforcedx-vscode-lightning/package.json, packages/salesforcedx-vscode-lwc/package.json
Updates to the newest version of LWC and Aura language servers which fixes issue #2575 
#2575 , @W-8222106@
=> chore: update lwc & aura language servers to v3.0.10

packages/salesforcedx-vscode-apex/snippets/apex.json
Improved @AuraEnabled snippet by adding try catch block which catch apex exception and throw AuraHandledException which is properly handled by LWC and show error to user instead of ugly internal server error message.
Inspired by https://developer.salesforce.com/blogs/2017/09/error-handling-best-practices-lightning-apex.html
@W-8235555@
In case of apex exception thrown it will show ugly internal error to user. User don't know what to do.
In case of apex exception thrown it is catch and re thrown as AuraHandledException which will show popup to user.
=> Improve @AuraEnabled for better error handling.

packages/salesforcedx-utils-vscode/package.json, packages/salesforcedx-utils-vscode/src/telemetry/cliConfiguration.ts, packages/salesforcedx-utils-vscode/src/telemetry/configUtil.ts, packages/salesforcedx-utils-vscode/src/telemetry/index.ts, packages/salesforcedx-utils-vscode/src/telemetry/telemetry.ts, packages/salesforcedx-utils-vscode/test/unit/telemetry/telemetry.dev.test.ts, packages/salesforcedx-utils-vscode/test/unit/telemetry/telemetry.test.ts, packages/salesforcedx-utils-vscode/webpack.config.js, packages/salesforcedx-vscode-lightning/package.json, packages/salesforcedx-vscode-lightning/src/index.ts, packages/salesforcedx-vscode-lwc/package.json, packages/salesforcedx-vscode-lwc/src/index.ts, packages/salesforcedx-vscode-lwc/test/vscode-integration/activation/MockContext.ts, packages/salesforcedx-vscode-lwc/test/vscode-integration/activation/activationMode.test.ts
Porting fix #2655 to release 50.2.0
@W-8252102@
=> fix: use webpack for salesforcedx-utils-vscode module (#2655)

packages/salesforcedx-vscode/CHANGELOG.md
=> chore: changelog for release 50.2.0

packages/salesforcedx-vscode-core/package.json, packages/salesforcedx-vscode-core/src/commands/util/retrieveParser.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/util/retrieveParser.test.ts
This PR updates the dependencies for `@salesforce/core`, SDR, and the Apex library
@W-8264757@
=> chore: Update @salesforce/core and library dependencies

packages/salesforcedx-vscode-core/src/commands/forceApexExecute.ts
Ports #2673 from the release branch to develop
=> Port #2673 to develop

packages/salesforcedx-vscode/CHANGELOG.md
=> chore: changelog v50.3.0

docs/_articles/en/getting-started/install.md, docs/_articles/ja/getting-started/install.md
Porting fix #2677 to develop branch
@W-8277599@
=> fix: broken java setup links in doc site (#2677)

packages/salesforcedx-vscode-soql/src/constants.ts, packages/salesforcedx-vscode-soql/src/queryDataView/queryDataHtml.ts, packages/salesforcedx-vscode-soql/src/queryDataView/queryDataViewService.ts
This PR will set webview URI's for SLDS icons we use for our save buttons in the SOQL Builder.
@W-8253104@
no icons
=> JHork: Save Button Icons

packages/salesforcedx-utils-vscode/src/commands/channelService.ts, packages/salesforcedx-utils-vscode/src/commands/index.ts, packages/salesforcedx-utils-vscode/src/commands/notificationService.ts, packages/salesforcedx-utils-vscode/test/unit/commands/channelService.test.ts, packages/salesforcedx-utils-vscode/test/unit/commands/notificationService.test.ts, packages/salesforcedx-vscode-lwc/src/channel/index.ts, packages/salesforcedx-vscode-lwc/src/commands/commandUtils.ts, packages/salesforcedx-vscode-lwc/src/commands/forceLightningLwcPreview.ts, packages/salesforcedx-vscode-lwc/src/commands/forceLightningLwcStart.ts, packages/salesforcedx-vscode-lwc/src/commands/forceLightningLwcStop.ts, packages/salesforcedx-vscode-lwc/src/messages/i18n.ja.ts, packages/salesforcedx-vscode-lwc/src/messages/i18n.ts, packages/salesforcedx-vscode-lwc/src/testSupport/testRunner/taskService.ts, packages/salesforcedx-vscode-lwc/test/vscode-integration/commands/commandUtils.test.ts, packages/salesforcedx-vscode-lwc/test/vscode-integration/commands/forceLightningLwcPreview.test.ts
This PR update channel service so we can create unique channels by extension.
@W-8183064@
=> Channel service refactor

packages/salesforcedx-vscode-lightning/package.json, packages/salesforcedx-vscode-lwc/package.json
Updates Aura and LWC language servers to the latest release which has a fix for triggering suggestions when using curly braces.
#2681, @W-8289975@
=> fix: update aura & lwc lang servers to 3.0.11

packages/salesforcedx-vscode-core/package.json, packages/salesforcedx-vscode-core/src/commands/forceSourceRetrieveSourcePath.ts, packages/salesforcedx-vscode-core/src/commands/util/retrieveParser.ts, packages/salesforcedx-vscode-core/src/messages/i18n.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/util/retrieveParser.test.ts
Enables multiple component retrieve when using the beta retrieve
@W-7963272@
Only individual components could be retrieved when beta retrieve is enabled
Multiple components can be retrieved with beta retrieve
=> perf(deploybeta): allow multiple component retrieve for performance beta

packages/salesforcedx-vscode/CHANGELOG.md
=> chore: generated CHANGELOG for release v50.4.0

packages/salesforcedx-vscode-lwc/package.nls.json, packages/salesforcedx-vscode-lwc/src/messages/i18n.ts, packages/salesforcedx-vscode-lwc/test/vscode-integration/commands/commandUtils.test.ts
This PR reverts the label changes from PR #2670 since we're not ready to make them available in production.
@W-8247907@
=> fix: revert label changes from PR 2670

packages/salesforcedx-apex-debugger/package.json, packages/salesforcedx-apex-replay-debugger/package.json, packages/salesforcedx-sobjects-faux-generator/package.json, packages/salesforcedx-test-utils-vscode/package.json, packages/salesforcedx-utils-vscode/package.json, packages/salesforcedx-utils-vscode/test/unit/telemetry/MockContext.ts, packages/salesforcedx-visualforce-language-server/package.json, packages/salesforcedx-visualforce-markup-language-server/package.json, packages/salesforcedx-vscode-apex-debugger/package.json, packages/salesforcedx-vscode-apex-debugger/test/vscode-integration/adapter/MockApexExtension.ts, packages/salesforcedx-vscode-apex-replay-debugger/package.json, packages/salesforcedx-vscode-apex-replay-debugger/src/breakpoints/checkpointService.ts, packages/salesforcedx-vscode-apex-replay-debugger/test/vscode-integration/adapter/MockApexExtension.ts, packages/salesforcedx-vscode-apex/package.json, packages/salesforcedx-vscode-apex/src/views/testOutlineProvider.ts, packages/salesforcedx-vscode-core/package.json, packages/salesforcedx-vscode-core/src/conflict/conflictOutlineProvider.ts, packages/salesforcedx-vscode-core/src/orgBrowser/metadataOutlineProvider.ts, packages/salesforcedx-vscode-core/src/statuses/taskView.ts, packages/salesforcedx-vscode-core/test/vscode-integration/telemetry/MockContext.ts, packages/salesforcedx-vscode-expanded/package.json, packages/salesforcedx-vscode-lightning/package.json, packages/salesforcedx-vscode-lwc/package.json, packages/salesforcedx-vscode-lwc/src/testSupport/testExplorer/testOutlineProvider.ts, packages/salesforcedx-vscode-lwc/src/testSupport/testIndexer/lwcTestIndexer.ts, packages/salesforcedx-vscode-lwc/test/vscode-integration/activation/MockContext.ts, packages/salesforcedx-vscode-lwc/test/vscode-integration/testSupport/mocks/vscodeConfiguration.ts, packages/salesforcedx-vscode-visualforce/package.json, packages/salesforcedx-vscode/package.json, packages/system-tests/package.json
Update the project to use version 1.46.0 and above for VSCode.
@W-8374828@
=> chore: update to vscode engine 1.46.0

packages/salesforcedx-vscode/CHANGELOG.md
=> Change log v50.5.0

packages/salesforcedx-vscode-soql/src/queryDataView/queryDataFileService.ts
Fixes an issue where saved soql query result files are not revealed in the file explorer in Windows.
@W-8383294@
=> fix(soql): parse uri for saved results as file

packages/salesforcedx-vscode-soql/.vscodeignore
This PR will include the readme.md file in the packaged vsix so that it can be rendered on the marketplace.
@W-8214787@
=> fix(soql): include the readme in the vsix

packages/salesforcedx-vscode-lightning/package.json, packages/salesforcedx-vscode-lwc/package.json
Updates aura & lwc language servers to version 3.0.12 which has multiple fixes.
forcedotcom/salesforcedx-vscode#1684, @W-8484957@
forcedotcom/salesforcedx-vscode#2703, @W-8339743@
forcedotcom/salesforcedx-vscode#2624, @W-8484972@
forcedotcom/salesforcedx-vscode#2636, forcedotcom/salesforcedx-vscode#2570, @W-8221074@
=> fix: update aura & lwc language servers to v3.0.12

package.json
Explicitly define shelljs as a devDependency at the top of the project
https://github.com/forcedotcom/salesforcedx-vscode/issues/2771
=> fix: shelljs not getting installed at the top-level

packages/salesforcedx-vscode/CHANGELOG.md
=> chore: generated CHANGELOG for origin/release/v50.7.0

packages/salesforcedx-vscode-soql/.vscodeignore
This PR reduces the size of the soql-biulder extension by 9mb.
@W-8529985@
21.5 mb
12.5 mb
=> chore: improve . vscodeignore in utils package

docs/_articles/en/index.md
change to coming soon vs. in pilot.  adjusted the intro to focus on the extensions and only mention COde Builder below.
=> Update doc homepage for Code Builder updates

packages/salesforcedx-vscode-core/package.json
=> chore: Update sdr to 1.1.14

packages/salesforcedx-vscode-soql/package.json
The [soql-tooling](https://github.com/forcedotcom/soql-tooling) repo is going to be open source. We would like to direct user issues and q&a there instead of this repo.
We also want to add the two scripts that will allow the tooling repo to be published with more regularity like the rest of the extensions.
@W-8437912@
=> Jhork- Update issue and Q&A url, join publishing automation.

packages/salesforcedx-vscode/CHANGELOG.md
- generated CHANGELOG for 50.8.0
=> chore: generated CHANGELOG for origin/release/v50.8.0

packages/salesforcedx-vscode-lwc/src/index.ts, packages/salesforcedx-vscode-lwc/src/languageClient/index.ts, packages/salesforcedx-vscode-lwc/test/vscode-integration/hover.test.ts
Fixes LWC hover tests from failing in autobuilds due to language client not being ready yet.
@W-8583127@
=> test: fix lwc hover tests in autobuilds

packages/salesforcedx-vscode-soql/package.json
…(#2794)"
This change reverts auto-publish of SOQL extension
=> Revert auto-publish of SOQL extension

packages/salesforcedx-vscode-soql/package.json
Stops auto-publishing SOQL extension updates
=> Revert auto-publish of SOQL extension (#2843)

packages/salesforcedx-vscode/CHANGELOG.md
=> chore: generated CHANGELOG for origin/release/v50.14.0

packages/salesforcedx-vscode-apex/package.json
This PR updates the version of the Apex library. This update contains fixes for some open issues.
#2872, #2863, @W-8776090@
=> chore: update version of apex

packages/salesforcedx-vscode-soql/package.json
This PR patches the soql-builder to fix [issue 120](https://github.com/forcedotcom/soql-tooling/issues/120), which affected our 50.14.0 release.
#https://github.com/forcedotcom/soql-tooling/issues/120, @W-8780780@
https://user-images.githubusercontent.com/599418/105518691-d2b6a600-5c95-11eb-9b57-4a88023e3f11.mov
https://user-images.githubusercontent.com/599418/105518715-d813f080-5c95-11eb-9cd1-cf6c65906ddf.mov
=> fix: update fixes soql-tooling issue 120

packages/salesforcedx-utils-vscode/src/commands/commandletExecutors.ts, packages/salesforcedx-utils-vscode/src/index.ts, packages/salesforcedx-vscode-core/src/channels/index.ts, packages/salesforcedx-vscode-core/src/commands/forceApexExecute.ts, packages/salesforcedx-vscode-core/src/commands/forceApexLogGet.ts, packages/salesforcedx-vscode-core/src/commands/forceApexTestRun.ts, packages/salesforcedx-vscode-core/src/commands/forceSourceDeployManifest.ts, packages/salesforcedx-vscode-core/src/commands/forceSourceDeploySourcePath.ts, packages/salesforcedx-vscode-core/src/commands/forceSourceRetrieveManifest.ts, packages/salesforcedx-vscode-core/src/commands/forceSourceRetrieveMetadata/forceSourceRetrieveCmp.ts, packages/salesforcedx-vscode-core/src/commands/forceSourceRetrieveSourcePath.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceSourceDeployManifest.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceSourceRetrieveManifest.test.ts
Updates the library based commands in core to use the library commandlet in the utils package.
@W-8749976@
=> refactor: use utils package library commandlet

packages/salesforcedx-vscode-expanded/README.md, packages/salesforcedx-vscode-expanded/package.json
Adds Apex Log Analyzer to extended extension pack.
@W-8822490@
=> Added apex analyzer to expanded pack

docs/_articles/en/apex/isv-debugger.md
Adds missing step to ISV Debugger documentation
@W-7939662@
=> fix: add missing permission step to ISV Debugger docs

docs/_articles/en/getting-started/recommended-extensions.md
Follow up to PR https://github.com/forcedotcom/salesforcedx-vscode/pull/2900, it adds it to the Recommended Extensions article in the doc site.
@W-8822490@
=> fix: add Log Analyzer to recommended ext doc

packages/salesforcedx-vscode-apex-debugger/src/index.ts, packages/salesforcedx-vscode-apex-replay-debugger/src/index.ts, packages/salesforcedx-vscode-visualforce/src/extension.ts
Porting PR #2913 to this week's release branch
@W-8792554@
=> fix: remove use of missing telemetry method (#2913)

packages/salesforcedx-vscode/CHANGELOG.md
Updates changelog for release 50.16.0
=> chore: generated CHANGELOG for origin/release/v50.16.0

packages/salesforcedx-vscode-apex/src/commands/forceApexExecute.ts, packages/salesforcedx-vscode-apex/src/messages/i18n.ts, packages/salesforcedx-vscode-apex/test/vscode-integration/commands/forceApexExecute.test.ts
Fixes an issue where the diagnostic message wasn't set properly
@W-8857272@
=> fix: apex execute diagnostic reporting

packages/salesforcedx-vscode-soql/CHANGELOG.md
This PR updates the soql extension changelog.
=> SOQL Builder: Update changelog

package.json
Fix failing integration tests caused by new versions of `vscode-test`
@W-8903508@
=> chore: test pinning version of vscode-test dependency

packages/salesforcedx-vscode-core/package.json, packages/salesforcedx-vscode-core/package.nls.json, packages/salesforcedx-vscode-core/src/commands/forceProjectCreate.ts, packages/salesforcedx-vscode-core/src/commands/index.ts, packages/salesforcedx-vscode-core/src/commands/templates/forceAnalyticsTemplateCreate.ts, packages/salesforcedx-vscode-core/src/commands/templates/forceApexClassCreate.ts, packages/salesforcedx-vscode-core/src/commands/templates/forceApexTriggerCreate.ts, packages/salesforcedx-vscode-core/src/commands/templates/forceLightningAppCreate.ts, packages/salesforcedx-vscode-core/src/commands/templates/forceLightningComponentCreate.ts, packages/salesforcedx-vscode-core/src/commands/templates/forceLightningEventCreate.ts, packages/salesforcedx-vscode-core/src/commands/templates/forceLightningInterfaceCreate.ts, packages/salesforcedx-vscode-core/src/commands/templates/forceLightningLwcCreate.ts, packages/salesforcedx-vscode-core/src/commands/templates/forceLightningLwcTestCreate.ts, packages/salesforcedx-vscode-core/src/commands/templates/forceVisualforceComponentCreate.ts, packages/salesforcedx-vscode-core/src/commands/templates/forceVisualforcePageCreate.ts, packages/salesforcedx-vscode-core/src/commands/templates/index.ts, packages/salesforcedx-vscode-core/src/constants.ts, packages/salesforcedx-vscode-core/src/settings/sfdxCoreSettings.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceProjectCreate.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/templates/forceAnalyticsTemplateCreate.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/templates/forceApexClassCreate.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/templates/forceApexTriggerCreate.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/templates/forceLightningAppCreate.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/templates/forceLightningComponentCreate.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/templates/forceLightningEventCreate.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/templates/forceLightningInterfaceCreate.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/templates/forceLightningLWCCreate.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/templates/forceVisualforceComponentCreate.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/templates/forceVisualforcePageCreate.test.ts
Deprecate code that calls the cli on templates command and the gating setting.
@W-8913415@
=> chore: deprecate cli template code

packages/salesforcedx-vscode-soql/package.json
This PR will update the SOQL Builder Extension to use the latest version of the SOQL Builder UI.
@W-8922671@
v0.0.32
v0.0.33 include better support for LIKE operators: [PR](https://github.com/forcedotcom/soql-tooling/pull/192)
https://user-images.githubusercontent.com/25188632/108784548-dfe0e200-752c-11eb-9ec9-c138b9d1c6b8.mov
=> chore: SOQL Builder Release v0.0.33

docs/_articles/en/soql/soql-builder.md, docs/_articles/ja/soql/soql-builder.md
Forgot to upload both versions of docs.
=> SOQL Builder docs - update for like for both en and ja

packages/salesforcedx-vscode-core/package.json
Add applicationinsights dependency to core which was removed by mistake on PR #2955
@W-8914940@
=> fix: add applicationinsights dependency to core

packages/salesforcedx-vscode/CHANGELOG.md
=> chore: generated CHANGELOG for origin/release/v51.2.0

packages/salesforcedx-vscode-core/package.json, packages/salesforcedx-vscode-core/test/vscode-integration/commands/templates/forceApexClassCreate.test.ts
Updating the @salesforce/templates library to get the latest updates/fixes
=> chore: update to v51.2.0 of templates library

packages/salesforcedx-vscode-soql/package.json, packages/salesforcedx-vscode-soql/src/editor/queryRunner.ts
Bump version of `soql-language-server` dependency. Add `soql-common`.
@W-8842328@
No functionality changes
No functionality changes
=> refactor: new soql-lsp version. Some functions now in soql-common

packages/salesforcedx-vscode-core/.vscodeignore
Removes unused code in `salesforcedx-vscode-core` introduced by `salesforcedx-sobjects-faux-generator`
@W-8953248@
=> chore: remove unused code from core vsix

packages/salesforcedx-vscode-apex/src/messages/i18n.ts, packages/salesforcedx-vscode-core/src/messages/i18n.ts
Port message changes to release 51.3.0
=> chore: port 3005 to release 51.3.0

packages/salesforcedx-vscode/CHANGELOG.md
=> chore: generated CHANGELOG for origin/release/v51.3.0

packages/salesforcedx-vscode-apex-replay-debugger/src/commands/quickLaunch.ts, packages/salesforcedx-vscode-apex-replay-debugger/test/vscode-integration/commands/quickLaunch.test.ts
This PR fixes an issue with debugging a single test method.
#3026, @W-8977004@
=> fix: issue with debugging single test method

packages/salesforcedx-vscode-apex-replay-debugger/.vscodeignore
Reduce size of replay debugger extension to 4.96MB (from 13.9MB)
@W-8979930@
=> chore: remove duplicated dependencies

packages/salesforcedx-vscode-core/package.nls.json
Update description for the deploy retrieve flag.
@W-8872046@
=> fix: update wording description for deploy retrieve setting

packages/salesforcedx-vscode/CHANGELOG.md
=> chore: generated CHANGELOG for origin/release/v51.4.0

contributing/publishing.md
update publishing doc to check for scheduled build
=> chore: update publishing doc to check for scheduled build

packages/salesforcedx-utils-vscode/src/commands/commandletExecutors.ts, packages/salesforcedx-utils-vscode/src/commands/notificationService.ts, packages/salesforcedx-utils-vscode/test/unit/commands/commandletExecutor.test.ts
Changes to the libraryCommandletExecutor interface to support progress reporting and cancellation
@W-8965162@
=> feat: changes to libraryCommandletExecutor interface to support cancellation

packages/salesforcedx-vscode/CHANGELOG.md
=> chore: generated CHANGELOG for origin/release/v51.5.0

.git2gus/config.json
Updates the default Found In Build to api version 51
was offcore.tooling.48
now offcore.tooling.51
@W-9027802@
=> Bump default Found In Buid

packages/salesforcedx-vscode/CHANGELOG.md
changeling for release v51.6.0
=> Change log v51.6.0

packages/salesforcedx-vscode-soql/package.json, packages/salesforcedx-vscode-soql/src/commands/soqlBuilderToggle.ts, packages/salesforcedx-vscode-soql/src/commands/soqlFileCreate.ts, packages/salesforcedx-vscode-soql/test/vscode-integration/commands/soqlBuilderToggle.test.ts, packages/salesforcedx-vscode-soql/test/vscode-integration/commands/soqlFileCreate.test.ts
This PR cherry-picks into the release branch.  Please reference that merged PR for all the relevant info on this fix.  @smaddox-sf would like to get this out if possible.
https://github.com/forcedotcom/salesforcedx-vscode/pull/3091
@W-8990594@
=> fix: create new query command opens soql builder (#3091)

packages/salesforcedx-vscode-soql/package.json
This PR updates soql builder to pull in some of the latest improvements in the dependencies.  It's customer visibility is a fix to align labels and fields better.  But otherwise, there are no customer facing changes.  The rest is under-the-covers tooling.
https://github.com/forcedotcom/soql-tooling/pull/239
=> fix: update dependencies - better align labels and inputs

packages/salesforcedx-sobjects-faux-generator/src/generator/fauxClassGenerator.ts, packages/salesforcedx-sobjects-faux-generator/test/integration/fauxGenerate.test.ts
Cancels sobject refresh at different points during the execution
Previous spike PR - https://github.com/forcedotcom/salesforcedx-vscode/pull/3092
Spike doc - https://salesforce.quip.com/3U2GAgP3wPsH
@W-9067574@
We use the same UI as above, now the cancellation works at different points during the execution.
=> feat: cancel sobject refresh at different points @W-9067574@

packages/salesforcedx-utils-vscode/src/messages/i18n.ja.ts, packages/salesforcedx-utils-vscode/src/messages/i18n.ts, packages/salesforcedx-vscode-core/src/messages/i18n.ja.ts, packages/salesforcedx-vscode-core/src/messages/i18n.ts
Fix for a labels issue users reported
#3111  @W-9088000@
N/A
N/A
=> fix: move labels to utils @W-9088000@

docs/_articles/en/user-guide/perf-enhancements.md, docs/_articles/ja/user-guide/perf-enhancements.md
- update the status of Apex to reflect that the CLI is updated
- Add a little more detail on the setting so users understand the choice more clearly
=> Update to Apex status - clarity on status

docs/_articles/en/user-guide/perf-enhancements.md, docs/_articles/ja/user-guide/perf-enhancements.md
Port Apex status update to release branch v51.8.0
=> Update to Apex status - clarity on status (#3119)

packages/salesforcedx-vscode/CHANGELOG.md
=> Change log v51.8.0

packages/salesforcedx-vscode/CHANGELOG.md
Updates the changelog for v51.10.0 of the extensions.
=> Change log v51.10.0

packages/salesforcedx-sobjects-faux-generator/src/transformer/transformerFactory.ts
Disable LWC type generation in the core extension during sobject refresh.
@W-9168796@
=> fix: disable lwc type generation

packages/salesforcedx-sobjects-faux-generator/src/transformer/transformerFactory.ts
Porting PR 3165 to this week's release.
@W-9168796@
=> fix: disable lwc type generation (#3165)

packages/salesforcedx-vscode-core/package.json
Bumps SDR for misconfiguration fix of AccountRelationshipShareRules
@W-9156885@
Could not deploy/retrieve AccountRelationshipShareRules
Now can deploy/retrieve AccountRelationshipShareRules
=> fix: account relationship share rules in deploy/retrieve beta

packages/salesforcedx-vscode/CHANGELOG.md
=> chore: generated CHANGELOG for origin/release/v51.11.0

.vscode/tasks.json, scripts/change-log-generator.js
1. Adds ability to pass a date param to the script. If empty, autogenerates with today's date.
2. Perform a git pull to ensure the listing for release branches is up to date.
3. Set the base branch as part of opening the PR.
4. Update documentation.
5. Adds the ability to override the previous release branch. This was not added to the task generation since I don't expect this to be run very often. This will be useful in the event that we can't release during a given week or have to run the creation of the release branch manually (in the event of a major version bump). This helps give the release individual peace of mind knowing they aren't missing anything.
@W-9214907@
=> chore: change log generation updates

packages/salesforcedx-vscode/CHANGELOG.md
=> chore: generated CHANGELOG for origin/release/v51.12.0

.circleci/config.yml, scripts/aggregate-junit-xml.js
Ports the relaunch of VSCode integration test failures to main.
=> test: relaunch crashed VSCode Integration Tests (#3206)

packages/salesforcedx-vscode-core/package.json
Updates salesforce/template version
@W-9234447@
N/A
N/A
=> chore: update salesforce/template version @W-9234447@

packages/salesforcedx-vscode/CHANGELOG.md
Changelog for release v51.13.0
=> chore: generated CHANGELOG for origin/release/v51.13.0

packages/salesforcedx-vscode-soql/package.json
This PR updates dependencies that allow the user to quickly select "ALL FIELDS" or "Clear Selections" in the soql builder ui.  The dependency update comes from publishing after merging [this PR](https://github.com/forcedotcom/soql-tooling/pull/251).
https://github.com/forcedotcom/soql-tooling/issues/89
None
https://user-images.githubusercontent.com/599418/117862934-72ea0800-b250-11eb-9bd5-4057c2a792f4.mov
=> feat: release ALL FIELDS feature

packages/salesforcedx-vscode-lightning/package.json, packages/salesforcedx-vscode-lwc/package.json
update lightning language servers to latest
@W-9260287@
=> chore: update lightning language servers to latest

packages/salesforcedx-vscode-core/package.json
Removes file diff command to be shown on folder level
@W-9166550@
=> fix: remove file diff on folders @W-9166550@

packages/salesforcedx-vscode-core/src/commands/templates/baseTemplateCommand.ts, packages/salesforcedx-vscode-core/src/commands/templates/forceFunctionCreate.ts, packages/salesforcedx-vscode-core/src/commands/templates/forceLightningLwcTestCreate.ts, packages/salesforcedx-vscode-core/src/commands/templates/metadataTypeConstants.ts, packages/salesforcedx-vscode-core/src/commands/util/sourcePathStrategies.ts, packages/salesforcedx-vscode-core/src/util/metadataDictionary.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/templates/forceFunctionCreate.test.ts
Uses new cli for function creation - either JS or Java.
Remove support for typescript
@W-9282205@
@W-9282425@
N/A
=> feat: use new cli for function creation + java support @W-9282205@

docs/package.json, lerna.json, packages/salesforcedx-apex-debugger/package.json, packages/salesforcedx-apex-replay-debugger/package.json, packages/salesforcedx-sobjects-faux-generator/package.json, packages/salesforcedx-test-utils-vscode/package.json, packages/salesforcedx-utils-vscode/package.json, packages/salesforcedx-visualforce-language-server/package.json, packages/salesforcedx-visualforce-markup-language-server/package.json, packages/salesforcedx-vscode-apex-debugger/package.json, packages/salesforcedx-vscode-apex-replay-debugger/package.json, packages/salesforcedx-vscode-apex/package.json, packages/salesforcedx-vscode-core/package.json, packages/salesforcedx-vscode-expanded/package.json, packages/salesforcedx-vscode-lightning/package.json, packages/salesforcedx-vscode-lwc/package.json, packages/salesforcedx-vscode-soql/package.json, packages/salesforcedx-vscode-visualforce/package.json, packages/salesforcedx-vscode/package.json, packages/system-tests/package.json
Set release version to 51.14.0
Operation
=> fix: set release version to 51.14.0

packages/salesforcedx-vscode-apex/package.json, packages/salesforcedx-vscode-apex/src/commands/forceApexTestRunCodeAction.ts, packages/salesforcedx-vscode-apex/test/vscode-integration/commands/forceApexTestRunCodeAction.test.ts, packages/salesforcedx-vscode-core/package.json
update @salesforce/source-deploy-retrieve to 2.1.4
=> chore: update @salesforce/source-deploy-retrieve to 2.1.4

packages/salesforcedx-vscode/CHANGELOG.md
Update the changelog for version 51.15.0
=> Change log v51.15.0

packages/salesforcedx-vscode-soql/package.json
update salesforce/core version in vscode-soql
=> chore: update core version in vscode-soql

packages/salesforcedx-vscode-core/src/commands/forceStartApexDebugLogging.ts
- Fix the creation of debug log trace flags when running `SFDX Turn on Apex Debug Log`
#3288, @W-9359890@
=> fix: correct creation of trace flags

packages/salesforcedx-vscode/CHANGELOG.md
=> chore: generated CHANGELOG for origin/release/v51.17.0

packages/salesforcedx-vscode-core/package.json
=> chore: update template major version

packages/salesforcedx-vscode-core/src/commands/auth/authParamsGatherer.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/auth/authParameterGatherer.test.ts
=> fix: make input prompt persistent for auth tokens

packages/salesforcedx-vscode/CHANGELOG.md
=> Change log v52.1.0

packages/salesforcedx-sobjects-faux-generator/src/transformer/transformerFactory.ts, packages/salesforcedx-vscode-apex/src/languageServer.ts
Updated Apex Language Server to incorporate features:
- debug test code lens for Apex tests
- LWC typing generation
@W-9497942@
=> feat: incorporate Apex Language Server updates

packages/salesforcedx-vscode/CHANGELOG.md
=> chore: generated CHANGELOG for origin/release/v52.2.0

packages/salesforcedx-vscode/CHANGELOG.md
Updates changelog for release v52.3.0
=> chore: update changelog for v52.3.0

packages/salesforcedx-vscode/CHANGELOG.md
=> chore: generated CHANGELOG for v52.4.0

docs/_articles/en/user-guide/detect-conflicts.md, packages/salesforcedx-vscode-core/src/commands/forceSourceRetrieveManifest.ts, packages/salesforcedx-vscode-core/src/commands/forceSourceRetrieveSourcePath.ts
=> chore: port 3382 to release 52.4.0

packages/salesforcedx-vscode-core/src/commands/util/postconditionCheckers.ts, packages/salesforcedx-vscode-core/src/messages/i18n.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/util/postconditionCheckers.test.ts
This PR updates the conflict detection modal wording and highlights the show conflict choice.
@W-9565057@
=> feat: conflict detection update modal

packages/salesforcedx-vscode-core/package.json, packages/salesforcedx-vscode-core/package.nls.json
Do not show option to enable/disable function in the settings page
@W-9311863
The above option is not shown
=> fix: remove setting to enable function @W-9311863

packages/salesforcedx-vscode-core/package.nls.json
This PR updates the setting description for `Detect Conflicts at Sync`. 
@W-9549951@
=> feat: update conflict detection setting description

packages/salesforcedx-sobjects-faux-generator/src/generator/typingGenerator.ts
Correctly create target directory during LWC typing generation for new projects
@W-9604074@
=> fix: correct LWC typing generation for new projects

packages/salesforcedx-vscode/CHANGELOG.md
=> chore: generated CHANGELOG for release v52.7.0

packages/salesforcedx-vscode/CHANGELOG.md
=> chore: generated CHANGELOG for origin/release/v52.8.0

packages/salesforcedx-vscode-apex/package.json, packages/salesforcedx-vscode-core/package.json, packages/salesforcedx-vscode-core/src/commands/baseDeployRetrieve.ts, packages/salesforcedx-vscode-core/src/conflict/metadataCacheService.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/baseDeployRetrieve.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceSourceDeployManifest.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceSourceDeploySourcePath.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceSourceRetrieveManifest.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceSourceRetrieveMetadata/forceSourceRetrieveCmp.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceSourceRetrieveSourcePath.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/conflict/metadataCacheService.test.ts
This PR reverts SDR to 2.1.5.
https://github.com/forcedotcom/source-deploy-retrieve/pull/334, https://github.com/forcedotcom/salesforcedx-vscode/issues/3495, @W-9750616@
=> fix: revert SDR to 2.1.5

packages/salesforcedx-vscode/CHANGELOG.md
=> chore: generated CHANGELOG for origin/release/v52.9.1

packages/salesforcedx-sobjects-faux-generator/package.json, packages/salesforcedx-utils-vscode/package.json, packages/salesforcedx-vscode-apex-replay-debugger/package.json, packages/salesforcedx-vscode-apex-replay-debugger/src/commands/quickLaunch.ts, packages/salesforcedx-vscode-apex/package.json, packages/salesforcedx-vscode-apex/src/commands/forceApexTestRun.ts, packages/salesforcedx-vscode-apex/src/commands/forceApexTestRunCodeAction.ts, packages/salesforcedx-vscode-apex/test/vscode-integration/commands/forceApexTestRun.test.ts, packages/salesforcedx-vscode-apex/test/vscode-integration/commands/forceApexTestRunCodeAction.test.ts, packages/salesforcedx-vscode-core/package.json, packages/salesforcedx-vscode-core/src/commands/baseDeployRetrieve.ts, packages/salesforcedx-vscode-core/src/conflict/metadataCacheService.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/baseDeployRetrieve.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceSourceDeployManifest.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceSourceDeploySourcePath.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceSourceRetrieveManifest.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceSourceRetrieveMetadata/forceSourceRetrieveCmp.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceSourceRetrieveSourcePath.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/conflict/metadataCacheService.test.ts, packages/salesforcedx-vscode-lightning/package.json, packages/salesforcedx-vscode-lwc/package.json, packages/salesforcedx-vscode-soql/package.json
Follow up to #3451, but to 4.1.1 for later version. Also references recent Apex library release to fix the breaking change that resulted from 3451.
@W-9765184@
=> chore: bump SDR to 4.1.1

packages/salesforcedx-vscode-core/src/messages/i18n.ts
External contribution to fix a typo - https://github.com/forcedotcom/salesforcedx-vscode/pull/3516
=> Pr/3516 - Fix a typo

packages/salesforcedx-vscode/CHANGELOG.md
=> chore: generated CHANGELOG for origin/release/v52.12.0

packages/salesforcedx-vscode-apex/package.json, packages/salesforcedx-vscode-apex/package.nls.json
This PR adds in the code completion setting to enable telemetry collection on code completion statistics
@W-9676036@
=> chore: add code completion setting

packages/salesforcedx-vscode-soql/tsconfig.json
=> port fix: fix soql build

packages/salesforcedx-vscode/CHANGELOG.md
=> chore: generated CHANGELOG for origin/release/v52.13.0

packages/salesforcedx-vscode/CHANGELOG.md
=> chore: generated CHANGELOG for origin/release/v52.16.0

packages/salesforcedx-vscode-apex/src/languageServer.ts, packages/salesforcedx-vscode-apex/test/vscode-integration/languageServer.test.ts
Enable completion support for anonymous Apex files
@W-9787754@
=> feat: code completion for anonymous apex

packages/salesforcedx-vscode/CHANGELOG.md
=> chore: generated CHANGELOG for origin/release/v53.2.0

docs/_articles/ja/functions/overview.md, docs/_articles/ja/user-guide/byotemplate.md
Added articles in the /ja folder.
Copied files into the /ja folder.
No base files for japanese transation.
=> Added New Articles for Japanese

packages/salesforcedx-vscode/CHANGELOG.md
=> chore: generated CHANGELOG for origin/release/v53.3.0

packages/salesforcedx-vscode/CHANGELOG.md
=> chore: generated CHANGELOG for origin/release/v53.4.0

packages/salesforcedx-vscode/CHANGELOG.md
=> chore: generated CHANGELOG for origin/release/v53.7.0

packages/salesforcedx-vscode/CHANGELOG.md
=> Update date of release

packages/salesforcedx-vscode-core/package.json, packages/salesforcedx-vscode-core/src/orgBrowser/nodeTypes.ts
chore: port 3697 to release 53.8.0
=> fix: display retrieve source button (#3697)

packages/salesforcedx-vscode/CHANGELOG.md
=> chore: generated CHANGELOG for origin/release/v53.8.0

.circleci/config.yml, contributing/publishing.md
Changes release branch cut time to Tuesday evenings PST 
Release branch cut weekly Mondays
Release branch cut weekly Tuesdays
=> chore: change release branch cut time to tuesday evenings PST

packages/salesforcedx-vscode/CHANGELOG.md
Changelog for release v53.12.0
=> chore: generated CHANGELOG for origin/release/v53.12.0

packages/salesforcedx-vscode/CHANGELOG.md
=> chore: generated CHANGELOG for origin/release/v53.13.0

.github/CODEOWNERS
add gusinfo to codeowners
@W-9377468@
N/A
No change in functionality
=> chore: add gusinfo to codeowners @W-9377468@

packages/salesforcedx-visualforce-language-server/package.json, packages/salesforcedx-vscode-visualforce/package.json
Reverts forcedotcom/salesforcedx-vscode#3770
Dependabot PR was merged by CLI BOT even though PR had failed status check.
=> revert "chore(deps): bump vscode-languageserver-protocol from 3.14.1 to 3.16.0"

.circleci/config.yml, packages/salesforcedx-apex-debugger/package.json, packages/salesforcedx-apex-replay-debugger/package.json, packages/salesforcedx-test-utils-vscode/package.json, packages/salesforcedx-utils-vscode/package.json, packages/salesforcedx-vscode-apex-replay-debugger/package.json, packages/salesforcedx-vscode-core/package.json
Reverts the last 3 dependabot PRs that were merged with failed status checks: #3719, #3727, #3755 
TODO :
=> revert: dependabot automerges with failed status checks

packages/salesforcedx-vscode/CHANGELOG.md
=> chore: generated CHANGELOG for origin/release/v53.16.0

.git2gus/config.json
Update git2gus config to 54.0 offcore build
=> Update git2gus config default build value

packages/salesforcedx-vscode/CHANGELOG.md
=> chore: generated CHANGELOG for origin/release/v53.17.0

packages/salesforcedx-vscode-apex/src/index.ts
#@W-10679231@
The Execute Anonymous Apex code lens in our anon Apex files was broken
This PR fixes this functionality and restores it back to the way it was.
=> fix: fixed issue with execute anonymous apex code lens not working

packages/salesforcedx-vscode/CHANGELOG.md
=> chore: generated CHANGELOG for origin/release/v54.0.0

.vscode/tasks.json, contributing/publishing.md
Small doc update to reflect major release process.
=> docs: update major release process

packages/salesforcedx-vscode-apex/test/vscode-integration/apexLspJarContents.test.ts
Remove unessential apex classes from Apex LSP jar
@W-10433780@ 
N/A
No change in functionality
=> Remove unessential apex classes from Apex LSP jar

packages/salesforcedx-vscode/CHANGELOG.md
=> chore: generated CHANGELOG for origin/release/v54.2.0

lerna.json, scripts/create-release-branch.js
This is part of the overall story to simplify release process
@W-10785024@
We allow lerna version update only in develop
We allow lerna version update only in specific release branches
=> Change lerna release config to allow version update in release branches

.circleci/config.yml, contributing/publishing.md
documentation around new release process + release cut time
@W-10785024@
N/A
No change in functionality
=> chore: documentation around new release process + release cut time @W-10785024@

packages/salesforcedx-vscode/CHANGELOG.md
edit changelog to include enhanced lwc autocompletion in lightning-language-server
[#487 feat: enhance autocompletion across JS/HTML](https://github.com/forcedotcom/lightning-language-server/pull/487)
[#3865 chore: bump lightning language server to v3.5.0](https://github.com/forcedotcom/salesforcedx-vscode/pull/3865)
=> docs: edit changelog to include lwc autocompletion in lightning-language-server

SHA256.md, docs/package.json, lerna.json, packages/salesforcedx-apex-debugger/package.json, packages/salesforcedx-apex-replay-debugger/package.json, packages/salesforcedx-sobjects-faux-generator/package.json, packages/salesforcedx-test-utils-vscode/package.json, packages/salesforcedx-utils-vscode/package.json, packages/salesforcedx-visualforce-language-server/package.json, packages/salesforcedx-visualforce-markup-language-server/package.json, packages/salesforcedx-vscode-apex-debugger/package.json, packages/salesforcedx-vscode-apex-replay-debugger/package.json, packages/salesforcedx-vscode-apex/package.json, packages/salesforcedx-vscode-core/package.json, packages/salesforcedx-vscode-expanded/package.json, packages/salesforcedx-vscode-lightning/package.json, packages/salesforcedx-vscode-lwc/package.json, packages/salesforcedx-vscode-soql/package.json, packages/salesforcedx-vscode-visualforce/package.json, packages/salesforcedx-vscode/CHANGELOG.md, packages/salesforcedx-vscode/package.json, packages/system-tests/package.json
A manual merge of main into develop
=> Main (54.4.1) into develop

packages/salesforcedx-vscode-lightning/package.json, packages/salesforcedx-vscode-lwc/package.json
Consumes the latest lightning-language-server packages, which includes the addition of the iterator syntax, and additional description information on the other directives.
@W-10809426@
The template directive iterator:it was not appearing in our list of auto-complete attributes, and description information was broken.
The directive appears, and the description information is now available for all other template directives. 🎉
=> feat: add iterator template directive and improve directive descriptions

.circleci/config.yml, packages/salesforcedx-vscode-soql/package.json, packages/salesforcedx-vscode-soql/test/ui-test/soql-ui-smoke.test.ts
Fixes soql test:ui suite failure
Github issue: https://github.com/forcedotcom/easywriter/issues/10
@[W-10832767](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000sXZeeYAG/view)@
=> test: fix failures on soql test:ui suite

packages/salesforcedx-vscode/CHANGELOG.md
Fixes an issue with the release notes.
=> fix: update release notes for 54.4.1 release

package-lock.json, package.json, packages/salesforcedx-vscode-lwc/package.json
- Removes unused dependency [ajv-validator/ajv: The fastest JSON schema Validator](https://github.com/ajv-validator/ajv)
@W-10852020@
=> build: remove unused dep ajv (JSON validator)

contributing/developing.md, package-lock.json, package.json
- Reverts https://github.com/forcedotcom/salesforcedx-vscode/pull/3922
- that inadvertently removed a peer dependency listed as a dev dep (which made it seem unused)
- Adds a checker to make sure peer deps are installed to the post install step
@W-10852020@
- Missing peer deps 
```
$ npm install
...
npm WARN @octokit/plugin-request-log@1.0.4 requires a peer of @octokit/core@>=3 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-errors@1.0.1 requires a peer of ajv@>=5.0.0 but none is installed. You must install peer dependencies yourself.
$ npm list --all
...
npm ERR! peer dep missing: @octokit/core@>=3, required by @octokit/plugin-request-log@1.0.4
npm ERR! peer dep missing: ajv@>=5.0.0, required by ajv-errors@1.0.1
```
- No check to find missing peer deps
- …
=> build: add missing peer deps (ajv, acorn, @octokit/core)

docs/package.json, lerna.json, packages/salesforcedx-apex-debugger/package.json, packages/salesforcedx-apex-replay-debugger/package.json, packages/salesforcedx-sobjects-faux-generator/package.json, packages/salesforcedx-test-utils-vscode/package.json, packages/salesforcedx-utils-vscode/package.json, packages/salesforcedx-visualforce-language-server/package.json, packages/salesforcedx-visualforce-markup-language-server/package.json, packages/salesforcedx-vscode-apex-debugger/package.json, packages/salesforcedx-vscode-apex-replay-debugger/package.json, packages/salesforcedx-vscode-apex/package.json, packages/salesforcedx-vscode-core/package.json, packages/salesforcedx-vscode-expanded/package.json, packages/salesforcedx-vscode-lightning/package.json, packages/salesforcedx-vscode-lwc/package.json, packages/salesforcedx-vscode-soql/package.json, packages/salesforcedx-vscode-visualforce/package.json, packages/salesforcedx-vscode/CHANGELOG.md, packages/salesforcedx-vscode/package.json, packages/system-tests/package.json
Manual merge of main to develop
=> chore: merge main to develop

scripts/create-release-branch.js
Bring back release branch into develop as soon as it is cut.
@W-10943603@
=> chore: merge release branch into develop once it is cut

packages/salesforcedx-vscode/CHANGELOG.md
Added changelog for release v54.11.0.
=> docs: Changelog v54.11.0

docs/_articles/en/apex/writing.md
=> docs: fix typo

package-lock.json, packages/salesforcedx-vscode/CHANGELOG.md
Removed the text about enabling SDR from the changelog
=> Jb/remove SDR command from changelog

package-lock.json
Commit that package-lock.json file from the release build again, similar to #4137.
=> chore: update package-lock.json again

.git2gus/config.json, docs/package.json, lerna.json, packages/salesforcedx-apex-debugger/package.json, packages/salesforcedx-apex-replay-debugger/package.json, packages/salesforcedx-sobjects-faux-generator/package.json, packages/salesforcedx-test-utils-vscode/package.json, packages/salesforcedx-utils-vscode/package.json, packages/salesforcedx-visualforce-language-server/package.json, packages/salesforcedx-visualforce-markup-language-server/package.json, packages/salesforcedx-vscode-apex-debugger/package.json, packages/salesforcedx-vscode-apex-replay-debugger/package.json, packages/salesforcedx-vscode-apex/package.json, packages/salesforcedx-vscode-core/package.json, packages/salesforcedx-vscode-expanded/package.json, packages/salesforcedx-vscode-lightning/package.json, packages/salesforcedx-vscode-lwc/package.json, packages/salesforcedx-vscode-soql/package.json, packages/salesforcedx-vscode-visualforce/package.json, packages/salesforcedx-vscode/package.json, packages/system-tests/package.json, scripts/create-release-branch.js
Revert the last minor release version update and fix the create-release-branch script to correctly add the package-lock.json file. 
#1491 
package-lock.json would not be updated as part of cutting the release branch. 
package-lock.json is appropriated updated.
=> chore: revert last release and fix major release 

packages/salesforcedx-vscode-core/src/commands/forceOrgList.ts, packages/salesforcedx-vscode-core/src/panels/orgListPanel.ts
This is my addition to jeff's work on hackday.  It adds a column for defaultDevhubUsername and defaultUsername.  I had to execute the command from the root workspace directory to get those fields into the results.
It also hacks together some styling changes in a very bad way....until we can get some time to investigate how better to style these vscode webview components.
=> fix: add defaultUsername and defaultDevhubUsername to ui

package-lock.json, packages/salesforcedx-apex-debugger/src/core/streamingClient.ts, packages/salesforcedx-sobjects-faux-generator/package.json, packages/salesforcedx-utils-vscode/package.json, packages/salesforcedx-vscode-apex-replay-debugger/package.json, packages/salesforcedx-vscode-apex/package.json, packages/salesforcedx-vscode-core/.vscode/tasks.json, packages/salesforcedx-vscode-core/package.json, packages/salesforcedx-vscode-core/src/commands/forceCreateManifest.ts, packages/salesforcedx-vscode-core/src/commands/forceStartApexDebugLogging.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/auth/forceAuthLogout.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/context/workspaceOrgType.test.ts, packages/salesforcedx-vscode-lightning/package.json, packages/salesforcedx-vscode-lwc/package.json, packages/salesforcedx-vscode-soql/package.json
Goal was to get the project to compile.  The simplest alignment across seemed to be jumping to the latest (ish) of core. 
PR is target a merge with ra/upgrade branch
- code compiled briefly.  Now has only the following issue `Type 'string | null | undefined' is not assignable to type 'string'.
Type 'undefined' is not assignable to type 'string'.`. Can be fixed by adding a return type to the method but wanted to ensure I understood it before changing it.
=> chore: bump core to 3.23.2 across repo. 

package-lock.json
update the package-lock.json file to pick up changes from our deps
attempted to get cut release branch to work for release v55.4.0
=> chore: add updated package lock file

docs/_articles/en/codebuilder/cb-start.md, docs/_articles/en/vscode-desktop/install.md
Fixed a broken link and some odd rendering.
#4276 , @<W-11412829>@
Brokenn doc links
Fixed broken doc links
=> Minor docs fixes

packages/salesforcedx-vscode-core/src/commands/baseDeployRetrieve.ts, packages/salesforcedx-vscode-core/src/commands/forceCreateManifest.ts
Some minor fixes for Gordon's PR
@W-11150601@
=> fix: feedback-changes-for-update_v3_test1

packages/salesforcedx-vscode-apex-debugger/package.json, packages/salesforcedx-vscode-apex-replay-debugger/package.json, packages/salesforcedx-vscode-apex/package.json, packages/salesforcedx-vscode-core/package.json, packages/salesforcedx-vscode-expanded/package.json, packages/salesforcedx-vscode-lightning/package.json, packages/salesforcedx-vscode-lwc/package.json, packages/salesforcedx-vscode-soql/package.json, packages/salesforcedx-vscode-visualforce/package.json, packages/salesforcedx-vscode/package.json
While developing on core v3 upgrade, ran packaging the extensions command locally. It added the __metadata_ entries to package.json automatically. So removing the unnecessary __metadata_ entries.
__metadata_ property added to package.json
Removed the property __metadata_ from package.json of each package.
=> fix: remove unnecessary configs

packages/salesforcedx-sobjects-faux-generator/src/generator/configUtil.ts, packages/salesforcedx-vscode-core/src/commands/auth/forceAuthAccessTokenLogin.ts, packages/salesforcedx-vscode-core/src/orgPicker/orgList.ts, packages/salesforcedx-vscode-core/src/util/authInfo.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/auth/forceAuthAccessTokenLogin.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/auth/forceAuthLogout.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/orgPicker/orgList.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/util/authInfo.test.ts
My assigned cleanup for the auth and org work.
#4282
=> fix: cleanup auth and login from v3 first pass

packages/salesforcedx-vscode-core/src/commands/forceStartApexDebugLogging.ts, packages/salesforcedx-vscode-core/src/commands/templates/libraryBaseTemplateCommand.ts, packages/salesforcedx-vscode-core/src/context/workspaceOrgType.ts
=> fix: minor code changes

packages/salesforcedx-utils-vscode/src/types/constants.ts, packages/salesforcedx-vscode-soql/test/vscode-integration/client/completion.test.ts
=> fix: revert sfdx folder to use .sfdx again

packages/salesforcedx-sobjects-faux-generator/src/generator/configUtil.ts, packages/salesforcedx-sobjects-faux-generator/src/transformer/transformerFactory.ts, packages/salesforcedx-utils-vscode/src/types/constants.ts, packages/salesforcedx-vscode-core/src/commands/baseDeployRetrieve.ts, packages/salesforcedx-vscode-core/src/commands/templates/libraryBaseTemplateCommand.ts, packages/salesforcedx-vscode-core/src/decorators/scratch-org-decorator.ts, packages/salesforcedx-vscode-core/src/util/authInfo.ts, packages/salesforcedx-vscode-core/src/util/configUtil.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/baseDeployRetrieve.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/util/cliConfiguration.test.ts, packages/salesforcedx-vscode-soql/test/vscode-integration/client/completion.test.ts
Incorporates PR feedback from https://github.com/forcedotcom/salesforcedx-vscode/pull/4325
=> PR feedback for salesforce/core config values branch 

packages/salesforcedx-utils-vscode/src/helpers/index.ts, packages/salesforcedx-utils-vscode/src/helpers/utils.ts, packages/salesforcedx-utils-vscode/src/requestService/requestService.ts, packages/salesforcedx-vscode-core/src/orgPicker/orgList.ts, packages/salesforcedx-vscode-core/src/util/index.ts, packages/salesforcedx-vscode-core/src/util/metadataDictionary.ts, packages/salesforcedx-vscode-core/src/util/orgUtil.ts, packages/salesforcedx-vscode-core/test/vscode-integration/orgPicker/orgList.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/util/orgUtil.test.ts
This PR updates `checkForExpiredOrgs()` to use OrgAuthorization, which was a change with a recent merge.
No GitHub issue for this PR
=> fix: update for checkForExpiredOrgs() to use OrgAuthorization

packages/salesforcedx-vscode-core/src/commands/auth/forceAuthLogout.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/auth/forceAuthAccessTokenLogin.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/auth/forceAuthLogout.test.ts
Update the forceAuthAccessTokenLogin test to reflect the changes from the core v3 update. 
@W-11553059@
=> chore: fix forceAuthAccessTokenLogin tests

package-lock.json, package.json
update-workspaces-to-typescript-project-references-to-2.8.2
=> fix: update-workspaces-to-typescript-project-references-to-2.8.2

.git2gus/config.json
Bump the git2gus setting for the major release. 
n/a
=> chore: update git2gus for major release

.github/workflows/createReleaseBranch.yml, .github/workflows/publishBetaRelease.yml, .github/workflows/slackNotification.yml
Update existing Github actions to use the secrets from the org level instead of the repo.
@W-11949791@ continued
=> chore: update secrets in GHA to use org values

.github/workflows/slackNotification.yml
- updates secrets in order to represent better what they're used for
[#109](https://github.com/forcedotcom/easywriter/issues/109), @W-12213077@
=> chore: secrets update

contributing/publishing.md
Typos and updates to what the workflows actually do.
@W-12370302@
=> chore: update publishing.md

docs/_articles/en/codebuilder/about.md, docs/_articles/en/codebuilder/cb-start.md
Removed waitlist information and consolidated "Important Considerations" to a single topic.
Made an update to Code Builder docs regarding waitlists. 
#<Insert GitHub Issue>, @W-12545655@
=> Code Builder Beta Doc update

CHANGELOG.md, contributing/publishing.md
Change log and publishing updates
Updates to publishing.ms and changelog.md
@W-12557973@
* Changed the URL in CHANGELOG.md to a relative path.
(the link now works in branches)
* Made minor updates to the publishing doc (contributing/publishing.md), mostly comprising of minor formatting changes and some updated steps in the "Merging the Release Branch into Main" and "Publishing Main" sections.
=> Change log and publishing updates

package-lock.json, packages/salesforcedx-vscode-core/package.json
###What does this PR do?
Bumps @heroku/functions-core from 0.5.1 to 0.7.0
###What issues does this PR fix or reference?
@W-12514513@ for the 0.7.0 release
###Changes:
heroku/sf-functions-core/compare/v0.5.1...v0.7.0
External contribution from https://github.com/forcedotcom/salesforcedx-vscode/pull/4708
=> chore: update heroku functions core 0.7.0

packages/salesforcedx-vscode/CHANGELOG.md
=> add: changelog for v57.6.0

.github/CODEOWNERS
Update the CODEOWNERS file to reflect the github team name change. 
@W-12703646@
PRs didn't require an approval from ide-experience
PRs do require an approval from ide-experience
=> chore: update code owner file

scripts/change-log-generator-utils.js, scripts/create-release-branch.js
Fix the auto-generation of changelog content
Changelog content was not getting generated.
Changelog content is auto-generated.
=> fix: changelog-auto generation

package-lock.json, packages/salesforcedx-sobjects-faux-generator/package.json, packages/salesforcedx-utils-vscode/package.json, packages/salesforcedx-vscode-apex-debugger/package.json, packages/salesforcedx-vscode-apex-replay-debugger/package.json, packages/salesforcedx-vscode-apex/package.json, packages/salesforcedx-vscode-core/package.json, packages/salesforcedx-vscode-lightning/package.json, packages/salesforcedx-vscode-lwc/package.json, packages/salesforcedx-vscode-soql/package.json
* Bumps core across the packages so that it is at latest and compiles across the vsce monorepo
* This PR is a requirement for #4773 
@W-12971145@
=> chore: bump core lib

package-lock.json, packages/salesforcedx-vscode-lightning/package.json, packages/salesforcedx-vscode-lwc/package.json
Updates the lightning language server versions to 4.6.0, to pick up forcedotcom/lightning-language-server#566.
@W-13089840@
=> feat: update lightning language server version

packages/salesforcedx-vscode-core/src/commands/forceSourceDeployManifest.ts, packages/salesforcedx-vscode-core/src/commands/forceSourceDeploySourcePath.ts, packages/salesforcedx-vscode-core/src/commands/forceSourceRetrieveMetadata/forceSourceRetrieveCmp.ts, packages/salesforcedx-vscode-core/src/commands/templates/forceApexClassCreate.ts, packages/salesforcedx-vscode-core/src/commands/templates/forceApexTriggerCreate.ts, packages/salesforcedx-vscode-core/src/commands/templates/forceLightningAppCreate.ts, packages/salesforcedx-vscode-core/src/commands/templates/forceLightningComponentCreate.ts, packages/salesforcedx-vscode-core/src/commands/templates/forceLightningEventCreate.ts, packages/salesforcedx-vscode-core/src/commands/templates/forceLightningInterfaceCreate.ts, packages/salesforcedx-vscode-core/src/commands/templates/forceLightningLwcCreate.ts, packages/salesforcedx-vscode-core/src/commands/templates/forceLightningLwcTestCreate.ts, packages/salesforcedx-vscode-core/src/commands/templates/forceVisualforceComponentCreate.ts, packages/salesforcedx-vscode-core/src/commands/templates/forceVisualforcePageCreate.ts, packages/salesforcedx-vscode-core/src/commands/util/compositePostconditionChecker.ts, packages/salesforcedx-vscode-core/src/commands/util/createComponentCount.ts, packages/salesforcedx-vscode-core/src/commands/util/formatException.ts, packages/salesforcedx-vscode-core/src/commands/util/index.ts, packages/salesforcedx-vscode-core/src/commands/util/overwriteComponentPrompt.ts, packages/salesforcedx-vscode-core/src/commands/util/sourcePathStrategies.ts, packages/salesforcedx-vscode-core/src/commands/util/timestampConflictChecker.ts, packages/salesforcedx-vscode-core/src/util/metadataDictionary.ts, packages/salesforcedx-vscode-core/test/jest/commands/deployExecutor.test.ts, packages/salesforcedx-vscode-core/test/jest/commands/templates/forceApexClassCreate.test.ts, packages/salesforcedx-vscode-core/test/jest/commands/templates/forceApexTriggerCreate.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceSourceDeploySourcePath.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/util/postconditionCheckers.test.ts
Absolutely nothing.
No code was modified, it was only moved.
This is for files in `packages/salesforcedx-vscode-core/src/commands/util`
Please note that not all files in `commands/utils` were spilt up - the file count grew large and I'm going to split this up into two PRs to make it easier for the reviewers to review.
@W-10273533@
=> Break up files in salesforcedx vscode core/src/commands/util

package-lock.json, packages/salesforcedx-vscode-core/package.json
Updates the `@salesforce/templates` version to at least 57.1.2, to pick up forcedotcom/salesforcedx-templates#555.
@W-13144541@
=> fix: update @salesforce/templates version

packages/salesforcedx-vscode-core/src/commands/baseDeployRetrieve.ts, packages/salesforcedx-vscode-core/src/commands/forceSourceDeployManifest.ts, packages/salesforcedx-vscode-core/src/commands/forceSourceDeploySourcePath.ts, packages/salesforcedx-vscode-core/src/commands/forceSourceRetrieveManifest.ts, packages/salesforcedx-vscode-core/src/commands/forceSourceRetrieveSourcePath.ts, packages/salesforcedx-vscode-core/src/conflict/metadataCacheService.ts, packages/salesforcedx-vscode-core/src/services/sdr/componentSetUtils.ts, packages/salesforcedx-vscode-core/src/sfdxProject/sfdxPackageDirectories.ts, packages/salesforcedx-vscode-core/src/sfdxProject/sfdxProjectConfig.ts, packages/salesforcedx-vscode-core/test/jest/conflict/metadataCacheService.test.ts, packages/salesforcedx-vscode-core/test/jest/services/sdr/componentSetUtils.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/baseDeployRetrieve.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceSourceDeployManifest.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceSourceDeploySourcePath.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceSourceRetrieveSourcePath.test.ts
Reverts forcedotcom/salesforcedx-vscode#4801
=> Revert "Org browser ignores sfdx project.json api version"

.github/workflows/unitTestsLinux.yml, .github/workflows/unitTestsWindows.yml
Bump the memory allow for node processes when running unit tests in GHA
@W-13513042@
Unit tests were failing due to memory constraints
Unit tests pass.
=> chore: bump GHA memory for unit tests

package-lock.json, packages/salesforcedx-vscode-lightning/package.json, packages/salesforcedx-vscode-lwc/package.json
Updates the version of the lightning language server that just went from relying on @lwc/compiler to @lwc/metadata.
@W-13512133@
=> feat: bump lightning-language-server version

contributing/publishing.md
Updates publishing.md to include how we can update changelog from browser.
@W-13712605@
=> chore: update publishing doc

packages/salesforcedx-vscode-core/src/commands/baseDeployRetrieve.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/baseDeployRetrieve.test.ts
fixes issue that displayed errors in the problems tab even after a successful deployment
@W-13553883@
closes https://github.com/forcedotcom/salesforcedx-vscode/issues/4904
- errors in problems tab not cleared after successful deployment
- errors in problems tab cleared after successful deployment
=> fix: fix for problems tab not clearing errors

.github/workflows/e2e.yml
This PR modifies the existing End To End workflow to run tests on windows-latest in addition to macos-latest.
@W-13751849@
End To End Test were running only on macOs-latest.
End To End Test runs on two remote env - macos- latest & windows-latest
=> feat: add e2e run on windows

.github/workflows/e2e.yml
Reverts forcedotcom/salesforcedx-vscode#4978
=> Revert "feat: add e2e run on windows"

.github/workflows/e2e.yml
Adds windows and ubuntu in os environment.
Handles the job failures. Fail-fast is set to be false, which allows the e2e tests to run on three environments independently. Tests are completed even when others fail.
@W-13751849@
Tests were running only on macos env.
Tests run independently on macos, windows and ubuntu environments.
=> chore: add runners

packages/salesforcedx-vscode-lwc/resources/static/js-meta.xsd
Remove the stale pilot notice from the `analytics__Dashboard` lwc target type description, which is what shows for code-completion and hover text in the `js-meta.xml` file.
Fixes @W-13867886@
=> fix: analytics dashboard lwcs are GA

packages/salesforcedx-vscode-core/src/commands/isvdebugging/bootstrapCmd.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/isvdebugger/bootstrapCmd.test.ts
Changes the way we build the commands for ISV debugger
@W-13905666@
=> fix: colon instead of spacing for isv commands

packages/salesforcedx-utils-vscode/src/helpers/env.ts, packages/salesforcedx-utils-vscode/src/helpers/index.ts, packages/salesforcedx-vscode-core/src/commands/auth/forceAuthDevHub.ts, packages/salesforcedx-vscode-core/src/commands/auth/forceAuthWebLogin.ts, packages/salesforcedx-vscode-core/src/commands/forceOrgOpen.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/auth/forceAuthDevHub.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/auth/forceAuthWebLogin.test.ts, packages/salesforcedx-vscode-core/test/vscode-integration/commands/forceOrgOpen.test.ts, packages/salesforcedx-vscode-lwc/src/commands/forceLightningLwcPreview.ts, packages/salesforcedx-vscode-lwc/test/jest/commands/forceLightningLwcPreview.test.ts, packages/salesforcedx-vscode-lwc/test/vscode-integration/commands/forceLightningLwcPreview.test.ts
Updates env var SFDX_CONTAINER_MODE to SF style --> SF_CONTAINER_MODE
#5003 , @W-13897591@
env var SFDX_CONTAINER_MODE
env var SF_CONTAINER_MODE
=> fix: update to sf style env var

packages/salesforcedx-vscode-soql/test/vscode-integration/client/client.test.ts
Increases wait time in soql test to stop it from failing intermittently.
@W-13908566@
SOQL Windows integration test failing
SOQL Windows integration test not failing
=> fix: fix soql int test

packages/salesforcedx-vscode/CHANGELOG.md
new change log.
<!--- PR title should follow the pattern: <type>(optional scope): <description>.
New change log entry for 58.11
#<Insert GitHub Issue>, @W-13951558@
No change log
new change log.
=> docs: change log for 58.11

packages/salesforcedx-utils-vscode/test/unit/telemetry/MockExtensionContext.ts, packages/salesforcedx-vscode-core/test/vscode-integration/telemetry/MockExtensionContext.ts, packages/salesforcedx-vscode-lwc/test/vscode-integration/activation/MockExtensionContext.ts
Fixes the build error
Adds a method getScoped in class MockEnvironmentVariableCollection
@W-14088801@
Build is failing: [Run](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/6115542983) ⛔ 
Build is passing: [Run](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/6115787032) ✅
=> chore: fix build

packages/salesforcedx-vscode-apex/package.nls.json, packages/salesforcedx-vscode-apex/src/messages/i18n.ts
Removes a couple of typos from messages
@W-14067954@
=> fix: remove unneeded comma in messages

docs/_articles/en/apex/language-server.md, docs/_articles/en/bugs-and-feedback.md, docs/_articles/en/codebuilder/cb-start.md, docs/_articles/en/deploy-changes/detect-conflicts.md, docs/_articles/en/deploy-changes/metadata-operations.md, docs/_articles/en/einstein/einstein-apex.md, docs/_articles/en/einstein/einstein-setup.md, docs/_articles/en/functions/overview.md, docs/_articles/en/lwc/lwc-get-started.md, docs/_articles/en/sf-dev-env/org-browser.md, docs/_articles/en/sf-dev-env/vscode-commands.md, docs/_articles/en/soql/soql-tasks.md, docs/_articles/en/vscode-desktop/desktop-intro.md, docs/_articles/en/vscode-desktop/java-setup.md, docs/_articles/ja/codebuilder/about.md, docs/_articles/ja/codebuilder/cb-setup.md, docs/_articles/ja/codebuilder/cb-start.md, docs/_articles/ja/einstein/einstein-apex.md, docs/_articles/ja/einstein/einstein-setup.md, docs/_articles/ja/functions/overview.md, docs/_articles/ja/soql/soql-tasks.md, docs/_data/sidebar.yml
Replaces all the relative links to the images folder. 
#<Insert GitHub Issue>, @W-14331081@
Broken images link causes images to not render in doc on dev docs website
Images render correctly.
=> docs: update relative links to images folder

docs/_articles/en/codebuilder/cb-setup.md
requested based on https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001czuPgYAI/view
We were asked to move information for government cloud from setup to a different section.
#<Insert GitHub Issue>, @W-14350330@
Doc updated.
=> docs: gov cloud update

lerna.json, package-lock.json, packages/salesforcedx-apex-debugger/package.json, packages/salesforcedx-apex-replay-debugger/package.json, packages/salesforcedx-sobjects-faux-generator/package.json, packages/salesforcedx-test-utils-vscode/package.json, packages/salesforcedx-utils-vscode/package.json, packages/salesforcedx-utils/package.json, packages/salesforcedx-visualforce-language-server/package.json, packages/salesforcedx-visualforce-markup-language-server/package.json, packages/salesforcedx-vscode-apex-debugger/package.json, packages/salesforcedx-vscode-apex-replay-debugger/package.json, packages/salesforcedx-vscode-apex/package.json, packages/salesforcedx-vscode-core/package.json, packages/salesforcedx-vscode-expanded/package.json, packages/salesforcedx-vscode-lightning/package.json, packages/salesforcedx-vscode-lwc/package.json, packages/salesforcedx-vscode-soql/package.json, packages/salesforcedx-vscode-visualforce/package.json, packages/salesforcedx-vscode/package.json, packages/system-tests/package.json
This reverts commit d3c97e1b64d7e71c7f90bf97e56982fbb48af938.
revert that patch commit. 
#5222
=> Revert "chore: update to version 59.4.1"

packages/salesforcedx-apex-debugger/test/unit/core/breakpointService.test.ts, packages/salesforcedx-apex-debugger/test/unit/core/sessionService.test.ts
@W-14464952@
bypass flaky tests for the moment
=> fix: bypass tests

packages/salesforcedx-vscode-apex-debugger/package.json, packages/salesforcedx-vscode-apex-replay-debugger/package.json, packages/salesforcedx-vscode-apex/package.json, packages/salesforcedx-vscode-core/package.json, packages/salesforcedx-vscode-lightning/package.json, packages/salesforcedx-vscode-lwc/package.json, packages/salesforcedx-vscode-soql/package.json, packages/salesforcedx-vscode-visualforce/package.json
Remove the `-P ./tsconfig.json` for target vscode:extension
@W-14536918@
=> chore: build failure on vscode:package

package-lock.json, packages/salesforcedx-vscode-lightning/package.json, packages/salesforcedx-vscode-lwc/package.json
- bumps LLS to 4.7.3
@W-14196500@
LLS uses node 16
LLS uses node 18
=> chore: bump lls to 4.7.3

packages/salesforcedx-vscode-apex/fix-these-rules.json, packages/salesforcedx-vscode-apex/src/codecoverage/colorizer.ts, packages/salesforcedx-vscode-apex/src/commands/forceAnonApexExecute.ts, packages/salesforcedx-vscode-apex/src/commands/forceApexLogGet.ts, packages/salesforcedx-vscode-apex/src/commands/forceApexTestRun.ts, packages/salesforcedx-vscode-apex/src/commands/forceApexTestRunCodeAction.ts, packages/salesforcedx-vscode-apex/src/commands/forceApexTestSuite.ts, packages/salesforcedx-vscode-apex/src/commands/forceLaunchApexReplayDebuggerWithCurrentFile.ts, packages/salesforcedx-vscode-apex/src/embeddedSoql/soqlCompletion.ts, packages/salesforcedx-vscode-apex/src/index.ts, packages/salesforcedx-vscode-apex/src/languageServer.ts, packages/salesforcedx-vscode-apex/src/languageServerOrphanHandler.ts, packages/salesforcedx-vscode-apex/src/languageUtils/javaDocSymbols.ts, packages/salesforcedx-vscode-apex/src/languageUtils/languageClientUtils.ts, packages/salesforcedx-vscode-apex/src/languageUtils/languageServerUtils.ts, packages/salesforcedx-vscode-apex/src/messages/index.ts, packages/salesforcedx-vscode-apex/src/requirements.ts, packages/salesforcedx-vscode-apex/src/settings.ts, packages/salesforcedx-vscode-apex/src/testRunCache/forceApexTestRunCacheService.ts, packages/salesforcedx-vscode-apex/test/vscode-integration/commands/forceApexTestRunCodeAction.test.ts, packages/salesforcedx-vscode-apex/test/vscode-integration/embeddedSoql/soqlCompletion.test.ts, packages/salesforcedx-vscode-apex/test/vscode-integration/views/testDataUtil.ts
Apply arrow function refactor to apex extension
@W-14564471@
=> fix: refactor to arrow functions

packages/salesforcedx-sobjects-faux-generator/fix-these-rules.json, packages/salesforcedx-sobjects-faux-generator/src/describe/sObjectDescribe.ts, packages/salesforcedx-sobjects-faux-generator/src/messages/index.ts, packages/salesforcedx-sobjects-faux-generator/test/unit/fauxClassGenerator.test.ts, packages/salesforcedx-sobjects-faux-generator/test/unit/soqlMetadataGenerator.test.ts
@W-14564471@
refactor sobject faux generator to arrow functions
=> chore: refactor to arrow functions

packages/salesforcedx-utils-vscode/fix-these-rules.json, packages/salesforcedx-utils-vscode/src/cli/commandExecutor.ts, packages/salesforcedx-utils-vscode/src/commands/progressNotification.ts, packages/salesforcedx-utils-vscode/src/date/format.ts, packages/salesforcedx-utils-vscode/src/helpers/env.ts, packages/salesforcedx-utils-vscode/src/helpers/extensionUris.ts, packages/salesforcedx-utils-vscode/src/helpers/paths.ts, packages/salesforcedx-utils-vscode/src/helpers/utils.ts, packages/salesforcedx-utils-vscode/src/helpers/validations.ts, packages/salesforcedx-utils-vscode/src/messages/index.ts, packages/salesforcedx-utils-vscode/src/telemetry/cliConfiguration.ts, packages/salesforcedx-utils-vscode/src/workspaces/rootWorkspace.ts, packages/salesforcedx-utils-vscode/src/workspaces/workspaceUtils.ts
@W-14564471@
Refactor vscode-utils to use arrow functions
=> chore: vscode-utils arrow functions

packages/salesforcedx-test-utils-vscode/fix-these-rules.json, packages/salesforcedx-test-utils-vscode/src/orgUtils.ts, packages/salesforcedx-test-utils-vscode/src/testrunner.ts
@W-14564471@
refactor to use arrow functions
=> chore: refactor test utils for arrow functions

packages/salesforcedx-vscode-visualforce/fix-these-rules.json, packages/salesforcedx-vscode-visualforce/src/extension.ts, packages/salesforcedx-vscode-visualforce/src/tagClosing.ts, packages/salesforcedx-vscode-visualforce/test/vscode-integration/fileAssociations.test.ts
@W-14564471@
Refactor function to arrow functions where appropriate
=> chore: refactor vf ext to use arrow functions

packages/salesforcedx-vscode-lightning/fix-these-rules.json, packages/salesforcedx-vscode-lightning/src/index.ts, packages/salesforcedx-vscode-lightning/src/messages/index.ts, packages/salesforcedx-vscode-lightning/test/unit/package/packageDependencies.test.ts, packages/salesforcedx-vscode-lightning/test/vscode-integration/extension.test.ts, packages/salesforcedx-vscode-lightning/test/vscode-integration/hover.test.ts, packages/salesforcedx-vscode-lightning/test/vscode-integration/intellisense.test.ts, packages/salesforcedx-vscode-lightning/test/vscode-integration/navigation.test.ts
@W-14564471@
Refactor to arrow functions
=> chore: refactor to arrow function vscode lightning

packages/salesforcedx-apex-debugger/fix-these-rules.json, packages/salesforcedx-apex-debugger/src/messages/index.ts, packages/salesforcedx-apex-debugger/test/integration/adapter.test.ts, packages/salesforcedx-apex-debugger/test/unit/adapter/apexDebugVariablesHandling.test.ts, packages/salesforcedx-apex-debugger/test/unit/commands/baseDebuggerCommand.test.ts
@W-14564471@
refactor apex debugger function defs to arrow functions
=> chore: apex debugger arrow functions

packages/salesforcedx-vscode-apex-debugger/fix-these-rules.json, packages/salesforcedx-vscode-apex-debugger/src/context/isvContext.ts, packages/salesforcedx-vscode-apex-debugger/src/index.ts, packages/salesforcedx-vscode-apex-debugger/src/messages/index.ts, packages/salesforcedx-vscode-apex-debugger/test/vscode-integration/adapter/MockApexExtension.ts
@W-14564471@
Refactor vscode apex debugger to arrow functions
=> chore: move vscode apex debugger to arrow functions

SHA256.md
This reverts commit 367019dea7e163d09596f47b73aaff6345f33c6b.
=> Revert extra SHA256 commit on main branch

docs/_articles/en/einstein/einstein-example-prompts.md
well, the table doesn't render correctly so redoing.
#<Insert GitHub Issue>, @W-14740530@
Table looks funky
deleted table format
=> docs: fix bombed table rendering

docs/_articles/en/codebuilder/cb-setup.md
how to buy additional code builder licenses.
information about additional code builder licenses. 
#<Insert GitHub Issue>, @W-14765484@
No information about additional licenses. 
new information.
=> docs: add on license information

package-lock.json, packages/salesforcedx-sobjects-faux-generator/package.json, packages/salesforcedx-utils-vscode/package.json, packages/salesforcedx-vscode-apex-debugger/package.json, packages/salesforcedx-vscode-apex-replay-debugger/package.json, packages/salesforcedx-vscode-apex/package.json, packages/salesforcedx-vscode-core/package.json, packages/salesforcedx-vscode-lightning/package.json, packages/salesforcedx-vscode-lwc/package.json, packages/salesforcedx-vscode-soql/package.json
- Bumps SDR to 10.3.3
- Bumps core to 6.5.2
- Bumps source-tracking to 5.1.11
@W-14901910@, Closes #5364
=> feat: bump SDR to catch new expression sets

docs/_articles/en/apex/interactive-debugger.md, docs/_articles/en/deploy-changes/metadata-operations.md, docs/_articles/en/localdev/set-up-lwc-local-dev.md, docs/_articles/en/sf-dev-env/byotemplate.md, docs/_articles/en/source-control/source-format.md
Reverts forcedotcom/salesforcedx-vscode#5430
=> Revert "fix: update "sfdx" examples in docs to their "sf" equivalents"

package-lock.json, packages/salesforcedx-apex-debugger/package.json, packages/salesforcedx-apex-replay-debugger/package.json, packages/salesforcedx-sobjects-faux-generator/package.json, packages/salesforcedx-test-utils-vscode/package.json, packages/salesforcedx-utils-vscode/package.json, packages/salesforcedx-visualforce-language-server/package.json, packages/salesforcedx-visualforce-markup-language-server/package.json, packages/salesforcedx-vscode-apex-debugger/package.json, packages/salesforcedx-vscode-apex-replay-debugger/package.json, packages/salesforcedx-vscode-apex/package.json, packages/salesforcedx-vscode-core/package.json, packages/salesforcedx-vscode-expanded/package.json, packages/salesforcedx-vscode-lightning/package.json, packages/salesforcedx-vscode-lwc/package.json, packages/salesforcedx-vscode-soql/package.json, packages/salesforcedx-vscode-visualforce/package.json, packages/salesforcedx-vscode/package.json, packages/system-tests/package.json
@W-15091730@
Updates the vscode engine version to 1.82.0 or greater
There should be not change in functionality
=> fix: update vscode engine to 1.82.0

packages/salesforcedx-utils-vscode/src/cli/parsers/projectDeployStartResultParser.ts, packages/salesforcedx-utils-vscode/src/cli/parsers/projectRetrieveStartResultParser.ts
- Fixes display of conflicts for push and pull commands
@W-14717018@
- No conflicts shown in output table upon conflicts
- Conflicts correctly shown in output table upon conflicts
=> fix: push and pull conflicts not shown

package-lock.json, packages/salesforcedx-vscode-lightning/package.json, packages/salesforcedx-vscode-lwc/package.json
- Bumps LLS to catch up with https://github.com/forcedotcom/lightning-language-server/pull/584
=> fix: bump lls to catch pr 584 which Add Edu PostBenefitAssignment adapter

package-lock.json, packages/salesforcedx-vscode-apex-replay-debugger/package.json, packages/salesforcedx-vscode-apex/package.json
This PR bumps apex-node to v4.
@W-15354956@
apex-node version is v3
apex-node version is v4
=> chore: bump apex-node to v4

docs/_articles/en/codebuilder/about.md, docs/_articles/en/codebuilder/cb-setup.md, docs/_articles/ja/codebuilder/about.md, docs/_articles/ja/codebuilder/cb-setup.md
Update doc to clarify that Code Builder doesn't work in sandboxes. You must deploy code to a sandbox.
#@W-15577815@
=> docs: update codebuilder usage in sandboxes

package-lock.json, packages/salesforcedx-vscode-core/package.json, packages/salesforcedx-vscode-core/package.nls.ja.json, packages/salesforcedx-vscode-core/package.nls.json, packages/salesforcedx-vscode-core/src/index.ts, packages/salesforcedx-vscode-core/src/services/getCoreLoggerService.ts, packages/salesforcedx-vscode-core/src/services/index.ts, packages/salesforcedx-vscode-core/test/jest/services/getCoreLoggerService.test.ts
Establish the vscode command that will be used to fetch an instance of a logger
@W-15295896@
This work is preparation for follow-on work items, so no change in behavior.
=> chore: define vscode command for get logger

packages/salesforcedx-vscode-core/src/commands/templates/apexGenerateClass.ts, packages/salesforcedx-vscode-core/src/commands/templates/apexGenerateUnitTestClass.ts, packages/salesforcedx-vscode-core/src/commands/util/parameterGatherers.ts, packages/salesforcedx-vscode-core/test/jest/commands/templates/apexGenerateClass.test.ts, packages/salesforcedx-vscode-core/test/jest/commands/templates/apexGenerateUnitTestClass.test.ts
Opening a new PR to allow tests to run
See #5544 for implementation details.
=> feat: do not prompt for output dir when called from context menu #5544

docs/_articles/en/apex/replay-debugger.md
add a consideration about file versions.
@W-15655239@
no consideration about file version and debug log match.
new consideration
=> docs: update replay debugger content

packages/salesforcedx-vscode-core/src/commands/source/viewChanges.ts, packages/salesforcedx-vscode-core/test/jest/commands/source/viewChanges.test.ts
Remove some duplicate code
Change covered existing unit tests
@W-14866436@
=> refactor: refactor dup code from viewChanges cmd

docs/_articles/en/codebuilder/about.md
Add a link to the release notes for Code Builder
@W-15705045@
=> docs: add link to Code Builder release notes

.vscode/settings.json
Modify `.vscode/settings.json` to include the setting `"files.insertFinalNewline": true` so that our repo defaults to having newlines added at the end of files.
=> chore: update settings.json to add newline at end of files

docs/_articles/en/einstein/einstein-faq.md
remove a line of code being used to improve E4D. Per this -- https://trailhead.salesforce.com/trailblazer-community/feed/0D54V00007ZBmP7
#<Insert GitHub Issue>, @W-15678451@
FAQ not updated.
FAQ Updated.
=> docs: update einstein faq

package-lock.json, packages/salesforcedx-vscode-apex-debugger/.eslintrc.json, packages/salesforcedx-vscode-apex-debugger/esbuild.config.js, packages/salesforcedx-vscode-apex-debugger/package.json, packages/salesforcedx-vscode-apex-replay-debugger/.eslintrc.json, packages/salesforcedx-vscode-apex-replay-debugger/esbuild.config.js, packages/salesforcedx-vscode-apex-replay-debugger/package.json, packages/salesforcedx-vscode-apex/.eslintrc.json, packages/salesforcedx-vscode-apex/esbuild.config.js, packages/salesforcedx-vscode-apex/package.json, packages/salesforcedx-vscode-core/.eslintrc.json, packages/salesforcedx-vscode-core/esbuild.config.js, packages/salesforcedx-vscode-core/package.json, packages/salesforcedx-vscode-lightning/.eslintrc.json, packages/salesforcedx-vscode-lightning/esbuild.config.js, packages/salesforcedx-vscode-lightning/package.json, packages/salesforcedx-vscode-lwc/.eslintrc.json, packages/salesforcedx-vscode-lwc/esbuild.config.js, packages/salesforcedx-vscode-lwc/package.json, packages/salesforcedx-vscode-soql/.eslintrc.json, packages/salesforcedx-vscode-soql/esbuild.config.js, packages/salesforcedx-vscode-soql/package.json
@W-15635210@
The eslint rules are not set for node.
The bundling scripts are string within package.json which are not adjustable
get rid of the issues above
=> Chore: update in order to facilitate bundling

.github/workflows/coreE2E.yml
- Adds new e2e subcategory for miscellaneous commands
@W-14344606@
=> chore: add miscellaneous subcategory in Core E2E Tests

packages/salesforcedx-vscode-apex-replay-debugger/package.json, packages/salesforcedx-vscode-apex/package.json, packages/salesforcedx-vscode-lwc/package.json
Reverts the ordering of the following package.json files from alphabetical order to the original order:
1. packages/salesforcedx-vscode-apex/package.json
2. packages/salesforcedx-vscode-apex-replay-debugger/package.json
3. packages/salesforcedx-vscode-lwc/package.json
@W-15345797@
=> refactor: revert package.json files to original ordering instead of alphabetical

docs/_articles/en/codebuilder/cb-setup.md
Document the number of Code Builder licenses associated with add-ons
@W-15794780@
=> docs: Code Builder licenses for add-ons

.gitignore, packages/salesforcedx-vscode-apex/src/messages/i18n.ja.ts, packages/salesforcedx-vscode-apex/src/messages/i18n.ts, packages/salesforcedx-vscode-apex/src/requirements.ts, packages/salesforcedx-vscode-apex/test/jest/languageUtils/requirements.test.ts
@W-14486693@
Add support for java 21
Should be no functional changes
=> feat: add java v 21 support for apex lsp

packages/salesforcedx-vscode-core/test/jest/telemetry/MockExtensionContext.ts, packages/salesforcedx-vscode-core/test/vscode-integration/telemetry/MockExtensionContext.ts, packages/salesforcedx-vscode-core/test/vscode-integration/telemetry/index.test.ts, packages/salesforcedx-vscode-lwc/test/vscode-integration/activation/MockExtensionContext.ts
Build was failing due to compile error on a mismatched type in tests
=> chore: fix build [skip-validation]

.git2gus/config.json
@W-15476622@
bump default build for git2gus
=> chore: update git2gus default build for v61

package-lock.json, packages/salesforcedx-vscode-core/package.json
@W-15476622@
bump templates to v 61
=> fix: bump dx templates to v61

package-lock.json, packages/salesforcedx-vscode-apex-replay-debugger/esbuild.config.js, packages/salesforcedx-vscode-apex-replay-debugger/package.json, packages/salesforcedx-vscode-apex/esbuild.config.js, packages/salesforcedx-vscode-apex/package.json
bump apex-node to 6.1.2 and resolve the issue caused by bfj from apex-node v6.1.2
@W-16002826@
apex-node is v6.0.1
apex-node v6.1.2
=> feat: bump apex-node to 6.1.2

package-lock.json, packages/salesforcedx-sobjects-faux-generator/package.json, packages/salesforcedx-utils-vscode/package.json, packages/salesforcedx-vscode-apex-debugger/package.json, packages/salesforcedx-vscode-apex-replay-debugger/package.json, packages/salesforcedx-vscode-apex/package.json, packages/salesforcedx-vscode-core/package.json, packages/salesforcedx-vscode-lightning/package.json, packages/salesforcedx-vscode-lwc/package.json, packages/salesforcedx-vscode-soql/package.json
Bump sdr and related dependencies to fix the issue that the action of deploying MD files forever deploys the first-time snapshot. 
@W-15952068@
The action of deploying MD files forever deploys the first-time snapshot. 
It will deploy MD with the correct content.
=> fix: bump sdr to resolve the issue of deploying MD files

docs/_articles/en/einstein/einstein-troubleshoot.md
We updated the required CLI Integration extension version.
This PR updates the Salesforce CLI extension version 
@W-16162342@
=> Update required Salesforce CLI Integration extension version

package-lock.json, packages/salesforcedx-sobjects-faux-generator/package.json, packages/salesforcedx-utils-vscode/package.json, packages/salesforcedx-vscode-apex-replay-debugger/package.json, packages/salesforcedx-vscode-apex/package.json, packages/salesforcedx-vscode-core/package.json, packages/salesforcedx-vscode-lightning/package.json, packages/salesforcedx-vscode-lwc/package.json, packages/salesforcedx-vscode-soql/package.json
Pulls in the fix in https://github.com/forcedotcom/sfdx-core/pull/1098
@W-16083844@
=> fix: bump @salesforce/core to v8.1.1

.github/workflows/runE2ETest.yml
add platform specific throttle factors for e2e
@W-14867258@
=> build: add platform specific throttle factors for e2e

packages/salesforcedx-vscode-lwc/snippets/lwc-html.json
Supports lwc-record-picker
#<Insert GitHub Issue>, @W-14457297@
N/A
lwc-record-picker is supported
=> feat: support lwc-record-picker

package-lock.json, packages/salesforcedx-sobjects-faux-generator/package.json, packages/salesforcedx-utils-vscode/package.json, packages/salesforcedx-vscode-apex-replay-debugger/package.json, packages/salesforcedx-vscode-apex/package.json, packages/salesforcedx-vscode-core/package.json, packages/salesforcedx-vscode-lightning/package.json, packages/salesforcedx-vscode-lwc/package.json, packages/salesforcedx-vscode-soql/package.json
- Bumps apex-node library to catch up with last feature: new section in apex test results for test setup methods 
@W-15923420@
- new section in apex test results for test setup methods 
- new property in summary for test setup time
=> feat: new section in apex test results for test setup methods

package-lock.json, package.json
@W-16283687@
resolve node version incompatibility due to indirect dep on glob v11.
=> build: pin ovsx to 0.8.0

.github/workflows/e2eNew.yml
- Adds deploy and retrieve e2e tests to run on testesm branch
@W-16285977@
=> chore: add deploy and retrieve e2e tests to run on testesm branch

packages/salesforcedx-vscode/CHANGELOG.md
=> Release/v61.6.0 (#5700)

packages/salesforcedx-vscode-core/src/index.ts
@W-16124376@
adds an process.on handler for unhandled rejection and reports as exception in telemetry
=> fix: handle and report unhandled rejections

docs/_articles/en/vscode-desktop/recommended-extensions.md, packages/salesforcedx-vscode-expanded/README.md, packages/salesforcedx-vscode-expanded/package.json
Includes salesforce code analyzer in expanded pack
@W-16268138@
sfca not included
download expanded pack and code analyzer will be included
=> feat: include code analyzer in expanded pack

packages/salesforcedx-vscode-expanded/README.md, packages/salesforcedx-vscode/README.md
Minor cleanup for Visual Studio Marketplace READMEs for Salesforce extension packs.
1. Minor language cleanup for https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode
2. Minor language cleanup for https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode-expanded
3. Added SOQL extension to listing for Salesforce Extension Pack (Expanded)
@W-16443370@
nice READMEs
niceR READMEs
=> docs: small clarifications in Marketplace READMEs

packages/salesforcedx-apex-replay-debugger/src/adapter/apexReplayDebug.ts, packages/salesforcedx-apex-replay-debugger/src/constants.ts, packages/salesforcedx-apex-replay-debugger/src/index.ts, packages/salesforcedx-apex-replay-debugger/test/unit/adapter/apexReplayDebug.test.ts, packages/salesforcedx-vscode-apex-replay-debugger/src/index.ts, packages/salesforcedx-vscode-apex-replay-debugger/src/telemetry/telemetry.ts
- Adds more telemetry to the Apex Replay Debugger.
@W-16499105@
=> fix: add more telemetry to apex replay debugger

package-lock.json, packages/salesforcedx-vscode-lightning/package.json, packages/salesforcedx-vscode-lwc/package.json
Bumps LLS to catch up fix for right generation of jsconfig.json file
@W-15374337@
- Incorrect generation of jsconfig.json file
- Correct generation of jsconfig.json file
=> fix: bump lls to fix jsconfig issue

.github/workflows/e2e.yml, .github/workflows/runE2ETest.yml
Adds back LWC tests to the main E2E workflow so they run nightly
@W-16475385@
=> Add LWC tests to main E2E workflow

.github/workflows/e2e.yml
Adds LWC tests to workflow_dispatch options in e2e workflow
=> chore: lwc tests in workflow dispatch

packages/salesforcedx-vscode-core/src/commands/source/sourceTrackingGetStatusExecutor.ts
=> fix: forever truthy constructor for options

.github/workflows/apexE2E.yml, .github/workflows/coreE2E.yml, .github/workflows/deployRetrieveE2E.yml, .github/workflows/e2e.yml, .github/workflows/lspE2E.yml, .github/workflows/lwcE2E.yml
- Updates branch name for e2e tests to main
=> chore: rename e2e branch from testesm to main

packages/salesforcedx-utils-vscode/test/jest/telemetry/reporters/appInsights.test.ts
- Mocks os.cpus() to fix test flapper
=> test: fix unit test flapper in linux

lerna.json, package-lock.json, packages/salesforcedx-apex-debugger/package.json, packages/salesforcedx-apex-replay-debugger/package.json, packages/salesforcedx-sobjects-faux-generator/package.json, packages/salesforcedx-test-utils-vscode/package.json, packages/salesforcedx-utils-vscode/package.json, packages/salesforcedx-utils/package.json, packages/salesforcedx-visualforce-language-server/package.json, packages/salesforcedx-visualforce-markup-language-server/package.json, packages/salesforcedx-vscode-apex-debugger/package.json, packages/salesforcedx-vscode-apex-replay-debugger/package.json, packages/salesforcedx-vscode-apex/package.json, packages/salesforcedx-vscode-core/package.json, packages/salesforcedx-vscode-expanded/package.json, packages/salesforcedx-vscode-lightning/package.json, packages/salesforcedx-vscode-lwc/package.json, packages/salesforcedx-vscode-soql/package.json, packages/salesforcedx-vscode-visualforce/package.json, packages/salesforcedx-vscode/package.json, packages/system-tests/package.json
=> fix: revert v63 in deps

.github/workflows/apexE2EredHat.yml, .github/workflows/e2e.yml, .github/workflows/e2eRedHat.yml
- Makes Apex LSP run on redhat repo
=> chore: apex LSP running on redhat

.github/workflows/runE2ETest.yml
- adds missing step for setup e2e
=> chore: add missing step for setup

.github/workflows/e2e.yml, .github/workflows/e2eRedHat.yml, .github/workflows/lspE2EredHat.yml, .github/workflows/soqlE2E.yml, .gitignore
- Adds new workflow for LSP category in redhat repo
- Migrates all SOQL category to run in redhat repo
- Adds extensions folder to .gitignore to not see trash changes while doing local e2e development
@W-17032852@
=> Modify/add workflows for LSP and SOQL in redhat

.github/workflows/coreE2EredHat.yml
- Adds sfdxProjectJson to run in redhat
@W-17039293@
=> Modify workflow to add sfdxProjectJson test in redhat

.github/workflows/coreE2EredHat.yml, .github/workflows/deployRetrieveE2EredHat.yml, .github/workflows/e2eRedHat.yml
- Adds manifestBuilder to run in redhat
@W-17039237@
=> Modify workflow to add manifestBuilder test in redhat

.github/workflows/coreE2EredHat.yml
- Adds sObjectsDefinitions to run in redhat
@W-17044345@
=> Modify workflow to add sObjectsDefinitions test in redhat

.github/workflows/coreE2EredHat.yml
- Adds miscellaneous to run in redhat
@W-17039265@
=> Modify workflow to add miscellaneous test in redhat

.github/workflows/coreE2EredHat.yml
Adds authentication test to redhat
@W-17039188@
=> Modify workflow to add authentication test in redhat

.github/workflows/coreE2E.yml, .github/workflows/e2e.yml, .github/workflows/e2eRedHat.yml
- Adds templates test to redhat
- Migrates all core e2e workflow to run in redhat
@W-17041184@
=> Modify workflow to add templates test in redhat

.github/workflows/deployRetrieveE2EredHat.yml, .github/workflows/runE2ETest.yml
- Adds orgBrowser test to redhat
- Modify runE2ETests.yml to add screenshots functionality for redhat
@W-17041496@
@W-17042844@
=> Modify workflow to add orgBrowser test in redhat

.github/workflows/deployRetrieveE2EredHat.yml
- Add deployAndRetrieve E2E test
@W-17055686@
=> Modify workflow to add deployAndRetrieve test in redhat

.github/workflows/deployRetrieveE2EredHat.yml
- Add pushAndPull test in redhat
@W-17055716@
=> Modify workflow to add pushAndPull test in redhat

.github/workflows/e2eRedHat.yml, .github/workflows/lwcE2EredHat.yml
- Add runLwcTests E2E test
- LWC Tests can now also run on ubuntu and windows 🥳 
@W-17041388@
=> Modify workflow to add runLwcTests test in redhat 

.github/workflows/apexE2EredHat.yml
Add runApexTests E2E test
@W-17055421@
=> Modify workflow to add runApexTests test in redhat

.github/workflows/apexE2EredHat.yml
Add debugApexTests E2E test
@W-17055444@
=> Modify workflow to run debugApexTests in redhat

.github/workflows/apexE2EredHat.yml
- Add trailApexReplayDebugger E2E test
@W-17055663@
=> Modify workflow to run trailApexReplayDebugger in redhat

README.md, contributing/developing.md
1. Fix a broken link in the README
2. Update developing.md to say Node 20 is the minimum supported version
#5957, @W-17299438@
=> docs: update README and developing.md

README.md, contributing/developing.md, lerna.json, package-lock.json, package.json, packages/salesforcedx-apex-debugger/package.json, packages/salesforcedx-apex-replay-debugger/package.json, packages/salesforcedx-sobjects-faux-generator/package.json, packages/salesforcedx-test-utils-vscode/package.json, packages/salesforcedx-utils-vscode/package.json, packages/salesforcedx-utils/package.json, packages/salesforcedx-visualforce-language-server/package.json, packages/salesforcedx-visualforce-markup-language-server/package.json, packages/salesforcedx-vscode-apex-debugger/package.json, packages/salesforcedx-vscode-apex-replay-debugger/package.json, packages/salesforcedx-vscode-apex/package.json, packages/salesforcedx-vscode-core/package.json, packages/salesforcedx-vscode-expanded/package.json, packages/salesforcedx-vscode-lightning/package.json, packages/salesforcedx-vscode-lwc/package.json, packages/salesforcedx-vscode-soql/package.json, packages/salesforcedx-vscode-visualforce/package.json, packages/salesforcedx-vscode/package.json, packages/system-tests/package.json
Merge develop to oas for alignment
@W-0@
=> build: merge develop to oas

packages/salesforcedx-vscode-apex/src/commands/apexActionController.ts, packages/salesforcedx-vscode-apex/src/commands/metadataOrchestrator.ts, packages/salesforcedx-vscode-apex/src/openApiUtilities/schemas.ts, packages/salesforcedx-vscode-apex/test/jest/commands/metadataOrchestrator.test.ts
@W-17249057@
Add support for new property isApexOasEligible to eligibility checks.
Includes the needed jorje jar for testing.
=> fix: adjust for new eligibility properties

packages/salesforcedx-vscode-core/package.json
- Hides deploy and retrieve OAS commands
=> feat: hide deploy and retrieve oas commands

packages/salesforcedx-vscode-apex/src/languageServer.ts, packages/salesforcedx-vscode-apex/src/settings.ts
Update the configurations for class and method annotations.
@W-17429259@
there were only general annotations, which does not fit the need.
as above
=> chore: eligibility criteria for class and method annotations

packages/salesforcedx-vscode-apex/src/languageServer.ts, packages/salesforcedx-vscode-apex/src/settings.ts
Reverts forcedotcom/salesforcedx-vscode#5976
=> Revert "chore: eligibility criteria for class and method annotations"

packages/salesforcedx-vscode-apex/src/commands/apexActionController.ts, packages/salesforcedx-vscode-apex/src/commands/metadataOrchestrator.ts, packages/salesforcedx-vscode-apex/src/messages/i18n.ja.ts, packages/salesforcedx-vscode-apex/src/messages/i18n.ts
- Modifies vscode apex extension to create/update an ESR record with generated OAS spec
- Prompts user to select/type named credential for ESR record
@W-17482259@, @W-17543634@
=> feat: create/update an ESR record with generated OAS spec

packages/salesforcedx-vscode-core/package.json
Reverts forcedotcom/salesforcedx-vscode#6003 to address [this comment](https://github.com/forcedotcom/salesforcedx-vscode/pull/6003#issuecomment-2585965769)
@W-17568713@
=> Revert "fix: hide commands outside of forceapp main default"

packages/salesforcedx-utils-vscode/src/telemetry/reporters/logStream.ts
fix the error caused by parameter mismatch
=> fix: resolve call

packages/salesforcedx-vscode-apex/src/commands/apexActionController.ts
- Makes esr deployable with operations removing <ExternalServiceOperation> tags
- Removes prompt for named credential if org version is higher than 254
=> fix: make esr deployable with operations

packages/salesforcedx-vscode-apex/src/openApiUtilities/schemas.ts
@W-17645605@
moved comments from ApexClassOASGatherContextResponse and added comment property to class/method/property
=> fix: add comment property to context

packages/salesforcedx-vscode-apex/src/openApiUtilities/schemas.ts
- updates jar with changes in lsp to add comments in context
=> feat: update jar with changes in lsp to add comments in context

package-lock.json, packages/salesforcedx-sobjects-faux-generator/package.json, packages/salesforcedx-utils-vscode/package.json, packages/salesforcedx-vscode-apex-replay-debugger/package.json, packages/salesforcedx-vscode-apex/package.json, packages/salesforcedx-vscode-core/package.json, packages/salesforcedx-vscode-lightning/package.json, packages/salesforcedx-vscode-lwc/package.json, packages/salesforcedx-vscode-soql/package.json
Bump SDR to v12.14.0, STL to v7.3.0, Core to v8.8.2 in order to handle decomposed ESR metadata.
@W-17681752@
=> feat: bump SDR to v12.14.0, STL to v7.3.0, Core to v8.8.2

packages/salesforcedx-vscode-apex/src/commands/metadataOrchestrator.ts, packages/salesforcedx-vscode-apex/src/messages/i18n.ja.ts, packages/salesforcedx-vscode-apex/src/messages/i18n.ts, packages/salesforcedx-vscode-apex/src/oas/generationStrategy/methodByMethodStrategy.ts, packages/salesforcedx-vscode-apex/src/oas/generationStrategy/prompts.ts, packages/salesforcedx-vscode-apex/src/oas/generationStrategy/promptsHandler.ts, packages/salesforcedx-vscode-apex/src/oas/schemas.ts
- Ensures Salesforce changes to yaml specification are emphasized in OAS generation prompts
@W-17695231@
=> W-17695231 - chore: update prompts to ensure compliance with validation rules

packages/salesforcedx-vscode-apex/esbuild.config.js, packages/salesforcedx-vscode-apex/package.json
@W-17751384@
exclude jsonc-parser from apex ext bundle
=> fix: exclude jsonc-parser from apex bundling

packages/salesforcedx-vscode-apex/src/commands/apexActionController.ts, packages/salesforcedx-vscode-apex/src/oas/generationStrategy/prompts.ts, packages/salesforcedx-vscode-apex/src/oas/promptGenerationOrchestrator.ts
=> chore: stick to method-by-method strategy

packages/salesforcedx-vscode-apex/package.nls.ja.json, packages/salesforcedx-vscode-apex/package.nls.json, packages/salesforcedx-vscode-apex/src/commands/apexActionController.ts
- Adds beta tag to `SFDX: Create OpenAPI Document from This Class` command
@W-17771013@
=> chore: add beta tag to command label

package-lock.json, packages/salesforcedx-utils-vscode/package.json, packages/salesforcedx-vscode-apex/package.json, packages/salesforcedx-vscode-core/package.json
bump service-provider to consume CallLLMOptions
@W-17823213@
no CallLLMOptions
CallLLMOptions available with guided_json and stop_sequence
=> chore: bump service-provider to consume CallLLMOptions

.github/workflows/publishOpenVSX.yml, .github/workflows/publishVSCode.yml
Reverts forcedotcom/salesforcedx-vscode#6011
=> chore: put ctc step back to publish workflows

packages/salesforcedx-vscode-apex/src/oas/generationStrategy/json/jsonMethodByMethod.ts, packages/salesforcedx-vscode-apex/src/oas/schemas.ts
As is noticed in today's meeting, add more deterministic checks.
@W-17877257@ @W-17877388@ @W-17877277@
=> chore: remove unneeded components section,non-2xx responses,non-related request methods

packages/salesforcedx-vscode-apex/src/oas/documentProcessorPipeline/propertyCorrectionStep.ts, packages/salesforcedx-vscode-apex/test/jest/oas/propertyCorrectionStep.test.ts
@W-17909070@ remove security sections
add test to confirm
=> fix: [W-17909070] remove security sections from generated oas doc

packages/salesforcedx-vscode-apex/src/oas/generationStrategy/buildPromptUtils.ts, packages/salesforcedx-vscode-apex/src/oas/generationStrategy/formatUtils.ts, packages/salesforcedx-vscode-apex/src/oas/generationStrategy/json/jsonMethodByMethod.ts, packages/salesforcedx-vscode-apex/src/oas/generationStrategy/promptsHandler.ts, packages/salesforcedx-vscode-apex/test/jest/oas/generationStrategy/buildPromptUtils.test.ts, packages/salesforcedx-vscode-apex/test/jest/oas/generationStrategy/formatUtils.test.ts, packages/salesforcedx-vscode-apex/test/jest/oas/generationStrategy/promptsHandler.test.ts
add jest test coverage for utils in generation strategy
@W-17146736@
=> W-17146736 test: generation strategy

packages/salesforcedx-vscode-apex/src/oas/generationInteractionLogger.ts
Fix llm logging on windows
@W-17920354@
=> @W-17920354 fix: llm logging fails on windows

packages/salesforcedx-vscode-apex/package.json, packages/salesforcedx-vscode-apex/src/apexLanguageClient.ts, packages/salesforcedx-vscode-apex/src/commands/apexActionController.ts, packages/salesforcedx-vscode-apex/src/commands/metadataOrchestrator.ts, packages/salesforcedx-vscode-apex/src/oas/generationInteractionLogger.ts, packages/salesforcedx-vscode-apex/src/oas/generationStrategy/yaml/wholeClassStrategy.ts, packages/salesforcedx-vscode-apex/src/oas/schemas.ts, packages/salesforcedx-vscode-apex/test/jest/commands/metadataOrchestrator.test.ts
@W-17920354@
Modify code to properly channel uris through language client
=> [W-17920354] fix: windows bug for handling path

packages/salesforcedx-vscode-apex/src/oasUtils.ts
fix the wrong reference in problems tab in VSCode 
@W-17920354@
=> @W-17920354 fix wrong vscode url

packages/salesforcedx-utils-vscode/src/messages/index.ts, packages/salesforcedx-vscode-core/src/messages/index.ts, packages/salesforcedx-vscode-core/test/jest/telemetry/MockExtensionContext.ts, packages/salesforcedx-vscode-core/test/vscode-integration/telemetry/MockExtensionContext.ts
[skip-validate-pr] fix post merge compilation errors
=> build: fix post merge compile errors

packages/salesforcedx-vscode-apex/src/oas/documentProcessorPipeline/oasProcessor.ts, packages/salesforcedx-vscode-apex/src/oas/documentProcessorPipeline/propertyCorrectionStep.ts, packages/salesforcedx-vscode-apex/src/oasUtils.ts
Modify correction step to handle descriptions properly Change valiation command to not run corrections
@W-17952548@
=> [W-17952548] fix: properly handle missing descriptions

package-lock.json, packages/salesforcedx-utils-vscode/package.json, packages/salesforcedx-vscode-apex/package.json, packages/salesforcedx-vscode-core/package.json
@W-17971279@
bump service provider to 1.4.0
=> [W-17971279] fix: bump service provider to 1.4.0

packages/salesforcedx-vscode-apex/src/commands/apexActionController.ts, packages/salesforcedx-vscode-apex/src/oas/ExternalServiceRegistrationManager.ts, packages/salesforcedx-vscode-apex/src/oas/esrHandler.ts, packages/salesforcedx-vscode-apex/src/oasUtils.ts, packages/salesforcedx-vscode-apex/test/jest/oas/externalServiceRegistrationManager.test.ts, scripts/setup-jest.ts
- Refactor ESR handling to a new class
@W-17700700@
=> chore: W-17700700 - refactor esr handling 

eslint.config.mjs
@W-14314586@
make unused vars an error
=> chore: [W-14314586] adjust eslint rule

packages/salesforcedx-vscode-apex/package.nls.json
Fixes the name
@W-14314735@
Bad name
Good name
=> W-14314735 fix: adding 'SFDX:' to restart command name

packages/salesforcedx-vscode-apex/src/requirements.ts, packages/salesforcedx-vscode-apex/test/jest/languageUtils/requirements.test.ts
Changes allowable JVM to version 11 and greater.
@W-18194032@ #6068
=> fix: [@W-18194032@] allow jvm v11 or greater

packages/salesforcedx-vscode-automation-tests/test/specs/deployAndRetrieve.e2e.ts
Implements deploy and retrieve from context menu for ubuntu and windows
@W-17081276@
=> chore: update branch

package-lock.json, packages/salesforcedx-vscode-core/package.json
=> chore: bump @salesforce/templates to v63.0.2

package-lock.json, packages/salesforcedx-vscode-core/package.json
fixes import in lwc test
@W-15275731@, https://github.com/forcedotcom/salesforcedx-vscode/issues/5510
=> fix: W-15275731 - fix import in lwc test template

package-lock.json, packages/salesforcedx-sobjects-faux-generator/package.json, packages/salesforcedx-utils-vscode/package.json, packages/salesforcedx-vscode-apex-replay-debugger/package.json, packages/salesforcedx-vscode-apex/package.json, packages/salesforcedx-vscode-core/package.json, packages/salesforcedx-vscode-lightning/package.json, packages/salesforcedx-vscode-lwc/package.json, packages/salesforcedx-vscode-soql/package.json
- Catches up with latest for some deps
@W-18297030@
[End to End Tests](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/14511252159) ✅
=> feat: W-18297030 - bump core, sdr, st, apex-node and jsforce

packages/salesforcedx-vscode-apex/package.nls.ja.json, packages/salesforcedx-vscode-apex/package.nls.json
=> [W-18309862] fix: text for java home setting

packages/salesforcedx-vscode-apex/src/messages/i18n.ja.ts, packages/salesforcedx-vscode-apex/src/messages/i18n.ts
https://github.com/forcedotcom/salesforcedx-vscode/issues/6227, @W-18309862@
=> [W-18309862] fix: fix error message for wrong_java_version_text

packages/salesforcedx-vscode-core/package.json, packages/salesforcedx-vscode-core/src/context/packageDirectoriesContext.ts, packages/salesforcedx-vscode-core/src/index.ts, packages/salesforcedx-vscode-core/test/jest/context/packageDirectoriesContext.test.ts
=> fix: [@W-18538360@] revert explorer chgs

package-lock.json, packages/salesforcedx-vscode-automation-tests/package.json, packages/salesforcedx-vscode-automation-tests/test/specs/runApexTests.e2e.ts
=> fix: W-18542925 - update selector for checkbox in runApexTests.e2e.ts

package-lock.json, package.json, packages/salesforcedx-apex-debugger/package.json, packages/salesforcedx-apex-replay-debugger/package.json, packages/salesforcedx-sobjects-faux-generator/package.json, packages/salesforcedx-utils-vscode/package.json, packages/salesforcedx-utils/package.json, packages/salesforcedx-visualforce-language-server/package.json, packages/salesforcedx-visualforce-markup-language-server/package.json, packages/salesforcedx-vscode-apex/package.json, packages/salesforcedx-vscode-core/package.json, packages/salesforcedx-vscode-lightning/package.json, packages/salesforcedx-vscode-lwc/package.json, packages/salesforcedx-vscode-soql/package.json, packages/salesforcedx-vscode-visualforce/package.json
use current TS, and put it only at the top-level pjson
=> chore: bump ts

packages/salesforcedx-sobjects-faux-generator/src/transformer/sobjectTransformer.ts, packages/salesforcedx-vscode-core/src/commands/refreshSObjects.ts, packages/salesforcedx-vscode-core/src/index.ts
recent bug: when there's not default org, don't get a connection for `min`
old bug: when you can't get a connection, use `min` for startup
@W-18820066@
=> fix: W-18820066 - sobject refresh infinite loops

packages/salesforcedx-vscode-core/src/commands/orgDisplay.ts
fix a ui bug (wrong command name appearing)
refactor for immutability (moving towards https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-single-call.md)
=> chore: bug-and-refactor

.github/workflows/dependabot-auto-merge.yml
Passing the token explicitly so the workflow runs as svc-idee-bot
@W-19047827@
=> W-19047827: fix: pass the idee gh token explicitly

.github/dependabot.yml, .github/workflows/dependabot-auto-merge.yml
update dependabot run schedule to off hours
@W-19122147@
=> W-19122147: ci: update dependabot run schedule to off hours

package-lock.json, package.json, packages/salesforcedx-apex-debugger/package.json, packages/salesforcedx-apex-replay-debugger/package.json, packages/salesforcedx-sobjects-faux-generator/package.json, packages/salesforcedx-utils-vscode/package.json, packages/salesforcedx-utils/package.json, packages/salesforcedx-vscode-apex-debugger/package.json, packages/salesforcedx-vscode-apex-replay-debugger/package.json, packages/salesforcedx-vscode-apex/package.json, packages/salesforcedx-vscode-core/package.json, packages/salesforcedx-vscode-lightning/package.json, packages/salesforcedx-vscode-lwc/package.json, packages/salesforcedx-vscode-soql/package.json
Update versioning as follow up to hrtime removal stories
@W-18587324@
=> W-18587324 chore: update versions for hrtime removals

packages/salesforcedx-vscode-automation-tests/test/specs/orgBrowser.e2e.ts, packages/salesforcedx-vscode-automation-tests/test/specs/runApexTests.e2e.ts, packages/salesforcedx-vscode-automation-tests/test/utils/copilotHidingHelper.ts
Fixes the orgbrowser e2e test and hides the ai features/copilot side window.
@W-19387779@
=> W-19387779: fix: add zoom out and message to failing test

package-lock.json, packages/salesforcedx-vscode-lightning/package.json
=> fix: update the missed version upgrade W-19377429

.vscode/tasks.json, CONTRIBUTING.md, package-lock.json, package.json, packages/salesforcedx-vscode-automation-tests/package.json
remove the commiten stuff and some devDeps that overlap between the repo-level and e2e package
=> ci: drop commitizen

packages/salesforcedx-vscode-core/src/index.ts
deduplicate the api for core ext
inline all the named variables that are onlu used to create the disposable
=> refactor: dedupe apis and inline command registrations

package-lock.json, packages/salesforcedx-vscode-core/package.json
[@W-19704215@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002M9aKZYAZ/view)
=> chore: bump @salesforce/templates to 65.1.0 - W-19704215

packages/salesforcedx-utils-vscode/src/helpers/paths.ts, packages/salesforcedx-vscode-org-browser/src/index.ts, packages/salesforcedx-vscode-services/src/core/configService.ts, packages/salesforcedx-vscode-services/src/core/connectionService.ts, packages/salesforcedx-vscode-services/src/core/defaultOrgService.ts, packages/salesforcedx-vscode-services/src/extensionScope.ts, packages/salesforcedx-vscode-services/src/index.ts, packages/salesforcedx-vscode-services/src/observability/spans.ts, packages/salesforcedx-vscode-services/src/observability/spansNode.ts, packages/salesforcedx-vscode-services/src/virtualFsProvider/indexedDbStorage.ts, packages/salesforcedx-vscode-services/src/vscode/workspaceService.ts, packages/salesforcedx-vscode-services/test/jest/index.test.ts
=> feat: config changes reload the org browser W-19450827
